### ISSUE TITLE
why uaac does not use uaa API?

### ISSUE THREAD

**Issue by jamee** [cloudfoundry/uaa#100]
I traced the uaac to create new user

POST /Users HTTP/1.1
Accept: application/json;charset=utf-8
User-Agent: Ruby
Authorization: bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIyYjQ1YWM1Ni03NDk4LTQ5YjctOWJhMC01YjBiZjhmOWY2OTIiLCJzdWIiOiJwb3J0YWxfZGVtb19jbGllbnQiLCJhdXRob3JpdGllcyI6WyJzY2ltLndyaXRlIiwiY2xvdWRfY29udHJvbGxlci53cml0ZSIsInNjaW0ucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIuYWRtaW4iXSwic2NvcGUiOlsic2NpbS53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJzY2ltLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLmFkbWluIl0sImNsaWVudF9pZCI6InBvcnRhbF9kZW1vX2NsaWVudCIsImNpZCI6InBvcnRhbF9kZW1vX2NsaWVudCIsImdyYW50X3R5cGUiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJpYXQiOjE0MTA4NjAxNDMsImV4cCI6MTQxMDkwMzM0MywiaXNzIjoiaHR0cHM6Ly91YWEuMTkyLjE2OC4wLjIyMy54aXAuaW8vb2F1dGgvdG9rZW4iLCJhdWQiOlsic2NpbSIsImNsb3VkX2NvbnRyb2xsZXIiXX0.dmzKzg5ElB--oZugY6pT7s2JktNNYXscVjkxv4BPN7_y5hJ8IlpWdVMwvXSvLh2rEsmPCOe3uZXyH6fPmOy1hfXoM_QmOjeajeg2McfamGgTOupfnKKRf2x-n66XB5qBW6PxyaYy2i4bI7M59DfX9jCLm0SpmILxQQoL-i7Kbwg
Content-Type: application/json;charset=utf-8
Content-Length: 92
Connection: close
Host: 192.168.1.167:8080

{"userName":"portal_admin","password":"abc123","emails":[{"value":"portal_admin@test.com"}]}

which is not consistent with the api document: https://github.com/cloudfoundry/uaa/blob/ac69ac2ea93c6ae9d6a751adf03596a18fe0e9d5/docs/UAA-APIs.rst#create-a-user-post-users

**Comment by fhanik** [comment]
Closing due to insufficient information.
