### ISSUE TITLE
Latest releases of CF UAA (>4.30.0) are not available on Maven Central

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#1075]
The latest version of CF UAA on Maven Central is currently 4.30.0 - see: https://mvnrepository.com/artifact/org.cloudfoundry.identity/cloudfoundry-identity-uaa

It would be great, if CF UAA's releases are continously published to Maven Central to allow consumption of the war files.

**Comment by andrewedstrom** [comment]
Hi @sebastianGit ,

We no longer publish war files to maven central. The only UAA artifact we officially publish is the bosh release (https://github.com/cloudfoundry/uaa-release)

Sorry for the inconvenience :/

**Comment by kirankbs** [comment]
@andrewedstrom we are using 4.30 right now and we tested with bosh release successfully using `https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=73.7.0`

But, I don't need all the packaged available with `uaa-release*.tgz` except `cloudfoundry-identity-uaa.war`.  

Is there any way that I can download directly `cloudfoundry-identity-uaa.war`?
