### ISSUE TITLE
Support for Jackson 2

### ISSUE THREAD

**Issue by vkhoroshko** [cloudfoundry/uaa#108]
Hello,

Are there any plans to add support for Jackson 2? This prevents us (and probably many other people) to switch to Jackson 2 completely cause currently UAA forces you to use Jackson 1. 

It's not a problem where Jackson 1 is used programmatically  (i.e. ObjectMapper is constructed directly in code) but there are also some places where  Jackson 1 annotations are used (example - [Approval](https://github.com/cloudfoundry/uaa/blob/3ce2a53c261790f5a4cbddff3dd4dcf4a82d69ac/common/src/main/java/org/cloudfoundry/identity/uaa/oauth/approval/Approval.java) class). Obviously, they are not recognized by Jackson 2.

Spring does that by putting same annotations for both Jackson 1 and 2 (in order to do not break users who use Jackson 1).  Probably the same approach could be implemented in UAA.

Thanks in advance

**Comment by fhanik** [comment]
We suggest doing a pull request as a contribution

**Comment by kdombeck** [comment]
Yep, we already have a couple of people working on it. You should see it in a couple of weeks. thanks

**Comment by cf-identity** [comment]
We got this commit - as part of upgrading to Spring 4.1.x we're forced to go with Jackson 2
https://github.com/cloudfoundry/uaa/commit/19b9016df44813ee313d55c6cf3d3726ba2c1b00

However, we are probably not going to leave in Jackson 1 support. As this would increase our testing matrix by trying to support this old library.
