### ISSUE TITLE
Error in the Ruby sample

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/uaa#110]
https://github.com/cloudfoundry/uaa/blob/master/samples/login/login.rb#60 shows why I
prefer to rarely use 'unless', and even then I tend to use DeMorgan's law when translating 
to an 'if' form to make sure I'm correct.

'unless username.nil? && password.nil?' is wrong.  It should be

if username && password
...

Yes, I realize it's just a sample.

**Comment by sreetummidi** [comment]
Login Server has been deprecated and is no longer used
