### ISSUE TITLE
is it possible to use permitAll access with using ClientAuthenticationFilter?

### ISSUE THREAD

**Issue by jekalmin** [cloudfoundry/uaa#111]
Since ClientAuthenticationFilter redirects the user to the login page before AccessDecisionManager, it seems to be impossible to use permitAll access. If I want to allow anonymous users to certain url, how should it be done?

**Comment by fhanik** [comment]
Closing. URLs protected by the ClientAuthenticationFilter are intentionally protected. Do not see an issue nor feature request in this issue.
