### ISSUE TITLE
uaac - problems creating a client with implicit grant

### ISSUE THREAD

**Issue by joeldsa** [cloudfoundry/uaa#112]
If you create a client with implicit grant, uaac prompts you for a client secret and then errors saying that it does not need one.

$ uaac client add test --scope "test_scope" --authorized_grant_types "implicit" --signup_redirect_url "http://localhost:9000/callback"
New client secret:  ********
Verify new client secret:  ********

error response:
{
  "error": "invalid_client",
  "error_description": "Implicit grant should not have a client_secret"
}

**Comment by fhanik** [comment]
Yes, the intention is to not be able to have a client that has implicit as well as other grant types. The work around is really a bug, but we may leave it open to allow for some leniency.
