### ISSUE TITLE
UAA - SCIMUsers - Search API

### ISSUE THREAD

**Issue by sboorlagadda** [cloudfoundry/uaa#113]
There is not way to retrieve sub-list or page through when request is for all attributes of 'user'.

File: uaa/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpoints.java

 if (!StringUtils.hasLength(attributesCommaSeparated)) {
            // Return all user data
            return new SearchResults<ScimUser>(Arrays.asList(ScimCore.SCHEMAS), input, startIndex, count, result.size());
}

Here whole "input" list is returned when attributesCommaSeparated is empty. 

Though we can page through when request asks for certain attributes.

**Comment by sreetummidi** [comment]
Hi,
We don't have plans to support this flow at this time.

Thanks,
Sree
