### ISSUE TITLE
Run Tomcat on custom port

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/uaa#114]
Is there a known YAML config to run the bundled Tomcat on a custom port?

**Comment by d** [comment]
Hi @charyorde 

1. Please head over to [vcap-dev mailing list](https://groups.google.com/a/cloudfoundry.org/forum/#!forum/vcap-dev), that is a more appropriate venue for asking this sort of questions. We would appreciate it if you stop using Github issues for this purpose.
2. You asked the wrong question: We do not have a "bundled Tomcat". This project is a java web application, The artifact of this project is a WAR archive containing the servlet. We do not ship a servlet container (such as Tomcat).

Thanks!
Jesse

**Comment by pjk25** [comment]
I believe at one time the project did include the maven tomcat plugin, and
later similar functionality with grade cargo plugin. This allowed one to
run the app locally, but as Jesse states, it's not the production scenario,
and so it would not be configured via yml. You may be able to configure the
port via configuring the gradle task.  Try the mailing list as Jesse
suggests for more info.

**Comment by charyorde** [comment]
Well, I just modify build.gradle cargo definition.
