### ISSUE TITLE
How to setup UAA in eclipse STS?

### ISSUE THREAD

**Issue by imvishalpatel** [cloudfoundry/uaa#1144]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you expect to see? What goal are you trying to achieve with the UAA?

I want to set up this project in Eclipse but I'm unable to do so. I tried importing as Gradle project but end up having a compile-time error regarding javax.servlet and Catalina. 

How you guys did setup this project successfully. could anyone help me?

**Comment by shamus** [comment]
Hello there.  I don't know that any of the contributing team is using eclipse or STS to develop.

If you figured out how to solve this problem, please feel free to share the solution!
