### ISSUE TITLE
Port 8080 used error

### ISSUE THREAD

**Issue by DeterminedPanda** [cloudfoundry/uaa#1148]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

I am using the current git repository

### How are you deploying the UAA?

I am deploying the UAA locally only using `gradlew run`

### What did you do?

I am still trying to get UAA to work on my windows 10 machine. I clonedthe git repository, extracted the directory and executed the command `gradlew run` using administrator priviledges.
Afterwards I get following error message:
* What went wrong:
```
Execution failed for task ':cargoRunLocal'.
> org.codehaus.cargo.container.ContainerException: Port number 8080 (defined with the property cargo.servlet.port) is in use. Please free it on the system or set it to a different port in the container configuration.
```
I dont have anything running on port 8080, so I am kinda confused what the problem could be.

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected to see UAA start normally, because the port 8080 is not used.

### What did you see instead?

My dreams shatter into thousand pieces

All errors that occure when running `gradlew run --debug`:

```
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':cargoRunLocal'.
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > org.codehaus.cargo.container.ContainerException: Port number 8080 (defined with the property cargo.servlet.port) is in use. Please free it on the system or set it to a different port in the container configuration.
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
17:12:55.725 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
17:12:55.726 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 25s
```

**Comment by joshuatcasey** [comment]
Hi @DeterminedPanda could you verify that nothing else is running on your system? I develop on OSX and run `lsof -i :8080` to see what else is running on the system. Without that we won't be able to reproduce this.

**Comment by andrewedstrom** [comment]
It looks like you have another process running on :8080 on your system. Closing this out but feel free to reopen if you continue to have issues!
