### ISSUE TITLE
Changes to UAA between 189 and 195 regarding checking issuers

### ISSUE THREAD

**Issue by nastacio** [cloudfoundry/uaa#115]
Has there been any change to UAA between CF 189 and CF 195 where UAA started to check the issuers?

**Comment by fhanik** [comment]
Is this for the /check_token endpoint? 
we added a check on Nov 5th last year. As we should not allow decoding of tokens generated from another system, even if the key is a match
https://github.com/cloudfoundry/uaa/commit/6d7fa9bb0629f28ed7bdb04d38211acec36623ee#diff-ff524e857b3c9ccb197027822179edd8R766
