### ISSUE TITLE
Allow usernames containing an exclamation mark

### ISSUE THREAD

**Issue by michaljemala** [cloudfoundry/uaa#116]
The JdbcScimUserProvisioning has a check for valid usernames defined using the following regexp "[a-zA-Z0-9+\\-_.@']+" which prevents username with "!" in it...and more. Is there any way to relax the constraint to allow for more characters in the username.

**Comment by fhanik** [comment]
Thanks for the issue,we could express that pattern as a configuration variable to allow for more options

**Comment by d** [comment]
What's the scenario when this relaxation is needed? If we allow extract this pattern to a config option, how should UAA act when we change said option such that the change invalidates existing, previously valid user names?

**Comment by michaljemala** [comment]
Any updates here?

**Comment by sreetummidi** [comment]
@michaljemala This issue has been prioritized in the public tracker.

**Comment by fhanik** [comment]
@michaljemala we are working on this right now. If you weren't aware, you can change the pattern through [config](https://github.com/cloudfoundry/uaa/blob/83f4b23052c325950f865485c475f39113d34dc6/uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml#L35-35)!

**Comment by fhanik** [comment]
This is has been fixed in [development](https://github.com/cloudfoundry/uaa/commit/563875cdf0ab256c418baf2af8fae1715fa2d829) and will be part of future releases
