### ISSUE TITLE
Question: Is it possible to use UAA with desktop applications?

### ISSUE THREAD

**Issue by pratapagiri** [cloudfoundry/uaa#1160]
Is it possible to use UAA with desktop applications?

**Comment by joshuatcasey** [comment]
Hi @pratapagiri Do you have more information on this use-case? Do you anticipate running the UAA locally? Or setting up a desktop application as an OAuth client of the UAA?

**Comment by pratapagiri** [comment]
@joshuatcasey  We are planning to use desktop application as an OAuth client of the UAA.

**Comment by shamus** [comment]
Hi there. There are many ways to answer this question, it's highly dependent on the specifics of your use case. I'd recommend learning about the different grant types in OAuth (authorization code, implicit, and password) and then figuring out from there how to integrate that functionality into your app.

https://www.oauth.com/ is a good resource for learning more about oauth.
