### ISSUE TITLE
How to customize  uaa log file 

### ISSUE THREAD

**Issue by tppalani** [cloudfoundry/uaa#1178]
Hi Team

I deployed cloud foudary war file inside the tomcat, and we can able to access foundry home page in browser.
 when i am doing startup.sh to start tomcat server my server is coming up and i can able to see the UI changes in the browser.

Now uaa.log file is available under the /tomcat/logs folder location by default, now the question is i don't want generate uaa.log file in this location, instead of this it should be some where else required.
For example /root/user/logs.

 Please find the below logs view structure. 
root@linux-vm:/opt/tomcat/apache-tomcat-9.0.26/logs# ls -lrt

-rw-r----- 1 root root 0 Dec 26 06:01 manager.2019-12-26.log
-rw-r----- 1 root root 0 Dec 26 06:01 host-manager.2019-12-26.log
-rw-r----- 1 root root 0 Dec 26 06:01 localhost_access_log.2019-12-26.txt
-rw-r----- 1 root root 2481 Dec 26 06:12 localhost.2019-12-26.log
-rw-r----- 1 root root 31443 Dec 26 06:12 catalina.2019-12-26.log
-rw-r----- 1 root root 179793 Dec 26 06:24 uaa.log
-rw-r----- 1 root root 1042803 Dec 26 06:24 catalina.out

Thanks,
Palani

**Comment by tppalani** [comment]
Hi team, can you please someone help me on this.

**Comment by strehle** [comment]
Hi, dont know if still needed.
log configuration from uaa is here
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializer.java#L185-L204

You you could add environement to have on lo42j configuration
