### ISSUE TITLE
How to get group or roles information by ID_Token？

### ISSUE THREAD

**Issue by ZBYuan0813** [cloudfoundry/uaa#1179]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
UAA version:74.11.0

I curl the UAA API to get id_token,access_token info.

### How are you deploying the UAA?

I am deploying the UAA
locally only using gradlew

### What did you do?
1. I use the uaa.yaml like this https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/resources/required_configuration.yml
2. I use uaac creates a client:
uaac client add webappclient -s webappclientsecret \ 
--name WebAppClient \ 
--scope roles,openid,profile,email,address,phone \ 
--authorized_grant_types authorization_code,refresh_token,client_credentials,password,implicit \ 
--authorities uaa.resource \ 
--redirect_uri http://localhost:8081/login/oauth2/code/uaa

3.I create a user named appuser and secret is appusersecret

4.I add the user to roles

5.I curl the uaa api get Id_token:
eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBz...Jmq2Wg

6.I use jwt to decode id_token and get the payload data:
```
{
  "sub": "8b029dc5-3a23-4664-8308-81a03e5b5c76",
  "aud": [
    "webappclient"
  ],
  "iss": "http://uaa-dev.mstech.com.cn/uaa/oauth/token",
  "exp": 1577387266,
  "iat": 1577344066,
  "amr": [
    "pwd"
  ],
  "azp": "webappclient",
  "scope": [
    "openid"
  ],
  "email": "appuser@acme.com",
  "zid": "uaa",
  "origin": "uaa",
  "jti": "66456ec7bf2b429bbfc9659f52dcc80d",
  "previous_logon_time": 1577340823852,
  "email_verified": true,
  "client_id": "webappclient",
  "cid": "webappclient",
  "grant_type": "implicit",
  "user_name": "appuser",
  "rev_sig": "220f04ed",
  "user_id": "8b029dc5-3a23-4664-8308-81a03e5b5c76",
  "auth_time": 1577340823
}
```
The id_token do not contains information about roles?

### What did you expect to see? What goal are you trying to achieve with the UAA?
I hope I can get roles information from id_token and I think it is necessary.
Thanks!
### What did you see instead?

Please include UAA logs if available.

**Comment by shamus** [comment]
Thanks for the question. Long story short, the `roles` claim in the id_tokens minted by the UAA represents role data present in an _external_ IdP. The user you're working with is in the internal user store, so the `roles` claim is empty.

In the UAA, groups represent the scopes that can be requested on a user's behalf.

I agree it's a bit confusing and we get a lot of questions about it.
