### ISSUE TITLE
Role which need to create set-running-environment-variable-group

### ISSUE THREAD

**Issue by Muruganfly03** [cloudfoundry/uaa#1180]
Below is the command executed from Admin level, but not from Normal user.

Error:
cf set-running-environment-variable-group '{"TEST_VARIABLE":"TEST"}'
Setting the contents of the running environment variable group as ...
FAILED
Server error, status code: 403, error code: 10003, message: You are not authorized to perform the requested action

Admin user:
openid
approvals.me
scim.me
notification_preferences.read
cloud_controller_service_permissions.read
notification_preferences.write
cloud_controller.read
actuator.read
profile
doppler.firehose
uaa.user
oauth.approvals
cloud_controller.admin
uaa.admin
password.write
roles
user_attributes
cloud_controller.write
uaa.offline_token
scim.write
cloud_controller.user
scim.read

Normal User:
password.write
roles
user_attributes
actuator.read
profile
oauth.approvals
cloud_controller.write
uaa.user
cloud_controller_service_permissions.read
cloud_controller.read
scim.me
openid
approvals.me
notification_preferences.read
uaa.offline_token
notification_preferences.write
cloud_controller.user

Please confirm which additional privilege scope/role added for Normal user to execute that command.  Kindly assist on priority. Thanks in Advance.

**Comment by shamus** [comment]
The answer to your question really depends on which cf components the CLI is interacting with as part of the `set-running-environment-variable-group` command.

This question is best posted to the cli team, either in the cf slack or in their [github repo](https://github.com/cloudfoundry/cli)

**Comment by yap-karman** [comment]
Hi, any solution for this issue please?

**Comment by strehle** [comment]
Hi solution is to give your use the needed org or space role, e.g.
See command help from cf 

cf set-space-role -h


Setting env variables is something you need SpaceDeveloper or SpaceManager

This authorization is maintained and set in cloud controller. UAA only has the user as identity, but cc is controlling the authorization here
