### ISSUE TITLE
Info on UAA Metric Vitals

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/uaa#1184]
This is more of a question rather than a bug

From the [statsd module](https://github.com/cloudfoundry/uaa/blob/3bbe8ff1981295a657820a02f0a32e6aaf224327/statsd/src/main/java/org/cloudfoundry/identity/statsd/UaaMetricsEmitter.java#L155) we see that the value comes as SystemLoad * 100.

If I induce load on UAA and run `cf nozzle --no-filter | grep vitals.vm.cpu.load`, I get output as follows:
```
origin:"uaa" eventType:ValueMetric timestamp:1579020239845168801 deployment:"cf" job:"uaa" index:"4432ac22-f683-466c-a787-98d6b86b459d" ip:"x.x.x.x" tags:<key:"source_id" value:"uaa" > valueMetric:<name:"vitals.vm.cpu.load" value:689 unit:"gauge" >
origin:"uaa" eventType:ValueMetric timestamp:1579020244844394785 deployment:"cf" job:"uaa" index:"4432ac22-f683-466c-a787-98d6b86b459d" ip:"x.x.x.x" tags:<key:"source_id" value:"uaa" > valueMetric:<name:"vitals.vm.cpu.load" value:658 unit:"gauge" >
```
As can be seen the values can be seen in accordance to [SystemLoad * 100](https://github.com/cloudfoundry/uaa/blob/3bbe8ff1981295a657820a02f0a32e6aaf224327/statsd/src/main/java/org/cloudfoundry/identity/statsd/UaaMetricsEmitter.java#L155).

So my first question is: Based on [the documentation](https://docs.cloudfoundry.org/uaa/uaa-metrics.html),  [here](https://github.com/cloudfoundry/docs-uaa/blob/411d1a8364221ff3d3ac4ad95e7a04172e81dd28/uaa-metrics.html.md.erb#L183) it states that the 

> If the value of (cpu.load / 100.0 / CPU count) is more than 2.0, this is an indicator that the system may be overloaded and processing data slowly.

How is this conversion from `SystemLoad*100` being converted to a whole number value `(cpu.load / 100.0 / CPU count)`? I.E where is this conversion being done? I didn't notice any code implementation for the same, Does the document mean that we should do this conversion and calculate it?

2) Also as [system load](https://docs.oracle.com/javase/7/docs/api/java/lang/management/OperatingSystemMXBean.html#getSystemLoadAverage()) and [CPU Load](https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad()) seem to be different shouldn't it either be renamed or use the right bean?

I may be missing something here. Help to point to the right direction of the conversion and also SystemLoad vs CpuLoad would be of great help. 

Thanks 😄

**Comment by shamus** [comment]
> How is this conversion from SystemLoad*100 being converted to a whole number value (cpu.load / 100.0 / CPU count)? I.E where is this conversion being done? I didn't notice any code implementation for the same, Does the document mean that we should do this conversion and calculate it?

I believe the documentation is making a recommendation for how processes monitoring statsd  should interpret `cpu.load`. The UAA does not provide any tools to monitor the metrics it emits. So, the short answer to your question is yes, you should do this conversion.

> Also as system load and CPU Load seem to be different shouldn't it either be renamed or use the right bean?

I can't say how these names were originally chosen, but I'm guessing they weren't meant to exactly mirror the backing mbean implementations in terms of naming.
