### ISSUE TITLE
war file contains software licensed under JSON license

### ISSUE THREAD

**Issue by kranich** [cloudfoundry/uaa#1191]
The current uaa war file contains `com.unboundid.components:json:1.0.0` as `json-1.0.0.jar` in `WEB-INF/lib`.

It comes into `cloudfoundry-identity-server` via the `cloudfoundry-identity-model` dependency `com.unboundid.product.scim:scim-sdk:1.8.22`.

`com.unboundid.components:json:1.0.0` is licensed under the controversial [JSON License](http://www.json.org/license.html).

Due to the statement 

> The Software shall be used for Good, not Evil.

 it is questionable if software under the JSON license can be used in a commercial context by companies that take open source software clearing seriously. This then also applies to UAA because of this dependency.

**Comment by dbeneke** [comment]
Thank you for submitting the concern and supporting context.  

We've reached out to discuss use of this license with our licensing/legal supporters and it was suggested that even though they agree the language is a bit subjective it's clear for use.  At this point we aren't recommending any change and will continue to use remain dependent on `com.unboundid.product.scim:scim-sdk:1.8.22`.  The CF commercial community hasn't historically raised its use as an issue.
