### ISSUE TITLE
How to run flywayMigrate after the ./gradlew run?

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/uaa#120]
Running uaa with postgres doesn't execute the alter db scripts. I guess this can be achieved with the gradle flyway definition.

Can you please add a way to achieve this into the docs?

**Comment by fhanik** [comment]
Take a look at the .travis.yml script to see how to apply the PostgreSQL profile. if a migrate didn't happen, those tests wouldn't be passing

**Comment by fhanik** [comment]
https://github.com/cloudfoundry/uaa/commit/308bd975c7f9398a8b8f523b4395b22963ad5600

**Comment by fhanik** [comment]
I am closing this issue. After reviewing all the details, the system will always run a flyway migrate as it starts up. The documentation of how to apply the profile is [available](https://github.com/cloudfoundry/uaa#using-gradle-to-test-with-postgresql-or-mysql), it is not immediately clear.

We will add command line options to set the profile, and to enable/disable the flyway clean script during Tomcat startup and update the documentation as such

**Comment by charyorde** [comment]
Thanks for this. Just a little concerned that the flyway migrate script only runs when you run a test. Please correct me if I'm wrong. 

However, is there a flag to add to `gradlew run` in order to execute flyway migrate as well?

**Comment by fhanik** [comment]
@charyorde When you do 

    ./gradlew run

It will launch a Tomcat container, and deploy the UAA war file. This war file reads the DB configuration from the uaa.yml, and will connect to what ever DB you have specified in the `spring_profiles` setting.
The war file (the UAA application) always runs the migrate script. However, if you haven't specified the MySQL profile, the UAA simply starts an in memory database and runs the migration scripts on the in memory DB.

In the [following commit](https://github.com/cloudfoundry/uaa/commit/accc46674530f2c7df2894fb1ba792b2dea58d0e) we are also providing you with the ability to configure the spring profiles for gradlew run on the command line, as such

    ./gradlew -Dspring.profiles.active=default,mysql run

The migrations scripts always run. They are part of the application lifecycle. However, you must configure which DB they run on.

**Comment by fhanik** [comment]
Here we show how 'flyway.migrate' always runs when the app is started up and loads the Spring XML files

https://github.com/cloudfoundry/uaa/blob/master/common/src/main/resources/spring/data-source.xml#L35

**Comment by charyorde** [comment]
@fhanik Thanks for the detailed explanation.
However, here's my manual test that caused the illusion on `gradlew run`:
```
bash-3.2$ cat ~/javaprojects/uaa/common/build/resources/main/org/cloudfoundry/identity/uaa/db/postgresql/V1_6_0__ExtendAuthzApprovalUsername.sql
ALTER TABLE authz_approvals ALTER COLUMN username TYPE VARCHAR(255);
```

I was expecting to see username column on authz_approvals table but I was only able to find it in authz_approvals_old. Don't know where authz_approvals_old comes from though ;)
```
uaa=# \d authz_approvals;
                                Table "public.authz_approvals"
     Column     |            Type             |                   Modifiers
----------------+-----------------------------+------------------------------------------------
 user_id        | character varying(36)       | not null
 client_id      | character varying(36)       | not null
 scope          | character varying(255)      | not null
 expiresat      | timestamp without time zone | not null default now()
 status         | character varying(50)       | not null default 'APPROVED'::character varying
 lastmodifiedat | timestamp without time zone | not null default now()
Indexes:
    "new_authz_approvals_pkey" PRIMARY KEY, btree (user_id, client_id, scope)

uaa=#  \d authz_approvals_old;
                              Table "public.authz_approvals_old"
     Column     |            Type             |                   Modifiers
----------------+-----------------------------+------------------------------------------------
 username       | character varying(255)      | not null
 clientid       | character varying(36)       | not null
 scope          | character varying(255)      | not null
 expiresat      | timestamp without time zone | not null default now()
 status         | character varying(50)       | not null default 'APPROVED'::character varying
 lastmodifiedat | timestamp without time zone | not null default now()
Indexes:
    "authz_approvals_pkey" PRIMARY KEY, btree (username, clientid, scope)
```
Thanks all the same.

**Comment by fhanik** [comment]
Look through the other migration scripts. You will see each change as it is performed. Alternatively, you can enable debug output. and see each SQL command being executed. 

So it seems all your migrations are run. Do a 'select * from schema_version' to see if your migrations have been applied or not. It will list all versions there. Migrations are not run everytime, only when they are needed as determined by the content in the schema_version table

If all seems ok, I will ask you to close this issue.
