### ISSUE TITLE
400 Bad Request html response

### ISSUE THREAD

**Issue by m42s** [cloudfoundry/uaa#1218]
### What version of UAA are you running?
```
{
  "app": {
    "version": "74.13.0"
  },
...
}
```

### How are you deploying the UAA?

I am deploying the UAA
- using a bosh release I downloaded from bosh.io

### What did you do?

   ```
curl -X POST \
    'https://uaa.mydomain.com/check_token?tok=' \
    -H 'Accept: application/json' \
    -H 'Authorization: Basic ...' \
```
### What did you expect to see? What goal are you trying to achieve with the UAA?

Since the expected token query parameter is missing, I expect a 400 Bad Request, with `Content-Type: application/json`

### What did you see instead?
```
Content-Type: text/html;charset=utf-8

<!doctype html>
<html lang="en">
<head>
	<title>HTTP Status 400 – Bad Request</title>
	<style type="text/css">
		body {
			font-family: Tahoma, Arial, sans-serif;
		}

		h1,
		h2,
		h3,
		b {
			color: white;
			background-color: #525D76;
		}

		h1 {
			font-size: 22px;
		}

		h2 {
			font-size: 16px;
		}

		h3 {
			font-size: 14px;
		}

		p {
			font-size: 12px;
		}

		a {
			color: black;
		}

		.line {
			height: 1px;
			background-color: #525D76;
			border: none;
		}
	</style>
</head>
<body>
	<h1>HTTP Status 400 – Bad Request</h1>
</body>
</html>
```

**Comment by srwaggon** [comment]
Hi @m42s thanks for bringing this up. That error looks like it's from Tomcat, not from the UAA. It's hard to debug more without knowing how `https://uaa.domain.com` is configured and how the UAA is running. I suspect there's a misconfiguration somewhere. Are you running the UAA locally in a local BOSH director? Is the UAA by itself or part of a CF deployment?

**Comment by m42s** [comment]
Hi @srwaggon, I'm running this UAA (https://github.com/cloudfoundry/uaa-release) as part of a CF deployment; I haven't tested locally yet.

**Comment by srwaggon** [comment]
Hey @m42s. Can you describe more how the domain `https://uaa.domain.com` is configured so that we can try to reduce the possible surface area of the potential misconfiguration?

**Comment by m42s** [comment]
Hi @srwaggon, I retested from the UAA VM:

```
curl -kv -X POST -H 'Authorization: Basic ttt' -H 'Accept: application/json' 'https://localhost:8443/check_token?notoken=t'
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
...
> POST /check_token?notoken=t HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.47.0
> Authorization: Basic ttt
> Accept: application/json
>
< HTTP/1.1 400
< X-Content-Type-Options: nosniff
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< Content-Type: text/html;charset=utf-8
< Content-Language: en
< Content-Length: 435
< Date: Wed, 04 Mar 2020 08:05:32 GMT
< Connection: close
<
* Closing connection 0
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2
{font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
```

localhost_access.log correlated log entry:
```
127.0.0.1 - - [04/Mar/2020:08:05:32 +0000] https-jsse-nio-8443-exec-9 "POST /check_token?notoken=t HTTP/1.1" 400 435
```

uaa.log correlated log entry:
```
[2020-03-04 08:05:32.241] uaa - 15 [https-jsse-nio-8443-exec-9] ....  WARN --- DefaultHandlerExceptionResolver: Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Requir
ed String parameter 'token' is not present]

```

It's possible that Tomcat interferes somehow but I haven't found yet the root cause.

For what it's worth, I take the release from https://github.com/cloudfoundry/uaa-release/releases and deploy it.

This is reproducible also in the latest v74.15.0.

Regarding your last comment, the setup of the domain https://uaa.domain.com should not matter right (given the test above)?
