### ISSUE TITLE
Bootstrap properties from a spring-cloud-config-server

### ISSUE THREAD

**Issue by mikeroda** [cloudfoundry/uaa#123]
Right now UAA reads properties from uaa.yml and login.yml, and there is ability to specify a local or remote URI for these files. I'm wondering how to go about bootstrapping the properties from a spring-cloud-config-server and eventually consul.

**Comment by mikeroda** [comment]
After a lot of tweaks and workarounds, I managed to build UAA as a spring boot application and get it to read configuration from consul using spring-cloud. Let me know if interested and I can fork and submit a pull request.

**Comment by fhanik** [comment]
Very interested. Any help is always appreciated.

**Comment by fhanik** [comment]
Closing this issue in anticipating of a forked example

**Comment by bisbos** [comment]
Hi Mikeroda,
I am interested for the spring-boot version of UAA. Your help is very much appreciated

**Comment by angelo-chan** [comment]
Hi @mikeroda ,
I'm also interested for the spring-boot version of UAA. Could you give me some advice?

**Comment by czerwina** [comment]
@mikeroda @fhanik did this fork and work get done? We're also interested in a springboot version  of the uaa

**Comment by mikeroda** [comment]
Sorry I haven't had time to do the forked example but I can provide a high level overview and answer any questions.

Basically what I have is a new project that has dependencies on the three UAA jars (common, scim, and login), a completely different build.gradle script, and a copy of everything under the uaa/src/main which is all the spring XML configuration. 

In the main Application class I do an @ImportResource("classpath:spring-servlet.xml"), and critically, a BeanFactoryPostProcessor that creates a FilterRegistrationBean for every Filter it finds and sets enabled=false so boot doesn't interfere with all the filters registered in spring XML. Also I had to exclude ThymeleafAutoConfiguration.class from @EnableAutoConfiguration.

There are unfortunately several tweaks to the XML and build dependencies to get things working. I'm using spring boot 1.3.0.RELEASE and for example I have to specify specific versions of spring (4.0.1) and other jars like spring-jdbc (4.1.6.RELEASE) to get it to work with UAA, which uses some older APIs. You might save yourself some trouble if you pick a version of Spring boot that is matched to the versions of spring that UAA is using.

There are a bunch of other things required to get it so the war file can be run with an external tomcat container still. I'll leave those details out for now. 

Good luck!

**Comment by czerwina** [comment]
@mikeroda thanks for the pointers. Always good to have a start from someone who went through the pain already
