### ISSUE TITLE
UaaRandomStringUtilImpl will hang and not allow UAA to start.

### ISSUE THREAD

**Issue by KowalczykBartek** [cloudfoundry/uaa#1233]
### What version of UAA are you running?
applies to commit #edd9e74 (v74.15.0) 

### How are you deploying the UAA?
doesn't matter here.

### What did you do?
I run UAA on machine with limited entropy , because of that **/dev/random** block and UAA cannot start. Please consider that part of UAA
```java
public UaaRandomStringUtilImpl() throws NoSuchProviderException, NoSuchAlgorithmException {
  secureRandom = SecureRandom.getInstance("SHA1PRNG", "SUN");
  secureRandom.setSeed(secureRandom.generateSeed(1024));
}
```
to be more "tolerant" - initialize secureRandom on first use, maybe secure random is not required ? Atm I had to  use **java.security.egd=file:/dev/urandom**

**Comment by shamus** [comment]
Hi there!  Yes, that's right. The UAA will need to be run with `java.security.egd=file:/dev/urandom` (or `java.security.egd=file:/dev/./urandom` for OpenJDK).

I see that we didn't include that in the release notes, we'll address that now.
