### ISSUE TITLE
Regression in httpclient v4.5.11 (in UAA v74.15.0) likely breaks compatibility with OIDC domains that don't use ICAAN TLDs

### ISSUE THREAD

**Issue by peterellisjones** [cloudfoundry/uaa#1239]
Hi UAA Team,

The following issue is for UAA version v74.15.0 deployed via BOSH as part of cf-deployment

### What did you do?

We deploy Cloud Foundry via BOSH and CF deployment on Openstack. We noticed that upgrading the UAA to v74.15.0 with no other configuration changes breaks the integration with our OIDC provider. Downgrading back to UAA v74.14.0 (with no other configuration changes) fixes the issue. 

With UAA v74.15.0 (but not v74.14.0) the OIDC provider gets the following error response from the UAA when trying to do a token exchange:

```json
{"error":"unauthorized","error_description":"Unable to map issuer, https://cloudportal-idp.vw.vwg/auth/realms/meshfed , to a single registered provider"}
```
Our OIDC configuration looks like this and has not changed recently:

```yaml
providers:
      meshfed:
        addShadowUserOnLogin: true
        attributeMappings:
          email: sub
          family_name: sub
          given_name: sub
          user_name: sub
        discoveryUrl: https://cloudportal-idp.vw.vwg/auth/realms/meshfed/.well-known/openid-configuration
        linkText: Login with Cloudportal IDP
        redirectUrl: https://uaa.sys.p.ocf.de-wob-2.cloud.vwgroup.com
        relyingPartyId: meshfed-oidc
        relyingPartySecret: no_used_by_idp
        scopes:
        - openid
        - email
        showLinkText: true
        skipSslValidation: false
        type: oidc1.0
```

Looking at the UAA logs we see the following frequent errors when running UAA v74.15.0 (but not v74.14.0)

```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://cloudportal-idp.vw.vwg/auth/realms/meshfed/.well-known/openid-configuration": Certificate for <cloudportal-idp.vw.vwg> doesn't match any of the subject alternative names: [cloudportal-idp.vw.vwg]; nested exception is javax.net.ssl.SSLPeerUnverifiedException: Certificate for <cloudportal-idp.vw.vwg> doesn't match any of the subject alternative names: [cloudportal-idp.vw.vwg]
```

I have verified that the certificate for `cloudportal-idp.vw.vwg` is valid and it has a common name of `cloudportal-idp.vw.vwg` and a SAN of `cloudportal-idp.vw.vwg`. Therefore UAA log error is surprising because it is claiming that the discoveryURL host name is not a SAN for the certificate, which is untrue. 

Googling revealed the same error occurring with Spring Boot 2.2.3 via [this post](https://henningwaack.wordpress.com/2020/01/26/javax-net-ssl-sslpeerunverifiedexception-certificate-for-server-dev-untrusted-doesnt-match-any-of-the-subject-alternative-names-server-dev-unstrusted-web-dev-unstrusted-localhost/) where the author got the certificate error when making requests to a non-public TLD. In that case the root cause was [this regression](https://issues.apache.org/jira/browse/HTTPCLIENT-2047) in Apache httpclient v4.5.11 which inadvertently enforced public hostnames (ie those with [ICANN TLDs](http://data.iana.org/TLD/tlds-alpha-by-domain.txt)).

@joshuatcasey confirmed in [our conversation on the Cloud Foundry Slack #uaa channel](https://cloudfoundry.slack.com/archives/C03FXANBV/p1584000868019000)  that UAA v74.15.0 updates the Apache httpclient library from v4.5.10 to v4.5.11, suggesting this is the cause of the errors we are seeing. Please could you upgrade the httpclient library to v4.5.12 which [fixes the issue](https://archive.apache.org/dist/httpcomponents/httpclient/RELEASE_NOTES-4.5.x.txt).

cheers,

Pete

**Comment by joshuatcasey** [comment]
@peterellisjones Thanks for the detailed writeup! This is in front of our product managers now. Based on the Slack conversation, it sounds like you're not blocked as you can pin to UAA 74.14.0 right now.

**Comment by dbeneke** [comment]
@peterellisjones We're looking into exactly how we are dependent on httpclient and exploring the dependency.  It looks like we consume it through a spring-framework release and if so we'll get in touch with them to raise the concern and understand their release timing/strategy before determining how to address this for UAA.

**Comment by peterellisjones** [comment]
Thanks @dbeneke and @joshuatcasey — we've pinned the release in the meantime

**Comment by peterellisjones** [comment]
Hi folks -- thanks for your support with this issue. I can confirm that the problem is fixed with the latest release (I expect you fixed it many releases ago but I forgot to check :) )
