### ISSUE TITLE
org.cloudfoundry.identity:cloudfoundry-identity-common:2.x is missing on maven central

### ISSUE THREAD

**Issue by mvach** [cloudfoundry/uaa#124]
Hi,
within SAP we noticed that org.cloudfoundry.identity:cloudfoundry-identity-common:2.x is missing on maven-central.
Only version 1.4.3 is available: http://search.maven.org/#artifactdetails|org.cloudfoundry.identity|cloudfoundry-identity-common|1.4.3|jar

Can you please provide org.cloudfoundry.identity:cloudfoundry-identity-common:2.x also?

Best Regards
Matthias

**Comment by fhanik** [comment]
Will this suffice?
http://repo.spring.io/webapp/search/artifact/?1&q=cloudfoundry-identity-common-2.0.3

**Comment by mvach** [comment]
Sadly it will not, since the http://repo.spring.io repository is continuously breaking the rules of immutable artifacts too often in the past we don't have access to spring.io anymore in our enterprise. with maven-central it is much easier cause artifacts deployed there are in fact immutable. Which is a must for build reproducibility.

**Comment by fhanik** [comment]
Let's us see what we can do, we've run into immutability problems too with other libraries, but not as of lately. We will explore the possibility of publishing to Sonatype's OSS repo and from there it should be mirrored to maven central

**Comment by fhanik** [comment]
We will start publishing releases on Maven Central from here on.
http://search.maven.org/#search%7Cga%7C1%7Corg.cloudfoundry.identity

We still have some issues to work out internally on how to use our CI/publish system with the branch flow that we prefer. but the release is available and will be available for future releases.
