### ISSUE TITLE
UAA not observing interface spec.

### ISSUE THREAD

**Issue by Houlistonm** [cloudfoundry/uaa#1243]
I created an [issue](https://github.com/cloudfoundry-incubator/uaa-cli/issues/38) with the uaa-cli team regarding an error from uaa-cli.

$ uaa version
0.10.0 8626b94
OM/PAS = 2.8.5

"uaa list-clients" returns:
```
An unknown error occurred while parsing response from https://uaa.run.markspcffoundry.com/oauth/clients?count=100&sortOrder=ascending&startIndex=1. Response was <18150 characters of redacted json>: json: cannot unmarshal string into Go struct field Client.resource_ids of type []string
```

Developer on that team investigated and his findings are [here](https://github.com/cloudfoundry-incubator/uaa-cli/issues/38#issuecomment-542838600)

**Comment by strehle** [comment]
uaa cli must handle it
