### ISSUE TITLE
Spring no longer supporting authorization servers, spring-security-oauth2 in maintenance mode

### ISSUE THREAD

**Issue by mbalsam82** [cloudfoundry/uaa#1244]
Spring announced that
- spring-security-oauth2 is officially in maintenance mode,
- EOL for the latest version (2.4.x) will probably be around a year from now and
- support for authorization servers will be stopped completely in following spring versions.

See: https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update

Since UAA uses spring-security-oauth2 2.4.0 for its authorization server implementation, what's UAA's mitigation strategy?

**Comment by shamus** [comment]
Hi there.  Thanks for the question.

Our current strategy is to "take ownership" of this code by repackaging it and incorporating it into the UAA.

**Comment by mbalsam82** [comment]
In case you missed the announcement, there seems to have been a change of mind: https://spring.io/blog/2020/04/15/announcing-the-spring-authorization-server

**Comment by shamus** [comment]
I'm going to close this out, I think the question is answered.
