### ISSUE TITLE
Provide link to uaa docker image used in kubernetes deployment

### ISSUE THREAD

**Issue by rohitsakala** [cloudfoundry/uaa#1251]
### What version of UAA are you running?

uaa in kuberentes

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

```
{"app":{"version":"74.17.0"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"f006642","idpDefinitions":{},"prompts":{"username":["text","Email"],"password"["password","Password"]},"timestamp":"2020-03-27T21:45:56+0000"}
```

### How are you deploying the UAA?

`make minikube` inside k8's folder.

### What did you expect to see? What goal are you trying to achieve with the UAA?

We are on a spike to understand how we can consume uaa into [KubeCF](https://github.com/cloudfoundry-incubator/kubecf). 

Can you provide access to the place where the `cfidentity/uaa` docker image is being built ? and how we can subscribe to it ?

**Comment by shamus** [comment]
@rohitsakala did our conversation on slack yesterday help answer your question, or do you need more?

**Comment by rohitsakala** [comment]
@shamus , I created this issue before our conversation on slack.
