### ISSUE TITLE
How can we check the /health status of our UAA deployment

### ISSUE THREAD

**Issue by jdepaul-mx** [cloudfoundry/uaa#1253]
Is there an application /health uri that can be enabled like in some of the SpringBoot applications that would show the basic status of the application?  We need to register some reliable mechanism in Kubernetes to check the application status so it can be aware when the application becomes unstable and may require a re-start.

### What version of UAA are you running?
"app":{"version":"74.7.0"}

### How are you deploying the UAA?
Helm deploy into a Kubernetes 1.16 cluster

I am deploying the UAA
- helm deploy command into a running Kubernetes cluster

**Comment by mwdb** [comment]
/healthz is the uaa monitoring endpoint. It will check the tomcat is reachable, but will not check for uaa state or healthy DB connection.

**Comment by shamus** [comment]
Thanks @mwdb!
