### ISSUE TITLE
Impersonation setting in yaml config doesn't get set on startup

### ISSUE THREAD

**Issue by zenbones** [cloudfoundry/uaa#126]
In uaa.yaml we would like to use...
oauth:
  client:
    redirect_uri:
      - "http://impersonate/"
    autoapprove:
      - oauth.approvals
      - openid

...which I believe should work, but impersonation fails on startup until we run...

sudo /usr/local/bin/uaac target http://<uaa url>/uaa
sudo /usr/local/bin/uaac token client get login -s <secret>
sudo /usr/local/bin/uaac client update login --redirect_uri "http://impersonate/"
sudo /usr/local/bin/uaac client update login --autoapprove oauth.approvals,openid

.which is a pain when the service has to be auto started as we should not need a bash script to get a servlet properly setup. Are we missing something? Is there a better way to do this? Or is this really a feature/bug?

Thanks,
David Berkman
dberkman@forio.com

**Comment by sreetummidi** [comment]
Seems like a bug. We will look into it

**Comment by fhanik** [comment]
Looks like a misconfiguration in your example. You would specify oauth.clients and then the client ID.

    oauth:
      clients:
        cf:
          id: cf
          authorized-grant-types: implicit
          scope: cloud_controller.read,cloud_controller.write,openid,password.write
          authorities: uaa.none
          resource-ids: none
          redirect-uri: https://uaa.cloudfoundry.com/redirect/cf
