### ISSUE TITLE
Feature Request: Add Support for forceAuthn Flag for SAML IdPs

### ISSUE THREAD

**Issue by scult** [cloudfoundry/uaa#1261]
Hi Guys,

we are currently using UAA with a SAML IdP. We were trying to pass the forceAuthn flag as part of the login request, but it looks like UAA currently doesn’t support this.

From what I’ve you are using the Spring Security SAML extension for SAML SSO. The extension itself supports [passing this flag](https://docs.spring.io/autorepo/docs/spring-security-saml/1.0.x-SNAPSHOT/reference/htmlsingle/#configuration-sso-process-sp-init), but UAA doesn’t seem to expose any way to configure it.

Would you please consider adding support for this flag?

Cheeers

**Comment by strehle** [comment]
recommend that you provide a PR, you can add your feature into
https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/webapp/WEB-INF/spring/saml-providers.xml#L36
