### ISSUE TITLE
Deploying UAA with CF v200 will not start due to monit job trying to call /healthz when require_https is true

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/uaa#127]
We are trying to upgrade from CF v192 to v200 and the UAA jobs will not stay running.  There are new instructions in the monit job to verify the service is responding to healthz:

if failed port <%= p('uaa.port') %> protocol http
    request "/healthz"
    with timeout 60 seconds for 10 cycles
  then restart

However, when monit tries to query healthz it's rejected due to the request not being over HTTPS:

[2015-02-24 20:24:52.804] uaa - 2373 [http-bio-8080-exec-1] .... DEBUG --- AntPathRequestMatcher: Checking match of request : '/healthz'; again
st '/healthz/**'
[2015-02-24 20:24:52.805] uaa - 2373 [http-bio-8080-exec-1] .... DEBUG --- FilterChainProxy: /healthz at position 1 of 1 in additional filter c
hain; firing Filter: 'HttpsEnforcementFilter'
[2015-02-24 20:24:52.805] uaa - 2373 [http-bio-8080-exec-1] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Bad (non-ht
tps) request received from: 127.0.0.1

If we set the require_https property in the uaa config to false, then healthz starts working but all requests are then allowed via HTTP.

**Comment by rdgallagher** [comment]
Hi @amhuber,

`require_https` defaults to false and is really only useful when running the UAA standalone, since in a typical CF installation SSL terminates at the load balancer (HA Proxy) and communication to the UAA is over HTTP. It should be safe to leave the default value of `false` in place for that property.

**Comment by amhuber** [comment]
The require_https property is what makes the UAA and Login components check that the X-Forward-Proto header is set to https, otherwise they issue a redirect.  Even in a "typical CF installation" with HAProxy terminating SSL, there would be nothing to prevent UAA and Login from servicing requests via HTTP without this setting, unless you also removed the HTTP listenter from HAProxy, which would disable HTTP for everything in the environment.

Am I missing something?  Based on my understanding this is a very necessary setting, so unless there is some other way to configure this that I'm missing, this issue needs to be re-opened.

Aaron

**Comment by amhuber** [comment]
I just tested this to confirm, and without the require_https = true, the UAA is happily accepting my username and password and issuing me a token in clear text over HTTP through HAProxy as it's not enforcing the X-Forwarded-Proto check.  This means with the require_https setting there is no way to enforce password and token security.

The login server is using the login.protocol = https setting to enforce HTTPS via the header.  There is a reference to uaa.require_https in login.yml but I'm not sure what it's using it for.

Both the login and UAA healthchecks are current broken now that I test them.  The UAA healthz just returns an error when require_https is true (what I submitted the issue for), but the login server is issuing a 302 redirect to HTTPS when you hit healthz and login.protocol = https. Monit is apparently OK with the 302 and doesn't kill the login server, but it's still not actually checking the health.

The actual fix would be for both components to allow HTTP traffic to healthz even when uaa.require_https and login.protocol are configured.

Please re-open this issue or explain how this setting isn't needed.

Aaron

**Comment by rdgallagher** [comment]
Hi Aaron,

Thanks for testing and the info. We're reopening the issue and investigating, and will get back to you.

In the meantime, other than setting `require_https` to `false`, as a workaround you could edit the monit script either directly on the UAA VM (/var/vcap/data/jobs/uaa/monit) or in cf-release (/jobs/uaa/monit).

Rob & Bokuk

**Comment by d** [comment]
Couple points:
- [`required_https` does not check `X-Forward-Proto` header](https://github.com/cloudfoundry/uaa/blob/5d2d698dd2f3e79706326e0b343ee078a4fa525b/common/src/main/java/org/cloudfoundry/identity/uaa/security/web/SecurityFilterChainPostProcessor.java). You have been misinformed.
- Where did you get the link to submit your password in clear text? I believe our default configuration never generates non-TLS (http) links in either the web UI or for CLI.
- If your custom client submits password and username over cleartext, you're in deeper trouble than the token being evesdropped.

[Re: "did I miss anything?"](http://www.loc.gov/poetry/180/013.html)

**Comment by amhuber** [comment]
With all due respect, I'm not the one who's misinformed (shortening some of the output to make it readable):

    root@9e5ad843-0182-4708-ad18-3aba64c6007a:~# cat /var/vcap/jobs/uaa/config/uaa.yml | grep require_https
    require_https: true
    root@9e5ad843-0182-4708-ad18-3aba64c6007a:~# curl -v http://127.0.0.1:8080/healthz
    HTTP Status 400 - request must be over https
    root@9e5ad843-0182-4708-ad18-3aba64c6007a:~# curl -H"X-Forwarded-Proto: https" http://127.0.0.1:8080/healthz
    ok

    root@3b8079c4-097a-4330-a0d5-d96469b2babf:~# cat /var/vcap/jobs/login/config/tomcat/web.xml | grep -i confidential
               <transport-guarantee>CONFIDENTIAL</transport-guarantee>
    root@3b8079c4-097a-4330-a0d5-d96469b2babf:~# curl -v http://127.0.0.1:8080/healthz
    < HTTP/1.1 302 Found
    < Location: https://127.0.0.1/healthz
    root@3b8079c4-097a-4330-a0d5-d96469b2babf:~# curl -H"X-Forwarded-Proto: https" http://127.0.0.1:8080/healthz
    ok

The reason you don't see it in the UAA or Login code is because Tomcat is taking care of it for you:

https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/webapp/WEB-INF/spring-servlet.xml#L58
https://github.com/cloudfoundry/uaa/blob/master/common/src/main/java/org/cloudfoundry/identity/uaa/security/web/SecurityFilterChainPostProcessor.java#L170
https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/filters/RemoteIpFilter.html

https://github.com/cloudfoundry/cf-release/blob/master/jobs/login/templates/web.xml.erb#L4609-L4619
http://mail-archives.apache.org/mod_mbox/tomcat-users/201410.mbox/%3C542C4559.3010709@mayr-stefan.de%3E

You're implying that as long as everyone who ever touches our UAA API uses TLS then we should be fine.  In my opinion, that's not security, just hoping for the best.  That would be like my bank allowing HTTP to their site as long as they only send me https:// links and calling it secure.

In order to deploy CF I must ensure that there is no way for the username and password to appear in clear text on the network, and fortunately I can do that by:

* Ensuring that all traffic to UAA and Login has to go through HAProxy
* Ensuring that HAProxy will set the X-Forwarded-Proto header so it can't be spoofed
* Enable uaa.require_https so that UAA will reject any non-TLS connections
* Enable login.protocol = https so that Login will reject any non-TLS connections

That all worked until you guys added the monit checks for healthz.  :-)

I would still prefer that the healthz checks be modified to not require TLS even when it's forced for the other endpoints, but it occurs to me that a simple work-around would be to just have monit add the X-Forwarded-Proto header to it's check.  I'll test that out and reply shortly with a working configuration.

Aaron

**Comment by amhuber** [comment]
As expected, this can be fixed by simply adding the header to the monit script.  Without the header:

    root@9e5ad843-0182-4708-ad18-3aba64c6007a:~# monit validate
    HTTP error: Server returned status 400
    'uaa' failed protocol test [HTTP] at INET[localhost:8080/healthz] via TCP

Unfortunately, monit doesn't directly support adding headers until version 5.9, but we can do the same thing with a TCP check and sending the HTTP request by hand.  I've tested this on both UAA and Login, and this also actually checks that the result of the healthcheck is "ok" as opposed to just making sure that the port is alive:

    if failed port 8080
      send "GET /healthz HTTP/1.1\r\nHost: 127.0.0.1:8080\r\nX-Forwarded-Proto: https\r\nConnection: close\r\n\r\n\"
      expect "ok"
      with timeout 60 seconds for 10 cycles
    then restart

This would also work fine regardless of the login.protocol or uaa.require_https setting as the header will just be ignored if they aren't configured.  If you guys would like I'd be happy to submit a pull request to change the monit script for both components.

Aaron

**Comment by fhanik** [comment]
@amhuber I would favor simply removing the X-Forward-Proto requirement from the /healthz end point for our next release of the UAA. 

In the meantime, you can submit a PR/fix to the monit script. That would be much appreciated. Remember to take into account that the port is configurable, and not hard coded to 8080 in the manifest.

We'll create a story for sorting out the actual meaning of require_https. The setting implies that traffic should be protected under some sort of encryption, so we're not sure if just the presence of a header can negate that requirement.

**Comment by amhuber** [comment]
Great, thanks for the update.  I'll submit a pull request shortly to update the monit scripts and I'll definitely be sure to include the parameter for the port number.  I actually need to test if the port is needed on the host header, I'm hoping I don't need to specify it twice.

I definitely agree that clarifying the uaa.require_https and login.protocol settings (either by renaming them or in documentation) is a good idea.  They are fully secure in the scenario I lay out above (HAproxy configuration + the settings), but it's a good idea to make that obvious to anyone deploying the platform.  It's a pretty typical pattern for SSL offload to use the header and you actually document it for the run.pivotal.io platform (http://docs.pivotal.io/pivotalcf/opsguide/ssl-term.html).

Finally, I would be very happy if the tracker created above to remove the setting (https://www.pivotaltracker.com/story/show/89047788) was either deleted or modified to be more reflective of what you plan to do, just so it doesn't get worked on accidentally.  :-)

Aaron

**Comment by sreetummidi** [comment]
I have updated the description on story to reflect our fix strategy

**Comment by fhanik** [comment]
[Proposed fix](https://github.com/cloudfoundry/uaa/commit/3865332af8b1011968a883fdb57aa50fc10d0340)

**Comment by fhanik** [comment]
Merged to [develop](https://github.com/cloudfoundry/uaa/commit/9f703a011a6ab2fd81b52a8c897ad627cfbe58c4)

**Comment by amhuber** [comment]
That looks like it should do it.  Will this also cover login after they have been merged into a single job?

**Comment by fhanik** [comment]
Yes, our develop branch contains the merged code.
