### ISSUE TITLE
There was an error when authenticating against the external identity provider: Could not verify token signature.

### ISSUE THREAD

**Issue by krecmech** [cloudfoundry/uaa#1280]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
`{
	"app": {
		"version": "4.27.0"
	},
	"showLoginLinks": true,
	"links": {
		"uaa": "http://localhost:8080/uaa",
		"login": "http://localhost:8080/uaa"
	},
	"zone_name": "uaa",
	"entityID": "cloudfoundry-saml-login",
	"commit_id": "76e960d",
	"idpDefinitions": {},
	"prompts": {
		"username": ["text", "Username"],
		"password": ["password", "Password"],
		"passcode": ["password", "Temporary Authentication Code ( Get one at https://dl-bnaaeap2058.dev.healthcareit.net:8443/rem-uaa/passcode )"]
	},
	"timestamp": "2019-01-25T17:50:24+0000"
}`

### How are you deploying the UAA?

I am deploying the UAA

deployed uaa.war in tomcat container

### What did you do?

- configured UAA to federate with external IdP (used Ping for my use case).  
- on the UAA login screen I see link for "my oidc provider".  Click on link takes me to the IdP login screen
- after I login to IdP, there is redirect from IdP -> UAA with the tokens (id_token and access_token).  
- token info : when I decode the id_token, alg used in RS512 but for access_token is RS256
- RsaVerifier.java verify fails to verify the signature for id_token

Looking at the code RsaVerifier.java - default initialized to SHA256withRSA and which is used (since I added few lines to RsaVerifier to debug the algorithm used in the verify method call.  I deployed this updated jar (spring-security-jwt).  If I comment the verify method uaa continues and generates its tokens and integration works fine.  

### What did you expect to see? What goal are you trying to achieve with the UAA?

code should look at alg in the header of the token and use the right hashing algorithm.

JwkDefinitionSource.java - I see this has write calls to get the RsaVerifier.  I am not sure why this is not used for this flow.

### What did you see instead?

Please include UAA logs if available.

`
 cloudfoundry-identity-server - ???? [https-jsse-nio-8443-exec-6] .... ERROR --- XOAuthAuthenticationFilter: XOauth Authentication exception
error="invalid_token", error_description="Could not verify token signature."
        at org.cloudfoundry.identity.uaa.util.TokenValidation.checkSignature(TokenValidation.java:122)
        at org.cloudfoundry.identity.uaa.util.TokenValidation.buildIdTokenValidator(TokenValidation.java:78)
        at org.cloudfoundry.identity.uaa.provider.oauth.XOAuthAuthenticationManager.validateToken(XOAuthAuthenticationManager.java:523)
        at org.cloudfoundry.identity.uaa.provider.oauth.XOAuthAuthenticationManager.getClaimsFromToken(XOAuthAuthenticationManager.java:498)
`

**Comment by strehle** [comment]
Thanks for reporting, this will be fixed with next release.
The full JWS list, e.g. https://datatracker.ietf.org/doc/html/rfc7518#section-3.1 still is open
