### ISSUE TITLE
Also use environment variables to configure UAA

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry/uaa#1281]
Since we're trying to run UAA in containers, we should also make it configurable using environment variables.

Some reasons why:
- That's what 12 factor apps should do https://12factor.net/
- Cloud Foundry [does it](https://docs.cloudfoundry.org/devguide/services/application-binding.html)
- Users no longer need to understand UAA's config file or use workarounds #904 
- Easier to run UAA as a Cloud Foundry app

**Comment by strehle** [comment]
@viovanov issue is valid, would you propose a PR for it ?
e.g. StringSubstitutor could be used https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlProcessor.java

https://gist.github.com/amr/897109c2c9a5d3b317e6a97fe74f321f

**Comment by viovanov** [comment]
@strehle unfortunately I can't find the time to help, sorry - I'm not working with UAA currently
