### ISSUE TITLE
Exposse number of active jdbc connections /  Database connections

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/uaa#1284]
### This is more of a feature request.

we would like the UAA metrics to provide the total number of JDBC connections that are being used by per instance to see if an instance is increasing suddenly 

The current metrics shows only total count of completed JDBC connections and healthy count. 
It would be nice to get the total number of active connections per instance as well.

**Comment by strehle** [comment]
see here following properties will be exposed via JMX
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/resources/spring/data-source.xml#L65
getMaxIdle,getMaxActive,getNumIdle,**getNumActive**
