### ISSUE TITLE
Client resource_ids should always be an array

### ISSUE THREAD

**Issue by sneal** [cloudfoundry/uaa#1287]
### What version of UAA are you running?
74.5.5

### How are you deploying the UAA?
I am deploying the UAA as part of a Tanzu Application Service.

### What did you do?
Executing `uaa get-client identity` against a Tanzu Application Service installation, https://github.com/cloudfoundry-incubator/uaa-cli/issues/63

### What did you expect to see? What goal are you trying to achieve with the UAA?
I would expect the UAA server to honor the data contract and always return an array for client resource_ids.

### What did you see instead?
Resulted in `json: cannot unmarshal string into Go struct field Client.resource_ids of type []string`. It seems the builtin `identity` client returns a single string for the client's resource_ids instead of an array.

**Comment by shamus** [comment]
Hi there. While I agree that the uaa cli should be able to handle the responses coming from the UAA API.

Closing this issue in favor of cloudfoundry-incubator/uaa-cli#63
