### ISSUE TITLE
How to customize the login error / session expired page

### ISSUE THREAD

**Issue by JaiVignesh-2309** [cloudfoundry/uaa#1289]
When an IDP is configured on the custom UAA and the login session expires, refreshing the page navigates to an error page. Is there a way to customize this page, like changing the icon.

![image](https://user-images.githubusercontent.com/23031682/81816762-6a7dc500-9549-11ea-9ac3-0f5624701dfd.png)

Best Regards,
Jai

**Comment by strehle** [comment]
The page is customized already because this is the SAP (forked) color, so you have to ask these colleagues
