### ISSUE TITLE
Can not obtain token through the uaa API

### ISSUE THREAD

**Issue by andrei1610399** [cloudfoundry/uaa#129]
How can I get token with user name/password and validate token using http uaa api?
API endpoints described in the documentation don't work.
Could you provide clear example that I can user from Postman or Python code
for the following workflow:
- Log in using user name and password
- Get token
- Validate token

**Comment by fhanik** [comment]
I would email vcap-dev mailing list. 

Start out with starting the server per 
https://github.com/cloudfoundry/uaa

documentation. that is 

    ./gradlew run

after that, a simple curl command will get you a token

curl -v -XPOST --data "username=marissa&password=koala&client_id=cf" -u "cf:" "http://localhost:8080/uaa/oauth/token?grant_type=password&client_id=cf"

**Comment by fhanik** [comment]
If you wish to validate the token, check the /check_token API at 
https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#oauth2-token-validation-service-post-check_token

**Comment by anitalpatil** [comment]
I am integrating cf uaa with third party application (using sso), in third party application am unable to get token of uaa. Is there any thing settings needs to be done at uaa? becoz  am able to integrate my third party application with git.
