### ISSUE TITLE
Documentation Client Credentials Token: scope parameter

### ISSUE THREAD

**Issue by nenaraab** [cloudfoundry/uaa#1306]
### What version of UAA are you running?
74.18.0

### What did you do?
called oauth token (grant-type client-credentials) with `scope` request parameter and it worked: i was able to restrict the scopes of this token to those, I've requested for.

### What did you expect to see? What goal are you trying to achieve with the UAA?
https://docs.cloudfoundry.org/api/uaa/version/74.18.0/index.html#client-credentials-grant
should document scope parameter for all flows  as described here
https://docs.cloudfoundry.org/api/uaa/version/74.18.0/index.html#jwt-bearer-token-grant

Or, have you omitted it on purpose?

**Comment by shamus** [comment]
Thanks! I think this was an accidental omission.  The docs should be updated with the next release.

**Comment by nenaraab** [comment]
@shamus 
@strehle 
Thanks a lot for the fast correction!
