### ISSUE TITLE
AccountsController gives misleading username_exists error if password validator fails

### ISSUE THREAD

**Issue by mthx** [cloudfoundry/uaa#131]
If I:

1. set a non-zero value for password-policy.required-score
2. attempt to create an account via /uaa/create_account with a non-compliant password

...then the InvalidPasswordException from JdbcScimUserProvisioning.createUser(ScimUser, String) is wrapped up in a UaaException and mishandled as "username_exists" in AccountsController.sendActivationEmail.  So the end user is told:

> There is already a user with that username

I'll happily look at fixing this, but I'd like some guidance on what is supposed to happen.  To me, even if UAA output the message "Insufficient password strength: 5" out from ZxcvbnPasswordValidator, it would be rather cryptic for the end user.  Has there been any work on implementing a password strength meter?  I've noticed there is a REST endpoint that could be used.  Any other suggestions as to how best to approach this welcome.

**Comment by fhanik** [comment]
The ZxcvbnPasswordValidator has been deprecated in favor of the Passay library, which yields more user friendly password rules 6b1411ae8dbbea974e9bacfb003b0148b6bcb8f3
