### ISSUE TITLE
RemoteTokenServices does not return the "issu" from the JWT

### ISSUE THREAD

**Issue by dave-chen** [cloudfoundry/uaa#133]
Hi,
We need to get the "issu" from the JWT but the RemoteTokenServices does not return it. We have to modify the code to extract the "issu" from JWT and set it in the loadAuthentication method as following:

        if (map.containsKey("iss")) {
            Map<String, String> requestParameters = new HashMap<String, String>();
            requestParameters.put("iss", (String) map.get("iss"));
            clientAuthentication.setRequestParameters(requestParameters);
        }

Can you include this in the future version/release?

Thanks,,
Dave

**Comment by fhanik** [comment]
Fixed.
https://www.pivotaltracker.com/story/show/90296800
