### ISSUE TITLE
ISSUER_URI equals to token_endpoint

### ISSUE THREAD

**Issue by peacetrue** [cloudfoundry/uaa#1332]
![image](https://user-images.githubusercontent.com/38878763/85524432-bf2d5900-b63a-11ea-94cf-d02635b17ed5.png)

when I test in spring:

![image](https://user-images.githubusercontent.com/38878763/85526980-087ea800-b63d-11ea-882b-0152593caab0.png)

**Comment by shamus** [comment]
I'm not 100% certain, but is this the same issue as https://github.com/cloudfoundry/uaa/issues/805?

**Comment by peacetrue** [comment]
@shamus yes, same to #805
