### ISSUE TITLE
Configurable prompt labels

### ISSUE THREAD

**Issue by jeseen** [cloudfoundry/uaa#1334]
Is it possible to have the prompt labels in IdentityZoneConfiguration configurable in the manifest? Currently they are hard coded in uaa/model/src/main/java/org/cloudfoundry/identity/uaa/zone/identityZoneConfiguration.java :
`    private List<Prompt> prompts = Arrays.asList(
        new Prompt("username", "text", "Email"),
        new Prompt("password", "password", "Password"),
        new Prompt("passcode", "password", "Temporary Authentication Code (Get on at /passcode)")
    );`
In case you don't use an Email address to authenticate, this is a bit confusing for end users.

**Comment by strehle** [comment]
in login.yml, see
https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/webapp/WEB-INF/spring-servlet.xml#L380-L397
e.g.
login.prompt.username.text
login.prompt.password.text
