### ISSUE TITLE
JQuery requires version bump

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#1340]
### What version of UAA are you running?

74.21.0

### How are you deploying the UAA?

- using a bosh release

### What did you do?

Call the following URL via browser:
https://\<uaa URL\>/vendor/jquery/javascripts/jquery.js

### What did you expect to see? What goal are you trying to achieve with the UAA?

Newest JQuery version (currently 3.5.1)

### What did you see instead?

Older JQuery version (3.4.1)

The UAA file that requires the version update is:
https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/webapp/vendor/jquery/javascripts/jquery.js

_Note:_
It seems that JQuery 3.5.1 is not completely backward compatible:
http://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
`The jQuery team agreed it was necessary to fix this in a minor release, even though some code relies on the previous behavior and may break.`

**Comment by shamus** [comment]
Thanks for the report @tack-sap, we should see if dependabot can be used to keep this up to date.  Until that happens, if you'd like to submit a PR we'd happily accept it.
