### ISSUE TITLE
External IDP using OIDC token still valid after UAA tokens are revoked on logout

### ISSUE THREAD

**Issue by bdselle** [cloudfoundry/uaa#1341]
### What version of UAA are you running?

uaa74.21.0

### How are you deploying the UAA?

I am deploying the UAA

Using uaa.war in Tomcat9

### What did you do?

1. Configured UAA to use an external IDP via OIDC.
2. After logging into application and getting an id and access token, logging out of said application.
3. Request to logout.do happens.
4. I am revoking the tokens for a given user and client via the revoke tokens api (oauth/tokens/revoke/user/{userId}/client/{clientId}). Those tokens seem to be deleted from the revocable_tokens table (I am hooked to a postgresql db). 
4. Application is automatically logged back in without redirecting back to the login form.

What seems to be happening is the tokens are being revoked in UAA but UAA seems to be contacting the external OIDC application (Okta in my case) and it still has a valid session so UAA is issuing new access tokens. Is there a way to have UAA also revoke the tokens or invalidate the session in the external IDP (Okta)?

### What did you expect to see? What goal are you trying to achieve with the UAA?

I was expecting UAA to contact Okta and invalidate the user session or revoke the tokens using the metadata in the discovery URL setting for the oauth provider in the yaml.

### What did you see instead?

Application auto logged back in with new access tokens from UAA being issued.

**Comment by shamus** [comment]
I think you're asking about Single Log Out, is that right? I believe there is further configuration you need to do with the external IdP to achieve this outcome. See here:

https://help.okta.com/en/prod/Content/Topics/Apps/Apps_Single_Logout.htm

**Comment by bdselle** [comment]
I was working on it and found that. I am calling logout.do for UAA and in the redirect passing the logout URL for Okta. Once logout.do completes for UAA it redirects to Okta (which is whitelisted in the yml) and logs out of Okta and redirects appropriately. Closing this issue.
