### ISSUE TITLE
Why UAA is considering username field instead of email field from uaa users table for sending reset password link ?

### ISSUE THREAD

**Issue by ShilpaVKulkarni** [cloudfoundry/uaa#1343]
Hi All,

while creating user I have not given email address as username  but the user is having email address in email field. when i try to check the forgot password(reset password) functionality it is not sending password reset link to that email address. So again I tried by changing the username to the proper email address  and given that email address (which is username) for sending reset password link  then the password reset link has been sent to the email address which is saved as username filed. Why UAA is considering username field instead of email field from uaa users table? Can anyone please answer to this?

**Comment by strehle** [comment]
Have you solved this, if not please re-open

Relation of username and email is maybe not known and was changed with https://github.com/cloudfoundry/uaa/commit/3a7749a6d327cacbc7bf93cd50a0e2dee0b935ba but for email there is an email_verified and this could lead to the situation.

code of reset is here
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/account/PasswordResetEndpoint.java
