### ISSUE TITLE
Account Chooser does not work without IdP discovery

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#1345]
### What version of UAA are you running?

74.21.0

### How are you deploying the UAA?

- using a bosh release

### What did you do?

An [identity zone](https://docs.cloudfoundry.org/api/uaa/version/74.21.0/index.html#creating-an-identity-zone) was created with `accountChooserEnabled` set to `true` and `idpDiscoveryEnabled` set to `false`. 

### What did you expect to see? What goal are you trying to achieve with the UAA?

The account chooser starts up and the user is able to select an account. Further, the user can choose the option "Sign in to another account" on the account chooser page and gets redirected to a page similar to the [otherAccountSignIn page](https://github.com/cloudfoundry/uaa/blob/c8589816062dbcc8dd75357945327a161173681e/server/src/main/resources/templates/web/idp_discovery/account_chooser.html#L42). In case `idpDiscoveryEnabled` is set to `false` the page provides an input field for the origin value, so that the user can state the IdP for redirection. If the parameter `defaultIdentityProvider` is set for the identity zone, the user shall have a simple way to use that option without providing the origin. Once the user presses a button to continue, the redirection happens to the IdP that is configured for the origin value. If the origin value is invalid, an error message is shown to the end user.

### What did you see instead?

The account chooser did not show up during login. Instead the normal login page appears.

**Comment by shamus** [comment]
Hi @torsten-sap, does this bug related to any of the account choose PRs that were merged recently?

**Comment by torsten-sap** [comment]
@shamus No, this is not related in any way. For some reason the account chooser never worked without IdP discovery.

**Comment by strehle** [comment]
@torsten-sap is this solved now ?

**Comment by strehle** [comment]
not fixed until https://github.com/cloudfoundry/uaa-release/pull/303 is made available

**Comment by strehle** [comment]
fixed with 
https://bosh.io/releases/github.com/cloudfoundry/uaa-release?version=75.5.0
re-open if not fixed
