### ISSUE TITLE
Postgresql requires version bump

### ISSUE THREAD

**Issue by Subbu3992** [cloudfoundry/uaa#1347]
### What version of UAA are you running?

74.22.0

### How are you deploying the UAA?

I am deploying the UAA

- using a bosh release I downloaded from bosh.io

### What did you expect to see? What goal are you trying to achieve with the UAA?
PostgreSQL JDBC Driver 42.2.13

### What did you see instead?
PostgreSQL JDBC Driver 42.2.12

Notes:
PostgreSQL JDBC Driver versions < 42.2.13 is prone to XXE vulnerability.
https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13
https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html

**Comment by shamus** [comment]
Thanks for the report! Indeed this needs to be bumped.  👍 

This should be resolved with the merging of https://github.com/cloudfoundry/uaa/pull/1367

Expect to see this in the next release.

**Comment by strehle** [comment]
@shamus  re-opened it because uaa.war does not include an updated version of https://jdbc.postgresql.org/documentation/changelog.html but still version x.12 - mentioned in this ticket, therefore add the version label to the gradle definition
