### ISSUE TITLE
App crashes when pushed to CF

### ISSUE THREAD

**Issue by frankimhof** [cloudfoundry/uaa#1354]
### What version of UAA are you running?
I don't know which version I'm using. I just downloaded it from github today.

### How are you deploying the UAA?
I am deploying the UAA as part of a commercial Cloud Foundry distribution
I also ran it locally (see last section)

### What did you do?
`git clone git://github.com/cloudfoundry/uaa.git`
`./gradlew :cloudfoundry-identity-uaa:war`
`cf push my-uaa -m 512M -p uaa/build/libs/cloudfoundry-identity-uaa-0.0.0.war --no-start`
`cf set-env my-uaa SPRING_PROFILES_ACTIVE default`
`cf start my-uaa`

### What did you expect to see? What goal are you trying to achieve with the UAA?
I expected the app to start and run without errors on the CF space.

### What did you see instead?
App crashed and I got the following error in the log file:
`[APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.core.StandardContext SEVERE  One or more Filters failed to start. Full details will be found in the appropriate container log file`
`[APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.core.StandardContext SEVERE  Context [] startup failed due to previous errors`
`[APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.loader.WebappClassLoaderBase   WARNING The web application [ROOT] registered the JDBC driver [org.hsqldb.jdbc.JDBCDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.`

### When running locally
When I do 
`./gradlew run`
and
`curl localhost:8080/uaa/info -H'Accept: application/json'`
then I get the following
`{"app":{"version":"0.0.0"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"cf8506e","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2020-07-16T00:57:48+0200"}`

**Comment by shamus** [comment]
It doesn't look like the UAA deployed via `cf push` has been fully configured.

The UAA comes with a default [config file](https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/resources/uaa.yml), but those configurations are not enough for the UAA to start up. This config is packaged up in the `uaa.war` and is available via the classpath. On start up, the UAA finds this file on the classpath and consumes it.

The UAA  provides a [minimal development configuration](https://github.com/cloudfoundry/uaa/blob/develop/scripts/cargo/uaa.yml) which is meant to make getting started as a developer easy. This is not packed up with the `uaa.war`, instead build.gradle points the UAA to this extra config on start up.  See [here](https://github.com/cloudfoundry/uaa/blob/develop/build.gradle#L187). This is what happens behind the scenes when `./gradlew run` is invoked.

When using `cf push`, a config for the UAA will need to be made available via one of the methods used by [this class](https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializer.java).

**Comment by frankimhof** [comment]
Hey Shamus, thank you so much for your answer.

So did I understand correctly:
1. I should customize the "minimal development configuration" file
2. I should make this file available when cf pushing

Can you elaborate on the 2nd step? I don't know how to do this.

**Comment by frankimhof** [comment]
Ok, I just realized that I don't even need uaa. I can use a ready-made service in my cf-space.
Thanks anyways!
