### ISSUE TITLE
Activation link is not received on email while creating User

### ISSUE THREAD

**Issue by akshaygik** [cloudfoundry/uaa#1368]
### What version of UAA are you running?
V74.23.0

### How are you deploying the UAA?
Inside docker container on Docker Desktop

### What did you do?
On login after entering email and password to create user, it says activation link is sent to mail but its not received (no logs created in uaa). I believe some SMTP settings are need to be done but could not find any steps mentioned inside doc. 
May be you help me with more better way to create user. I have already created superadmin user via initial yml fie configuration.

Also, I have pulled an image **docker pull cfidentity/uaa:74.23.0**  can you confirm exact git repository corresponding to this image so that, I can be sure while referring to UAA documentations.

**Comment by akshaygik** [comment]
Hi, any suggestions on this problem?

**Comment by shamus** [comment]
Hi there! Sorry for the delay.

Are you using the YTT templates to generate the UAA K8s resources (config map, secrets, etc?). If so, you can use these configuration options:

You can learn about what SMTP values can be specified when rendering the templates here:

https://github.com/cloudfoundry/uaa/blob/f49f7d7a3a9919801124618ba0bfc844c341e419/k8s/templates/values/_values.yml#L42

If you're creating your config map by hand, you can see here for an example:

https://github.com/cloudfoundry/uaa/blob/f49f7d7a3a9919801124618ba0bfc844c341e419/k8s/templates/uaa.lib.yml#L27

One thing to keep in mind is that we don't consider the docker UAA release to be stable yet, so there could be breaking changes in a future release.

**Comment by akshaygik** [comment]
> Hi there! Sorry for the delay.
> 
> Are you using the YTT templates to generate the UAA K8s resources (config map, secrets, etc?). If so, you can use these configuration options:
> 
> You can learn about what SMTP values can be specified when rendering the templates here:
> 
> https://github.com/cloudfoundry/uaa/blob/f49f7d7a3a9919801124618ba0bfc844c341e419/k8s/templates/values/_values.yml#L42
> 
> If you're creating your config map by hand, you can see here for an example:
> 
> https://github.com/cloudfoundry/uaa/blob/f49f7d7a3a9919801124618ba0bfc844c341e419/k8s/templates/uaa.lib.yml#L27
> 
> One thing to keep in mind is that we don't consider the docker UAA release to be stable yet, so there could be breaking changes in a future release.

Thanks for reply.
I am not using ytt so will prefer second approach.
One more thing, I understand that current docker release is not stable but, can you let me know exact git hub repo corresponding to image tag I am using? This will help me to relate more on code and documentation I am referring.

**Comment by shamus** [comment]
The `cfidentity/uaa` image contains artifacts generated from the code in this repo.

**Comment by shamus** [comment]
The `cfidentity/uaa` image contains artifacts generated from the code in this repo.

I think you should have what you need to configure an SMTP server in the UAA.  I'm going to close this issue.
