### ISSUE TITLE
How i can disable spring security headers or append my landing page to i frame

### ISSUE THREAD

**Issue by subinsoman** [cloudfoundry/uaa#1369]
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

i want to avoid the above headers

**Comment by shamus** [comment]
Hi there. I'm not sure what iFrame you're referring to.

Could you provide some more detail on what you're trying to achieve?

**Comment by subinsoman** [comment]
Hi there i want to disable
