### ISSUE TITLE
Authentication issues during using Nginx proxy

### ISSUE THREAD

**Issue by shaikshajahan7640** [cloudfoundry/uaa#1371]
I have to use an Nginx proxy for one of my web application which is using UAA. when I configure Nginx for my web application, during login service it restricts and again redirects the login portal only. again when I remove the Nginx proxy it successfully login into the portal. it may be due to the restriction of CSRF. if it is true how can achieve login using Nginx proxy.

**Comment by shamus** [comment]
Hi. How are you deploying the UAA? What version are you using?

Answering the questions in the [issue template](https://github.com/cloudfoundry/uaa/blob/develop/issue_template.md) help us help you better.

The UAA BOSH release supports a set of proxy settings, have you explored them?

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L146
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L151
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L169
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L172
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L175
