### ISSUE TITLE
Allow an user to request his own tokens without a special scope like "tokens.list"

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#1372]
### What version of UAA are you running?

74.23.0

### How are you deploying the UAA?

I am deploying the UAA
- using cf-deployment

### What did you do?

As an end user, I want to retrieve the list of tokens for my own user. Thus, I am calling the existing endpoint `/oauth/token/list/user/{userId}` ([API documentation](https://docs.cloudfoundry.org/api/uaa/version/74.23.0/index.html#list-all-tokens-for-a-user)).

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expect that I can call the endpoint without any special scope like "tokens.list" for my **own** user.

### What did you see instead?

The API requires scope "tokens.list". But this scope has too much authorizations in order to assign it to a common user.

**Comment by shamus** [comment]
This seems like a reasonable request. Also, [revoke tokens](https://docs.cloudfoundry.org/api/uaa/version/74.23.0/index.html#revoke-tokens) has a similar access policy.

Is this something you'd like to provide a PR for?

**Comment by strehle** [comment]
https://github.com/cloudfoundry/uaa/pull/1446#issuecomment-744879508
