### ISSUE TITLE
Oracle Db support for UAA

### ISSUE THREAD

**Issue by ASHISHTOM** [cloudfoundry/uaa#1373]
I found that UAA supports the databases like mysql, hsql, postgresql and sqlserver. And I also read that UAA was supporting Oracle before the license issues. 

Is there any way to get support for the Oracle DB??

**Comment by shamus** [comment]
I don't think it's likely. 

This is first request I've seen for Oracle support. I don't get the impression there's much need for this in the community.

**Comment by strehle** [comment]
please see discussion https://github.com/cloudfoundry/uaa/issues/1751
