### ISSUE TITLE
Login server references need cleanup

### ISSUE THREAD

**Issue by mikeroda** [cloudfoundry/uaa#138]
Now that the login server has been merged into UAA as a module, there are several places in the doc that refer to the login server as a separate entity and need to be cleaned up. In login.yml there is the client secret and uaa URLs, can those be removed?  Can the login client be removed from oauth-clients.xml?

**Comment by fhanik** [comment]
The login client in oauth-clients.xml is still valid. We still support the endpoints used by the login-server, and they are used by other products. For the rest of the issues, a PR would be helpful, or more specific references.
