### ISSUE TITLE
Unable to get the oauth/authorize endpoint to work

### ISSUE THREAD

**Issue by githubuser88442** [cloudfoundry/uaa#1381]
I've been trying to get a authorization code from the oauth/authorize endpoint for 3 days now with no success.

Neither of the examples in https://docs.cloudfoundry.org/api/uaa/version/74.23.0/index.html#authorization
nor in https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#non-browser-requests-code-get-oauth-authorize
work out of the box, and I am not clear on how to get them to work.

I either run into some issue with invalid/insufficient scopes, or get a 500 server error.
I also made a StackOverflow post with more detail: https://stackoverflow.com/questions/63490231/cloudfoundry-uaa-oauth-authorize-endpoint-giving-500-internal-server-error

Could someone please demonstrate/explain how to create a valid call to the oauth/authorize endpoint?

Another thing what I don't understand, is why when I add "uaa.admin,uaa.user" to the scope of the "login" account, it doesn't preserve:

Authenticate as the admin client:
`$ uaac token client get admin -s adminsecret`

Update the login client to include the scope it had previously, as well as "uaa.login" and "uaa.admin":
```
$ uaac client update login --scope clients.read,emails.write,scim.userids,password.write,idps.write,notifications.write,oauth.login,scim.write,critical_notifications.write,uaa.user,uaa.admin
/var/lib/gems/2.7.0/gems/cf-uaa-lib-3.14.3/lib/uaa/scim.rb:261: warning: URI.escape is obsolete
/var/lib/gems/2.7.0/gems/multi_json-1.12.2/lib/multi_json/options_cache.rb:12: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/json_pure-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/var/lib/gems/2.7.0/gems/cf-uaa-lib-3.14.3/lib/uaa/scim.rb:195: warning: URI.escape is obsolete
/var/lib/gems/2.7.0/gems/multi_json-1.12.2/lib/multi_json/options_cache.rb:12: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/json_pure-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/var/lib/gems/2.7.0/gems/cf-uaa-lib-3.14.3/lib/uaa/scim.rb:273: warning: URI.escape is obsolete
/var/lib/gems/2.7.0/gems/json_pure-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
  scope: clients.read emails.write scim.userids password.write idps.write notifications.write oauth.login uaa.admin
      scim.write critical_notifications.write uaa.user
  client_id: login
  resource_ids: none
  authorized_grant_types: refresh_token client_credentials authorization_code
  redirect_uri: http://localhost:800/api/v1/health
  autoapprove:
  access_token_validity: 444444
  refresh_token_validity: 44444
  authorities: clients.read emails.write scim.userids password.write idps.write notifications.write oauth.login
      scim.write critical_notifications.write
  name: login
  signup_redirect_url:
  required_user_groups:
  lastmodified: 1597922528189
```
As the scope in the output now includes uaa.user and uaa.admin, it seems as if it was successful.

However, when I authenticate as the login user:
`$ uaac token client get login -s loginsecret`

And check the context:
```
$ uaac context

[0]*[http://localhost:8080/uaa]

  [4]*[login]
      client_id: login
      access_token: eyJhbGciOiJIUzI1NiIsImprdSI6Imh0dHBzOi8vbG9jYWxob3N0OjgwODAvdWFhL3Rva2VuX2tleXMiLCJraWQiOiJsZWdhY3ktdG9rZW4ta2V5IiwidHlwIjoiSldUIn0.eyJqdGkiOiJjOTFlOWY2MjkyNGQ0MzliOGQ5OTg1NGRlMDMyNjdlZSIsInN1YiI6ImxvZ2luIiwiYXV0aG9yaXRpZXMiOlsiY2xpZW50cy5yZWFkIiwiZW1haWxzLndyaXRlIiwic2NpbS51c2VyaWRzIiwicGFzc3dvcmQud3JpdGUiLCJpZHBzLndyaXRlIiwibm90aWZpY2F0aW9ucy53cml0ZSIsIm9hdXRoLmxvZ2luIiwic2NpbS53cml0ZSIsImNyaXRpY2FsX25vdGlmaWNhdGlvbnMud3JpdGUiXSwic2NvcGUiOlsiY2xpZW50cy5yZWFkIiwiZW1haWxzLndyaXRlIiwic2NpbS51c2VyaWRzIiwicGFzc3dvcmQud3JpdGUiLCJpZHBzLndyaXRlIiwibm90aWZpY2F0aW9ucy53cml0ZSIsIm9hdXRoLmxvZ2luIiwic2NpbS53cml0ZSIsImNyaXRpY2FsX25vdGlmaWNhdGlvbnMud3JpdGUiXSwiY2xpZW50X2lkIjoibG9naW4iLCJjaWQiOiJsb2dpbiIsImF6cCI6ImxvZ2luIiwiZ3JhbnRfdHlwZSI6ImNsaWVudF9jcmVkZW50aWFscyIsInJldl9zaWciOiIyNDQzOWM1NiIsImlhdCI6MTU5NzkyMjY4OCwiZXhwIjoxNTk4MzY3MTMyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvdWFhL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiYXVkIjpbImVtYWlscyIsInNjaW0iLCJwYXNzd29yZCIsImNyaXRpY2FsX25vdGlmaWNhdGlvbnMiLCJjbGllbnRzIiwibG9naW4iLCJvYXV0aCIsIm5vdGlmaWNhdGlvbnMiLCJpZHBzIl19.qI7ybG2P464IT2ra3S1BgzO0Gi_ihnNLPEZUi2VqV9s
      token_type: bearer
      expires_in: 444443
      scope: clients.read emails.write scim.userids password.write idps.write notifications.write oauth.login scim.write critical_notifications.write
      jti: c91e9f62924d439b8d99854de03267ee
```

The scope doesn't have uaa.user and uaa.admin anymore. Why is that?

**Comment by githubuser88442** [comment]
Update on the situation:

I tried using this URL instead: http://localhost:8080/uaa/oauth/authorize?response_type=code&client_id=login&scope=password.write&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fapi%2Fv1%2Fhealth

Which redirects me to the uaa/login endpoint and asks me to log in:
![image](https://user-images.githubusercontent.com/16505733/90770298-3a894f00-e2fa-11ea-8795-c1d9e82db7e6.png)

I tried doing this before too, but no matter how I tried to log in, it always told me "Provided credentials are invalid. Please try again.", which made matters even more confusing. 

Now, I inspected the sign in request, and it signs in with the username instead of the email?
![image](https://user-images.githubusercontent.com/16505733/90770449-7ae8cd00-e2fa-11ea-93fe-c6041d82621f.png)

So, when I inputted the username (test1), NOT the email, into the EMAIL field, it successfully logged me in, and the callback was successfully called.

**Comment by shamus** [comment]
Hello. Sorry you're not having an easy time getting up and running. It can be difficult to get started.

There's more than one valid way to make a call against the `/authorize` endpoint, the specifics depend on the grant type you're trying to use. It looks like you're trying to get a token on behalf of a user using the `authorization_code` grant type. The examples you've included look fine. Most likely some of the supporting data / configuration isn't in place to make it work.

If you're not familiar with OAuth and the authorization_code grant type, https://www.oauth.com/ is a good resource to learn more.

Things you'll want to verify:
- Is the client you're using allowed to ask for tokens using the authorization_code grant type. You can discover this via `uaac client get` and inspecting the `authorized_grant_types` field. It will contain `authorization_code` if the client is configured for the authorization_code grant type.
- Is the client allowed to access the scopes being requested on behalf of the user. The `scopes` field will contain the list of scopes the client may ask for on behalf of a user.
- It appears you're using the UAA as a user store as well. Have you created a user with the credentials "test1@test1.com" / "test1"? If not, that's most likely why you can't log in. Users can be created using `uaac user add`.
- Does the user belong to the appropriate groups? For example, if you're using a client `testclient` which can request scopes `uaa.user` and you want a token on behalf of `test1@test1.com` that contains `uaa.user`, does `test1@test1.com` belong to the `uaa.user` group? You can verify this via `uaac user get` and you can add a user to a group using `uaac member add`

I see you also have a question about updating client scopes. This one is a bit tricky. The `scope` attribute of a client is the list of scopes a client may ask for on behalf of a user.  In your example, the login client was updated to add `uaa.user` & `uaa.admin` to the list of allowed scopes. Inspecting the CLI output we can see that they were added:

> scope: clients.read emails.write scim.userids password.write idps.write notifications.write oauth.login uaa.admin scim.write critical_notifications.write uaa.user

If you were trying to get a token on behalf of a user, it would be the right thing to do to extend the permissions of the client.

But I see you've attempted to get a token via the client credentials grant. This grant type isn't used to get a token on behalf of a user, but rather a token that represents the login client itself. In this case, before a token is granted the UAA will check the authorities field of the client to see what scopes may be included in the token.

I don't think this answers every question in this issue, but I hope there's enough pointers here to get up and going.

**Comment by githubuser88442** [comment]
Thank you for the detailed response! I'm sure it will help others along the way as well.
