### ISSUE TITLE
Reset Password API from User Perspective

### ISSUE THREAD

**Issue by tiagokv** [cloudfoundry/uaa#1382]
### How are you deploying the UAA?

I am deploying the UAA using as kubernetes application.

### What did you do?

I'm investigating the password reset using UAA either via policy or enforcement from other admin user. We are using UAA as a service for managing users. 

### What did you expect to see? What goal are you trying to achieve with the UAA?

I couldn't find an API where the user itself calling the API could reset it's password when they already have their password blocked/expired. The only endpoints available seems to use redirection to a HTTP page. Is there a way to achieve this using only API interaction?

**Comment by shamus** [comment]
Thanks for the question.

Setting aside the OAuth related APIs, the remaining APIs provided by the UAA are focused on the administration and management of a running instance. They're meant to enable IdP management, client management, user management, etc. by users and applications with privileged access. They're not intended for regular users.

I don't imagine we'd consider shifting this focus. The main interface for a user interacting with their account in the UAA is by logging in via the UI, most often in service of granting an application access to their account. As a result, actions like force password reset are built into this interaction.

**Comment by tiagokv** [comment]
@shamus thanks for the thorough answer. Do you see any way to circumvent this without having us to manage the password policy ourselves?

**Comment by shamus** [comment]
Making sure I'm following you. This is about human users changing their password via an API, not rotating an OAuth client secret?

I'm not sure I understand the use case. Could you tell me more?

**Comment by tiagokv** [comment]
Our main intention is not having the user to interact directly with the API to reset one's password (although this may be useful, considering that one can [change](https://docs.cloudfoundry.org/api/uaa/version/74.24.0/index.html#change-user-password) it's own password via API), but a privileged client/application (with uaa.admin) to reset the password reset flag when changing the user's password to a new one. 

Currently, if the password from the user is expired (i.e. returning "password change required" as error description) and another client uses the `/password` endpoint to reset this user 's password to a new one, this is not removing the force password change flag and still requests the user to change their password.

I think that undoing password reset flag when the password is changed by providing both old password and new password using an access token having `uaa.admin` suit us on solving this issue, for example. This would make UAA's API more uniform in allowing API interaction with the whole password expiration feature, as opposed to having some parameters completely inaccessible. Additionally, this would also cover our use case where there's a privileged app that offloads some of its user management operations to the UAA.

**Comment by tiagokv** [comment]
@shamus what do you think on the proposal? would it make sense from your perspective?

**Comment by shamus** [comment]
Thanks for the explanation.

The UAA's focus is on acting as an authorization server.he user management features built into the UAA are there to help people get started using the tool. Beyond that,  we don't generally recommend using the UAA as an identity management solution, instead we encourage the use of an external provider.

With that focus in mind, I don't think we'd be likely to shift the focus of these APIs from what I described earlier.

Hope this helps.

**Comment by tiagokv** [comment]
hey @shamus , thanks for your support and reply here. Are you really sure that's a focus' shift? what's basically required is a way to deactivate the password required change flag from the administrator (`uaa.admin` scope) to a specific user, for example. 

Most functions like password resetting, user locking mechanisms, etc. are already available as well, just this bit piece misses from our perspective. Would you accept a PR adding such enhancement?
