### ISSUE TITLE
UAA using insufficient default configurations for RestTemplates

### ISSUE THREAD

**Issue by tack-sap** [cloudfoundry/uaa#1430]
### What version of UAA are you running?

Latest CF release, but issue is still present in the develop branch

### How are you deploying the UAA?

We saw the issue both as part of a CF release and using the UAA locally as standalone.

### What did you do?

When using the RestTemplates configured in [RestTemplateConfig](https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/RestTemplateConfig.java) (that are used e.g. by the password grant against an OIDC provider) we experienced connection problems for this connection. We found, that this was due to the limited size of the connection pool that is used by the underlying HttpClient. Unfortunately this property is not configurable, but even the documentation of the HttpClient states, that the default values may be to restrictive ([see here, Section 2.3.3](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html))

### What did you expect to see? What goal are you trying to achieve with the UAA?

Similar to the timeout, that is already configurable using the uaa.yml, we would like to introduce new configuration options for the HttpClient. To solve our problem we would need to be able to configure the poolsize of the connection pool as well as the maximum connections per route. 

We propose to contribute a PR that makes those two values configurable, similar to the timeout value that is already configurable.

**Comment by shamus** [comment]
This makes sense to me.

A PR for this behavior sounds good, thank you for offering to put that together.  I assume the new config will be expressed inside of [RestTemplateConfg](https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/RestTemplateConfig.java) like:

```
    @Value("${rest.template.timeout:10000}")
    public int timeout;

    @Value("${rest.template.maxTotal:20}")
    public int maxTotal;

    @Value("${rest.template.maxPerRoute:2}")
    public int maxPerRoute;
```

Or did you have something else in mind?

**Comment by tack-sap** [comment]
Yes, that's what we had in mind. So all the parameters for the rest templates are configured in the same way and read in the same class.

**Comment by tack-sap** [comment]
I opened a PR with our proposal of how to implement it. We are open for feedback on that proposal.

**Comment by strehle** [comment]
@shamus because of pipeline issues, I debugged this code and even if 
[Section 2.3.3](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html) explain 2 / 20 as default I see 
5 / 10. Same is described here
https://stackoverflow.com/questions/44188847/springs-resttemplate-default-connection-pool

There I will create a PR to adapt the defaults
