### ISSUE TITLE
UAA integration tests fail on a clean checkout

### ISSUE THREAD

**Issue by metacubed** [cloudfoundry/uaa#1437]
### What version of UAA are you running?

UAA 74.27.0

### How are you deploying the UAA?

I am deploying the UAA
- locally only using gradlew

### What did you do?

```sh
# Check out a clean version of UAA from GitHub
git clone https://github.com/cloudfoundry/uaa && cd uaa

# Switch to the release tag
git reset --hard v74.27.0

# Run the integration tests
run-integration-tests postgres
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

All integration tests should pass.

### What did you see instead?

There are integration tests failures:

- `org.cloudfoundry.identity.uaa.integration.feature.InvitationsIT` - 5 failed / 5 total
- `org.cloudfoundry.identity.uaa.integration.feature.OIDCLoginIT` - 11 failed / 11 total
- `org.cloudfoundry.identity.uaa.integration.feature.SamlLoginIT` - 24 failed / 24 total

These failures are caused by unreachable routes for the SAML and OIDC identity providers:

> `ERR_NAME_NOT_RESOLVED: http://simplesamlphp.uaa-acceptance.cf-app.com`

and

> `ERR_NAME_NOT_RESOLVED: https://oidc10.uaa-acceptance.cf-app.com`

According to the commit https://github.com/GESoftware-CF/uaa/commit/1cd9ba4814c4869a8faca506d80a7fae033b3374, these URLs are provided by private applications that are pushed by the GCP acceptance pipeline.

Can these helper apps be made available as source code and/or docker images, and added to the integration-test script?

**Comment by strehle** [comment]
this issues seems to be related to your infrastructore. your network and your docker setup needs to be able to https://oidc10.uaa-acceptance.cf-app.com, yes but if this is the case then tests succeed
