### ISSUE TITLE
Mapping group to organization role

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/uaa#1444]
Hopefully just a quick question. I haven't been able to find any docs on the subject other than an old email thread from 2015 mentioning that support was on the way.

Is it possible to give external groups to users from OIDC/LDAP which grants them organization roles in CF? Or the ability to give a role in CF to a UAA group rather than per user?

Thank you.

**Comment by strehle** [comment]
see https://github.com/cloudfoundry/uaa/issues/1735
