### ISSUE TITLE
Feature request: Rotation of refresh tokens for public clients

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#1448]
The current OAuth drafts with security best practices for Single Page Applications / Browser-based Apps ask for refresh token rotation, in case refresh tokens are issued to public clients.
See:

- https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-07#section-4 
- https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-6.1

As of now (v74.28.0), refresh token rotation is not supported by CF UAA.
Are there already plans to support this in CF UAA (e.g., as a feature that can be enabled/configured per client)?

**Comment by strehle** [comment]
UAA currently does not have real public clients. We have confidential clients with known secrets, e.g. famous cf client

So I this ticket as 2 feature requests
a) support public clients ( maybe in combination with PKCE ;) )
b) support rotation in refresh flow for public clients

**Comment by strehle** [comment]
@sebastianGit UAA will get public feature with next release so we will start with this request and therefore a question.

a) do you expect that if a client has the new allowpublic feature that its refresh tokens replaced always ?
b) do you expect that if a client has the new allowpublic feature that the refresh of its token also is possible without client_secret
