### ISSUE TITLE
LDAP SSL Cert

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/uaa#145]
The uaa.yml file has ldap.ssl.sslCertificate option but it doesnt not appear to be utilized in the UAA anywhere. For ldaps, am I still required to add to my keystore and this property is redundant?

Any best practices about how to get this into my CF keystore when deploying with BOSH?

**Comment by johnmcteague** [comment]
I note that login.uaa_certificate is no longer present either. Now that they are merged, does the login server not make https calls to the UAA, is it all internal and therefore this is not needed?

I use self signed certs on some envs.

**Comment by johnmcteague** [comment]
I see its covered by the cf-release uaa start script - https://github.com/cloudfoundry/cf-release/blob/master/jobs/uaa/templates/uaa_ctl.erb#L69

**Comment by fhanik** [comment]
@johnmcteague That is correct. That property has never been used by the UAA codebase and will be deprecated in favor of the ldap.ssl.skipverification property

We will keep it in the cf-release for how it is for backwards compatibility for some time forward.
