### ISSUE TITLE
uaac target results "invalid status response: 404"

### ISSUE THREAD

**Issue by dave-chen** [cloudfoundry/uaa#146]
I am following the README instructions to deploy the latest uaa  2.1.0 to our private hosted cloud foundry environment. When I tried to "uaac target https://myhost-uaa.svc.ice.com", I got the following error:

"failed to access https://myhost-uaa.svc.ice.com: invalid status response: 404"

There was no such problem when we deployed uaa 1.8.0.

After spent a couple of days debugging, we fixed the problem by updating all "http://localhost:8080" in the https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/resources/login.yml file to "https://myhost-uaa.svc.ice.com" and few other config files (I can submit a complete list of the diff if needed). 

Could someone explain if there was anything changed regarding this? Is this a bug? Is there way to pass the url as a environment variable to the login.yml so we dont have to manually update the file each time?

Thanks,
Dave

**Comment by fhanik** [comment]
We shall update the documentation with a correct example

**Comment by fhanik** [comment]
Documentation updated in https://github.com/cloudfoundry/uaa#deploy-to-cloud-foundry
