### ISSUE TITLE
Possible improvement: Usage of database specific SQL Statements in JdbcUaaUserDatabase

### ISSUE THREAD

**Issue by tack-sap** [cloudfoundry/uaa#1473]
### What did you do?

In our monitoring of our database, we have still see that the dynamically generated SQL statements to resolve the group memberships of a user (that we have already optimized before: https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java#L197-L228 ) are rather expensive and look confusing for a larger amount of groups that need to be resolved. We are also not so happy with the restriction of the number of parameters, that may cause that the statement needs to be split. 

### What goal are you trying to achieve?

We see a chance for further improvement, especially regarding the splitting of the statement, by altering the statement that is used depending on the underlying database. For example: All of the three currently supported databases (HSQL, PostgreSQL, MySQL) have a support for an array type as parameter in a database statement. But the syntax that needs to be used is not the same between those three, which is the reason why we currently cannot use it. 

So we would like to discuss, whether it would make sense to introduce a mechanism to use different SQL Statements here for the different databases - so each statement could be optimized for the database it is targeted on. (Currently resolving the groups is the only place where we would like to have such an improvement, but maybe we will find other places in the future)

Of course such a decision is not needed for most of the other statements, that are plain select/update/insert statements, but as this is a rather complex operation, we see potential in using the database specific operations in such a case. 

We would like to hear, what you think of such a mechanism.

**Comment by metacubed** [comment]
There's a similar use case for client scopes. They are stored as a comma-separated TEXT column, but could be converted to an ARRAY column for supporting databases.

This will significantly speed up token generation, since scope-intersection checks can be done directly in the database query using array-specific operators.

**Comment by strehle** [comment]
Does #1652 solve it?
