### ISSUE TITLE
Extending user model to store additional attributes?

### ISSUE THREAD

**Issue by bsekar** [cloudfoundry/uaa#1480]
I am deploying the UAA
- using a bosh release I downloaded from bosh.io

### What did you expect to see? What goal are you trying to achieve with the UAA?
Add app specific custom attributes to UAA user model.

Hi, I came across an old [issue](https://github.com/cloudfoundry/uaa/issues/554) regarding this. Was wondering if this has changed?

**Comment by adarshasp87** [comment]
This is a much-needed feature. User model should allow to add custom attributes

**Comment by strehle** [comment]
I know that this feature is often requested, therefore I simply answer, please propose it via PR and then we can discuss it, because I agree, community asks for this

**Comment by bsekar** [comment]
Thanks @strehle . Created [PR](https://github.com/cloudfoundry/uaa/pull/1682)
