### ISSUE TITLE
UAA returns JSON error responses with incorrect media type.

### ISSUE THREAD

**Issue by metacubed** [cloudfoundry/uaa#1498]
### What version of UAA are you running?
v74.30.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?
```json
{"app":{"version":"74.30.0"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"8d26cf2","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2021-01-13T15:37:01-0800"}
```

### How are you deploying the UAA?

I am deploying the UAA
- locally only using gradlew

### What did you do?

- Download UAA 74.30.0 from GitHub
- Run the UAA locally using `./gradlew run`
- Call (most?) APIs with an invalid query parameter or an invalid request body

### What did you expect to see? What goal are you trying to achieve with the UAA?

In all cases, UAA returns a valid JSON response similar to this:

```json
{"error_description":"Invalid filter expression: [foo] [created]","error":"scim","message":"Invalid filter expression: [foo] [created]"}{"error_description":"Invalid filter expression: [foo] [created]","error":"scim","message":"Invalid filter expression: [foo] [created]"}
```

The `Content-Type` response header should always be `application/json` to match this response body.

### What did you see  instead?

If we pass in different `Accept` request headers, the response `Content-Type` header changes. The response body is still in the JSON format above.

| `Accept` request header | `Content-Type` response header | Valid |
| --- | --- | --- |
| unspecified | `application/octet-stream;charset=ISO-8859-1` | ✖️ |
| `*/*` | `application/octet-stream;charset=ISO-8859-1` | ✖️ |
| `application/json;charset=UTF-8` | `application/json;charset=UTF-8` | ✔️ |
| `application/json` | `application/json;charset=ISO-8859-1` | ✔️<sup>1</sup> |
| `application/json,*/*` | `application/json;charset=ISO-8859-1` | ✔️<sup>1</sup> |
| `application/json,text/html` | `application/json;charset=ISO-8859-1` | ✔️<sup>1</sup> |
| `*/*,application/json` | `application/json;charset=ISO-8859-1` | ✔️<sup>1</sup> |
| `text/html,application/json` | `text/html;charset=ISO-8859-1` | ✖️ |
| `text/html,*/*` | `text/html;charset=ISO-8859-1` | ✖️ |

<sup>[1]</sup> The JSON format uses ISO-8859-1 encoding, but RFC 8259 restricts it to UTF-8. See https://github.com/spring-projects/spring-framework/issues/22788 for more information.

This issue does not seem to be restricted to a specific API. It was tested on the following APIs:
- GET /v1/Users
- PUT /v1/Users/{userId}
- GET /v1/Groups
- PUT /v1/Groups/{groupId}
- POST /v1/Groups/{groupId}/members

**Comment by strehle** [comment]
Hi @metacubed ,
you already contributed so please provide a PR

**Comment by metacubed** [comment]
@strehle Can you point me to the class(es) which generate this error response? We'll need to set the media-type header on those handlers.

**Comment by strehle** [comment]
@metacubed 

Users endpoint
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpoints.java#L195

Groups
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpoints.java#L136

I assume missing is a produces attribute in requestmapping to restrict content type to json only

Please use a version 75.x or higher for your analysis and PRs

My hope is that with latest spring situation is better than expected

**Comment by metacubed** [comment]
@strehle I think the actual endpoints are fine, it's just the Spring MVC exception handlers that are not configured correctly. I can't find where they are defined in the UAA code.

**Comment by strehle** [comment]
>  I can't find where they are defined in the UAA code.

should be here as example from scim group endpoint
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpoints.java#L572-L591
e.g. search for ExceptionHandler

**Comment by metacubed** [comment]
Those handlers all seem to be using a `ConvertingExceptionView` to convert an `ExceptionReport` to the HTTP response. When the `Accept` header is absent or `*/*`, that class tries to infer the response media type:

https://github.com/cloudfoundry/uaa/blob/3ce614a62119132aa25f78f87134b0cbe6fa43d2/server/src/main/java/org/cloudfoundry/identity/uaa/web/ConvertingExceptionView.java#L130-L133

I think this might be a better place to add the fix, so it can be used for all response handling.

**Comment by strehle** [comment]
> I think this might be a better place to add the fix, so it can be used for all response handling.

ok for me, hope that not too many tests needs to be adopted
