### ISSUE TITLE
Upgrade MariaDB driver to 1.1.8

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa#151]
Driver 1.1.8 fixes a number of bugs: https://mariadb.com/kb/en/mariadb/mariadb-java-client-118-release-notes/

The one that is hitting us the hardest is the database name ones.  Our uaa databases have a '-' in them.  We were using a fork of uaa previously that used an older version of the mariadb driver without the database name bugs.

We are now trying to move to stock uaa and this is one of the issues we ran into.

**Comment by fhanik** [comment]
A PR may be quicker, as it already runs through the Travis CI and we can just click the button to merge it

**Comment by youngm** [comment]
K, I'll put together a PR.

**Comment by fhanik** [comment]
PR was submitted and merged
