### ISSUE TITLE
gradlew build was failing FAILURE:Execution failed for task ':cloudfoundry-identity-server:compileJava'. > Could not resolve all files for configuration ':cloudfoundry-identity-server:compileClasspath'.    > Could not resolve org.opensaml:opensaml:2.6.6.      Required by:          project :cloudfoundry-identity-server > org.springframework.security.extensions:spring-security-saml2-core:1.0.10.RELEASE 

### ISSUE THREAD

**Issue by HarshaVardhanAcharyAthaluri** [cloudfoundry/uaa#1519]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloudfoundry-identity-server:compileJava'.
> Could not resolve all files for configuration ':cloudfoundry-identity-server:compileClasspath'.
   > Could not resolve org.opensaml:opensaml:2.6.6.
     Required by:
         project :cloudfoundry-identity-server > org.springframework.security.extensions:spring-security-saml2-core:1.0.10.RELEASE
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by strehle** [comment]
should work in last versions
