### ISSUE TITLE
Invalid URL for document reference

### ISSUE THREAD

**Issue by b4viral** [cloudfoundry/uaa#152]
Hi,

I was referring documentation for UAA APIs for User creation at "https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#create-a-user-post-users" when I tried clicked SCIM link reference, it gave me 404! same applies to other SCIM links.

**Comment by b4viral** [comment]
*updated issue description, I mentioned SCM, instead SCIM!

**Comment by fhanik** [comment]
9e179183091e70d0ff26e3c7675be5ac4f50a589
