### ISSUE TITLE
Password Grant flow for getting token does not work with passcode

### ISSUE THREAD

**Issue by saurabhkagrawal** [cloudfoundry/uaa#1522]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
I am running 75.0.0 version of UAA

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?
```
{
  "app": {
    "version": "75.0.0"
  },
  "showLoginLinks": true,
  "links": {
    "uaa": "<someurl>,
    "passwd": "/forgot_password",
    "login": "<someurl>",
    "register": "<someurl>/create_account"
  },
  "zone_name": "uaa",
  "entityID": "<Someurl>",
  "commit_id": "17292b6",
  "idpDefinitions": {},
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ],
    "passcode": [
      "password",
      "Temporary Authentication Code ( Get one at <someurl>/passcode )"
    ]
  },
  "timestamp": "2021-01-29T08:15:12+0000"
}
```
### How are you deploying the UAA?

I am deploying the UAA

- using a bosh release I create from fork of uaa to apply only cosmetic changes

### What did you do?

I have UAA 1 and UAA2(as a zone in UAA1) , UAA1 has UAA2 as identity provider.
I get passcode from UAA1's /passcode endpoint (UAA1 redirects me to UAA2 where I enter credentials for user which is in UAA2.).
Than I try to use the PasswordGrant flow with /passcode as documented here "https://docs.cloudfoundry.org/api/uaa/version/75.0.0/index.html#one-time-passcode"
Please find below my curl request

```
curl -v -X POST 'https://<someurl>/oauth/token' \
-u clientid:clientsecret \
-H 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'token_format=jwt' \
--data-urlencode 'passcode=somecoderetrievedearlier'

* Server auth using Basic with user 'clientid'
> POST /oauth/token HTTP/1.1
> Host: <somehost>
> Authorization: Basic <some64encoded>
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 56
>
* upload completely sent off: 56 out of 56 bytes
< HTTP/1.1 401
< X-Content-Type-Options: nosniff
< Cache-Control: no-store
< Pragma: no-cache
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="UAA/client", error="unauthorized", error_description="Request is missing username or password."
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Thu, 11 Feb 2021 21:01:30 GMT
<
* Connection #0 to host <somehost> left intact
{"error":"unauthorized","error_description":"Request is missing username or password."}%
```
My client config looks like
```
  scope: <requested scopes>
  client_id: <someid>
  resource_ids: none
  authorized_grant_types: refresh_token password
  redirect_uri: https://dummyvalue
  autoapprove: true
  access_token_validity: 600
  refresh_token_validity: 86400
  authorities: uaa.none
  name: <somename>
  lastmodified: 1613041475000
```
The client(UAA2) connecting UAA2 to UAA1 as IDP looks like

```
  scope:  openid profile roles user_attributes email uaa.resource
  client_id: <someid>
  resource_ids: none
  authorized_grant_types: refresh_token password authorization_code
  redirect_uri: <someurl>
  autoapprove: true
  access_token_validity: 600
  refresh_token_validity: 86400
  authorities: uaa.resource
  name: <somename>
  lastmodified: 1613041475000
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected to get access token.

### What did you see instead?
{"error":"unauthorized","error_description":"Request is missing username or password."

Please include UAA logs if available.

**Comment by tack-sap** [comment]
Hi @saurabhkagrawal ,

I recently experienced the same problem and found, that this request only works when you provide the "Accept" Header as "application/json" (or no "Accept" Header at all) - and not when you use e.g. */* as Accept Header (which some clients set as default - and it seems curl does that also in your case).
Can you try if the flow works when setting the Header with the correct value (or no value at all)?

**Comment by saurabhkagrawal** [comment]
Hello @tack-sap,
Thanks for the hint, let me try this out, I will provide you feedback soon.

**Comment by saurabhkagrawal** [comment]
Hello @tack-sap 
This was really helpful. It worked. Thanks a lot.  I would like to know how you figured out the issue :)

**Comment by saurabhkagrawal** [comment]
I am closing this issue as it is resovled, but if we mention this in the documentation, it would be really nice :)
