### ISSUE TITLE
Identity provider not support OAuth2 access_token

### ISSUE THREAD

**Issue by xiaoyao9184** [cloudfoundry/uaa#1534]
### What version of UAA are you running?

75.0.0

### How are you deploying the UAA?

docker

### What did you do?

I add OAuth type of Identity provider, like this

```json
{
    "type":"oauth2.0",
    "config":{
        "emailDomain":[
            
        ],
        "additionalConfiguration":null,
        "providerDescription":null,
        "externalGroupsWhitelist":[
            
        ],
        "attributeMappings":{
            "external_groups":[
                
            ]
        },
        "addShadowUserOnLogin":true,
        "storeCustomAttributes":true,
        "authUrl":"http://me:7100/auth/oauth/authorize",
        "tokenUrl":"http://me:7100/auth/oauth/token",
        "tokenKeyUrl":"http://me:7100/auth/oauth/token_key",
        "tokenKey": "",
        "linkText":"use sys login",
        "showLinkText":true,
        "clientAuthInBody":false,
        "skipSslValidation":true,
        "relyingPartyId":"eProject-UAA",
        "scopes":[
            
        ],
        "issuer":null,
        "responseType":"id_token token",
        "userPropagationParameter":null,
        "checkTokenUrl":"http://me:7100/auth/oauth/check_token"
    },
    "id":"72cf6fae-d8a1-4f51-8339-cb89014bf0a0",
    "originKey":"sys",
    "name":"sys",
    "version":12,
    "created":1615186504960,
    "last_modified":1615256713726,
    "active":true,
    "identityZoneId":"uaa"
}
```
and my OAuth server use OAuth2 with JWT but not OIDC, so the token endpoint only return these fields, no `id_token` field

 - access_token
 - token_type
 - expires_in
 - refresh_token
 - scope

some error like this
```
There was an error when authenticating against the external identity provider: 400 : [{"error":"invalid_grant","error_description":"Invalid authorization code: "}]
```

So i change Identity provider `responseType` form `id_token token` to `code`, still error.

So i found this 

https://github.com/cloudfoundry/uaa/blob/1cc0557f10be15940d6fb9c10e7469b2412a8bca/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java#L441-L452

If not use `id_token` `responseType` is `token`

https://github.com/cloudfoundry/uaa/blob/1cc0557f10be15940d6fb9c10e7469b2412a8bca/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java#L446

OK，in OAuth2 authorization code flow `response_type` is token, this is correct

https://github.com/cloudfoundry/uaa/blob/1cc0557f10be15940d6fb9c10e7469b2412a8bca/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java#L567-L571

But the result field should not be `token` but `access_token`

https://github.com/cloudfoundry/uaa/blob/1cc0557f10be15940d6fb9c10e7469b2412a8bca/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java#L607

**Comment by strehle** [comment]
Hi,
this is currently not in focus, we have added Github als oauth provider , but this was contributed, so if you have needs for it, suggest you open a PR.
Or describe the Oauth2 provider you use. Most of them support in meanwhile OpenID connect and id_tokens

**Comment by strehle** [comment]
Hi, close this except you have a concrete oauth2 provider in mind , which is that big , like github so that it makes sense to check an integration, 
pls. reopen in this case
