### ISSUE TITLE
Dead code @ lines 118-120 of LoginSamlAuthenticationProvider.java

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#155]
Relatively, minor housekeeping issue. Here are a reproduction of lines 112-120 of LoginSamlAuthenticationProvider.java

    protected UaaUser getUser(UaaPrincipal principal) {
        String name = principal.getName();
        String email = null;
        String userId = Origin.NotANumber;
        String origin = principal.getOrigin()!=null?principal.getOrigin():Origin.LOGIN_SERVER;
        String zoneId = principal.getZoneId();
        if (name == null && email != null) {
            name = email;
        }

Note that the variable email is never assigned. Thus, the condition (name == null && email != null) is always false and therefore the whole conditional block is dead code.

**Comment by fhanik** [comment]
hi @amiri-ge 
Thanks for opening this. It is a symptom of a bigger issue, and that is that the UAA currently assumes that the username is an email address, and will actually fail if it isn't, even though SAML has the ability to provide email address in another attribute. 

I will leave this issue open until we have addressed the bigger task at hand.

**Comment by thomasdarimont** [comment]
Hi @fhanik,

is there already a public gh issue for the "UAA assumes the username to be an email address" problem? 

Cheers,
Thomas

**Comment by fhanik** [comment]
https://www.pivotaltracker.com/story/show/80135224

**Comment by sreetummidi** [comment]
New Story Added. https://www.pivotaltracker.com/story/show/105793904
