### ISSUE TITLE
Configuring Postgres Db into uaa

### ISSUE THREAD

**Issue by gulzarahamed** [cloudfoundry/uaa#1557]
I have some observation regarding configuring postgres for uaa, I have below configuration in my uaa.yml file (Windows 10 machine), but uaa is not able to connect into postgres uaa database, it requires uaa database should be created manually before starting Apache Service.
 
1) is this is intended behavior?
2) what I am expecting is, the uaa database in postgres should be created automatically.

Please clarify me.

uaa.yml:-

spring_profiles: postgresql

database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql:uaa
  username: xxxxxx
  password: xxxxxx

**Comment by strehle** [comment]
uaa uses flyway to create db tables but the DB itself needs to be created , so yes it is expected behaviour.
see here for uaa ci pipeline the docker setup
https://github.com/cloudfoundry/uaa/blob/develop/ci/image/Dockerfile#L162-L166
