### ISSUE TITLE
Some integration test classes for login server have hard-coded redirect URIs to "localhost"

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#156]
Firstly, and perhaps this merits a opening a second issue, there is a discrepancy between how integration tests for UAA and login server are configured. I am assuming this is a symptom of the fact that they used to be different projects and that there is already an effort under way to address that.

Secondly, while the UAA integration tests are easy enough to run against a remote deployment. Some of the Login Server integration tests have hard-coded references to "localhost". Some of the ones that I have found:

SamlLoginIT.java
ChangeEmailIT.java
LoginIT.java

Thirdly, at least one Login Server integration test has a dependency on an external SAML identity provider. It would be nice if this external dependency was configurable for the SAML integration tests.

Finally, I might be able to submit pull requests to address some of these issues. Please let me know if there is any interest in that.

**Comment by fhanik** [comment]
Pull requests are always welcome. Especially the hard coded localhost, since the integration tests can be ran against another system.

The SAML one is a bit more tricky. SAML is a two way contract. So while it is a good idea to have the external SAML provider configurable, that external provider must meet the contract obligations for the test to succeed.

**Comment by amiri-ge** [comment]
Agreed, SAML is a two-way contract between SP and IdP. A configurable integration tests would assume that the IdP was configured to accept requests from the SP.

In my mind, this is no different than any other external dependencies (e.g. SMTP server, database, etc.) that we assume are available and properly configured for integration test purposes.

**Comment by amiri-ge** [comment]
@fhanik Would you be so kind as to explain the process (or provide a link to documentation) for submitting a pull request? Currently, I'm not authorized to create a branch.

**Comment by fhanik** [comment]
@amiri-ge You first fork the repository (the fork button is at the top right of the page)
https://help.github.com/articles/using-pull-requests/
