### ISSUE TITLE
Not able to update default identity-zone(uaa) with PUT /identity-zones/{id}

### ISSUE THREAD

**Issue by Harish717** [cloudfoundry/uaa#1610]
### What version of UAA are you running?
75.2.0

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?
I'm trying to enable mfa on default identityzone (uaa) with PUT API call.
PUT http://localhost:8081/uaa/identity-zones/uaa

Authorizatoin :

"access_token": "eyJhbGciOiJIUzI1NiIsImprdSI6Imh0dHBzOi8vbG9jYWxob3N0OjgwODAvdWFhL3Rva2VuX2tleXMiLCJraWQiOiJsZWdhY3ktdG9rZW4ta2V5IiwidHlwIjoiSldUIn0.eyJqdGkiOiI3YzBkMjBmNmIyYjk0NGNmOWU3OTVlNTQxY2UzMTgwMyIsInN1YiI6ImlkZW50aXR5IiwiYXV0aG9yaXRpZXMiOlsiem9uZXMucmVhZCIsImNsb3VkX2NvbnRyb2xsZXIucmVhZCIsInpvbmVzLndyaXRlIiwic2NpbS56b25lcyIsInVhYS5yZXNvdXJjZSJdLCJzY29wZSI6WyJ6b25lcy5yZWFkIiwiY2xvdWRfY29udHJvbGxlci5yZWFkIiwidWFhLnJlc291cmNlIiwiem9uZXMud3JpdGUiLCJzY2ltLnpvbmVzIl0sImNsaWVudF9pZCI6ImlkZW50aXR5IiwiY2lkIjoiaWRlbnRpdHkiLCJhenAiOiJpZGVudGl0eSIsImdyYW50X3R5cGUiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJyZXZfc2lnIjoiNzQ5M2RmZGEiLCJpYXQiOjE2MjY0NDc5MTIsImV4cCI6MTYyNjQ5MTExMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3VhYS9vYXV0aC90b2tlbiIsInppZCI6InVhYSIsImF1ZCI6WyJjbG91ZF9jb250cm9sbGVyIiwic2NpbSIsInVhYSIsImlkZW50aXR5Iiwiem9uZXMiXX0.3Kp1SwqQ2hpKiE4UxOrVgn9svnLw9rWuxIbF1FMkYHE",
    "token_type": "bearer",
"scope": "zones.read cloud_controller.read uaa.resource zones.write scim.zones"

### What did you expect to see? What goal are you trying to achieve with the UAA?
I'm expecting the API should allow me to update default identity-zone(uaa ) as long as the bearer token has scope zones.write or uaa.admin

### What did you see instead?
403, There is no response body.

**Comment by strehle** [comment]
See here
https://github.com/cloudfoundry/uaa/blob/8609315fadb8243ab38ed261a8bcfb34095de96e/uaa/src/main/webapp/WEB-INF/spring/multitenant-endpoints.xml#L56

That is no bug but wanted behavior

**Comment by Harish717** [comment]
May I know the reason for not allowing updates to default Identity-zone(uaa). We are building UI for UAA API's  and customer wants to have control over enabling/disabling MFA on default identiy-zone at UI level.  I know we can do it through uaa.yml configuration, but Is there a way to enable/disable MFA on default identity zone through API's?

**Comment by strehle** [comment]
This check was added many years ago, I was not involved, see
https://github.com/cloudfoundry/uaa/commit/5ba3b73adebabc48fe82bfecd483da0d14ab4520
But the default / system zone with name uaa is always updated from YAML config, e.g. uaa.yml.

And mfa switch is : login.mfa.enabled
https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/webapp/WEB-INF/spring-servlet.xml#L474

In CF you have always green / blue deployment and changes can be done to uaa.yml and then redeploy

All other zones except uaa is kept, but if you would make changes to uaa zone and restart/redeploy you would loose the setting, because of mentioned logic with uaa.yml.

**Comment by Harish717** [comment]
It would be of great help, if the same information added to the UAA API documentation https://docs.cloudfoundry.org/api/uaa/version/75.6.0/index.html#updating-an-identity-zone
It would save a lot of time for new users of UAA

**Comment by strehle** [comment]
@Harish717 please check if this
https://github.com/cloudfoundry/uaa/pull/1646/files
would be ok with you?

**Comment by Harish717** [comment]
Thank you @strehle

**Comment by Harish717** [comment]
Hi @strehle 

I want to know is there way to enable mfa only for a specific identity provider. By default I could see it's enabling or disabling MFA for ["uaa","ldap"].It's hardcoded in UAA code that - 
public static final List<String> DEFAULT_MFA_IDENTITY_PROVIDERS = Arrays.asList("uaa", "ldap");
