### ISSUE TITLE
using slashes in client ids is broken

### ISSUE THREAD

**Issue by mvach** [cloudfoundry/uaa#1628]
The UAA does allow (via rest api) to create clients who do have slash in the id.
But these clients can then later neither read nor deleted since the slash is then used as part of the resource.

e.g. https://10.0.3.12:8443/oauth/clients/foo/bar'

If we url encode the client id to foo%2Fbar then the UAA returns http-400 while creating the client.

**Comment by strehle** [comment]
Hi ,
I think we have to forbid / and \, or do you expect to have this in client_id ?

The UAA API uses the client id in request path and with spring upgrade to 5.x ? such pathes must not contain URL encoded characters, but with that / must not be in client_id.

OK ?

**Comment by mvach** [comment]
That is oke for me.
From my perspective UAA should either allow to encode slashes or prevent using it. But allowing to create clients with / in the id and failing while getting or deleting it is broken. BTW: The only way to get rid of such clients is to delete them from the database via SQL :-(.
