### ISSUE TITLE
Querying users with pagination will return duplicate users

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/uaa#164]
Issuing something like the following:
```GET uaa.mydomain.org/Users?attributes=userName%2Cmeta.created&count=10000```
will result in duplicate users. By adding sortBy=id the problem goes away.

A user shouldn't be required to add a sortBy to make pagination work out of the box.

**Comment by cdutra** [comment]
Hi Michael, we're not being able to reproduce it. Do you get the same id if you request ```GET uaa.mydomain.org/Users?attributes=id%2CuserName%2Cmeta.created&count=10000```?

We have a guess that the duplicate users could be a shadow account created by LDAP or SAML.

**Comment by fraenkel** [comment]
The real issue is that there is no stable sort across the queries. If you retrieve 5 rows at a time with 80k users, and no sort by is defined, any changes made to the table across these queries can and will affect the starting offset.

We have over 80k users so requesting 10k is still at least 8 requests.
We are not using LDAP or SAML.

**Comment by fhanik** [comment]
Wouldn't you see the same thing if a row gets created and another deleted? I'm not sure we can completely guard against that, afterall we're not promising ACID

We could add a default sortBy if none is specified.This would be done here:
https://github.com/cloudfoundry/uaa/blob/develop/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpoints.java#L260-260

**Comment by fraenkel** [comment]
There is no foolproof way to guarantee that you see them all or that you see stale ones, but we should never see duplicates. Add a default would fix the issue since our solution is to always add a sortBy which is the same thing.

**Comment by fhanik** [comment]
If you paginate by 1, and I insert a row, you may see that row again. So we may to have to relax the 'never' in 'should never see duplicates'

**Comment by fraenkel** [comment]
Sure, but normally you would use an auto increment id so that would rarely happen.

**Comment by sreetummidi** [comment]
Fixed
