### ISSUE TITLE
Support a copy to clipboard for passcode 

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#1640]
### What version of UAA are you running?

Latest , or 75.6.0

### How are you deploying the UAA?

./gradlew --no-daemon -Dspring.profiles.active=default,debug --no-daemon run

### What did you do?

Login via browser and navigate to /passcode

### What did you expect to see? What goal are you trying to achieve with the UAA?

See a new passcode with a - (hyphen) in there and double click with mouse on code to copy it.

### What did you see instead?

Only parts of code is copied

**Comment by gregorwolf** [comment]
Seems that [server/src/main/resources/templates/web/passcode.html](https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/resources/templates/web/passcode.html) is the needed template. To avoid changes on the creation process for the passcode I would suggest to add a button to copy the passcode directly to the clipboard. A good example can be found in the MDN Web Docs: [Writing to the clipboard](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#writing_to_the_clipboard).

**Comment by strehle** [comment]
Before : Only with a mouse click on the code it can happen (depending on characters, e.g. - ) that we only get parts to the selection and then you have to select again.

![passcode_with-incode](https://user-images.githubusercontent.com/11627201/128465960-d97ca507-72f0-425a-b536-9bd6b0b8380e.png)

After: Click on the Link and you have the code (independent on characters) in your clipboard

<img width="620" alt="passcode_withcopytoClipboard" src="https://user-images.githubusercontent.com/11627201/128465996-0ec368b8-ede2-4e61-8e7d-27dfaaeeaeb9.png">

**Comment by gregorwolf** [comment]
Nice.

**Comment by strehle** [comment]
Another option to fix it - only with an icon. I try to find a UI expert because I am no UI expert and then one option / PR could be use. PR with Icon : https://github.com/cloudfoundry/uaa/pull/1643

![passcode_withcopytoClipboardIcon](https://user-images.githubusercontent.com/11627201/128474455-f589fcbe-4cf7-4ea9-a757-059ac7d89948.png)

**Comment by gregorwolf** [comment]
One example for such an UI can be found when you create an access token at https://github.com/settings/tokens. There the copy icon is directly beside the code:

![Screenshot 2021-08-06 at 09 44 07](https://user-images.githubusercontent.com/2639535/128475485-32526835-39b5-4e0e-aef6-454112e1f720.png)

**Comment by strehle** [comment]
#1643 

![image](https://user-images.githubusercontent.com/11627201/128510388-9959672c-9509-4745-9013-a634b74a0b5d.png)

**Comment by gregorwolf** [comment]
The red looks a bit strage. But I like the mono-spaced font.

**Comment by strehle** [comment]
#1643 updated , use samp instead of code . I dont want edit/change styles, from e.g.
https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/webapp/resources/oss/stylesheets/application.css#L519-L528

![image](https://user-images.githubusercontent.com/11627201/128513315-f68c7f1e-9c45-4885-aee4-590ec0d9604a.png)
