### ISSUE TITLE
Not able to update identity providers list in mfaConfig of UAA identity zone

### ISSUE THREAD

**Issue by Harish717** [cloudfoundry/uaa#1648]
### What version of UAA are you running?

75.2.0

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?

Since we can not update default identity zone (uaa) through update API. I'm trying to enable MFA on default identity zone (uaa) through uaa.yml file. I want to limit enabling MFA only to "uaa" alone but by default it's enabling MFA for 'uaa' and 'ldap'.

Here is what you can see in identity_zone table

mfaConfig":{"enabled":true,"providerName":"customProviderName","identityProviders":["uaa","ldap"]}}

Please take a look at this file

https://github.com/cloudfoundry/uaa/blob/develop/model/src/main/java/org/cloudfoundry/identity/uaa/zone/MfaConfig.java

### What did you expect to see? What goal are you trying to achieve with the UAA?

Should be able to enable mfa for a specific origin like uaa or ldap

### What did you see instead?

By default it's enabling MFA for both uaa and ldap origins

Please include UAA logs if available.

**Comment by strehle** [comment]
@Harish717 please checkout related PR and validate if this solves your issue, see
description about new option in uaa.yml,
https://github.com/cloudfoundry/uaa/pull/1666#issue-996921256

**Comment by strehle** [comment]
closed due to age
