### ISSUE TITLE
Process hangs on "Building BackwardsCompatibleDelegatingPasswordEncoder with {bcrypt} only"

### ISSUE THREAD

**Issue by figuernd** [cloudfoundry/uaa#1650]
### What version of UAA are you running?

75.0.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?

![image](https://user-images.githubusercontent.com/14897334/129813318-afd14af0-79a6-4da5-81d4-3a4f5ce9a512.png)

### How are you deploying the UAA?

Deployed the UAA war file to Tomcat on an EC2 instance.

- using cf-release

### What did you do?

Directly booted UAA using Java and a Tomcat runner JAR file: `java -jar ./binaries/webapp-runner-9.0.41.0.jar --port 7777 --proxy-base-url http://localhost:3000/binaries/cloudfoundry-identity-uaa-75.0.0.war`

### What did you expect to see? What goal are you trying to achieve with the UAA?

Complete the boot process and respond to requests as it does on our local machines.

### What did you see instead?

Process never advances past the "BackwardsCompatibleDelegatingPasswordEncoder" step on the EC2 instance, whereas we can get the boot process to continue normally on our local instances.

`2021-08-18T00:03:35,898 [main] INFO  (PostProcessorRegistrationDelegate.java:350) - Bean 'useCaseInsensitiveQueries' of type [java.lang.Boolean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-08-18T00:03:35,905 [main] INFO  (PostProcessorRegistrationDelegate.java:350) - Bean 'userDatabase' of type [org.cloudfoundry.identity.uaa.user.JdbcUaaUserDatabase] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-08-18T00:03:35,908 [main] INFO  (PostProcessorRegistrationDelegate.java:350) - Bean 'sessionResetFilter' of type [org.cloudfoundry.identity.uaa.authentication.SessionResetFilter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-08-18T00:03:35,993 [main] INFO  (PasswordEncoderConfig.java:17) - Building BackwardsCompatibleDelegatingPasswordEncoder with {bcrypt} only
`
Full log here:
[uaa_op.log](https://github.com/cloudfoundry/uaa/files/7003516/uaa_op.log)

**Comment by strehle** [comment]
I never start uaa in this way so I only see in your attached log, that setting java.security.egd is not done and I know from past, that missing of it caused trouble, see

https://github.com/cloudfoundry/uaa/issues/1233
https://github.com/cloudfoundry/uaa-release/issues/79

Therefore is bosh start it is set
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/bin/uaa#L30
K8s
https://github.com/cloudfoundry/uaa/search?q=%22Djava.security.egd%22&type=
but I dont find it in cargo start, mean when you start 
./gradlew run
e.g. https://github.com/cloudfoundry/uaa#quick-start

So I recommend set it into your start method
