### ISSUE TITLE
Eclipse Jakarta Expression Language library needs version bump

### ISSUE THREAD

**Issue by Subbu3992** [cloudfoundry/uaa#1653]
What version of UAA are you running?
75.5.0

How are you deploying the UAA?
I am deploying the UAA

using a bosh release I downloaded from bosh.io
What did you expect to see? What goal are you trying to achieve with the UAA?
Eclipse Jakarta Expression Language > 3.0.3

What did you see instead?
Eclipse Jakarta Expression Language = 3.0.3

Notes:
Eclipse Jakarta Expression Language <= 3.0.3 is prone to Remote Improper Input Validation Vulnerability.[Critical Impact]

**Comment by strehle** [comment]
Dependency updated needed
https://github.com/spring-projects/spring-boot/blob/2.4.x/spring-boot-project/spring-boot-dependencies/build.gradle#L334-L340

3.0.4 is built but not available on maven yet,
https://github.com/eclipse-ee4j/el-ri/pull/160
https://github.com/eclipse-ee4j/el-ri/compare/3.0.3-RELEASE...3.0.4-impl

dependent issue
https://github.com/eclipse-ee4j/el-ri/issues/155

**Comment by schrosolver** [comment]
I think 3.0.4 is now available on maven 
https://search.maven.org/artifact/org.glassfish/jakarta.el/3.0.4/jar
