### ISSUE TITLE
SAML SP metadata generation produces incorrect ID attribute in multi-tenant scenarios

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#168]
Scenario:
Two different zones: testzone1, testzone2

When query the SAML metadata for testzone1:
curl http://testzone1.localhost:8080/uaa/saml/metadata/alias/testzone1.cloudfoundry-saml-login

My SAML metadata begins with:
```<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="testzone1.cloudfoundry-saml-login" entityID="testzone1.cloudfoundry-saml-login">```

When query the SAML metadata for testzone2:
curl http://testzone2.localhost:8080/uaa/saml/metadata/alias/testzone2.cloudfoundry-saml-login

My SAML metadata begins with:
```<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="testzone1.cloudfoundry-saml-login" entityID="testzone2.cloudfoundry-saml-login">```

Note that the ID is the same as the metadata for the other zone and does not match the entityID. I don't think SAML cares much about this, since the entityID is correct, but it is an inconsistency that can create confusion and should be fixed.

This is easy enough to reproduce but I've attached a bash script that should help you setup the scenario to make it easier to reproduce. All you need to do is:
1. Add "127.0.0.1 testzone1.localhost" and "127.0.0.1 testzone2.localhost" to your hosts file.
2. gradle run
3. run the script: reproduce-entity-id-issue.sh
4. Use the CURL commands above to compare the generated SAML SP metadata in the two zones.

Here's the link to the script:
https://drive.google.com/file/d/0BwyEcEB-nIk0OFE3ZDFtek40V2s/view?usp=sharing

**Comment by sreetummidi** [comment]
Hi Dario,
This definitely seems like a bug. I will get this prioritized and fixed.

Thanks,
Sree

**Comment by fhanik** [comment]
Commit - 7828ae94797d27238059de08911983c3ffe98a10
