### ISSUE TITLE
UAA authorization codes still too short

### ISSUE THREAD

**Issue by meeque** [cloudfoundry/uaa#1698]
This is a follow-up to PR #1615. The fix there is incomplete, UAA still uses authorization codes that are only **120 bits** strong. That is better than before the PR (which was 60 bits, though erroneously reported as 80 bits), but still [less than suggested by the oAuth2 spec](https://datatracker.ietf.org/doc/html/rfc6749#section-10.10). The standard mandates **128 bits** of randomness and suggests **160 bits** of randomness.

I'm not reporting this to security@cloudfoundry.org, because imho the security risk is fairly low. Afaik UAA authorization codes are short-lived, single-use, and require an additional client secret to obtain an access token. So 120 bits might just be enough here. Still why not bump it up to **160 bits** and be on the safe side? Feel free to reject this issue, if you disagree.

### What version of UAA are you running?

Unknown. Sorry, couldn't find that info endpoint.

### How are you deploying the UAA?

I am **not** deploying UAA. I'm just a user.

### What did you do?

I signed in with the authorization code grant. I observed the network requests in my browser's developer tools.

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected to see UAA pass an authorization code based on **160 bits** of randomness to the application callback.

### What did you see instead?

I observed an authorization code of **20 characters** `length`. That was 20 url-safe, printable characters, mostly alpha-numeric, plus 2 punctuation, 64 possible characters altogether. Such code can only hold up to **120 bits** of randomness:
```
64^20 = (2^6)^20 = 2^(6*20) = 2^120
```

Here is an example authorization code:
```
IgXbFDZ6aV4LVmdbyBeR
```

### Root cause:

After PR #1615, UAA uses Spring's [RandomValueStringGenerator](https://github.com/spring-projects/spring-security-oauth/blob/main/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/common/util/RandomValueStringGenerator.java) with `length` 20. However, that `length` specifies the length of the resulting strings, not the number of random bytes encoded in those strings.

This is somewhat tricky to see in the source code of `RandomValueStringGenerator`. The implementation does in fact obtain `length` bytes from `SecureRandom`. But further down, it [performs a modulo operation](https://github.com/spring-projects/spring-security-oauth/blob/main/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/common/util/RandomValueStringGenerator.java#L73) that discards 2 bits of every byte, leaving 6 bits of randomness per byte. Therefore, `length` 20 corresponds to 20*6 bits = 120 bits.

Imho Spring Security oAuth does a poor job documenting that. Then again, it's deprecated anyways.

### Proposed fix:

In [UaaTokenStore](https://github.com/robl-sap/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java#L80), bump up the `length` of the `RandomValueStringGenerator` instance to **27**, which will result in authorization codes based on **162 bits** randomness:
```
private final RandomValueStringGenerator generator = new RandomValueStringGenerator(27);
```

**Comment by strehle** [comment]
Hi, thanks for the hint and thus I looked beyond the box (spring) and checked here 
https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/8.x/src/main/java/com/nimbusds/oauth2/sdk/AuthorizationCode.java
https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/8.x/src/main/java/com/nimbusds/oauth2/sdk/id/Identifier.java

that we should use 32 to be on the safe side, @robl-sap  FYI

**Comment by meeque** [comment]
Sorry, I've hit the wrong button, and closed this one. After reopening, a new Pivotal Tracker issue may have been created. Sorry, for that, please ignore it.

That said, `length` **32** sounds good to me. All else left unchanged, that will result in **192 random bits**.
