### ISSUE TITLE
Missing index for username and identity_zone on users table (Postgres)

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#1713]
### What version of UAA are you running?

75.9.0

### How are you deploying the UAA?

I am deploying the UAA
- locally only using gradlew

### What did you do?

Executed a SQL manually because we had a postgres issue in bigger landscapes

Example:
```
select count(*) from users where ((LOWER(username) = LOWER('marissa') and LOWER(identity_zone_id) = LOWER('uaa')))
```

You may execute explain analyze.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Expected is an indexed scan in the query plan to ensure that we run with the index.

### What did you see instead?

Sequenced scan is done because we have no lower index on idz and origin.

### Reason found in git log

Second query that way adapted in the following commit: https://github.com/cloudfoundry/uaa/commit/dca40d968c42a2b5e09b84639787f9517ecc68b8

**Comment by strehle** [comment]
@torsten-sap  since this seemed to be related to https://github.com/cloudfoundry/uaa/commit/dca40d968c42a2b5e09b84639787f9517ecc68b8 
The issue #1663 solved one, now additional one, but is there still one issue missing ? because there were 3 SQL changed to lower....?

**Comment by torsten-sap** [comment]
Yes, we should also check the third one. In the best case changing the order of the recently created index might also solve the others.

**Comment by strehle** [comment]
@torsten-sap  I verified with a colleague in a larger DB that existing index from
issue https://github.com/cloudfoundry/uaa/issues/1713 	and fix
https://github.com/cloudfoundry/uaa/pull/1663/files

solves also this. 
If you have other findings , please re-open

**Comment by torsten-sap** [comment]
Finding from productive CF UAA showed that there are situations where the existing index is not hit. The proposed index improved the situation significantly. Thus, reopening the issue.

**Comment by torsten-sap** [comment]
Affected queries:
`select count(*) from users where ((LOWER(username) = LOWER($1) AND LOWER(identity_zone_id) = LOWER($2)))`

`select id,version,created,lastModified,username,email,givenName,familyName,active,phoneNumber,verified,origin,external_id,identity_zone_id,salt,passwd_lastmodified,last_logon_success_time,previous_logon_success_time from users where ((LOWER(username) = LOWER($1) AND LOWER(identity_zone_id) = LOWER($2))) ORDER BY userName ASC limit ? offset ?`

**Comment by torsten-sap** [comment]
Command for index creation:
`create index concurrently users_username_idz_tmp on users(LOWER(username), LOWER(identity_zone_id))`

**Comment by strehle** [comment]
@torsten-sap  thanks, so can you please create PR for that
