### ISSUE TITLE
Support adding OIDC certificate to list of trusted certs

### ISSUE THREAD

**Issue by johnegrosjean** [cloudfoundry/uaa#1720]
### What version of UAA are you running?
"version":"75.6.0"

### How are you deploying the UAA?
I am deploying the UAA
- as part of a commercial Cloud Foundry distribution

### What did you do?
I've setup UAA to point to an OIDC provider, as I've done many times before.  The difference here is that the OIDC provider is using a web certificate signed by a private CA.  I've added the root CA cert to the bosh trusted_certs (https://bosh.io/docs/trusted-certs/), yet I'm still getting certificate errors when UAA tries to connect to OIDC.

### What did you expect to see? What goal are you trying to achieve with the UAA?
UAA should trust the provided root CA certificate, and trust the OIDC web certificate by validating the chain.  

### What did you see instead?
When I log in via CLI, I just get "HTTP/1.1 500 Internal Server Error"
But if I log into some of the apps that use UAA, I get a more descriptive "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

**Comment by strehle** [comment]
for UAA tomcat you can set property ca_certs, see
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L292-L314

**Comment by johnegrosjean** [comment]
Got it, thanks!
