### ISSUE TITLE
Mapping groups to scopes using OAuth (OIDC)

### ISSUE THREAD

**Issue by TimOwen21** [cloudfoundry/uaa#1735]
### What version of UAA are you running?
75.0.0

### How are you deploying the UAA?
As part of a commercial Cloud Foundry distribution

### What did you do?
I have UAA configured to connect to an external IdP via OAuth(OIDC); however, I can't get the groups from the IdP's Id token to map to Scopes in the UAA token. I noticed there was a 'groupMappingMode: AS_SCOPES' that could be used for SAML, but I didn't see the same option for OAuth/OIDC.

I tried creating an attributeMapping to map external_groups to the groups claim like this:
       attributeMappings:
             external_groups: groups
and from the logs this appears to work as far as getting/saving the groups for the user, however when the UAA token is created these groups still aren't included.

Can this be done, or am I off on the approach?
Thanks.

### What did you expect to see? What goal are you trying to achieve with the UAA?
The groups from the external IdP to appear in the Scopes of the UAA token.

### What did you see instead?
Groups are not included in the UAA token.

**Comment by strehle** [comment]
Hi, I have added a PR which provides such feature.
To me it makes sense because OIDC should replace SAML and in OIDC Idp like Azure you have a claim roles which makes sense to map it directly to a scope claim in UAA to allow external authorization management similar SAML provided it with SAML attribute mappings.

**Comment by strehle** [comment]
Example entries for  uaa.yml:
```
        attributeMappings:
          email: email
          external_groups:
            - roles
        groupMappingMode: AS_SCOPES
```
