### ISSUE TITLE
Access Denied when calling /introspect

### ISSUE THREAD

**Issue by bdselle** [cloudfoundry/uaa#1742]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

74.12.0

### How are you deploying the UAA?

We are running UAA using a Tomcat instance installed as a Windows Service per a vendor we use.

### What did you do?

Trying to use the /introspect endpoint for the first time as I see /check_token is deprecated. I am using a client_credential flow access token in the authorization header. Passing that token as a Bearer. It does have the uaa.resource scope. I verified that using a decoder. In the post body I am sending through the token="access token" per the documentation. This token is NOT the client_credential token. It is a user access token I'd like to verify. The response I'm getting back is an access_denied error. I am guessing that my client_credential flow token is wrong somehow. I have tried via the browser and using Postman to see if that would have a different result and it was the same.

I did set the client_credential access token to expire in 10 years to rule out an expired token. I included the scopes in the token below as a reference point in case something is wrong there. I did try to send through the deprecated Basic auth header and it did work for that. 

"scope": [
    "uaa.resource"
    "uaa.admin"
  ],

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected to get the result back per the API documentation for /introspect.

### What did you see instead?

{
    "error": "access_denied",
    "error_description": "Access is denied"
}

**Comment by bdselle** [comment]
I apologize I forgot to include that if I send a Basic Authorization header through it does work.

**Comment by strehle** [comment]
hi, 
the bearer token you use instead of authorization header must be a client credential token
e.g. here is the integration test
https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/IntrospectEndpointIntegrationTests.java

if you still have issue, please provide an example configuration with example tokens so that I can reproduce on my own.

**Comment by bdselle** [comment]
I did setup a new client in our yaml file. I used the oauth/token endpoint passing through grant_type=client_credentials. I am following the client credential grant (using the basic auth header client id/secret) to get the token back. I then take that token and put it into the Authorization header as a bearer token. I'm wondering if my client setup is incorrect in some way. I included an image of my client setup that I was testing with.

![image](https://user-images.githubusercontent.com/67925497/146424292-6f785335-0a57-44b1-af8c-b3c3f75b1bef.png)

**Comment by strehle** [comment]
do you have a "authorities": [ "uaa.resource" ] in your JWT ? which you set in Authorization header ? please check, 
because the check is simply for authorities using spring, see
https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/webapp/WEB-INF/spring/resource-endpoints.xml#L21

**Comment by strehle** [comment]
can you please check and if you see in code an issue, please provice a PR , as mentioned I have debugged it but did not found an issue

**Comment by bdselle** [comment]
Sorry for the late response. I do have the uaa.resource showing as an authority in the JWT. I will take a closer look at the code and try to debug further where the issue is.
