### ISSUE TITLE
The property mappings link for the current version seems to be down

### ISSUE THREAD

**Issue by pallav-bh** [cloudfoundry/uaa#1743]
[https://docs.cloudfoundry.org/api/uaa/version/75.11.0/propMappings](https://docs.cloudfoundry.org/api/uaa/version/75.11.0/propMappings/) is down for the version  75.11.0

### What version of UAA are you running?
75.11.0

**Comment by strehle** [comment]
do you see : https://docs.cloudfoundry.org/api/uaa/version/75.11.0/index.html#overview

**Comment by pallav-bh** [comment]
Yes but when I click on Internal Property Mappings its giving 404 error

**Comment by strehle** [comment]
oh ok, but I think we should remove this simply @peterhaochen47  ? agree ?
