### ISSUE TITLE
IdP configuration does not always update after PUT.

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#175]
We've noticed that when we PUT changes to /identity-providers they often don't take effect until we restart UAA. We've found a few ways of reproducing this.

1. Create a SAML identity provider.
2. PUT an updated SAML identity provider configuration with different SAML metadata.
3. The new SAML metadata does not take effect until we restart UAA

Is this a known issue?

**Comment by fhanik** [comment]
That is not a known issue, however there is a timelag for when a DB refresh happens. If the create happens within a second of each other, there is a chance the update time does not reflect properly.

We can extend the tests at to see if we can reproduce the issue

https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/test/java/org/cloudfoundry/identity/uaa/login/saml/SamlIDPRefreshMockMvcTests.java#L49-49

**Comment by amiri-ge** [comment]
OK. Let me see if I can create a test that reproduces this issue.

**Comment by sreetummidi** [comment]
Please re-open if reproducible
