### ISSUE TITLE
Redirect URIs with commas are badly treated upon creating Oauth2 client

### ISSUE THREAD

**Issue by phlawski** [cloudfoundry/uaa#1761]
### What version of UAA are you running?

v75.12.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?

```
{
    "app": {
        "version": "v75.12.0"
    },
    "links": {
        "uaa": "https://auth.devlocal",
        "passwd": "/forgot_password",
        "login": "https://auth.devlocal",
        "register": "/create_account"
    },
    "zone_name": "uaa",
    "entityID": "cas-saml-sp",
    "commit_id": "8a72ae3",
    "idpDefinitions": {},
    "prompts": {
        "username": [
            "text",
            "Email"
        ],
        "password": [
            "password",
            "Password"
        ]
    },
    "timestamp": "2021-12-15T19:20:32+0000"
}
```

### How are you deploying the UAA?

I am deploying the UAA in K8S cluster using a Docker Image crafted by me.

### What did you do?

When I am creating a new Oauth2 client using following request:

```
curl 'http://uaa.local-k8s/oauth/clients' -i -X POST \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer ${TOKEN}" \
    -H 'Accept: application/json' \
    -d '{
  "scope" : [ "clients.read", "clients.write" ],
  "client_id" : "xyz",
  "client_secret" : "foobar",
  "resource_ids" : [ ],
  "authorized_grant_types" : [ "client_credentials" ],
  "redirect_uri" : [ "http://test1.com/foo,bar", "http://test2/baz,boom" ],
  "authorities" : [ "clients.read", "clients.write" ],
  "token_salt" : "jGrvTR",
  "autoapprove" : true,
  "allowedproviders" : [ "uaa", "ldap", "my-saml-provider" ],
  "name" : "My Client Name"
}'
```

> please note commas in the path part of the redirect URIs I provide

Then I am getting 200 OK response with the body:

```
{
  "scope": [
    "clients.read",
    "clients.write"
  ],
  "client_id": "xyz",
  "resource_ids": [
    "none"
  ],
  "authorized_grant_types": [
    "client_credentials"
  ],
  "redirect_uri": [
    "http://test2/baz",
    "boom",
    "http://test1.com/foo",
    "bar"
  ],
  "autoapprove": [
    "true"
  ],
  "authorities": [
    "clients.read",
    "clients.write"
  ],
  "token_salt": "jGrvTR",
  "allowedproviders": [
    "uaa",
    "ldap",
    "my-saml-provider"
  ],
  "name": "My Client Name",
  "lastModified": 1641894301238,
  "required_user_groups": []
}
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expect to see two redirect URIs I provided:

```
{
  "scope": [
    "clients.read",
    "clients.write"
  ],
  "client_id": "xyz",
  "resource_ids": [
    "none"
  ],
  "authorized_grant_types": [
    "client_credentials"
  ],
  "redirect_uri": [
    "http://test1.com/foo,bar",
    "http://test2/baz,boom"
  ],
  "autoapprove": [
    "true"
  ],
  "authorities": [
    "clients.read",
    "clients.write"
  ],
  "token_salt": "jGrvTR",
  "allowedproviders": [
    "uaa",
    "ldap",
    "my-saml-provider"
  ],
  "name": "My Client Name",
  "lastModified": 1641894301238,
  "required_user_groups": []
}
```

### What did you see instead?

I see instead 4 redirect URIs. 

In your code you do the join on the provided list of URIs using a comma as a separator and next, when you read from a DB in order to return Oauth2 Client you again construct a list dividing elements using a comma delimiter, which is obviously wrong because both of my redirect URIs contains commas in the path, which is a valid URI from the RFC point of view.

The problematic part in the code is here:

```
org.cloudfoundry.identity.uaa.zone.MultitenantJdbcClientDetailsService#getFieldsForUpdate
```

In line 203 you're basically using `collectionToString`.

My suggestion:

Encode or escape parts of the provided list of URIs before joining and decode or unescape before constructing a list upon reading.

**Comment by strehle** [comment]
thanks for reporting the issue!

I have created 2 options see https://github.com/cloudfoundry/uaa/pull/1765 https://github.com/cloudfoundry/uaa/pull/1766

**Comment by phlawski** [comment]
Thanks. I'm gonna check both feature branches today or tomorrow, although, from what I see in the code,  I'm more into the second one which correctly treats provided URIs.
