### ISSUE TITLE
"Client is not authorized for specified user's identity provider." when two idps configured with the same SAML metadata.

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#177]
We're seeing a "Client is not authorized for specified user's identity provider." error in the UAA log when two idps are configured with the same SAML metadata. Here's the use case: a single IdP is shared by multiple customer organizations but we want to track user registration for each customer organization separately so we create separate IdPs for each customer organization that have the same SAML configuration.

In order to setup this scenario:
1. Include "127.0.0.1 testzone1.localhost" in your /etc/hosts file.
2. Run UAA from the develop branch locally as usual "gradle run".
3. Run this script: https://drive.google.com/file/d/0BwyEcEB-nIk0YlFkVzZxd3RSME0/view?usp=sharing
./reproduce-two-idp-issue.sh -s -b -u -z testzone1 -m shared-saml-metadata.xml

Open two separate tabs or browsers. In one navigate to:

http://testzone1.localhost:8080/uaa/oauth/authorize?client_id=sample_app_1&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A53143%2Fauthcode&state=7fd423952755c029e92614c42cc7c353

then log in. In the other tab/browser navigate to:

http://testzone1.localhost:8080/uaa/oauth/authorize?client_id=sample_app_2&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A53143%2Fauthcode&state=7fd423952755c029e92614c42cc7c353

This time, after logging into the SAML IdP you will get a: "The application is not authorized for your account" error in the browser and a "Client is not authorized for specified user's identity provider" in the UAA log.

I've tried attaching a debugger and troubleshooting this myself but so far my efforts are inconclusive. The only thing I have determined for sure is that regardless of what UAA client/idp configuration I use to initiate the authorization code grant, UAA always resolves to the same user. I believe there is probably a simple explanation for this but I can't seem to grasp it.

**Comment by fhanik** [comment]
If I remember it correctly, if you use the exact same metadata for two SAML providers, only one will be active. And that is probably what you are seeing. So when you attempt to login using sample_app_2, it is actually IDP1 that is performing the authentication.

I can dig into the exact details, but the easiest thing you can do, is record your HTTP transactions in your browser.

**Comment by fhanik** [comment]
The IDP entityID is supposed to be unique. If you create two IDPs with the same entityID, it will only look up one of them. 

I remember us having to setup two SAML providers to test authentication with both. There are some test cases you can use, and we have two SAML providers that are up and running

https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginIT.java#L367-L388

I'm going to turn the Pivotal Tracker issue, https://www.pivotaltracker.com/story/show/97862340 , into a feature to create a validation to avoid this scenario.
