### ISSUE TITLE
Missing indexes for lower(id) on users table on postgresql

### ISSUE THREAD

**Issue by nastacio** [cloudfoundry/uaa#178]
We are using CF 210 and we are hitting a performance problem with UAADB where it gets to 100% CPU with hundreds of queries like this taking minutes (sometimes hours) to complete:

"select count(*) from users where ((((((((((((((((((((((((((((((((((((((((((((((((((((((lower(id) = lower($1) or lower(id) = lower($2)) or lower(id) = lower($3)) or lower(id) = lower($4)) or lower(id) = lower($5)) or lower(id) = lower($6)) or lower(id) = lower($7)) or lower(id) = lower($8)) or lower(id) = lower($9)) or lower(id) = lower($10)) or lower(id) = lower($11)) or lower(id) = lower($12)) or lower(id) = lower($13)) or lower(id) = lower($14)) or lower(id) = lower($15)) or lower(id) = lower($16)) or lower(id) = lower($17)) or lower(id) = lower($18)) or lower(id) = lower($19)) or lower(id) = lower($20)) or lower(id) = lower($21)) or lower(id) = lower($22)) or lower(id) = lower($23)) or lower(id) = lower($24)) or lower(id) = lower($25)) or lower(id) = lower($26)) or lower(id) = lower($27)) or lower(id) = lower($28)) or lower(id) = lower($29)) or lower(id) = lower($30)) or lower(id) = lower($31)) or lower(id) = lower($32)) or lower(id) = lower($33)) or lower(id) = lower($34)) or lower(id) = lower($35)) or l ...."

...

The database has 80K users and some of these queries contain 60+ users.
...

After that point, UAA controllers start to run up the number of JDBC connections against UAADB until they become unresponsive to login requests and the only remedy is to restart UAADB to flush out the queries.
...
In response, we set "scim.userids_enabled: false", which we know will prevent cloud controllers from issuing those types of requests as a side-effect of /v2/spaces/..../developers , but there are still the cases where people may issue other requests that will trigger these types of slow requests.

It seems unecessary that UAA would use "lower(id)" in the SQL instead of just "id" (which is an index) , since user identifiers should be unique anyway. If there is some other technical reason for using the "lower" function (a cursory look at the source code suggests that the SQL generation code is too generic and adds "lower" to all parameters) , then at least there should be an index for "lower(id)"

**Comment by fhanik** [comment]
Thank you for your report, we will get those added.

**Comment by fhanik** [comment]
Closed vi 4711fe9e4f7e38b9ca7dfe41d91c9355bbeba3b5
