### ISSUE TITLE
Support specifying the identity provider for browser login

### ISSUE THREAD

**Issue by metacubed** [cloudfoundry/uaa#180]
Let's say that a specific UAA client has been configured with multiple allowed identity providers. When a browser uses `authorization_code` or `implicit` grant to log in, the webapp has no way to explicitly select the IDP.

Add a header/parameter to specify the IDP (origin) with the `/login` and `/oauth/authorize` calls.

**Comment by fhanik** [comment]
Some capability has been added to support this.
Your client can carry a field called "allowedproviders", this is a string array of IDP originKeys.

    {
        "client_id" : "limited-client",
        "client_secret" : "limited-client-secret",
        "authorized_grant_types" : ["authorization_code"],
        "scope" : ["openid"],
        "authorities" : ["uaa.resource"],
        "resource_ids" : ["none"],
        "allowedproviders" : ["uaa", "saml-idp-1"],
    }

For the above client definition, the call to /oauth/authorize?client_id=limited_client would display the username/password field and the link to saml-idp-1

Note the values in allowedproviders is the originKey field of the identity_provider

**Comment by fhanik** [comment]
Feel free to go on the mailing list to ask for more information.
https://lists.cloudfoundry.org/mailman/listinfo/cf-dev
