### ISSUE TITLE
UAADB Housekeeping

### ISSUE THREAD

**Issue by MartinSmolny** [cloudfoundry/uaa#182]
We are running a large CloudFoundry deployment and found several housekeeping issues: 
* *expiring_code_store:* even that a `expiresat` column exists in that table, expired one-time passcodes get never deleted; over time, that table will get bigger and bigger. In one of our internal test systems we already see 151,000 entries.
* *oauth_code:* If - for whichever reason - the OAuth2 authorization code was never exchanged for a token, entries in that table are not deleted also. Even worse, we do not have an expiration date in that table at all. In an internal test system, we can see already 173,000 most of them will never be used. Can we introduce an expiration into this table for this code (e.g. the duration that a token would be valid - I don't think that the authentication code should be valid for a longer period), so we have a chance to clean that up some time?
* For postgreSQL, I have never seen database maintenance scripts like VACUUM running. Do we have administration recommendations documented to do that manually, or should we have code to do that automatically?

For the first two bullets, we could either by having a regular maintenance job, e.g. started by CRON, or doing housekeeping during runtime, e.g. when creating a new `oauth_code` entry, we could first delete all expired `oauth_code` entries. This should not harm, as it will be only a few deleted rows during normal processing.

**Comment by fhanik** [comment]
Thanks for the report, let me address them by bullet

* expiring_code_store - that's a bug - currently the table only deletes expired rows when a code is retrieved. We should extend this to when a code is created too

* oauth_code - known issue - that should expire for sure. even tokens have expirations on them, so the code 

* Database maintenance - The UAA is only a consumer of the DB. While we create the schemas and maintain the data in there, the responsibilities of keeping the DB running would still fall on the DBA. If we automate it, are we potentially starting actions that would cause the DB to fail or fail to perform?

**Comment by fhanik** [comment]
Fixed via https://www.pivotaltracker.com/story/show/98149612
