### ISSUE TITLE
Issue with group visibility across zones

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#183]
It seems that the groups and group membership of UAA is not "zone-ified". This is leading to some interesting problems. Namely, if a user in one zone has read privileges on a group, they can see all users that are in the group, even users that don't belong to that zone.

Is there a way to correct this or is this a known issue?

**Comment by fhanik** [comment]
Good catch. This is definitely a bug. We will get it fixed unless you feel up for a PR :)

**Comment by amiri-ge** [comment]
Thanks. Also this issue may be related to: https://github.com/cloudfoundry/uaa/issues/184 which we just created.

**Comment by sreetummidi** [comment]
Addressed as part of UAA release 2.5.1 
https://www.pivotaltracker.com/n/projects/997278/stories/99086874
