### ISSUE TITLE
UAA does not work with MySQL 8.0.2 or higher

### ISSUE THREAD

**Issue by churib** [cloudfoundry/uaa#1832]
Hi,

I tried to deploy the UAA v75.17.0 
using cf-release 
with MySQL version 8.0.2 (AWS managed Aurora) or higher.

I got the following Exception:
`Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups g, group_membership gm where gm.group_id = g.id and gm.identity_zone_id =' at line 1
Query is: select g.id,g.displayName,g.description,g.created,g.lastModified,g.version,g.identity_zone_id from groups g, group_membership gm where gm.group_id = g.id and gm.identity_zone_id = g.identity_zone_id and gm.identity_zone_id = ? and gm.member_id in (?);, parameters ['uaa','1b41b788-2825-4eaa-ade5-cde7caffcf75']
java thread: main
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163) ~[mariadb-java-client-2.3.0.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280) ~[mariadb-java-client-2.3.0.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]`

In 2017 MySQL reserved the `groups` keyword since version 8.0.2 [(MySQL Ref, CTRL-f for groups)](https://dev.mysql.com/doc/refman/8.0/en/keywords.html).

BTW: #957 Didnt solve the problem entirely.

The table and column names should be quoted depending on the specific dbms (mysql or postgres).

**Comment by strehle** [comment]
Hi,
I assume that https://github.com/cloudfoundry/uaa/pull/940/files could fix it. However changing existing migrations causes new flyway execution in old DBs and thus I dont know how to solve for this DB.

I added the colleagues from VMware because UAA support both Maria/MySql and Postgresql but in reality we from SAP only know about postgresql and VMware uses mysql, there @bruce-ricard FYI.

regards
markus

**Comment by strehle** [comment]
tested this PR https://github.com/cloudfoundry/uaa/pull/1873
