### ISSUE TITLE
Zone users can't see the groups they create

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#184]
It seems that if a zone user with sufficient privileges creates a group, they are then not able to see that group and therefore not able to add users to that group. The only way to correct this problem is to log in as a admin user for the default zone and give the user read/write privileges to the group they just created. This seems odd. We are creating the group like so:

uaac target http://testzone1.locahost:8080/uaa
uaac token owner get client user
uaac group add my_group

Is UAAC missing some step in the group creation? Otherwise, can we modify the behavior of group creation so that the creator of a group is automatically added to the list of users that can read/write a group/membership? That's the behavior we would expect.

**Comment by fhanik** [comment]
This may have been resolved with group zonification?

    uaac target http://localhost:8080/uaa

    uaac token client get identity -s identitysecret

    uaac curl -H"Content-Type:application/json" -XPOST --data '{ "id":"testzone1", "subdomain":"testzone1", "name":"The Twiglet Zone", "description":"Like the Twilight Zone but tastier."}' /identity-zones

    uaac token client get admin -s adminsecret

    uaac group add zones.testzone1.admin

    uaac client update admin --authorities "clients.read,clients.secret,clients.write,uaa.admin,clients.admin,scim.write,scim.read,zones.testzone1.admin"

    uaac token client get admin -s adminsecret

    uaac curl -H"Content-Type:application/json" -H"Accept:application/json" --data '{ "client_id" : "admin", "client_secret" : "adminsecret", "scope" : ["uaa.none"], "resource_ids" : ["none"], "authorities" : ["uaa.admin","clients.admin","clients.read", "clients.write", "scim.read", "scim.write"], "authorized_grant_types" : ["client_credentials"] }' -H"X-Identity-Zone-Id:testzone1" -XPOST /oauth/clients

    uaac target http://testzone1.localhost:8080/uaa

    uaac token client get admin -s adminsecret

    uaac group add my_group

    uaac groups

      my_group
        meta
          version: 0
          created: 2015-08-19T13:00:01.644Z
          lastmodified: 2015-08-19T13:00:01.644Z
        schemas: urn:scim:schemas:core:1.0
        id: 6f867e90-43bc-45f6-a192-5b68a807b585

**Comment by amiri-ge** [comment]
@fhanik Yes, I can confirm that this issue does not exist anymore in 2.5.1. Thanks.
