### ISSUE TITLE
Logout in spring based example app doesn't work.

### ISSUE THREAD

**Issue by thomasdarimont** [cloudfoundry/uaa#185]
Steps to reproduce:
1) checkout out uaa repository.
2) run ./gradlew -daemon -x javadoc run
3) goto localhost:8080/app
4) login with user: marissa password: koala
5) click on logout in the "Sample Home Page"

Result:

```
HTTP Status 404 - /app/j_spring_security_logout

type Status report

message /app/j_spring_security_logout

description The requested resource is not available.

Apache Tomcat/7.0.55
```

Expected:
the user should be logged out of the sample app (/app)

**Comment by sreetummidi** [comment]
This app is not being actively maintained
