### ISSUE TITLE
Groups not visible 

### ISSUE THREAD

**Issue by friday11** [cloudfoundry/uaa#187]
I can read groups by ID (*GET /Groups/<id>*), but when I list groups via *GET /Groups*, the total number of groups is returned, but the groups itself are not visible (resources attribute is empty --> *"resources" : [ ]*). 

Even if  I create a new group, it is not visible when I list groups with a corresponding display-name-filter (*GET /Groups?filter=displayName eq 'myNewGroup'*). 

However, if I list users with a username-filter (*GET /Users?filter=username eq 'myUsername'*), the associated groups **are** visible. 

Why is a group **not** visible when invoking *GET /Groups*, but **is** visible when invoking "GET /Users*?

I am using a user with following scope: *scim.read, scim.write, cloud_controller.admin, cloud_controller.read, cloud_controller.write, password.write, openid*.

**Comment by fhanik** [comment]
I think we could use an example of how to reproduce this. Feel free to reopen this issue

Started up a local UAA, uaac target http://localhost:8080/uaa

`uaac groups 'displayName eq "openid"'`

    openid
      meta
        version: 0
        created: 2015-08-10T18:18:00.000Z
        lastmodified: 2015-08-10T18:18:00.000Z
      schemas: urn:scim:schemas:core:1.0
      id: 23d24b4a-1428-4d75-9c60-d77a78a3c952



`uaac groups` returns

      openid
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 23d24b4a-1428-4d75-9c60-d77a78a3c952
      uaa.user
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 80188d7d-7fea-4c14-9336-c2c54870f327
      approvals.me
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 7fc4c433-c067-4be2-b2c6-696cffb310bb
      scim.userids
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: cf652158-d71e-4f27-a68b-95e94a3cdc29
      password.write
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: d6451b85-004e-43d4-8924-289f08e38ed7
      scim.me
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 592881be-3a0b-4d04-84df-a1774a61ddfa
      cloud_controller.write
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: b1d9ba6e-f7be-42b7-a7cd-e700d3c809df
      cloud_controller_service_permissions.read
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: f451b332-9e9b-41e9-8552-6006b5da7bc1
      oauth.approvals
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: f12ed649-bfd7-4be2-bc24-75b9d39c8e74
      cloud_controller.read
        meta
          version: 0
          created: 2015-08-10T18:18:00.000Z
          lastmodified: 2015-08-10T18:18:00.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 4029485a-7808-4923-ad7c-344f38c0f47a
      scim.read
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: ebfe6231-0044-4b19-b370-d5cd957ae063
      acme
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        members: 
        -
          origin: uaa
          type: GROUP
          value: 28b4ad42-9975-49bf-9c60-97f985aa1da2
        -
          origin: uaa
          type: GROUP
          value: 6aaf3bfd-8546-487e-b11b-ed32d083989c
        id: db82bde1-652a-43b4-a84a-95b53a9544b1
      clients.secret
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: cbcaa45e-48d0-4d71-ad03-e461ee25d6a0
      organizations.acme
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: c831368f-247e-441c-8275-6c92fd3e7119
      cloud_controller.admin
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: bbc2d439-95fd-440f-8625-bdd534906b8d
      internal.superuser
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: da44ec70-3178-4fa6-93af-3af08328ba5c
      zones.write
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: ae496848-1d6f-4ecc-b948-62b55d224e6e
      clients.read
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 276f1a1f-2ce5-4bae-a2cb-5d3808bbc932
      acme.qa
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 28b4ad42-9975-49bf-9c60-97f985aa1da2
      internal.read
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 3cae2f17-9ebd-47d9-88cf-4d03f3a57e38
      scim.write
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 441f39ad-8b70-4ab3-a858-3fc8189b1222
      clients.write
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 4dcb95f8-a788-4a22-b406-bf1b86bdb0ac
      uaa.resource
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 64ca66b7-be09-40ae-bd95-fe2fad0d9118
      acme.dev
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        members: 
        -
          origin: uaa
          type: USER
          value: 72bfab40-636e-4f9f-9615-57aa807d8b9e
        id: 6aaf3bfd-8546-487e-b11b-ed32d083989c
      internal.everything
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: 811dab59-4953-4e4e-8d9b-85b413b5f77e
      clients.admin
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: a0897c21-3a70-455a-9b69-bbfde2e250cb
      internal.write
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: a8a151a5-3406-4fa9-8267-b5b2a5305c61
      uaa.admin
        meta
          version: 0
          created: 2015-08-10T18:18:01.000Z
          lastmodified: 2015-08-10T18:18:01.000Z
        schemas: urn:scim:schemas:core:1.0
        id: f5dfb701-e51d-49c5-ae94-64230ebf77e2

`uaac curl /Groups` returns

    200 OK
    RESPONSE HEADERS:
      Server: Apache-Coyote/1.1
      Access-Control-Allow-Origin: *
      Cache-Control: no-cache, no-store, max-age=0, must-revalidate
      Pragma: no-cache
      Expires: 0
      X-Xss-Protection: 1; mode=block
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff
      Content-Type: application/json;charset=UTF-8
      Transfer-Encoding: chunked
      Date: Tue, 11 Aug 2015 15:20:21 GMT
      Connection: close
    RESPONSE BODY:
    {
      "resources": [
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "openid",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "23d24b4a-1428-4d75-9c60-d77a78a3c952"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "uaa.user",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "80188d7d-7fea-4c14-9336-c2c54870f327"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "approvals.me",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "7fc4c433-c067-4be2-b2c6-696cffb310bb"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "scim.userids",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "cf652158-d71e-4f27-a68b-95e94a3cdc29"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "password.write",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "d6451b85-004e-43d4-8924-289f08e38ed7"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "scim.me",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "592881be-3a0b-4d04-84df-a1774a61ddfa"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "cloud_controller.write",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "b1d9ba6e-f7be-42b7-a7cd-e700d3c809df"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "cloud_controller_service_permissions.read",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "f451b332-9e9b-41e9-8552-6006b5da7bc1"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "oauth.approvals",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "f12ed649-bfd7-4be2-bc24-75b9d39c8e74"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:00.000Z",
            "lastModified": "2015-08-10T18:18:00.000Z"
          },
          "displayName": "cloud_controller.read",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "4029485a-7808-4923-ad7c-344f38c0f47a"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "scim.read",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "ebfe6231-0044-4b19-b370-d5cd957ae063"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "acme",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "members": [
            {
              "origin": "uaa",
              "type": "GROUP",
              "value": "28b4ad42-9975-49bf-9c60-97f985aa1da2"
            },
            {
              "origin": "uaa",
              "type": "GROUP",
              "value": "6aaf3bfd-8546-487e-b11b-ed32d083989c"
            }
          ],
          "id": "db82bde1-652a-43b4-a84a-95b53a9544b1"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "clients.secret",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "cbcaa45e-48d0-4d71-ad03-e461ee25d6a0"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "organizations.acme",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "c831368f-247e-441c-8275-6c92fd3e7119"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "cloud_controller.admin",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "bbc2d439-95fd-440f-8625-bdd534906b8d"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "internal.superuser",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "da44ec70-3178-4fa6-93af-3af08328ba5c"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "zones.write",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "ae496848-1d6f-4ecc-b948-62b55d224e6e"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "clients.read",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "276f1a1f-2ce5-4bae-a2cb-5d3808bbc932"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "acme.qa",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "28b4ad42-9975-49bf-9c60-97f985aa1da2"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "internal.read",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "3cae2f17-9ebd-47d9-88cf-4d03f3a57e38"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "scim.write",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "441f39ad-8b70-4ab3-a858-3fc8189b1222"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "clients.write",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "4dcb95f8-a788-4a22-b406-bf1b86bdb0ac"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "uaa.resource",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "64ca66b7-be09-40ae-bd95-fe2fad0d9118"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "acme.dev",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "members": [
            {
              "origin": "uaa",
              "type": "USER",
              "value": "72bfab40-636e-4f9f-9615-57aa807d8b9e"
            }
          ],
          "id": "6aaf3bfd-8546-487e-b11b-ed32d083989c"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "internal.everything",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "811dab59-4953-4e4e-8d9b-85b413b5f77e"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "clients.admin",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "a0897c21-3a70-455a-9b69-bbfde2e250cb"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "internal.write",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "a8a151a5-3406-4fa9-8267-b5b2a5305c61"
        },
        {
          "meta": {
            "version": 0,
            "created": "2015-08-10T18:18:01.000Z",
            "lastModified": "2015-08-10T18:18:01.000Z"
          },
          "displayName": "uaa.admin",
          "schemas": [
            "urn:scim:schemas:core:1.0"
          ],
          "id": "f5dfb701-e51d-49c5-ae94-64230ebf77e2"
        }
      ],
      "startIndex": 1,
      "itemsPerPage": 100,
      "totalResults": 28,
      "schemas": [
        "urn:scim:schemas:core:1.0"
      ]
    }
