### ISSUE TITLE
Possible bug in SignerProvider

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#188]
See lines 95-98 of SignerProvider.java under the "common" project. Note that to decide what kind of verifier to construct it uses the "isAssymetricKey(signingKey)" instead of isAssymetricKey(verifierKey)

    public SignatureVerifier getVerifier() {
        if (isAssymetricKey(signingKey)) {
            return new RsaVerifier(verifierKey);
        }
        else {
            return new MacSigner(verifierKey);
        }
    }

**Comment by amiri-ge** [comment]
If someone can confirm this is a bug I can submit a pull request to fix it.

**Comment by fhanik** [comment]
hi @amiri-ge - I'm not sure what you think the bug is here?

**Comment by amiri-ge** [comment]
The code is deciding whether or not to return an RSA (asymmetric crypto) verifier or a MAC (symmetric crypto) verifier based on the signing key. But that makes no sense because if anything it should do that by looking at the verifying key.

Imagine a scenario where I want to use this purely as a verifier who has a public key only, I would obviously not have signing key so I should not base my decision on what kind of verifier to create based on the signing key.

Hope that makes sense.

**Comment by fhanik** [comment]
>Imagine a scenario where I want to use this purely as a verifier who has a public key only

I can't imagine this scenario :) The name suggests that the class provides a signer 

The class is used by the UAA, to provide both the signing key and the verification key for tokens. 
There isn't an option to not have a signing key

But I do see your point, and would be happy to accept a PR against the develop branch

**Comment by fhanik** [comment]
But first, try to provide a test case where you only provide a public verifierkey

the afterPropertiesSet method should throw an exception

**Comment by amiri-ge** [comment]
I can see your point. But the method is called "getSignatureVerifier()". I would not expect a signature verifier to know anything about the signer's private key :)

**Comment by amiri-ge** [comment]
@fhanik The mechanism for determining whether it is a public key/symmetric key is primitive. It just looks for what is essentially the header of a PEM encoded public/private key. Obviously, I'll test it.

**Comment by sreetummidi** [comment]
@amiri-ge Can you please comment on your test results.
