### ISSUE TITLE
Documented /varz Endpoint doesn't exist anymore

### ISSUE THREAD

**Issue by thomasdarimont** [cloudfoundry/uaa#189]
The documentation mentions the /varz management endpoint but it it was removed in 2012 via b786a26
https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#management-endpoints

**Comment by sreetummidi** [comment]
@thomasdarimont We are in the process of implementing this as part of https://www.pivotaltracker.com/story/show/97771768
