### ISSUE TITLE
unable to specify base URL in the reset password link using uaa.yml

### ISSUE THREAD

**Issue by briceburg** [cloudfoundry/uaa#1908]
We have UAA running behind an nginx proxy, something like:

```
# docker-compse.yml

uaa-service:
  image: cloudfoundry/uaa:75.20.0
  volumes: [ "./uaa.yml:uaa.yml" ]
  
nginx:
  image: ...
  ports: [ "8080:8080" ]
```

```
# nginx.conf

upstream uaa {
  server uaa-service:8080;
}

location /uaa {
  proxy_pass http://uaa;
}
```

```
# uaa.yml

uaa:
  url: "http://foo.com/"
  
login:
  url: "http://foo.com/"
  
...
```

UAA comes up fine at http://localhost:8080/uaa and I'm able to create a user. 

The problem is that the emails UAA generate contain the wrong links. The reset password email has a link to:

http://uaa/uaa/reset_password?code=zzzz

(where `uaa` is the host header it's receiving from nginx -- and not the `foo.com` we expect as configured in the uaa.yml file). 

I'm confused because the [spec](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec) says that `uaa.url` and `login.url` will be used for email links... although it does not appear to be respecting these when rendering the templates, and instead relying on spring to determine host/port/proto ...

please advise on how we can configure these links used by emails.

**Comment by strehle** [comment]
yes is obviously a bug in  https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java#L58-L71

So for now I tried to find time to check it in more detail, but if you have found it already and could propose a PR then this would be very helpful and speed it up

**Comment by strehle** [comment]
see https://github.com/cloudfoundry/uaa/pull/1926 
I use login.url yaml and check if you configured value is a URL, but if this is the case, now this is used instead of request host
