### ISSUE TITLE
Jaeger integration into UAA auth server

### ISSUE THREAD

**Issue by mak-azad** [cloudfoundry/uaa#1910]
### What version of UAA are you running?
The version in the Github default repo

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?

I tried to include Jaeger tracing into the` gradle.build` dependencies, I found that the example request curl is not sending any traces into Jaeger running at `http://localhost:16686` on the same machine.

I added this line in the `dependencies.gradle` of the project by ` libraries.springBootJaegerWebStarter = "io.opentracing.contrib:opentracing-spring-jaeger-web-starter:3.3.1"`, then included it in the build.gralde file in the project's uaa directory, like this

```
description = "UAA"
dependencies {
    implementation(project(":cloudfoundry-identity-server")) {
        exclude(module: "jna")
    }
    implementation(project(":cloudfoundry-identity-statsd-lib"))
    implementation(libraries.springBootStarter)
    implementation(libraries.springBootStarterWeb)
    implementation(libraries.springBootJaegerWebStarter)
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

Since UAA server app looks like a Spring boot mvc app, how can I integrate Jaeger into this project like I do in a regular spring boot project.

**Comment by strehle** [comment]
@bruce-ricard  @torsten-sap   I dont know why this is need, so can you please judge if we should accept this

**Comment by bruce-ricard** [comment]
> UAA server app looks like a Spring boot mvc app

The UAA is not a traditional Spring boot app, these kind of things will not work as easily with the UAA.
