### ISSUE TITLE
Cannot specify groupRoleAttribute for dynamic LDAP identity provider registration.

### ISSUE THREAD

**Issue by thomasdarimont** [cloudfoundry/uaa#194]
The documentation about [LDAP identity providers](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md#ldap-groups-as-scopes-configuration) suggests that it is
possible to specify the extraction of groupRoles from an LDAP attribute via the `ldap.group.groupRoleAttribute` property.

A try to dynamically create an LDAP based identity provider via an `uaac curl POST ...` request to the `/identity-providers` endpoint will result in an internal server error, since the `groupRoleAttribute` property doesn't exist in `org.cloudfoundry.identity.uaa.ldap.LdapIdentityProviderDefinition` so it cannot be set / used.

At present it seems that one can only specify this globally in the `uaa.yml` configuration file via the `ldap.groups.groupRoleAttribute` setting which is referenced in the [ldap/ldap-groups-as-scopes.xml](https://github.com/cloudfoundry/uaa/blob/786372e012e29ec51e5d16a3971b4c04ec2e7fe0/uaa/src/main/resources/ldap/ldap-groups-as-scopes.xml#L22) file.

It would be helpful to be able to set the groupRoleAttribute on individual LdapIdentityProvider basis.

**Comment by fhanik** [comment]
I believe that https://github.com/cloudfoundry/uaa/commit/750b0bb3c396e13bc76b14e6d8a01614e3b57610 added that property.
