### ISSUE TITLE
install uaa standalone on ubuntu 14.04  failed

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/uaa#195]
Hi expert,
My environment: ubuntu 14.04 LTS ,java version 1.7.0. install uaa standalone.
after run ./gradlew run get below error. any suggestions, thanks.
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'cloudfoundry-identity-parent'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download gradle-cargo-plugin.jar (org.gradle.api.plugins:gradle-cargo-plugin:1.5)
      > Could not get resource 'https://jcenter.bintray.com/org/gradle/api/plugins/gradle-cargo-plugin/1.5/gradle-cargo-plugin-1.5.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/gradle/api/plugins/gradle-cargo-plugin/1.5/gradle-cargo-plugin-1.5.jar'.
            > peer not authenticated

**Comment by fhanik** [comment]
Clicking on the link https://jcenter.bintray.com/org/gradle/api/plugins/gradle-cargo-plugin/1.5/gradle-cargo-plugin-1.5.jar downloads the JAR for me. 
Are you behind a proxy? If so, read up on proxy settings for gradle at
https://docs.gradle.org/current/userguide/build_environment.html
