### ISSUE TITLE
Provide a SCIM admin user interface

### ISSUE THREAD

**Issue by thomasdarimont** [cloudfoundry/uaa#199]
It would be great to have an user interface for SCIM parts, that is administering resources, users, groups, clients, identity providers for the UAA.

The [osiam Project](https://www.osiam.org) has a small example for this with it's [addon-administration](https://github.com/osiam/addon-administration).
To try this out, just start their [docker container](https://github.com/osiam/docker-image) and goto the 
[addon-administration home](http://localhost:8080/addon-administration) with the login credentials from the [readme](https://github.com/osiam/docker-image/blob/master/README.md).

Maybe (with some configuration) one could use their addon to manage UAA users / groups etc.

**Comment by sreetummidi** [comment]
Hello Thomas,
We don't have any current plans to support an Administrative Interface for UAA.
We do provide a CLI for the same. Its available @ https://github.com/cloudfoundry/cf-uaac

Thanks,
Sree
