### ISSUE TITLE
DB version database type differences between database.

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/uaa#2005]
While working on migrating a client from PostgreSQL to MySQL, I encountered a few percularities.

In table groups, the version column is defined as an integer for MySQL and hssql databases but PostgreSQL has the type defined as bigint.   Would it make sense to bigint or integer all the databases to use the same size?

The case for the tables SPRING_SESSION  and SPRING_SESSION_ATTRIBUTES uppercase while all the other table names are in lowercase which is easier to deal when trying to compare data across the two databases.

**Comment by strehle** [comment]
for mysql the table names behaviour can be configured - as far as I know. Found
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names

In other DBs , e.g. postgresql the table names are always handled case insensitive, so no issue.

About bigint. Dont know, why postgresql has / needs bigint. The type is in java set only with int, so integer is enough and the version is only for some internal use cases
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupProvisioning.java#L238

If you have futher question, please ask them in slack
https://cloudfoundry.slack.com/archives/C03FXANBV

**Comment by norman-abramovitz** [comment]
Also found these differences
hsqldb/V1_5_2__initial_db.sql:  authorized_grant_types VARCHAR(256),
mysql/V1_5_2__initial_db.sql:  authorized_grant_types VARCHAR(**_255_**),
postgresql/V1_5_2__initial_db.sql:  authorized_grant_types VARCHAR(256)

hsqldb/V1_5_2__initial_db.sql:  client_secret VARCHAR(256),
mysql/V1_5_2__initial_db.sql:  client_secret VARCHAR(**_255_**),
postgresql/V1_5_2__initial_db.sql:  client_secret VARCHAR(256),

I found the sysvar as well but that does not exist as best as I can tell with MySQL 5.7 which is the version pxc is at the client.

**Comment by strehle** [comment]
From my side no problem. I was also surprised that we have here differences but both cells store data which does not reach the limit

**Comment by strehle** [comment]
close this now , since you should be able to proceed
