### ISSUE TITLE
Missing docu for Event LoginWithInstanceSecret

### ISSUE THREAD

**Issue by D035676** [cloudfoundry/uaa#2025]
Hi,
in BTP Audit Logging we found a log with Event
LoginWithInstanceSecret
in
{
message_uuid: "c621e53d-cef0-4a83-9de1-85303776a480",
time: "2022-05-02T08:09:03.177Z",
tenant: "19f17b61-41ab-465b-9c85-d4870aaec4b7",
org_id: "92f1da92-e5b3-4cc5-8c90-964165af11c8",
space_id: "92f1da92-e5b3-4cc5-8c90-964165af11c8",
app_or_service_id: "92f1da92-e5b3-4cc5-8c90-964165af11c8",
als_service_id: "47dc5776-73b2-4358-b62b-2693d59ad522",
user: "sb-auditlog-viewer!t6316",
category: "audit.security-events",
format_version: "",
message: {
uuid: "c621e53d-cef0-4a83-9de1-85303776a480",
user: "sb-auditlog-viewer!t6316",
time: "2022-05-02T08:09:03.177261Z",
ip: "3.66.68.201",
data: "{"level":"INFO","origin":"sb-auditlog-viewer!t6316","msgNo":1,"msgId":"f213e9b7-30bc-4f44-babe-80dafc860f2e","message":"LoginWithInstanceSecret: Client 'sb-auditlog-viewer!t6316' used an instance secret in the request body for login.","user":"sb-auditlog-viewer!t6316","version":"1.0"}",
attributes: [ ],
id: "572c8b53-6604-4fc6-8698-28e2cec139df",
category: "audit.security-events",
tenant: "19f17b61-41ab-465b-9c85-d4870aaec4b7",
customDetails: { }
}
}
Could you add a documentation for this event on
https://docs.cloudfoundry.org/running/managing-cf/uaa-audit-requirements.html
please?

**Comment by strehle** [comment]
Hi,
this here is the OSS UAA, I know it from @torsten-sap what you found is SAPs UAA (aka XSUAA) but the code for this is not available for public
