### ISSUE TITLE
Semantic Event is missing

### ISSUE THREAD

**Issue by D035676** [cloudfoundry/uaa#2046]
In Audit Log Viewer we found a message without Semantic Event:
{"message_uuid":"ab92c68b-f121-438c-bca9-23bca06da595","time":"2022-09-28T12:38:32.500Z","tenant":"3e43efa3-9f32-40b4-b980-9d913bc415e6","org_id":"92f1da92-e5b3-4cc5-8c90-964165af11c8","space_id":"92f1da92-e5b3-4cc5-8c90-964165af11c8","app_or_service_id":"92f1da92-e5b3-4cc5-8c90-964165af11c8","als_service_id":"657116bb-90a6-4aa8-8b1f-fe1f021a2087","user":"binding:992b012c-7376-44ca-ad31-7fe3578fe8d1","category":"audit.security-events","format_version":"","message":"{\"uuid\":\"ab92c68b-f121-438c-bca9-23bca06da595\",\"user\":\"binding:992b012c-7376-44ca-ad31-7fe3578fe8d1\",\"time\":\"2022-09-28T12:38:32.500821Z\",\"ip\":\"3.127.184.122\",\"data\":\"{\\\"request\\\":{\\\"url\\\":\\\[https://credstore.cfapps.sap.hana.ondemand.com/api/v1/credentials/password\\\](https://credstore.cfapps.sap.hana.ondemand.com/api/v1/credentials/password/),\\\"method\\\":\\\"GET\\\"},\\\"timestamp\\\":\\\"2022-09-28T12:38:32.498Z\\\",\\\"event\\\":\\\"read\\\",\\\"namespace\\\":\\\"HANA-Cloud\\\",\\\"credential\\\":{\\\"type\\\":\\\"password\\\",\\\"name\\\":\\\"hci-ibsoetdstaging1-staging-hana\\\",\\\"id\\\":\\\"794a5c76-d82d-4448-b5d0-22bc9f8a63dc\\\",\\\"status\\\":\\\"enabled\\\"},\\\"client_ip\\\":\\\"3.127.184.122\\\",\\\"service_instance\\\":{\\\"id\\\":\\\"d2f93d3d-97c0-43f6-845f-a659d913907b\\\"},\\\"service_binding\\\":{\\\"id\\\":\\\"992b012c-7376-44ca-ad31-7fe3578fe8d1\\\"},\\\"auth_type\\\":\\\"oauth:key\\\",\\\"access_token\\\":{\\\"id\\\":\\\"4988b6b2-d803-4c0b-b97d-cbff3e85c5be\\\",\\\"type\\\":\\\"jwt\\\",\\\"namespace\\\":\\\"HANA-Cloud\\\",\\\"scopes\\\":[\\\"credstore.read\\\",\\\"credstore.create\\\",\\\"credstore.update\\\",\\\"credstore.delete\\\",\\\"crypto.encrypt\\\",\\\"credstore.list\\\",\\\"crypto.decrypt\\\"]},\\\"tracking_id\\\":\\\"e2b9a425-9e50-4070-b4e9-f62e42e3c5b0\\\"}\",\"attributes\":[],\"id\":\"5f2161fc-a362-4d5d-bf83-74be3d5c3928\",\"category\":\"audit.security-events\",\"tenant\":\"3e43efa3-9f32-40b4-b980-9d913bc415e6\",\"customDetails\":{}}"}

What is the meaning of this? Could you tell us this and
could you add to this log a semantic event like those described in the docu:
https://docs.cloudfoundry.org/running/managing-cf/uaa-audit-requirements.html

regards,
Eugen

**Comment by bruce-ricard** [comment]
Hi Eugen,

I'm sorry I don't understand what you are talking about. I'm not familiar with what the "Audit Log Viewer" is, or with what a "Semantic Event" is. 

As you said, this log is not coming from the UAA. Why are you asking your question here?

**Comment by D035676** [comment]
Hi,
I didn't say that this is not coming from UAA. Actually, it is actually not clear from which component this log entry belongs. 
Probably you can tell, which component writes it?
The other question is, what is the Meaning of this log, which event was protocolled?

**Comment by swalchemist** [comment]
What application is this log from?

I don't recognize the path `/api/v1/credentials/password`. Maybe it's from the SAP Cloud Foundry Credential Store Service?

**Comment by strehle** [comment]
UAA does not fire these events, but yes that are from a SAP custom service, so please ask owner of "SAP Cloud Foundry Credential Store Service"
