### ISSUE TITLE
CVEs

### ISSUE THREAD

**Issue by carbonlex** [cloudfoundry/uaa#2055]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
76.1.0

We are builng the uaa with next dockerfile: 
FROM tomcat:9.0-jre11 AS uaa-https
RUN apt-get update && apt-get install -y netcat && rm -rf /var/lib/apt/lists/*
ENV LOGIN_CONFIG_URL WEB-INF/classes/required_configuration.yml
ENV CLOUD_FOUNDRY_CONFIG_PATH /uaa
ENV JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"
COPY uaa/uaa/build/libs/cloudfoundry-identity-uaa-*.war /usr/local/tomcat/webapps/uaa.war
COPY log4j2.properties /usr/local/tomcat/conf/
COPY server_https.xml /usr/local/tomcat/conf/server.xml
COPY startup.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
HEALTHCHECK --interval=60s --timeout=15s --start-period=30s --retries=3 \
  CMD curl http://127.0.0.1:8080/uaa/.well-known/openid-configuration
EXPOSE 8080
ENTRYPOINT ["docker-entrypoint.sh", "postgres:5432", "-t", "10", "--"]
CMD ["catalina.sh", "run"]

### How are you deploying the UAA?

I am deploying the UAA

- other (please explain)
in kubernetes with helm chart. 

### What did you do?

We are trying to run oss-scan and always recieve 2 high CVEs:

CVE_2017_4973 | high | uaa-v76.1.0 | LockoutPolicy.java | 92aa9fe0d8d6d6605676d1123c8ade6399c0e570 | Apache 2.0 | Oct 7th 2022 | Upgrade to version cf-release - v257;UAA release- v2.7.4.14,v3.6.8,v3.9.10,v3.15.0;UAA bosh release - v13.12,v24.7,v30

CVE_2017_4960 | high | uaa-v76.1.0 | LockoutPolicy.java | 92aa9fe0d8d6d6605676d1123c8ade6399c0e570 | Apache 2.0 | Oct 7th 2022 | Upgrade to version org.cloudfoundry.identity:cloudfoundry-identity-model:3.12.0

How we can fix this 2 CVEs in uaa? Maybe you already did something in this direction? 

Regards,
Oleksii Shcherbakov

**Comment by tack-sap** [comment]
For me this looks like a false positive by your scanner.
The mentioned CVE was already found and fixed by the UAA several years ago. So the current UAA version is not affected by this anymore.
