### ISSUE TITLE
Deployment of UAA in EKS is failed

### ISSUE THREAD

**Issue by KMahesh045** [cloudfoundry/uaa#2059]
### What version of UAA are you running?

76.1.0

### How are you deploying the UAA?

I am deploying the UAA
- using a bosh release I downloaded from bosh.io
- trying to deploying the package into EKS

### What did you do?

I am trying to deploy the UAA76.1.0 in EKS and it throws the error and it is not getting deployed
but 75.22.0 is deployed successfully and its working. I am facing the issue with the versions 76

### What did you expect to see? What goal are you trying to achieve with the UAA?

UAA-76.1.0 needs to be deployed properly in EKS

### What did you see instead?

Error log says  **`Error creating bean with name 'identityZoneConfigurationBootstrap' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Cannot resolve reference to bean 'uaaTokenPolicy' while setting bean property 'tokenPolicy';`**

logs have been attached for more details
Deployment of UAA fails and application is not getting started
[uaa-76.1_log.log](https://github.com/cloudfoundry/uaa/files/9777671/uaa-76.1_log.log)

**Comment by tack-sap** [comment]
Hi,

From your provided logs I see the following as root cause for this issue: 

`Caused by: java.lang.IllegalArgumentException: KeyId and Signing key should not be null or empty`

Are these properties set in your configuration? Are you using the same configuration for the version that did work?

**Comment by KMahesh045** [comment]
@tack-sap thanks for the quick response. yes the same configurations are used in old version(75.22.0) and its working fine. I am facing this issue in 76.1.0

**Comment by bruce-ricard** [comment]
From Tack's log, looks like the message is coming from this [code](https://github.com/cloudfoundry/uaa/blob/5275d299d535818153d2890b115766fb567259ae/model/src/main/java/org/cloudfoundry/identity/uaa/zone/TokenPolicy.java#L102-L105).  Which I'm guessing is loading the keys coming from [here](https://github.com/cloudfoundry/uaa-release/blob/dfc5377c4186598329d93dea501273a11edf5891/jobs/uaa/spec#L55-L61). 

Could you look at your deployment manifest and check what you have for the `encryption.encryption_keys:` field?

**Comment by KMahesh045** [comment]
@bruce-ricard yes I have. I have attached my uaa.yml file which I am using currently to run 75.22.0. 
[uaa.yml.txt](https://github.com/cloudfoundry/uaa/files/9808467/uaa.yml.txt)

**Comment by strehle** [comment]
I switched UAA between 75.22.0 and develop but with your uaa.yml I cannot start .
because of SAML keys missing, but with this

[uaa.yml.txt](https://github.com/cloudfoundry/uaa/files/9814166/uaa.yml.txt)

it works in all versions.

The keys (and structure) are from https://github.com/cloudfoundry/uaa-release/blob/develop/spec/compare/all-properties-set-uaa.yml

For our tests, local startup we and maybe also many customers/users still rely on the legacy key structure, which is jwt.token.signing-key
see
https://github.com/cloudfoundry/uaa/blob/develop/scripts/cargo/uaa.yml#L16-L18

**Comment by KMahesh045** [comment]
Thanks all.. Its working.
