### ISSUE TITLE
Zone resolution issue due to upper/lower case letters in zone name

### ISSUE THREAD

**Issue by vbanga** [cloudfoundry/uaa#208]
Zone creation APIs on UAA allow the user to create zone names which are case aware. During our integration testing, we ended up with zone names such as: 	test-zone-cDONUg or test-zone-QHau0w. The zones are created fine but when access via browser or UAAC throw 404. 

The problem is in the, IdentityZoneResolvingFilter and the way case works for URLs. It turns out the domain part of a url is case insensitive. Hence the subdomain(zone name) part of the URL reaches the IdentityZoneResolvingFilter as "test-zone-cdonug". In the private method getSubdomain of this class, the subdomain is returned with subdomain in lower case as a result of which, the call to database: "dao.retrieveBySubdomain(subdomain)" returns EmptyResultDataAccessException.

I would suggest converting the zone name to lower case always before storing and during lookups. Also the docs will need to be updated to mention that zone names are case insensitive. I would be happy to submit a PR if you agree with the issue & proposed solution.

As a side note, IdentityZoneResolvingFilter could use extra logging, EmptyResultDataAccessException is actually consumed without any log statement.

**Comment by mbhave** [comment]
@vbanga we'll be happy to accept a PR with this fix. 

Thanks

**Comment by fhanik** [comment]
https://github.com/cloudfoundry/uaa/commit/d8be1f8ae5618cb345541ca2ba1d813ec17b533c

**Comment by fhanik** [comment]
Closing as fixed
