### ISSUE TITLE
Use Azure Active Directory as an external user store

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/uaa#213]
Azure Active Directory supports SAML to enable SSO. And UAA also supports connecting to external user stores through LDAP and SAML. For SAML, my understanding is configuring a saml_login_server.
Does that mean I can integrate Azure AD with UAA and login-server just by changing configuration?
Thanks.

**Comment by fhanik** [comment]
The [login-server](https://github.com/cloudfoundry/login-server) project is deprecated. 

The UAA (which is now the old UAA and the login-server combined) does support SAML.
It's as easy as configuring them in the login.yml file, under the 'providers' element

https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/resources/login.yml#L125-L133
