### ISSUE TITLE
Logic for validating new client authorities does not match documentation

### ISSUE THREAD

**Issue by glammers** [cloudfoundry/uaa#219]
The documentation (docs/UAA-APIs.rst) states that 

clients.write - scope required to create and modify clients. **The scopes/authorities are limited to be prefixed with the scope holder's client id. For example, id:testclient authorities:client.write may create a client that has scopes/authorities that have the 'testclient.' prefix.**

However, looking at the code in ClientAdminEndpointsValidator starting at line 176, it seems that this is not the case:
```java
Set<String> validAuthorities = new HashSet<String>(NON_ADMIN_VALID_AUTHORITIES);
if (requestedGrantTypes.contains("client_credentials")) {
    // If client_credentials is used then the client might be a
    // resource server
        validAuthorities.add("uaa.resource");
    }

for (String authority : AuthorityUtils.authorityListToSet(client.getAuthorities())) {
    if (!validAuthorities.contains(authority)) {
        throw new InvalidClientDetailsException(authority + " is not an allowed authority for caller="
        + callerId + ". Must be one of: " + validAuthorities.toString());
    }
}
```

If the documentation's description is correct, then a simple startsWith check (as is done for scopes on lines 149-150) would solve this issue. I'd be happy to submit this as a pull request if this is indeed the desired behavior.

**Comment by fhanik** [comment]
Pull requests are always welcome with accompanied test cases. we love PRs!!!

**Comment by fhanik** [comment]
Update documentation to reflect behavior
https://github.com/cloudfoundry/uaa/commit/0ad08f33e7e19b0d620519fe0a2368c6bf078d00
