### ISSUE TITLE
UAA - Client credentials in request body

### ISSUE THREAD

**Issue by sivabalans** [cloudfoundry/uaa#221]
RFC 6749 states the following in section 2.3.1 - https://tools.ietf.org/html/rfc6749#section-2.3.1:
```
Alternatively, the authorization server MAY support including the
   client credentials in the request-body using the following
   parameters:

   client_id
         REQUIRED.  The client identifier issued to the client during
         the registration process described by Section 2.2.

   client_secret
         REQUIRED.  The client secret.  The client MAY omit the
         parameter if the client secret is an empty string.
```

Does CF UAA support this mechanism of passing client_id and client_secret? I tried passing the client credentials as shown below in Postman and I get an Unauthorized error:
![image](https://cloud.githubusercontent.com/assets/10453642/9773591/032bce68-56f8-11e5-8452-ebc082dcf21b.png)

Whereas if I pass the client credentials as "Authorization" header, it works fine. Can you confirm?

**Comment by fhanik** [comment]
Correct, we have not yet implemented the alternate authentication method.

**Comment by sivabalans** [comment]
Thanks for the update.
