### ISSUE TITLE
Token in oauth_code is being deleted immediately

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/uaa#223]
I've updated a test environment to CF v215 and I'm having trouble using the AdminUI tool from the incubator.  When I try to login to the UI I get a scope error and if I look in the UAA logs I see this error:

     Invalid authorization code: KnHCWu

Interesting, that appears immediately after this log entry:

     UaaTokenStore: [oauth_code] Removed 1 old entries.

Looking at the SQL queries, I can see that it's trying to delete any token that was created 5 minutes before current time (login occurred at 17:40 UTC):

     delete from oauth_code where.created < '2015-09-14.17:35:06.356'

Looking at this line of code, shouldn't the query be for "current time PLUS expiration", and not MINUS?

https://github.com/cloudfoundry/uaa/blob/master/common/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenStore.java#L212

**Comment by fhanik** [comment]
the line which you have high lighted, cleans 'old' entries. 
By default, any entry that is 5 minutes or more old, will be deleted. 
It's a backwards compatible feature, from the time when entries didn't have any expiration time set on them. In your case, if your login was at 17:40, the SQL that is run above

    delete from oauth_code where created < '2015-09-14.17:35:06.356'

will NOT delete your row. Because your row should have 

    created = '2015-09-14.17:40:00.000'

**Comment by amhuber** [comment]
OK, wasn't sure if I was getting the logic backwards.  So clearly the log entries are showing it's being deleted.  Basically what I've got is:

Insert in oauth_code
Cleanup code fires and deletes it
App tries to use it but it's already gone

I don't see the created record in the SQL query since it's generated so I guess I'll have to look at the data.  Could this be due to a timezone issue between the UAA server and MySQL?

Aaron

**Comment by amhuber** [comment]
My SQL instance is using Pacific time, NOW() is returning local time, so that definitely seems like the culprit.  So is MySQL supposed to take care of the math or is it something you guys have to do in the query parameters?

Aaron

**Comment by fhanik** [comment]
Yes, I believe you are running into a timezone issue. 

The UAA sends MySQL a `date` object set for the timezone that the UAA is running on. 
This means that the time on the UAA must match the one on the MySQL server.

That should fix your issue. Over here we will discuss that maybe we shouldn't rely on timezones, and store all of our dates in a specific timezone, like UTC.

Let us know if adjusting the time zone fixes your issue.

**Comment by amhuber** [comment]
We're using a shared MySQL instance so not sure I can change it's timezone, and I'm worried about running UAA in a different timezone than the rest of the CF environment.  Can you think of any reason that would cause problems?

**Comment by fhanik** [comment]
You may want to get to the bottom of the issue first

    ALTER TABLE oauth_code ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

According to [MySQL](https://dev.mysql.com/doc/refman/5.5/en/datetime.html), this value is stored in UTC. And so does Java. So I am thinking this should have worked.

**Comment by amhuber** [comment]
I already tested doing an insert and playing with a select query and it's definitely the timezone causing a problem.  It looks like MySQL does store the time in UTC but then it converts it to local when you look at it or use it in a query (http://dba.stackexchange.com/questions/20217/mysql-set-utc-time-as-default-timestamp).

It looks like for the CC database connection they are just forcing the timezone for any connections to UTC which would avoid this problem.  I'm thinking UAA should be doing the same:

https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller.rb#L23

Aaron

**Comment by fhanik** [comment]
We can definitely do that, it won't help you today. We will use this issue to track the progress.

**Comment by amhuber** [comment]
Yes, agreed.  As a temporary work-around I'm considering running just the UAA VMs on Pacific time, which is why I asked above if you can think of any problems with having UAA on a different TZ than the rest of CF.  I'll test it out in our lab but let me know if you can think of any obvious problems to expect and/or test for.

Aaron

**Comment by amhuber** [comment]
I've updated the UAAs to Pacific time and everything seems to be working.  We'll keep testing to see if we can find any problems, with the plan of moving back to UTC on the VMs in our next upgrade that includes updated UAA code.

**Comment by fhanik** [comment]
that implies that the JDBC driver is converting the timestamp, prior to sending it over to the DB, and thus we have an issue. If the driver and DB both used UTC, there should be no issue, no matter what timezones were set. We'll keep investigating on this end too. Thanks for the update.

**Comment by amhuber** [comment]
I appears to just be a mismatch in expectations.  JDBC thinks it's in UTC so when it creates the query it just puts the UTC time in as a string.  MySQL thinks it's just in PST as that is the default on my instance and you don't tell it otherwise, so it get's that string and compares it to the timestamp in Pacific time and it doesn't line up.  If you tell MySQL to use UTC when you connect (like CC is doing) then JDBC and MySQL will both use UTC and all should be well.

**Comment by fhanik** [comment]
The `oauth_code` table underwent an improvement. The old table wasn't deleting non claimed codes and the table grew forever.
So we added an `expiresat` column so that we could expire new entries. This column represents epoch time in milliseconds, so it wont matter what timezone UAA or DB is. 

We added in a `cleanup` for legacy entries that were marked with `expiresat=0` and used the `created` timestamp. Unfortunately the bug is that the cleanup statement didnt have `where expiresat=0` in it, or this issue would have never happened.

Going forward there should be zero entries with `expiresat=0` as those have long been removed. Should there still be some left, they will be deleted after sitting there for 2-3 days depending on timezone.

**Comment by fhanik** [comment]
I have added a story https://www.pivotaltracker.com/story/show/104574026

To expose `validationQuery` and `initSQL` - parameters that can be used to configure a DB session. 
This would mimic what CC is doing for example.

Our goal however is that we remain time zone agnostic in critical functions of the UAA, so we'd like bug reports rather than workarounds settings session values 

Thank you for your patience

**Comment by amhuber** [comment]
Looks good, thanks.  I agree that goal of being timzone agnostic is ideal, so we wouldn't plan on using the new parameters but it's great to have them there if needed.

**Comment by fhanik** [comment]
@amhuber just a quick fyi: I did debug the MySQL `over the net` protocol. It sends timestamps in text format, like yyyy-MM-dd HH:mm:sss.
That explains why we are having issues. I would have thought that a timestamp would be sent in a format, like Java's 64bit long or similar, thus removing all the time zone issues.

**Comment by amhuber** [comment]
Yeah, I saw that myself via tcpdump when I was talking above about how it was putting in the date as a string.  Definitely very dangerous if there is any mismatch in assumptions about the timezone.  It's actually not just a MySQL thing - anything ANSI SQL compliant will use the same types.
