### ISSUE TITLE
Support FIPS compliant BC

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#2230]
Support https://www.bouncycastle.org/fips-java/ instead of only https://www.bouncycastle.org/java.html

CF seems to provide FIPS containers, e.g. https://github.com/cloudfoundry/uaa-release/issues/358 but then UAA should support FIPS in runtime

**Comment by strehle** [comment]
Plan:
SAML2 , signing done via opensaml https://github.com/cloudfoundry/uaa/issues/2561, wait until update of opensaml , then enable FIPS in BC

OIDC done with deprecated https://github.com/cloudfoundry/uaa/issues/2229 , move to jose-jwt and then enable FIPS in BC initialization

**Comment by Tallicia** [comment]
Do we need to to wait for the update of openSAML to enable FIPS in BC? We have had FIPS compliant releases with bionic with the existing SAML and BC libraries.

**Comment by strehle** [comment]
> Do we need to to wait for the update of openSAML to enable FIPS in BC? We have had FIPS compliant releases with bionic with the existing SAML and BC libraries.

not necessarily, but I would like to first merge https://github.com/cloudfoundry/uaa/pull/2624 and then I can start on working to move towards BC with FIPs.

**Comment by Tallicia** [comment]
https://github.com/cloudfoundry/uaa/pull/2624 is merged, so this is likely ready as well @hsinn0 is this on your radar?

**Comment by hsinn0** [comment]
> so this is likely ready as well @hsinn0 is this on your radar?

@Tallicia, not sure what you mean. Our tribute handles SAP PRs not Issues.

**Comment by strehle** [comment]
> > so this is likely ready as well @hsinn0 is this on your radar?
> 
> @Tallicia, not sure what you mean. Our tribute handles SAP PRs not Issues.

finally here the PR https://github.com/cloudfoundry/uaa/pull/2693
