### ISSUE TITLE
Support private_key_jwt from https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#2235]
### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?
> Develop / 76.x.x

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew
- using a bosh release I downloaded from bosh.io
- using cf-release
- using cf-deployment
- as part of a commercial Cloud Foundry distribution
- other (please explain)

### What did you do?

Authenticate OAuth clients without secrets. Public Flow does not solve all cases, e.g. client_credential or password grant .
Private_key_jwt and https://www.rfc-editor.org/rfc/rfc8705 would solve that issue.

Private_key_jwt is part of OIDC standard , e.g.
https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

And therefore this is Expected to be Part of UAA

### What did you expect to see? What goal are you trying to achieve with the UAA?

Private_key_jwt is part of OIDC standard , e.g.
https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

### What did you see instead?

secret based authentication only

**Comment by swalchemist** [comment]
Was this fixed by #2385?

**Comment by strehle** [comment]
> Was this fixed by #2385?

No but https://github.com/cloudfoundry/uaa/pull/2385 is a preparation for it

**Comment by strehle** [comment]
Next stepp is, that oauth_client_details table will be extended with client_keys  or client_key_config so that an admin can upload trusted keys. The pure validation is a smaller step. 
Tokens with private_key_jwt will have this authentication method in the token.

**Comment by strehle** [comment]
@Tallicia @bruce-ricard Started to work on this. I created https://github.com/cloudfoundry/uaa/pull/2433 and I would like to discuss with you in next sync about the possible options to add the key configuration into DB table oauth_client_details.

1. Add an extra column e.g. private_key_jwt_config
2. Migrate additonal_information into text (to have capacity for it) and add the keys in map additional_information.

If you agree / vote for 1. then this PR https://github.com/cloudfoundry/uaa/pull/2433 is a pre-requisit. We need then to decouple from spring security oauth2 classes

**Comment by Tallicia** [comment]
I have added this to the agenda.

**Comment by strehle** [comment]
Added private_key_jwt into my spring demo app

https://github.com/strehle/spring-openid-client/commit/26a52b809ffd2a5ff3f69c20be930821089c7d09

Works with OIDC providers which support private_key_jwt, tested with Okta, SAP Authentication and MS Azure AD.

Plan: UAA supports this as well......
