### ISSUE TITLE
CORS filter blocks same origin requests

### ISSUE THREAD

**Issue by mikeroda** [cloudfoundry/uaa#224]
#173 added XHR support to the CORS filter. This code always expects an Origin header with the "X-Requested-With: XMLHttpRequest" header. However, the browser does not add an Origin header on same origin GET requests. The result is that same origin requests get a 403 error, and there is no way to whitelist these requests since there is no Origin header passed. The only workaround is to remove the CORS filter completely.

**Comment by fhanik** [comment]
If origin is missing, is the request valid? If it is valid, should the hostname in the header become Origin?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by mikeroda** [comment]
Tested this on Firefox and Chrome and they do not send an Origin header on same origin requests where the scheme/host/port are the same. Using the hostname in the header might work but why try to enforce CORS on a same origin request?

**Comment by fhanik** [comment]
This document seems to believe that missing or empty origin header should be rejected with a 403 FORBIDDEN, like our current implementation does
https://www.owasp.org/index.php/CORS_OriginHeaderScrutiny

**Comment by mikeroda** [comment]
Notice it says "for each incoming HTTP CORS requests:", implying that it is only for cross origin requests. It's unclear how the server would know a request is cross origin without an Origin header, so the page is not well written in my opinion. As a test, simply go to some sight that issues ajax requests and look at the requests using the developer tools in your browser. You will see no Origin header on same origin requests.  As further proof, we can look at the source code for mozilla.

http://mxr.mozilla.org/mozilla-release/source/dom/security/nsCORSListenerProxy.cpp

Follow the logic for mHasBeenCrossSite and look where it sets the Origin header.
