### ISSUE TITLE
User prompted for endpoint when UAA is being updated

### ISSUE THREAD

**Issue by ryunata** [cloudfoundry/uaa#229]
I am installing CloudFoundry Release 215 on Openstack with Stemcell 3062. I have installed CloudFoundry in multiple availability zones and the instances are redundant. I tried to perform upgrade (either stemcell, release or flavour) on cloudfoundry and I noticed that whenever CF is updating UAA job, users are prompted for endpoint and sometimes prompted for password even though I have redundant UAA instances. Is this behaviour normal?

This is my manifest file
https://gist.github.com/ryunata/e93d4c90e760d06c3561

**Comment by ryunata** [comment]
This is my manifest file
https://gist.github.com/ryunata/e93d4c90e760d06c3561

**Comment by sreetummidi** [comment]
Updating the issue wit information from the email chain
[User cannot login while UAA is being updated.docx](https://github.com/cloudfoundry/uaa/files/11001/User.cannot.login.while.UAA.is.being.updated.docx)

**Comment by sreetummidi** [comment]
@ryunata 
The issue is reproducible on our side. We think that the issue is occurring because of the UAA route not being un-registered properly. The Proxy/Load Balancer thinks the UAA instance is up when its not and hence the login failures.

@Amit-PivotalLabs Could you please add a story in the cf-release backlog to investigate this further.

**Comment by Amit-PivotalLabs** [comment]
The route registration in v215 was still being done by UAA, not by the `route_registrar` job in cf-release.

**Comment by sreetummidi** [comment]
@ryunata We will be able to address this issue in an upcoming version of cf-release. At this time this is a known issue with no potential workarounds.

**Comment by sreetummidi** [comment]
Being investigated as part of : https://www.pivotaltracker.com/story/show/105492412

**Comment by sreetummidi** [comment]
This will be fixed in cf-release 232
