### ISSUE TITLE
Reset password link points to wrong identity zone

### ISSUE THREAD

**Issue by heissa83** [cloudfoundry/uaa#2303]
### What version of UAA are you running?
We are running version 76.7.0

### How are you deploying the UAA?

I am deploying the UAA
- using a bosh release I downloaded from bosh.io

### What did you do?

We have a setup with multiple identity zones. The "central" one has a url like "example.com" and a "zone1" one under a subdomain like "zone1.example.com". We have configured the uaa.url to be "example.com". If we now start the reset password flow under "zone1.example.com", the generated link to change the password in the email will point to "example.com/reset_password". When clicked the site will say the link is already expired. If we manually change the link to "zone1.example.com/reset_password" it works and the password can be changed.

### What did you expect to see? What goal are you trying to achieve with the UAA?

The expected behaviour is a working password reset link pointing to the correct identity zone.

### What did you see instead?

The reset link is always pointing to login.url. We think this was introduced with [this pull reqeust](https://github.com/cloudfoundry/uaa/pull/1926).

**Comment by strehle** [comment]
hi @heissa83 , the https://github.com/cloudfoundry/uaa/pull/1926 PR is for reverse proxy usage mainly and assumption is that login.url is only set if you use / run external proxy before UAA, so do you have set login.url in use ? if yes, can you remove it, because uaa.url should be enough.

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L1331-L1336

**Comment by strehle** [comment]
I thought about your issue and created https://github.com/cloudfoundry/uaa/pull/2304 because even with an external URL (stable in reverse proxy scenarios) you should be able to get UAA urls dependent on zones

**Comment by heissa83** [comment]
Hello @strehle, we have not set login.url. 
And thank you for the fix. That should do everything we wanted.
