### ISSUE TITLE
New users in an identity zone should be part of uaa.user group (or some other default group)

### ISSUE THREAD

**Issue by william-tran** [cloudfoundry/uaa#232]
After creating  new user in a zone I would expect that the user would be part of a default group like uaa.user, but the user isn't part of any group, and can only get a token with openid.

**Comment by mbhave** [comment]
@william-tran what was the exact issue you ran into?

**Comment by fhanik** [comment]
uaa.user is a default scope for a user, but not for a client.

**Comment by fhanik** [comment]
Closing as invalid.

A user created in a zone will have uaa.user scope by default (assuming the client has it)

    jti: 6a1351b7-80d1-41bc-af61-abee2d0eb966
    sub: c34d42c9-f870-4142-bf5b-d915262719c6
    scope: uaa.user
    client_id: admin
    cid: admin
    azp: admin
    grant_type: password
    user_id: c34d42c9-f870-4142-bf5b-d915262719c6
    origin: uaa
    user_name: testuser
    email: testuser@test.org
    auth_time: 1450107407
    rev_sig: b0d48a5
    iat: 1450107407
    exp: 1450150607
    iss: http://testzone1.localhost:8080/uaa/oauth/token
    zid: testzone1
    aud: admin uaa

**Comment by william-tran** [comment]
This must have gotten fixed by something else, thanks Filip
