### ISSUE TITLE
Indirect group memberships in a zone are not allowed in tokens

### ISSUE THREAD

**Issue by william-tran** [cloudfoundry/uaa#233]
Steps to reproduce:

1. create a user bob
2. create a group direct
3. add bob to the direct group
4. create a group indirect
5. add direct to the indirect group (you'll need to do this with curl)
6. Now we have the relationships "user bob is a member of group direct, group direct is a member of group indirect"
7. create an authcode client with scopes direct,indirect
8. get a token with this client, don't speciy any scopes

I would expect the token to contain scope indirect, but it only contains direct.

**Comment by fhanik** [comment]
Fixed https://github.com/cloudfoundry/uaa/commit/92579ad0f82749e9fa0ef42ded2ae77703395b24
