### ISSUE TITLE
GET /identity-zones endpoint not protected

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#234]
I just download 'develop' code base and GET /identity-zones REST endpoint does not require any Authorization header or scope as documentation stated: 
Request Header	Authorization: Bearer Token containing zones.read 

try it out: curl -v http://localhost:8080/uaa/identity-zones

**Comment by fhanik** [comment]
@ilipkind Thanks for the report, we will get it taken care of

**Comment by fhanik** [comment]
Fixed in fd6e8d374833907cfb53c6794e3c034d9e20a6ff

**Comment by ilipkind** [comment]
Thanks @fhanik
