### ISSUE TITLE
User's tokens get revoked after every external ldap authentication

### ISSUE THREAD

**Issue by mikeroda** [cloudfoundry/uaa#235]
When using an external LDAP identity provider, UAA stores some hash value in the password field of the user table. I'm not sure how this is calculated but it changes each time you get a token using the password grant_type, which causes all previous tokens to be revoked for the user.

**Comment by fhanik** [comment]
hi @mikeroda - https://github.com/cloudfoundry/uaa/pull/214 was an attempt to fix a similar issue. 
I'll take a look at it today

**Comment by mikeroda** [comment]
Thanks Filip. I am using 2.5.2 so that may very well be since I see #214
was fixed in 2.7.0.

**Comment by fhanik** [comment]
Another story I'm working on will also add extra protection for this
https://github.com/cloudfoundry/uaa/commit/1cdcbfe86261e69505f99144094560dcf8fd6b68#diff-57214a7a08c8617e4241eadbff6e57d1R150

**Comment by fhanik** [comment]
Closing. Believe to be fixed.
