### ISSUE TITLE
Group member is not removed if user is deleted

### ISSUE THREAD

**Issue by kakamb0** [cloudfoundry/uaa#2368]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew
- using a bosh release I downloaded from bosh.io
- using cf-release
- using cf-deployment
- as part of a commercial Cloud Foundry distribution
- other (please explain)

### What did you do?

Steps to reproduce:
1. Create a user
2. Assign this user to a group
3. Delete the user
Result the user is still member of the group

### What did you expect to see? What goal are you trying to achieve with the UAA?
User should be deleted from group members

### What did you see instead?

Please include UAA logs if available.

**Comment by strehle** [comment]
hi,

I could verify the issue with commands

 uaac user add myuser --given_name gtest --family_name ftest --emails test@email.org --origin my.idp -p Test1234
 uaac group add mgroup
 uaac member add mgroup myuser
 uaac user delete myuser
