### ISSUE TITLE
Create account logic from Login Server front end is broken

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#237]
Login Server has "create account" link for new users provisioning via email. The problem is that it is single step process and once user is created it is functional user and be able to loggin using this new user credentials even without email confirmation. In my mind it should be 2 step process, so account is not active until user confirms identity using email link.

**Comment by sreetummidi** [comment]
@ilipkind Account Verification is turned on by a feature flag in login.yml called allowUnverfiedUsers which is set to true by default.

**Comment by ilipkind** [comment]
Thanks Sree. Will try it.
