### ISSUE TITLE
Full uaa.yml config file reference

### ISSUE THREAD

**Issue by dfraser** [cloudfoundry/uaa#238]
For those of us deploying this project as an end-user application, compete documentation on the yaml config file would be wonderful!

**Comment by sreetummidi** [comment]
@dfraser We will get the docs updated.  In the meantime please refer to the spec file here:  https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec which contains explanation of the properties.

**Comment by dfraser** [comment]
Thank you!  that's very helpful.
