### ISSUE TITLE
ls: cannot access '/layers/paketo-buildpacks_bellsoft-liberica/jre/bin/keytool': No such file or directory

### ISSUE THREAD

**Issue by harim-k** [cloudfoundry/uaa#2388]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

`76.14.0`

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?

### How are you deploying the UAA?

I am deploying the UAA

- other (please explain)

kubernetes 
`$ ytt -f templates -f overlays/values.yml -f | kubectl apply -f -`

### What did you do?

build-uaa-truststore container do not init with error
`ls: cannot access '/layers/paketo-buildpacks_bellsoft-liberica/jre/bin/keytool': No such file or directory`

If possible, provide a recipe for reproducing the error. Exact `curl` or `uaac` commands with verbose output are helpful. If your problem is configuration-related, please include portions of your uaa.yml or bosh deployment manifest that you believe may be relevant (but do not divulge secrets!)

### What did you see instead?

Please include UAA logs if available.

**Comment by strehle** [comment]
The K8s deployment is no longer supported, however if you have a PR we can check this, but I cannot really check your issue since we use bosh or docker based deployments only

**Comment by strehle** [comment]
we cannot support k8s anymore
