### ISSUE TITLE
Disabling self service links does not remove links from /info or /login JSON responses

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/uaa#245]
When the UAA's `login.yml` has the `selfServiceLinksEnabled` property set to `false`, the "new account" and "password reset" links are removed from the login form that is presented to the user and the associated endpoints are disabled.

When a client explicitly requests JSON with an `Accept: application/json` header, however, the UAA does not honor the disabled self service links configuration and populates the response with the `register` and `passwd` links.

When self service links are disabled, the expectation is that they're disabled for all clients and should not be advertised in the JSON response.

I'm also curious about the use cases around the 'linkCreateAccountShow` and `fieldUsernameShow` properties in the JSON response. Can you explain whether they are intended to be used by clients and how?

**Comment by sreetummidi** [comment]
@sykesm We will be deprecating these properties in favor of a new property disableInternalUserManagement https://www.pivotaltracker.com/story/show/101791634 which will block all access including API level access. This was not supported by the previous flags.
This new flag will be available in the next version of UAA. 

You have a valid point around client json and we will address this as part of this bug

**Comment by fhanik** [comment]
I believe this commit (and potentially others) have cleaned up what gets presented in a JSON response
https://github.com/cloudfoundry/uaa/commit/5a86b62d9dc69f26653b1b7e44b629ae07d76dd0

**Comment by fhanik** [comment]
https://github.com/cloudfoundry/uaa/commit/5f97bab464da9a928ab561cd8fe096074e6994dd
