### ISSUE TITLE
JWT token obtained via client credentials does not limit authorities based on requested scopes

### ISSUE THREAD

**Issue by vbanga** [cloudfoundry/uaa#250]
This looks like an issue especially given that the expectation is that resource server should validate the authorities instead of scope, when a token based on client credentials flow.  It also results in information leak because the token now carries all the authorities that this client might have but are not relevant for the current request.
Steps to reproduce:
1. Use uaac to retrieve a token for a client with multiple authorities. Use -scope field to limit the requested scope to one of the scopes
2. Decode the token that was fetched in step 1. 
3. The value of scope field is limited to requested scope but authorities field lists all the authorities assigned to the client id.

**Comment by fhanik** [comment]
resource servers should validate scope
authorities represent what the client is allowed to do on its own and are always present in the token.
if a resource server decides to validate the authorities for access control, that's on the resource server, but I am curious to learn more and why you think this is an issue?

**Comment by vbanga** [comment]
Two issues:
- In our deployments and uses cases, we end up with clients which have lots of authorities. A token obtained for such a client using client credentials results a large token and in a few cases exceed the default HTTP header size limit on tomcat (4KB). 
- Its somewhat of an information leak because resource server is able to view all the authorities that this client has, its neither required nor relevant.

**Comment by sreetummidi** [comment]
@vbanga 
I had a discussion with the team about the approaches to resolve this.
At this time we are leaning towards introducing a flag which allows for removal of authorities from the token completely. I will keep you posted with more updates.

**Comment by fhanik** [comment]
Resolved via bb4ebfd5f2d98dd92e5734ebb5509a3360aa2928

Rather than breaking backwards compatibility, we have added an option where you can exclude claims from tokens.

You can configure what claims to exclude. 

    jwt:
      token: 
        claims:
          exclude:
            - authorities
