### ISSUE TITLE
Issues with changed log behavior in CF v217

### ISSUE THREAD

**Issue by msmolny** [cloudfoundry/uaa#251]
In commit https://github.com/cloudfoundry/cf-release/commit/b2f6264397978a351a34450baa530809478a5fe4 *Let bosh handle log rotation and archiving*, the UAA changed the behavior from using a RollingFileAppender to using a "normal" FileAppender.
Basically, it is a good idea to go away from the old model to have only 5 backup files with 10MB size each - this was about 5 minutes log in some of our systems. Unfortunately, the current behavior is not working for large environments, too. Within a few hours, the uaa.log file was growing to more than 10 GB. Also, on systems with high workload, we have seen that logrotate had issues with files that are kept open, like that happens with log4j log files.

Not sure what the perfect solution is for this, so here are some ideas/thoughts:
- the uaa log file is full of entries of AntPathRequestMatcher and many proxies; is there a chance to make the log level configurable for these items?
- the previous self-rotating java log worked fine; if there would be parameters to control the file size and backup count, this would help a lot
- if using logrotate, the job would need to run more often, and the log file must be closed from time to time

**Comment by fhanik** [comment]
simplest work around right now would be to change the log level from DEBUG to INFO or WARN

that should drastically change the size. 

see the UAA job spec file for exact property name.

**Comment by mbhave** [comment]
@msmolny looking at the docs, we think that if logrotate is configured with copytruncate, instead of moving the file it will copy the contents to a new file and truncate the original one (and log4j will keep writing on the original log file). The max file size configured for logrotate by bosh is 50MB, so it should do the copytruncate once the log file reaches 50MB, regardless of if the file is open for logging or not. The only way the file could grow up to 10GB is if it grows to that size within an hour (since logrotate runs every hour). Is that something you are observing?

Also, are the other log files are being rotated?

**Comment by msmolny** [comment]
@mbhave 
10GB were not reached within an hour, so the solution with copytruncate sounds feasible.
Regarding other log files: Sorry, i cannot remember. We updated the affected system with different log settings, so I cannot reproduce it easily.

Generally, is it possible to make the log level of UAA configurable via yml file? This would be an easy fix in case somebody encounters issues with the massive logs of UAA.

**Comment by posijon** [comment]
Unfortunately `copytruncate` is already configured by default on BOSH's `logrotate`, so the problem should lie elsewhere.

**Comment by mbhave** [comment]
@msmolny you can configure logging level in the manifest under the property `uaa.logging_level`.

**Comment by msmolny** [comment]
@mbhave 
thanks, good to know. Currently, we have reverted the log4j.properties settings to pre-CF217. When we upgrade that environment next time, we will leave the original log4j.properties file in place, but change the uaa.logging_level to limit logging.

**Comment by mbhave** [comment]
sounds good. closing the issue for now but we will keep a watch on this.
