### ISSUE TITLE
Suggestion: View password requirements prior to initial submission

### ISSUE THREAD

**Issue by jcscottiii** [cloudfoundry/uaa#253]
I wanted to start the conversation for improving the usability for password resetting / setting.

Our users at @18F know they have to create complex passwords, however, they only receive feedback once they submit their first password. This is seen as frustrating from our usability tests.

I would like to propose two parts to this solution.
Part 1) Way for the frontend to the requirements prior to initial submission
Part 2) Pattern matcher so that the user can see what requirements are met as they construct the password.

We are currently developing this improvement and would love to contribute this back to the community if everyone thinks it would be beneficial for everyone. Also, we would like to get any feedback on other user experiences.

More info about the work can be found here: https://trello.com/c/tc2CAVkh/439-ui-changing-setting-password-should-show-requirements-beforehand

**Comment by sreetummidi** [comment]
@jcscottiii We will merge the pull request submitted by you. We are holding off because of a few UI changes made recently
