### ISSUE TITLE
Include an external configuration file when building a war

### ISSUE THREAD

**Issue by chendrix** [cloudfoundry/uaa#254]
The [UAA documentation](https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#configuration) states 

```
There is a default file in the WAR that you should not touch. Overrides and additions can come from an external location, the most convenient way to specify that is through an environment variable (or system property in the JVM) named CLOUD_FOUNDRY_CONFIG_PATH. 
```

Turns out that `CLOUD_FOUNDRY_CONFIG_PATH`, `UAA_CONFIG_URL`, `UAA_CONFIG_PATH` etc are all runtime configurations, i.e. if you want to build a `war` file to deploy the UAA standalone to cloudfoundry, there is no way to include an external configuration file. 

The current workaround is to modify the `uaa.yml` before building the `war`, explicitly warned against in the current documentation.

It would be nice to be able to include an external configuration file that replaces the included `uaa.yml` file when building the `war`.

**Comment by fhanik** [comment]
We have addressed by being able to pass in complete Yaml configuration through the CF application manifest

https://github.com/cloudfoundry/uaa/commit/f55f2b4d55c0b14dc76a4aa4d096595203770f37#diff-04c6e90faac2675aa89e2176d2eec7d8R207

**Comment by fhanik** [comment]
Work around for now is to either set individual environment variables or modify the war file to add in your own uaa.yml file.
