### ISSUE TITLE
SAML Integration tests not passing in release/2.7.1

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#255]
I'm having difficulties with the SAML integration tests in the release/2.7.1 branch. I know that these are run continuously so I'm hoping it's a configuration issue but either way it looks like maybe the default configuration is not correct for these integration tests. Here's the issue I am seeing:

org.openqa.selenium.NoSuchElementException: {"errorMessage":"Unable to find element with xpath '//h2[contains(text(), 'Enter your username and password')]'","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"86","Content-Type":"application/json; charset=utf-8","Host":"localhost:22082","User-Agent":"Apache-HttpClient/4.3.3 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"xpath\",\"value\":\"//h2[contains(text(), 'Enter your username and password')]\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/c0598c80-9219-11e5-803a-659861915331/element"}}

While troubleshooting this issue, I developed a theory for why this might be happening. Take "testSimpleSamlPhpLogin()" as an example. The test starts with a redirect to "http://localhost:8080/uaa/login" and expects to see the "simplesamlphp" login page. Instead it sees the UAA "Welcome" page to either login using the default UAA idp or click on the "Login with Simple SAML" link. It's as if the integration test expects that the user is automatically redirected to the Simple SAML login page but instead UAA is giving them the option of using the default IdP or the SAML login page.

**Comment by fhanik** [comment]
Here is what the test is expected to do:

1. Create  the SAML provider
2. GET to login page
3. Looks for `Cloud Foundry` to be the title of the page
4. Looks for a link with the text `Login with Simple SAML PHP("+alias+")`
5. Clicks on that link
6. Enters username and password

If the SimpleSAMLPhp site already thinks you are logged in, it will automatically redirect you back to UAA. Therefor, I suggest you take a screen shot before you evaluate the next page.

https://github.com/cloudfoundry/uaa/blob/32b5ea941d872b4160f6ed67b9323934ddbc1c75/uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginIT.java#L291-L291

you can simply call `IntegrationTestUtils.takeScreenshot(webdriver)`

and let us know what you see.

**Comment by amiri-ge** [comment]
@fhanik As I suspected the issue was our corporate proxy and I was able to confirm it by dumping the page source in the spot you suggested. Thanks.
