### ISSUE TITLE
Spring Security Oauth2 End of Life

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#2560]
UAA uses https://github.com/spring-attic/spring-security-oauth
This was no issues in the past but with the Spring Boot 3 update the library needs to be changed or removed

Similar issue in past https://github.com/cloudfoundry/uaa/issues/1728

Plan for Removal.
- copy base classes (most needed) and exceptions into UAA
- migrate other: https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide

**Comment by fhanik** [comment]
I did a similar migration this week on another project. The biggest helpful thing I did was to create classed `LegacyClientDetails` and `LegacyBaseClientDetails` to retain the JSON structure of clients as a data object.

**Comment by strehle** [comment]
> I did a similar migration this week on another project. The biggest helpful thing I did was to create classed `LegacyClientDetails` and `LegacyBaseClientDetails` to retain the JSON structure of clients as a data object.

@fhanik to me UAA is not legacy, so I will do this but called in UaaClientDetails :-)
Similar things I will to with exceptions, means I will move/copy them into UAA context, because many of them are still in use there.

**Comment by fhanik** [comment]
@strehle - I also found this answer to support the majority of the lifting when creating the new RestTemplates

https://stackoverflow.com/a/60634690
