### ISSUE TITLE
Authorization Request Error, There was an error. The request for authorization was invalid

### ISSUE THREAD

**Issue by harikrishna1210** [cloudfoundry/uaa#257]
Checked UAA code and modified all occurrences of "localhost" pattern with ip address (X.X.X.X) in the following files:
--------------------------------------------------------------------------------------------------------------------------
o	login.yaml  (located in "uaa/uaa/src/main/resources/login.yml")
o	application-local.properties (located in "uaa/samples/app/src/main/resources")
o	application.properties (located in "uaa/samples/api/src/main/resources")
o	export UAA_PROFILE=local and ran the ./gradlew run; UAA server setup is working fine with public ip address  http://X.X.X.X:8080/uaa/login (marissa/koala)
o	Browsed the http://X.X.X.X:8080/app/apps. According to sample application instructions it's redirects to user login and able to login with (marissa/koala)

Issue:
----------------------------------------------------------------------------------------------------------
o	After login it has to ask user to authorize, but it's failed by throwing below error:
Authorization Request Error: "There was an error. The request for authorization was invalid" 
------------------------------------------------------------------------------------------------------------------
o	Please let me know if anything went wrong in the above steps or advice steps required to test the  authorization code flow end-to-end

**Comment by harikrishna1210** [comment]
Resolved the issue by running the below command in uaa directory and ran the ./gradlew run
-----------------------------------------------------------------------------------------------------------------------
Command: find . -type f -exec sed -i "" -e "s#http://localhost#http://your-ap-address#g" 2> /dev/null {} \;

**Comment by fhanik** [comment]
two system properties should suffice

    -Dlogin.url=http://yourip:8080/uaa
    -Duaa.url=http://yourip:8080/uaa
