### ISSUE TITLE
SCIM user creation works when providing invalid origin

### ISSUE THREAD

**Issue by robl-sap** [cloudfoundry/uaa#2576]
### What version of UAA are you running?

76.21.0 , issue is also present in older versions

### How are you deploying the UAA?

Via bosh release. However, issue is independent of deployment

### What did you do?

Create or update a shadow user with invalid origin.

```
curl -X POST 'https://<uaaurl>/Users' -H "Authorization: bearer <admintoken>" -H "Content-type: application/json" -d '{"userName": "user-does-not-exist",  "origin": "does-not-exist", "emails": [{"value": [test@email.com](mailto:test@email.com), "primary": false}]}'
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

Creation or update is rejected because the origin does not map to a known identity provider.

### What did you see instead?

User is created or updated.

**Comment by klaus-sap** [comment]
Also mentioned here: https://github.com/cloudfoundry/uaa/issues/2505 -> Proposal 6.

**Comment by klaus-sap** [comment]
To avoid incompatible changes, we may add a switch to the IdZ configuration if the origin shall be checked when creating or updating users

**Comment by klaus-sap** [comment]
PR: https://github.com/cloudfoundry/uaa/pull/2688
