### ISSUE TITLE
OAuth POST /oauth/token does not work with IFTTT

### ISSUE THREAD

**Issue by vibgy** [cloudfoundry/uaa#258]
IFTTT oauth process tries to obtain token from UAA server using POST /oauth/token:

```
REQUEST
Method
post

Headers
Accept: application/json
Accept-Charset: utf-8
Accept-Encoding: gzip, deflate
User-Agent: IFTTT-Protocol/v1
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Request-ID: 2555c690f067418d854779bdcdadc08e

Form Data
client_id=xyz
client_secret=abc
grant_type=authorization_code
code=Ukuq8i
redirect_uri=https://djklsfghsjkfdghjksdfgjk.com/authorize

URL
/oauth/token
```

The above request does not work because the UAA server seems to be expecting the client_id and client_secret as a part of the Authorization header, as explained here: 
https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#client-obtains-token-post-oauth-token 

Even Google seems to accept the client_id and client_secret as a part of request body. Check here:
https://developers.google.com/identity/protocols/OAuth2WebServer

**Comment by fhanik** [comment]
Correct, the request authorization header is required by the Oauth 2 spec. The formdata is optional, and we haven't implemented it yet. We'll leave this issue open until we implement it.

**Comment by vibgy** [comment]
Do you have a quick link to the spec where it says that in OAuth 2 spec?

**Comment by fhanik** [comment]
https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by fhanik** [comment]
Fixed via https://github.com/cloudfoundry/uaa/commit/8cb166e4d8b699ea73444f45d9c87cf09f462bdb
