### ISSUE TITLE
Limit user creation within a zone

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#2581]
This is a request for a feature to limit the amount of users which can be created within the identity zone.

This is needed for https://github.com/cloudfoundry/uaa/issues/2505 but can used independently.

Scenario.
A foundational operator creates a zone for a department and provides this department access to maintain their zone themselves, e.g. scim.write . The department does not have access to maintain details or policies of the zone. This action is
only possible from uaa.admin. The depart does not have uaa.admin or zones.<idz.>.admin.

The department is trusted, however it must not exceed all resources in persistence by accident, therefore there must be a mechanism to limit scim users. The admin of the department may get zones.<zone id>.read to read own data but no more rights.

Proposal.
Identity-Zone-Configuration has some policy sections, e.g. tokenPolicy, . Here a limitPolicy should be added with such rules.
E.g. maxUsers or maxGroups

**Comment by klaus-sap** [comment]
I would propose to add it to the userConfig of the IdZ configuration, for example: UserConfig.maxNumber (https://github.com/cloudfoundry/uaa/blob/develop/model/src/main/java/org/cloudfoundry/identity/uaa/zone/UserConfig.java)
