### ISSUE TITLE
Support jwt-bearer grant type so tokens can be exchanged for new tokens with different scopes.

### ISSUE THREAD

**Issue by william-tran** [cloudfoundry/uaa#260]
POST to clientid:clientSecret@uaa.domain.com/oauth/token?grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=TOKEN[&scope=scopes to request (optional)] returns an access token. This works just like password grant but a JWT containing identity info is used to authenticate the user, instead of username and password. The same client registration rules as with password grant apply as well (must be admin to create clients with this grant type). Scope intersection with user authorities and wildcards also work the same way. All scopes are "auto-approved" by nature of the grant type.

This would allow backend clients (which are also resource servers) to request new tokens for further backend calls if the current token doesn't have the required scopes. 

See https://tools.ietf.org/html/rfc7523#section-2.1 and https://tools.ietf.org/html/rfc7523#section-4 for standards. This part of the introduction of RFC 7523 describes what's happening here:
```
   This document defines how a JWT Bearer Token can be used to request
   an access token when a client wishes to utilize an existing trust
   relationship, expressed through the semantics of the JWT, without a
   direct user-approval step at the authorization server.  
   ...
   JWT authorization grants may be used with or
   without client authentication or identification.  Whether or not
   client authentication is needed in conjunction with a JWT
   authorization grant, as well as the supported types of client
   authentication, are policy decisions at the discretion of the
   authorization server.
```

**Comment by fhanik** [comment]
Thanks for the issue, we will take it under consideration.
It is not entirely clear what token's can be used for this assertion, or how those tokens are selected. The authors of these specs are the SAML and OpenID Connect writers, so there is some information that may be clear to them that is not spelled out in the specifications. The `aud` field and it's usage for example, since OpenID Connect is slightly different. 

Also, since this step does bypass user approval, we have to also consider how a user can prevent this from happening, should that be desired.

Perhaps it should just be the id_token value that can be used for this type of assertion.

**Comment by gberche-orange** [comment]
@fhanik what about a variation of using the JWT access token as authorization grant that would enable micro service backends to exchange  access tokens they receive from their clients with new access tokens with their own client_id instead, while preserving the other claims such as ``sub`` or ''email``, in a similar way to what Dave Syer seems to describe at http://presos.dsyer.com/decks/microservice-security.html#slide25 ?

**Comment by fhanik** [comment]
@gberche-orange 
hi Guillaume,
that approach is possibly flawed, because the user has authorized client `foo` to perform actions on his/her behalf. So giving client `bar` the right to do so, without the user's consent, would possibly violate the users intent.

**Comment by william-tran** [comment]
It needs to be very clear that using this grant type implies auto-approval, but there's lots of examples in CF where auto-approval is desired. In the CF cli all scopes are autoapproved, as are with many other clients which are "part of the platform". To me, auto-approval is OK when both the client and resource are owned and controlled by the same entity. That seems to be the majority of situations in CF where users breaking apart monoliths into multiple apps.

**Comment by sreetummidi** [comment]
@fhanik @william-tran 
There is definitely a use-case around exchanging an existing JWT token for a new token based on the resource server needs.  SalesForce has popularized a similar flow, see here https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm
 GE had expressed interest in this as well

Let us do some more research on our side. I see a way to potentially exchange an exchanging a valid OpenID Connect ID token for a new access token with the restriction that we allow only auto-approved scopes

**Comment by fhanik** [comment]
@william-tran cf `cf cli` is not auto approved. The user approves it by giving the client her/his password.
for the password grant, that is the user's way of authorizing the client to act on its behalf.

**Comment by fhanik** [comment]
@william-tran this issue is still open, because no one is rejecting the use case. We get it, we just want to do it right if we're going to do it. Because, there is a way to do it already using UAA specific API.

**Comment by fhanik** [comment]
more interesting thoughts: if both the client and the resource are owned by the same entity, one could argue that they are the same client. 

ie, if you have 10 micro services accessing the same data, why would it require 10 different clients?

**Comment by william-tran** [comment]
@fhanik I don't want to seem defensive of the issue as I know there's no need for that, but I did want to bring up the idea of approval and under what circumstances can approval be implied, as I can't seem to find many statements describing what those circumstances are, other than "[Auto-approve for client apps that are part of platform](http://presos.dsyer.com/decks/oauth-rest.html#slide27)" and "[This avoids redundant and annoying requests to grant permission when there is not a reasonable need to ever deny them.](https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#id9)". Those speak to platform applications (eg Apps Manager UI) but some direction on what auto-approval means for end user applications and resources seems missing.

**Comment by gberche-orange** [comment]
Thanks @fhanik and @sreetummidi for considering this use-case.

In response to https://github.com/cloudfoundry/uaa/issues/260#issuecomment-203623800

> that approach is possibly flawed, because the user has authorized client foo to perform actions on his/her behalf. So giving client bar the right to do so, without the user's consent, would possibly violate the users intent.

In addition to propagating user consent for the auto-approved scopes as suggested above, another complementary approach is to introduce a relationship between the original client for which the user gave its consent and the clients to which derived tokens are obtained:

If the permission for the original client is revoked, then not only the original access token won't be refreshed (or validated with the check_token endpoint) but also derived access tokens won't be refreshed neither.

In response to https://github.com/cloudfoundry/uaa/issues/260#issuecomment-203651940 

> if you have 10 micro services accessing the same data, why would it require 10 different clients?

Here are some possible use-cases for distinct access tokens for each of the 10 clients:
- Different clients might have different [client scopes](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-Tokens.md#client-authorities-uaa-groups-and-scopes), that restrict the original access token scopes that the resource owner initially granted on the initial client. See [rfc7521#section-4.1](http://tools.ietf.org/html/rfc7521#section-4.1) that enforces that granted scopes to be ``be equal to or less than the scope originally granted to the authorized accessor.``

- Having distinct clients enable identifying each microservice client in the exchanges between micro services (in this case a client_id and client_secret would be passed in the JWT authorization grant)

I also wonder whether this feature #260 could avoid propagating (down to the micro service exchanges)  the original 3-leg access token, in addition authenticating using a 2-leg (client-credentials grant) access:  a single derived access token would be passed by each layer, propagating the (possibly reduced) user-granted scope and the current client identity. If this combined access token is granted the openid scope, then it could be exchanged for the id token to get full access to the end-user identity somewhere down the microservice call flow.

**Comment by william-tran** [comment]
> ie, if you have 10 micro services accessing the same data, why would it require 10 different clients?

If they were all accessing the same data I don't see the point of 10 different clients, and definitely not if all clients are equally trusted.  But what if internally, trust varies between the various clients and resources in a system, but this is an implementation detail you want to hide from the user? For example, a user logs into their web banking app at Acme Bank, and they see their account balance. From the user's perspective, there's one client, the webapp, and one resource, their account balance. 

In reality, the web app (client) makes a request to an account gatekeeper (resource + client), and that makes a request to the accounts System of Record (resource). One reason for breaking things apart this way could be that the web app team can't be trusted to have direct access to the SoR, so a different team implements all the enforcement logic in the gatekeeper. Here we have clients with varying levels of trust, the web app should only be allowed to access the gatekeeper, and the SoR should only allow access from the gatekeeper. 

When the web app gets a token, the token would have a scope of account-gatekeeper.read, this token would then be used in the request to account-gatekeeper, then account-gatekeeper exchanges the incoming token for another one with account-sor.read and uses that on the SoR.

**Comment by mwdb** [comment]
Using different OAuth2 clients for separate services makes sense for me. Our application developers develop applications split up in several micro services, each of them defining their own set of scopes. Aditionally there may be partner application involved, which provide services but have a reduced set of scopes; they must not have a scope to call other services.
As we have not yet the partner applications, we forward JWT token and use an JWT offline validation and an ACL to control OAuth2 tokens from what clients to accept. 
Obviously this will not work for partner application anymore, as they are less trusted.

I'd like to see a mechanism for app-to-app authentication based on a JWT token, e.g. a special scope controlling if this token can be used as user authentication when obtaining a token for another client.
For that case I'd see two use cases:
1) Tokens can be reduced in scope. Client a has scopes a.read, a.write, b.read. Client b has b.read, b.write. A token issued for a, used for user authentication towards b would then result in scope b.read (which is the only common scope)
2) Tokens sometimes get quite large, or maybe you don't want to give all scopes to a client. In that case an impersonation based on the authorities for a user stored in the UAA would be beneficial.

Besides that: What should be already possible today is to reduce the scopes by requesting a new token based on a refresh token and specifying the requested scopes

**Comment by sreetummidi** [comment]
I Have converted this to a feature story. I am closing this issue.

**Comment by gberche-orange** [comment]
Thanks @sreetummidi 

The url to this story as to ease following its progress https://www.pivotaltracker.com/story/show/109101552
