### ISSUE TITLE
question: /Groups: MEMBER as well as READER?

### ISSUE THREAD

**Issue by tony-kerz** [cloudfoundry/uaa#261]
i'm new to uaa, among other things, trying to understand the interactions between users, clients and scopes.

so, i set up a user called with `zones.uaa.admin` and i set up a client with same, 
then i issued the command:
```
uaac groups
``` 
and got zero hits.

after some research i came across [this line in ScimGroupEndpoints](https://github.com/cloudfoundry/uaa/blob/master/scim/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpoints.java#L136).

and it turns out that the user has an association with the `zones.uaa.admin`group with a "role" of `MEMBER` and not `READER`, so it isn't showing up in the result.

it seems like it should show up in the result set, and that the filter by `READER` should be expanded to include `MEMBER` as well?

i would be happy to submit a p/r, if someone can verify appropriate behavior.

cheers,
tony.

**Comment by plfx** [comment]
`zones.uaa.admin` is not a valid scope. This pattern is only used for zones other than the UAA. If you want to read groups in the UAA zone you will need either `scim.read` or else you need to make a request to `/groups/<group-id>` as a `READER` of the specified group.
