### ISSUE TITLE
 uaa/docs/UAA-APIs.rst POST /oauth/token missing info

### ISSUE THREAD

**Issue by sanjeevchopra** [cloudfoundry/uaa#265]
This document does not include what form (or other params) are needed to get a access token, using a refresh token.

**Comment by fhanik** [comment]
We don't support anything beyond the standard here.
https://tools.ietf.org/html/rfc6749#section-6
https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by fhanik** [comment]
Fixed via https://github.com/cloudfoundry/uaa/commit/9e3063d8af207588081306b2b8eb0acad4dec00f
