### ISSUE TITLE
question: per client jwt signing-key?

### ISSUE THREAD

**Issue by tony-kerz** [cloudfoundry/uaa#266]
is it possible/desirable to have jwt's issued to clients use client-specific signing keys?

best,
tony.

**Comment by fhanik** [comment]
It is not possible today. Starting with next release you can have mulitple keys and rotate them. 

It could be possible. what is the benefit of keys per client?

**Comment by tony-kerz** [comment]
thanks filip,

the only reason i was thinking about it was because i was looking at the [kong api manager](https://getkong.org/), and they have [a jwt-plugin](https://getkong.org/plugins/jwt/) which looks like it assigns a key per client.

i guess a potential benefit might be to segregate groups of clients that use the same key such that a 'single-sign-on' effect would only apply to a particular grouping?

with a single-key for a uaa install, would it imply that a token would be 'valid' for all clients defined in that install?

**Comment by sreetummidi** [comment]
@tony-kerz As Filip mentioned above we plan on supporting multiple signing keys for each identity zone. 
We don't plan on supporting this on a per client basis
