### ISSUE TITLE
Incomplete documentation on token revocation

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#268]
The "Access Tokens Administration APIs" section of https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst seems incomplete. There is a paragraph that mentions token revocation:
"
OAuth2 protected resources which deal with listing and revoking access tokens. To revoke a token with DELETE clients need to provide a jti (token identifier, not the token value) which can be obtained from the token list via the corresponding GET. This is to prevent token values from being logged in the server (DELETE does not have a body).
"
But there is no mention of the URI to use for token revocation or any other details for that matter.

**Comment by sreetummidi** [comment]
New docs available @ docs.cloudfoundry.com/uaa/
