### ISSUE TITLE
LDAP without e-mail leads to ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by momchil-sap** [cloudfoundry/uaa#269]
Hi,

If you configure UAA to delegate authentication to an LDAP server and that server does not return an e-mail field, then the `ExternalLoginAuthenticationManager ` class throws an `ArrayIndexOutOfBoundsException` exception.

The problem occurs in the following piece of code:
https://github.com/cloudfoundry/uaa/blob/master/common/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/ExternalLoginAuthenticationManager.java#L209

I believe it was introduced with this change (problem did not occur on CF 222): https://github.com/cloudfoundry/uaa/commit/7adc0b61dce6c284c46cc1453fbc46e9dd61a46b

The workaround for now is to configure the `uaa.ldap.mailSubstitute ` and `uaa.ldap.mailSubstituteOverridesLdap` properties explicitly.

P.S. It's important to note that login happens with user names that are not e-mails.

**Comment by paulcwarren** [comment]
Upon inspection we concluded that, when familyName and givenName are not mapped, there was little to no actual value in creating values from the email so we simply removed this code.  We believe this should resolve your issue as well.
