### ISSUE TITLE
Use of legacy library commons-httpclient:commons-httpclient:3.1

### ISSUE THREAD

**Issue by peterhaochen47** [cloudfoundry/uaa#2691]
[This library](https://mvnrepository.com/artifact/commons-httpclient/commons-httpclient/3.1) is very old and needs to be replaced. 

Some examples of usage in our code: 

In `ExternalOAuthAuthenticationFilter.java`

> import org.apache.commons.httpclient.util.URIUtil;
...
>     final String origin = URIUtil.getName(String.valueOf(request.getRequestURL()));

And in `TokenMvcMockTests.java` in the invalidScopeErrorMessageIsNotShowingAllClientScopes and 
invalidScopeErrorMessageIsNotShowingAllUserScopes test methods, for the same import.

See further discussion here: https://github.com/cloudfoundry/uaa/pull/2689#discussion_r1466794219
```[tasklist]
### Tasks
- [x] Remove direct usage, see https://github.com/cloudfoundry/uaa/pull/2826
- [x] Solve https://github.com/cloudfoundry/uaa/issues/2561
```

**Comment by strehle** [comment]
Will remove UAA usages, but the external dependency still requires it, see dep. tree

![image](https://github.com/cloudfoundry/uaa/assets/11627201/a763abf2-d5ef-49b8-9d49-9272a3c8f296)

**Comment by strehle** [comment]
solved
