### ISSUE TITLE
question: any way to get the "typ" in the generated token header?

### ISSUE THREAD

**Issue by tony-kerz** [cloudfoundry/uaa#270]
i'm trying to have [a third party](https://getkong.org/plugins/jwt/) validate a uaa jwt, 
and it is rejecting the uaa token because it doesn't have:

```
"typ": "JWT"
```
in the header...  

i gather `typ` is optional, but anyone have any suggestions as to how to (optionally),
get uaa to include it in the generated tokens?

regards,
tony.

**Comment by fhanik** [comment]
Thanks for filing this, we have added this to our enhancement list.

**Comment by tony-kerz** [comment]
thanks filip,

i'd be happy to attempt a p/r, if you happen to be able to direct me to the area of code which might be appropriate to effect that change. i tried some file searches in eclipse against the uaa source for things like `alg` or `HS256`, but didn't turn up anything obvious. wasn't sure if that kind of change may require a change to one of the members of the spring-security family. if it requires too much time to even research right now, i understand. 

have a good holiday!

cheers,
tony.

**Comment by fhanik** [comment]
https://github.com/cloudfoundry/uaa/blob/develop/common/src/main/java/org/cloudfoundry/identity/uaa/oauth/token/UaaTokenServices.java

see the class JwtHelper
