### ISSUE TITLE
Potential Error in the SCIM Filter Validation of the /ids/Users Endpoint

### ISSUE THREAD

**Issue by adrianhoelzl-sap** [cloudfoundry/uaa#2703]
The /ids/Users endpoint allows passing a SCIM filter as a URL parameter. For validating this filter string, the value is parsed and subsequently traversed recursively, checking each clause for validity.

When handling clauses joined by the operator `or` or `and`, we saw that an OR-operator is used for combining the validation result of the left-hand side and the right-hand-side of the expression (see https://github.com/cloudfoundry/uaa/blob/d962dd67cc08de7d43aeef9cf0ae92f8c4b5cb85/server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/UserIdConversionEndpoints.java#L123).

If the RHS of the expression is valid (i.e., `checkFilter` returned `true` for it) while the LHS is invalid (i.e., `checkFilter` returned `false` for it), the method will return `true` for the joined expression.

Instead, the two clauses should be combined by using an AND operator, so that both clauses are required to be valid.

If the current state of the code is however correct, this shall be made clear in the comments of the code.

**Comment by peterhaochen47** [comment]
Hi @adrianhoelzl-sap, is this PR ready for review? Asking because review is requested for #2704 (according to its description, depends on this current PR).
