### ISSUE TITLE
No way to set SAML or token private key password in SamlConfig class.

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#272]
The SamlConfig class allows the user to configure separate private keys for SAML or token signing. However, there is no way to specify the secret a private key that is encrypted. Of course, the secret living side by side with the private key is not terribly helpful for security but maybe we want this ability for ease of migration?

**Comment by fhanik** [comment]
As part of this class we will also add a field for signerKeyPassword. However, this does not imply that we support a passphrase of the token signing key at this time. We will add that as a separate story.
