### ISSUE TITLE
can a user manage all uaa resources(user, group,idp, sp)?

### ISSUE THREAD

**Issue by kooyeed** [cloudfoundry/uaa#276]
hi，all,

I want make a webui for uaa, but I have some questions.
1. when a user logined as a common user role, he can not fetch groups info。however, he has all scopes. how can I done with it?
2. how to delete a new identity-providers?

thank you very much.

**Comment by paulcwarren** [comment]
Re 1:-
Remember UAA is secured by OAuth2 so it's all about the client (i.e. an app - in this case your new webui) performing actions on behalf of the user (who approved the app to perform those actions) by presenting an access token.

The client gets an access token after the user authenticates with UAA, to prove who he is, and approves the client to do various things on his behalf.  Currently within UAA the user has a set of scopes representing the things he can do and the client also has a set of scopes representing the things he can *potentially* when allowed by a user.  The token will have the scopes that are shared by both user and the client (and that the user approved the client to perform on his behalf).

Re 2:-
Identity provider deletion is being added in the upcoming release (3.0)

HTH

**Comment by paulcwarren** [comment]
Any more information required @kooyeed?
