### ISSUE TITLE
Issue with different users from different origins but same username

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/uaa#277]
We are working with two user bases. The cf admins are entered into uaa with uaac and the regular user base comes via ldap. UAA allows for two user entities with same username but different origin.

Login with the different usernames and password combination works.
However, changing the password for either of them does not work.

Deleting a user with uaac does not work at all. Would also be questionable which user to delete as the only argument you can pass is username, which is not unique. Currently the message is "User not found".

Deleting the user with cf cli works, but also here the behavior is not well defined. Only username as parameter can be passed. This leads to deletion of user who was created first in the uaa. Executing the cf delete user command a second time deletes the remaining user entry.

This behavior was already reported in March in [Google group](https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/I_Uo63ZFEs0)

My proposal would be to extend the api and/or uaac and cf cli to support deleting a user based on its username and origin. If no origin is passed and the username is included multiple times, an error should be returned and no user should be deleted until it is clear which one really should be deleted.

**Comment by paulcwarren** [comment]
UAA API and uaac can support this today.  The API supports `DELETE` on `/Users/{userId}` which will delete a specific user BUT that assumes you know the ID of the user that you wish to delete.

The ID of a user can be found by issuing the following uaac command:-
```
uaac users 'username eq "marissa" and origin eq "saml"' -a ID,username
```
or, if the user you wish to find is in another zone:-
```
uaac users 'username eq "marissa" and origin eq "saml"' -a ID,username -z otherzone
```
(NB: you will need zone.{zoneId}.admin scope for the zone in question)

Once found the user can be deleted by issuing:-
```
uaac curl -XDELETE http://localhost:8080/Users/{userId} -H 'Accept: application/json'
``` 
or, if the user you wish to delete is in another zone:-
```
uaac curl -XDELETE http://localhost:8080/Users/{userId} -H 'Accept: application/json' -H 'X-Identity-Zone-Subdomain: otherzone'
``` 
(NB: but again you will need zone.{zoneId}.admin scope for the zone in question)

That said I also do agree that the CLI (uaac in our case) should have user management commands that allow a user to be uniquely identified (with perhaps a reasonable origin default of 'uaa') so I will leave this open and talk our PM about this.

**Comment by Kiemes** [comment]
Thanks for the detailed information. It is good that there is a way to delete specific users. However, it would be great to have this as integrated CLI user management commands.
Please keep me posted on the discussion with Sree.

**Comment by sreetummidi** [comment]
@Kiemes Ideally both Admins and Regular users should be coming from one source which incase of most enterprises is either SAML or LDAP based stores.
We have capabilities today to map scopes to ldap or saml groups. This allows LDAP and SAML users to have admin privileges. 

Is there any specific reason to have admin users in UAA and other users in LDAP?

**Comment by Kiemes** [comment]
@sreetummidi yes I know, ideally it would be the case, but in our setup the operations users (admins) come from our company and the regular CF users are users from our customer. There is no LDAP or SAML which holds all users from both companies.

However, regardless of the usage of the UAA, if the UAA supports the co-existence of multiple users from different sources at the same time, which it does, it would be great to have a more intuitive CLI command than using the uaac curl.

**Comment by sreetummidi** [comment]
@Kiemes point noted. We will add the cross origin smarts into the CLI
