### ISSUE TITLE
What is the REST method to refresh the token?

### ISSUE THREAD

**Issue by jabrena** [cloudfoundry/uaa#279]
Hi,

Using the UAA from CF, it is possible to authenticate a user to use the cloud controller. Once you have token and you know the expiration time is stored in this field: " expires_in: 599," my question is about refresh process in order to not loose the session.

``` bash
{ access_token: 'eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxNTgzNDFkYS02N2I5LTQwOWItYjNkNS
02ZDJmNDkzOTExNWIiLCJzdWIiOiIwNTQ0ODY5MS04YWU1LTQwZDktODU2Mi1kOWI4N2E2MTJiMzMiLC
JzY29wZSI6WyJzY2ltLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLmFkbWluIiwic2NpbS53cml0ZSIsIm
Nsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJwYXNzd29yZC53cml0ZSIsIm9wZW5pZCIsImNsb3VkX2Nvbn
Ryb2xsZXIucmVhZCIsImRvcHBsZXIuZmlyZWhvc2UiXSwiY2xpZW50X2lkIjoiY2YiLCJjaWQiOiJjZi
IsImF6cCI6ImNmIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcl9pZCI6IjA1NDQ4NjkxLThhZT
UtNDBkOS04NTYyLWQ5Yjg3YTYxMmIzMyIsInVzZXJfbmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbi
IsImlhdCI6MTQ1MDI3MzYwOSwiZXhwIjoxNDUwMjc0MjA5LCJpc3MiOiJodHRwczovL3VhYS4zNy40OC
44MS4xNzAueGlwLmlvL29hdXRoL3Rva2VuIiwiYXVkIjpbImNmIiwic2NpbSIsImNsb3VkX2NvbnRyb2
xsZXIiLCJwYXNzd29yZCIsIm9wZW5pZCIsImRvcHBsZXIiXX0.n_ji6NOioxY9rDJauW_Y67DGl-CLYk
GHUZBqpa0HScvvOHhj2BUZ6RuArQDmWQIVkOZpC3mWZoQczjtPvC5T6pbIEiDgTeGdTIrcjj4S52tRDe
-KpToduVihj8izPvOahhz0S1l7MAqwcxoDSLE5Jx3LMIAyF_nbMxziGZls8gA',
  token_type: 'bearer',
  refresh_token: 'eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJkMjAyZDBhNi0wMzUxLTRmZmMtYTRkY
y05OGQ4YTA0OGMwOTciLCJzdWIiOiIwNTQ0ODY5MS04YWU1LTQwZDktODU2Mi1kOWI4N2E2MTJiMzMiL
CJzY29wZSI6WyJzY2ltLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLmFkbWluIiwic2NpbS53cml0ZSIsI
mNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJwYXNzd29yZC53cml0ZSIsIm9wZW5pZCIsImNsb3VkX2Nvb
nRyb2xsZXIucmVhZCIsImRvcHBsZXIuZmlyZWhvc2UiXSwiaWF0IjoxNDUwMjczNjA5LCJleHAiOjE0N
TI4NjU2MDksImNpZCI6ImNmIiwiaXNzIjoiaHR0cHM6Ly91YWEuMzcuNDguODEuMTcwLnhpcC5pby9vY
XV0aC90b2tlbiIsImdyYW50X3R5cGUiOiJwYXNzd29yZCIsInVzZXJfbmFtZSI6ImFkbWluIiwidXNlc
l9pZCI6IjA1NDQ4NjkxLThhZTUtNDBkOS04NTYyLWQ5Yjg3YTYxMmIzMyIsImF1ZCI6WyJjZiIsInNja
W0iLCJjbG91ZF9jb250cm9sbGVyIiwicGFzc3dvcmQiLCJvcGVuaWQiLCJkb3BwbGVyIl19.YvndALXd
oMAbft8yrgZDWQrWEHX2eG4lGUEPhujP34YjeU0WNPQ8ssL9VBuakz0-qiCfuF_1fDnhF2vClBUVQBBd
4MeTkkxXQFZG5HJ8uNS6TaLSARMQ21IMpXukxzBD179s2AEOfhn8APQAqI7AqQEIhEwCxRPHOIBKVBsG
I50',
  expires_in: 599,
  scope: 'scim.read cloud_controller.admin scim.write cloud_controller.write pas
sword.write openid cloud_controller.read doppler.firehose',
  jti: '158341da-67b9-409b-b3d5-6d2f4939115b' }
```

**Comment by fhanik** [comment]
@jabrena What is your actual question?

**Comment by jabrena** [comment]
Yes, I would like to refresh the user token after 599 seconds or refresh in the middle of that time.

In OpenAM exist a way to refresh inactivity time:

``` bash
$ curl "https://openam.example.com:8443/openam/identity/attributes?\
subjectid=AQIC5wM2LY4SfcxuxIP0VnP2lVjs7ypEM6VDx6srk56CN1Q.*AAJTSQACMDE.*\
&refresh=true"
```

**Comment by fhanik** [comment]
hi @jabrena 

Refreshing an access token is part of the Oauth 2 specification
https://tools.ietf.org/html/rfc6749#section-6

You can issue a refresh grant for as long as the refresh token is invalid. This is a time longer than the access token is valid. Your refresh token below has `"exp": 1452865609,`. This represents the `Fri, 15 Jan 2016 13:46:49 GMT` in epoch time. You can get a new access token up until that time.

    {
      "jti": "d202d0a6-0351-4ffc-a4dc-98d8a048c097",
      "sub": "05448691-8ae5-40d9-8562-d9b87a612b33",
      "scope": [
        "scim.read",
        "cloud_controller.admin",
        "scim.write",
        "cloud_controller.write",
        "password.write",
        "openid",
        "cloud_controller.read",
        "doppler.firehose"
      ],
      "iat": 1450273609,
      "exp": 1452865609,
      "cid": "cf",
      "iss": "https://uaa.37.48.81.170.xip.io/oauth/token",
      "grant_type": "password",
      "user_name": "admin",
      "user_id": "05448691-8ae5-40d9-8562-d9b87a612b33",
      "aud": [
        "cf",
        "scim",
        "cloud_controller",
        "password",
        "openid",
        "doppler"
      ]
    }
