### ISSUE TITLE
Document logging usage for UAA

### ISSUE THREAD

**Issue by balteo** [cloudfoundry/uaa#281]
I haven't been able to figure out how to view the logs for the UAA application: no logs are generated on the console where the UAA app is started and no log file is generated either.

Would it be possible to document how to know view the logs or maybe there are alternative ways to monitor what is going on inside the UAA app?

**Comment by paulcwarren** [comment]
balteo, how are you running UAA?  ./gradlew run or are you using our bosh release or ???

**Comment by balteo** [comment]
Hi Paul,
I am running ./gradlew run
J.

2015-12-21 20:35 GMT+01:00 Paul Warren <notifications@github.com>:

**Comment by paulcwarren** [comment]
If you do a `sudo find / -name uaa.log` 

you should find the uaa.log under something like:-

`/private/var/folders/7v/518b18d97_3f4c8fzxphy6f8zcm51c/T/cargo/conf/logs/`

I will add a comment to our docs

**Comment by paulcwarren** [comment]
Updated docs as per the comment.  Please re-open if this isn't sufficient.  Thx.
