### ISSUE TITLE
/token_key possibly returns the wrong value for `alg`

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/uaa#282]
I was a bit confused as to why the JWK that is returned by `/token_key` has `alg` set to `SHA256withRSA`:

```
curl https://uaa.run.pivotal.io/token_key -s | jq .
{
  "alg": "SHA256withRSA",
  "value": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8/aXmEImpdwWHJlYc4G8\n3BgZVmyhCdy7SCL0kM7wV5xCvRKK0k4nKjH0QW2E+0GIKzIj4JQhYU+MeZHrArfC\nrfthIXcio/Ll6NvoTPY77XA7U6vBGCiLdGYSGrN8y064cF2uM8d3AEgTT0RzLK3E\n688Ltq38GxnoXOUuLZmXS2HeHNd2bW/k6Eyd9Z3ymmdpVZXMyLwepNxU38WQS2bJ\nPYXYvRkzoZ1ru/deExwbecI18NCeO/GKp3f8bwKuC2j3LKFJIAwW3zFoDrcAxpC/\nJDG2RSTj//CRvhtd7JkeQLVKGyIHNtACaPT3tFT6scvVXHGPB5fRTLB8Lr+mK4RI\nBwIDAQAB\n-----END PUBLIC KEY-----\n",
  "kty": "RSA",
  "use": "sig",
  "n": "APP2l5hCJqXcFhyZWHOBvNwYGVZsoQncu0gi9JDO8FecQr0SitJOJyox9EFthPtBiCsyI+CUIWFPjHmR6wK3wq37YSF3IqPy5ejb6Ez2O+1wO1OrwRgoi3RmEhqzfMtOuHBdrjPHdwBIE09EcyytxOvPC7at/BsZ6FzlLi2Zl0th3hzXdm1v5OhMnfWd8ppnaVWVzMi8HqTcVN/FkEtmyT2F2L0ZM6Gda7v3XhMcG3nCNfDQnjvxiqd3/G8Crgto9yyhSSAMFt8xaA63AMaQvyQxtkUk4//wkb4bXeyZHkC1ShsiBzbQAmj097RU+rHL1VxxjweX0UywfC6/piuESAc=",
  "e": "AQAB"
}
```

I did not find this string in any of the RFCs I looked at. I found it in the spring framework oauth code and that's about it. RFC7517 has an example JWK in the appendix that uses the same string (`RS256`) that is used in the JWT `alg` header.

https://tools.ietf.org/html/rfc7517#appendix-A.1

```
{"kty":"RSA",
          "n": "0vx7agoebGcQSuuPiLJXZptN9nndrQmbXEps2aiAFbWhM78LhWx
     4cbbfAAtVT86zwu1RK7aPFFxuhDR1L6tSoc_BJECPebWKRXjBZCiFV4n3oknjhMs
     tn64tZ_2W-5JsGY4Hc5n9yBXArwl93lqt7_RN5w6Cf0h4QyQ5v-65YGjQR0_FDW2
     QvzqY368QQMicAtaSqzs8KJZgnYb9c7d0zgdAZHzu6qMQvRL5hajrn1n91CbOpbI
     SD08qNLyrdkt-bFTWhAI4vMQFh6WeZu0fM4lFd2NcRwr3XPksINHaQ-G_xBniIqb
     w0Ls1jF44-csFCur-kEgU8awapJzKnqDKgw",
          "e":"AQAB",
          "alg":"RS256",
          "kid":"2011-04-29"}
```

This makes more sense to me. Is this a bug?

**Comment by fhanik** [comment]
The spec
  
    https://tools.ietf.org/html/rfc7517#section-4.4

contains no restrictions on the value of the `alg` parameter as long as it is collision resistant.
Are you asking for a feature to be able to define this value manually?

**Comment by jasonkeene** [comment]
This was more my confusion as to the difference between SHA256withRSA and RS256. I had to look at the oauth spring framework code to realize it is just an alias for the same algorithm. RS256 seems to be the more common name used in libraries and is listed in RFC 7518. It just seems like a better idea to use a value that is already established and defined in RFC 7518 vs making something up. In the end of the day it is a simple work around. I just wanted to make sure this was a conscious decision.

**Comment by whitlockjc** [comment]
While @fhanik is right that the spec allows for any _"collision resistant"_ value, UAA using a non-standard name for a standard algorithm is not only confusing but it also means that any spec-compliant JWS library will fail to be able to consume the `/token_key` document provided by UAA without **explicitly** supporting UAA.  My personal opinion on the matter is that this is a bug and should be reopened.  I will retract my statement if `SHA256withRSA` is different than `RS256` but my assumption is it is not.

**Comment by whitlockjc** [comment]
I'm sure you've found this list but here is the list of registered algorithms that any JWS compliant library will support out of the box: https://tools.ietf.org/html/rfc7518#page-6

**Comment by fhanik** [comment]
the name should be `RS256` and not `SHA256withRSA` according to 
https://tools.ietf.org/html/rfc7519#section-8

**Comment by whitlockjc** [comment]
After talking with @fhanik in Slack, just in case it wasn't clear, here is the issue.  The `/token_keys` URL should use `alg: RS256` but it is currently serving `alg: SHA256withRSA` which means any JWS complaint library will not be able to consume a UAA `/token_keys` document as-is without explicitly supporting the `SHA256withRSA` algorithm, which shouldn't be required since it's really just `RS256` but with a custom name.
