### ISSUE TITLE
Integrating UAA with a SAML app (UAA as SAML IDP and app as SAML SP)

### ISSUE THREAD

**Issue by slee-okta** [cloudfoundry/uaa#283]
I see that OAuth is the main vehicle for SSO into apps.  Was curious if there is a way to do it with SAML via what's here - or some workaround.

**Comment by sreetummidi** [comment]
@slee-okta 
UAA supports connecting SAML 2.0 based Identity Providers for the purposes of SSO.
In this situation the integration layer between UAA and the SAML IDP is SAML 2.0 and between the UAA and the APP is OAuth because the SAML Assertion is converted into an OAuth token for use by the APP

**Comment by pranjaljain** [comment]
This feature of UAA as SAML IDP is available now in UAA? Right?

**Comment by yhjhoo** [comment]
in this API document http://docs.cloudfoundry.org/api/uaa/

It says UAA support SAML protocol, any examples?
