### ISSUE TITLE
Issue with HSQL db

### ISSUE THREAD

**Issue by nileshmalpekar** [cloudfoundry/uaa#285]
"SELECT 1" seems to be no longer working to validate HSQLDB.
However following SQL statement works perfectly fine with HSQLDB
SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS

This one requires change in common/src/main/resources/spring/env.xml file

**Comment by fhanik** [comment]
Thank you, we received your PR, once you have signed the CLA we can merge it in. We will also figure out why `select 1` no longer works, as all our CI systems use it without any issue.

**Comment by nileshmalpekar** [comment]
Hi Filip,

My employer (Allstate insurance) confirmed yesterday that they have filed
CLA with cloudfoundray.org and that I'm free to submit the changes.

I've seen so many changes on the repo since then so I'll take a look into
the issue again.

Could you confirm if I need to submit the CLA copy still?

Nilesh

**Comment by fhanik** [comment]
I believe that we track this based on the organization you belong to (on
Github).
Submit a PR, see what the result is, and we can take it from there.

Filip

**Comment by nileshmalpekar** [comment]
Hi ,

Just spoke with someone at my office and now I'm part of the organization
on the GitHub which has CLA with Cloudfoundry.

I've got my code changes ready with testcases as well. It's a different
github id now (didn't want to use personal one).
Will submit pull request to "develop" branch
