### ISSUE TITLE
SAML redirect issue if SAML entity ID has spaces in it.

### ISSUE THREAD

**Issue by vbanga** [cloudfoundry/uaa#287]
This is a regression from build prior to November 11, 2015. We used to have an IDP definition which had the name, origin_key and entity id with a value which had spaces in it. E.g. "My IDP Defintion".
After upgrade to 2.7.3 release, this SAML redirect stopped working, instead it started to redirect to UAA login page.
After looking at the logs we suspect that the issue is during the following call: 

```
DispatcherServlet: Rendering view [org.springframework.web.servlet.view.RedirectView: unnamed; URL [saml/discovery?returnIDParam=idp&entityID=24fb29b7-286a-428f-8aaa-67e9e948426d.cloudfoundry-saml-login&idp=My IDP Definition&isPassive=true]] in DispatcherServlet with name 'spring'
```

We think this calls fails because the IDP name in the URL has spaces in it and is not URL encoded. From the code we found that LoginInfoEndpoint class was change on Nov 11th, when this change was made:https://github.com/cloudfoundry/uaa/commit/5a86b62d9dc69f26653b1b7e44b629ae07d76dd0#diff-994c256f86ac93251259ad46f0637232

This could be the root cause of the issue but requires more investigation.

**Comment by fhanik** [comment]
Created an IDP in the UAA

    entityID="My IDP"

Link shows up on home page. Clicking that link yields

    Request URL:http://localhost:8080/uaa/saml/discovery?returnIDParam=idp&entityID=cloudfoundry-saml-login&idp=okta-signed-or-encrypted&isPassive=true

Results in a 302 with Location

    Location:http://localhost:8080/uaa/saml/login/alias/cloudfoundry-saml-login?disco=true&idp=My+IDP

The space correctly encoded.

Please reopen if you see something different.
