### ISSUE TITLE
Unable to retrieve SAML user attribute values when NameFormat="...:unspecified"

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/uaa#288]
GIVEN SAML IPD post SAML assertions with user attribute
```
<ns2:Attribute Name="username" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
                <ns2:AttributeValue>Dummy</ns2:AttributeValue>
  </ns2:Attribute>
```
WHEN uaa retrieves user attribute values
THEN uaa should get "Dummy"

FAIL -> got following debug output :  SAML user attribute is not of type XSString

**Comment by paulcwarren** [comment]
We'll look into this but could you attach the stack trace of the actual error as well pls.

**Comment by fhanik** [comment]
This is fixed, and will be released as part of the next version. We now transform all SAML data types to strings.

**Comment by fhanik** [comment]
https://www.pivotaltracker.com/n/projects/997278/stories/111126154

**Comment by s-bortolussi** [comment]
Thanks
