### ISSUE TITLE
UAA is not able to use "public" schema in database after recreating postgresql job.

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/uaa#290]
This weekend we had stress test on our stage environment with CF release 207. To recover cluster we run `bosh cloudcheck` and recreated VMs with nats, etcd, postgres and CC. As far as I can see UAA was not affected by this test. After all jobs were in running state, CF applications were accessible, but we lost possibility to login to CF.

It appeared that uaa logs had an error `bad SQL grammar [select count(*) from users where id is not null ]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "users" does not exist`, looking into `uaadb` database I found out that there is a `public` schema that contained `users` table:

```
uaadb=> SELECT
    table_schema || '.' || table_name
FROM
    information_schema.tables
WHERE
    table_type = 'BASE TABLE'
AND
    table_schema NOT IN ('pg_catalog', 'information_schema');
           ?column?
-------------------------------
 public.schema_version
 public.users
 public.sec_audit
 public.groups
 public.oauth_code
 public.external_group_mapping
 public.expiring_code_store
 public.group_membership
 public.authz_approvals_old
 public.authz_approvals
 public.oauth_client_details
(11 rows)
```

To fix this issue I needed to run following command in postgresql console:

```
ALTER USER uaaadmin SET search_path to 'public';
```

I don't have too deep knowledge of the project, so I decided to ask question here. Do you know the possible reason of such problems? Thank you.

**Comment by sreetummidi** [comment]
@fhanik Can you please comment on this.
