### ISSUE TITLE
Oracle DB Support for UAA

### ISSUE THREAD

**Issue by hyadalam** [cloudfoundry/uaa#291]
I noticed this pull request from 2013 which provided Oracle DB support for UAA https://github.com/cloudfoundry/uaa/pull/39.

Is Oracle DB still being supported or has support for Oracle DB dropped as I am unable to find any documentation for the same.  Can you please point me to the right documentation.

**Comment by sreetummidi** [comment]
@hyadalam We are no longer testing and certifying with OracleDB because of the Enterprise License involved. That said, I would recommend that you take this up on the CF Mailing list to check if some other Open Source customer is using UAA with Oracle
