### ISSUE TITLE
SAML integration: possibility to 'track/map' users using external_id

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#292]
We noticed the improved SAML integration that arrived lately and are very happy about it!

However, there is a minor problem that we run into: 
- A SAML user logs in for the first time and a shadow user with his attributes is created in the UAA
- The user account on the external IdP changes, so that the NameID will be different than before (i.e. we have an external IDP that uses email addresses as NameID which can change)
- This user logs into CF again 

Now, the UAA user account is not updated but a new user is created. This is because [the UAA only checks for existing users by looking up the NameID as username](https://github.com/cloudfoundry/uaa/blob/868d1b66623c20290f87c424a27cbf12220ef1fe/login/src/main/java/org/cloudfoundry/identity/uaa/login/saml/LoginSamlAuthenticationProvider.java#L249).

Could this be improved? 
A proposal: Look up the user account in the UAA not only by username, but also by `external_id` attribute. Of course, this external_id attribute must be given in the SAML assertion (and mapped by the UAA SAML config).

**Comment by sreetummidi** [comment]
Hi @MatthiasWinzeler 
Previously UAA was limited to supporting only email-address as the nameid, but now we have added support all kinds. In addition to this we also have the capability to map the email address from an incoming claim in the SAML Assertion.

My recommendation would be to use an immutable field for NameID and pass the email separately in a claim

**Comment by MatthiasWinzeler** [comment]
Unfortunately, the only immutable field we get from the identity provider is the unqiue identifier (that resembles a GUID). If we use this as NameID, it ends up as username. So our users would have a rather ugly username which we like to avoid.

**Comment by jhamon** [comment]
I'm closing this issue since it's been quiet for 18 months. Please reopen a new issue if you have other problems or feedback.
