### ISSUE TITLE
Permit creation of long-lasting access tokens

### ISSUE THREAD

**Issue by ind1go** [cloudfoundry/uaa#293]
I'd like to be able to create access tokens that last for a long time - in the region of months or years - in a similar way to Github's access tokens.

For example, when integrating a Travis build of your application with Cloud Foundry (like https://docs.travis-ci.com/user/deployment/cloudfoundry), it's necessary to enter your account password to have your Travis server authenticate to Cloud Foundry, and this is then stored in your `.travis.yml` file for later deployments. This password can be encrypted, but it has the password lifecycle... so if your password changes (say regular forced changes), your builds fail until you update your `.travis.yml`.

**Comment by fhanik** [comment]
Nothing prevents you from creating clients that receive tokens with `Integer.MAX_VALUE` seconds expiration time. Example of uaa.yml config is

    oauth:
      clients:
        my-client:
          access-token-validity: 1209600
          refresh-token-validity: 1209600
          authorities: zones.write,cloud_controller.admin
          authorized-grant-types: authorization_code,client_credentials,refresh_token
          autoapprove: true
          override: true
          redirect-uri: https://p-identity.identity.cf-app.com/dashboard/
          scope: openid
          secret: my-client-secret

**Comment by ind1go** [comment]
Thanks for the comment @fhanik. Perhaps I'm confused about the relationship between the UAA and other parts of Cloud Foundry. How would I, as an application developer deploying apps to a Cloud Foundry installation, make use of that? Is there a `cf` command for it?

**Comment by fhanik** [comment]
hi @ind1go 

On Cloud Foundry (cf-release) the `UAA` job is there to handle authentication and authorization for all Cloud Foundry components. 

For an application to leverage that, you have a couple of options

1. If your the administrator of the CF itself, then you have permissions to create these clients.
They can be created in the CF deployment manifest or using the `uaac` command (ruby gem called cf-uaac)

2. You could deploy your own UAA instance as an application
https://github.com/cloudfoundry/uaa#deploy-to-cloud-foundry
