### ISSUE TITLE
Why does CloudFoundry-uaa save password in DB when using LDAP as authentication source?

### ISSUE THREAD

**Issue by hyadalam** [cloudfoundry/uaa#294]
UAA currently seems to save passwords for all users in the users table in the CloudFoundry's UAA db schema, whether it is authenticated within UAA or by an external identity provider such as LDAP.

Is there a way to disable passwords being saved for users when they are authenticated via LDAP (origin = LDAP).

My current setup is using cloudfoundy-uaa version 2.7.1 and the datastore as PostgresSQL.

The LDAP configuration in uaa.yaml is

    ldap:
      profile:
        file: ldap/ldap-search-and-bind.xml
      base:
        url: 'ldap://dev.local:389/'
        mailAttributeName: mail
        userDn: 'cn=manager,ou=admin,dc=company,dc=com'
        password: 'password'
        searchBase: 'ou=people,dc=company,dc=com'
        searchFilter: 'cn={0}'
      groups:
        file: ldap/ldap-groups-map-to-scopes.xml
        searchBase: 'ou=groups,dc=company,dc=com'
        searchSubtree: true
        groupSearchFilter: 'member={0}'
        maxSearchDepth: 10
        autoAdd: true

Here is a sample entry in the Users table - "e031c9cc-ed93-4c07-ac0b-8854997c54d9";"2015-12-30 07:56:47.235";"2015-12-30 07:56:47.235";0;"hyadalam";"$2a$10$.NF558BLXDX10znxWpS8e./H28TffmJmffiMBeaq9bhl/‌​WJKz8gCi";"hyadalam@email.com";0;"hyadalam";"hyadalam";TRUE;"";"uaa.user";TRUE;"l‌​dap";"cn=hyadalam,ou=people,dc=company,dc=com";"uaa";"";"2015-12-30 07:56:47"

**Comment by fhanik** [comment]
That's just a non null value never used. That is not the value of the password the user typed in.
The actual value is a blank string (encrypted with bcrypt), but the UAA will never use it for authentication, because the `origin=ldap` value.

Filip

**Comment by hyadalam** [comment]
Thank you Filip, that clears the confusion.
