### ISSUE TITLE
Improve Error Message on deleting members of groups

### ISSUE THREAD

**Issue by ChristianWilhelmSAP** [cloudfoundry/uaa#2999]
Hi UAA team,

when we get errors on deletion of member of groups, we get a very generic exception:
landscape_tools.uaa.UAAException: UAA replied error '[no error provided]' (500) on '<redacted Host>/Groups/<redacted groupId>/members/<redacted memberId>': [no description provided]

While the error itself was mostlikely caused by DB connection issues, the error message is extreme generic and could be enhanced in my opinion.

Best regards,
Christian

**Comment by strehle** [comment]
@ChristianWilhelmSAP 
Do you have a callstack or more insights?

**Comment by ChristianWilhelmSAP** [comment]
@strehle unfortunately not. This issue occurred during a degredation situation and was handed over by our SRE 
colleagues.
from our colleague @adrianhoelzl-sap I got this information: we call the repository directly without explicit error-handling: https://github.com/cloudfoundry/uaa/blob/02c4ec4a7d7f0b3713bb909b7a03c93469c455c5/server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpoints.java#L569
Within the exception handler the controllers UAA does not handle any more specific exception except the bad sql: https://github.com/cloudfoundry/uaa/blob/aa4c13e967cd3572960f13ef66b146d9c12737b3/uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml#L138

**Comment by strehle** [comment]
@ChristianWilhelmSAP I could not found the "no error provided" and from text it must be a client tool , so a tool in-between you and UAA.

However I created the PR to map generic DB issues into HTTP 422

Here is an example branch with a change
https://github.com/cloudfoundry/uaa/tree/scimMoreGenericExceptionHandling-example

Using

uaac member add internal.superuser marissa 
uaac member delete internal.superuser marissa 

show the new error using branch scimMoreGenericExceptionHandling-example
