### ISSUE TITLE
autocomplete=false does not work, it needs to be autocomplete=off

### ISSUE THREAD

**Issue by cantino** [cloudfoundry/uaa#300]
In the login page, the `autocomplete` attribute is [set dynamically with a boolean expression](https://github.com/cloudfoundry/uaa/blob/2324b38f690ff5809fefd8217b319c9dbdc10c99/server/src/main/resources/templates/web/login.html#L15).  The result is `true` or `false`, but unfortunately the spec requires `on` or `off` as the value of the `autocomplete` attribute.

**Comment by sreetummidi** [comment]
Fixed in UAA 3.2.0 and above !
