### ISSUE TITLE
Full PGSQL schema available?

### ISSUE THREAD

**Issue by RossRothenstine** [cloudfoundry/uaa#302]
Hey all,

I'm working on a cloud instance with a database that has BDR enabled, so certain migrations fail due to ALTER TABLE restrictions. I have no control over the BDR settings.

Is there a complete schema (that as all the migrations applied) that I could use for Postgres?

**Comment by fhanik** [comment]
You can create it by running the unit test
https://github.com/cloudfoundry/uaa/blob/master/server/src/test/java/org/cloudfoundry/identity/uaa/test/CreateDB.java

Uncomment the @Ignore annotation

If your postgreSQL is running locally do

    create database uaa;
    create user root with superuser password 'changeme';

and you don't need to change any config in `uaa.yml`

**Comment by RossRothenstine** [comment]
:+1: Worked like a charm! Thanks. I don't know why I didn't think of running it locally -.-
