### ISSUE TITLE
Remove dead invitations UI pages?

### ISSUE THREAD

**Issue by jcscottiii** [cloudfoundry/uaa#304]
The introduction of this [patch](https://github.com/cloudfoundry/uaa/commit/6e059f8d1ba0ebe95d1c606646ca99b32025d194) 
 deprecated the [UI endpoints](https://github.com/cloudfoundry/uaa/commit/6e059f8d1ba0ebe95d1c606646ca99b32025d194#diff-049cddf97ad8d6fb4d254486bb05c4f9R164). However, the pages are still around.

Examples:
- https://github.com/cloudfoundry/uaa/blob/2324b38f690ff5809fefd8217b319c9dbdc10c99/server/src/main/resources/templates/web/invitations/new_invite.html

Any idea why these haven't been removed yet. I can put up a PR if needed.

**Comment by mbhave** [comment]
@jcscottiii thanks for raising the issue. We will remove these pages.
