### ISSUE TITLE
Support for fine grained permissions via UMA

### ISSUE THREAD

**Issue by thomasdarimont** [cloudfoundry/uaa#305]
Any plans to support central management of fine grained permissions via User-Managed Access (UMA) Profile of OAuth 2.0?
https://docs.kantarainitiative.org/uma/draft-uma-core.html
https://kantarainitiative.org/confluence/display/uma/Home

**Comment by sreetummidi** [comment]
@thomasdarimont We don't have any plans yet. We are exploring different ways to achieve fine grained authorization. It may most likely be a separate project than UAA.
