### ISSUE TITLE
Vulnerable to 307 redirect?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#307]
Recently, a paper describing two new attacks on the OAuth2 protocol was published:
http://arxiv.org/pdf/1601.01229v2.pdf

The second attack (IdP Mix up) is not relevant for UAA since it does not act as OAuth RP.

My question: Is the UAA vulnerable to the first attack in the paper (307 redirect)?
It seems UAA always uses 302 redirects and is not vulnerable. But is it using 307 redirects under certain circumstances?
Does it use 307 redirects in its codebase at all? I does not seem like that when scanning through the code.

**Comment by posijon** [comment]
Thanks for the info and very relevant issue number! The UAA doesn't use 307 temporary redirects, so its safe on that front.
