### ISSUE TITLE
default redirect_url/target_url after login

### ISSUE THREAD

**Issue by clementchi** [cloudfoundry/uaa#314]
If using authorization code grant, when go to login page directly and login (through bookmarking login page), user will be redirected to an error page with message "You should not see this page. Setup your redirect URI". 
I understand the problem is due to unknown redirect uri. 

UAA's /oauth/authorize route should pass the redirect uri when it redirects the user to the login page. Therefore when user bookmark the login page, it includes the redirect_url and redirect the user back to the correct application after login. The redirect url should match the redirect url list that is set per client.

**Comment by sreetummidi** [comment]
@clementchi This implementation is on the same lines SAML redirects. Book marking intermediate login page redirects is not supported. The user should only be bookmarking the Application URL which is capable of redirecting to UAA with the proper client id and redirect uri
