### ISSUE TITLE
UAA Docs issue with 77.19.0

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#3155]
### What version of UAA are you running?

[What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?]

77.19.0
https://docs.cloudfoundry.org/api/uaa/version/77.19.0/index.html
> you cannot open the TOC on the left side.

If you open version before, e.g.
https://docs.cloudfoundry.org/api/uaa/version/77.18.0/index.html
you can open it.

### How are you deploying the UAA?

I am deploying the UAA

https://docs.cloudfoundry.org/api/uaa/version/77.19.0/index.html

### What did you do?

Open the documenation.

### What did you expect to see? What goal are you trying to achieve with the UAA?

TOC details

Maybe any change inbetwee

https://github.com/cloudfoundry/uaa/compare/v77.18.0...v77.19.0

@fhanik  FYI ?
https://github.com/cloudfoundry/uaa/pull/3091
Any idea ?

### What did you see instead?

nothing

**Comment by fhanik** [comment]
@strehle thanks! Taking a look

**Comment by fhanik** [comment]
@strehle https://github.com/cloudfoundry/uaa/pull/3156 should contain the correct generation of the menus
