### ISSUE TITLE
Switch in-project links in all Markdown documentation files to relative links

### ISSUE THREAD

**Issue by michael-fei** [cloudfoundry/uaa#317]
In your Markdown files you have links to other markdown files within your project (e.g. the main README.md file has links to UAA-Tokens.md, UAA-LDAP.md, and many others). The problem is that those links are all absolute links to those files in your GitHub account (e.g. the link in README.md to UAA-Tokens.md is "https://github.com/cloudfoundry/uaa/tree/master/docs/UAA-Tokens.md"). This is fine until people fork this UAA project. Anyone who forks your project will still have their copies of the Markdown files with link that point back to **your** versions of the files on **your** GitHub repository. People may want to modify the documentation files in their forks, but no one will be able to see those modifications on anything other than the main README.md file since the links will all go back to your copies of the files.

To fix this, I suggest you change all links in this project's Markdown documentation files which point to other Markdown files within this project to use relative paths. (For example, in the README.md file change the link to the UAA-Tokens.md file from "https://github.com/cloudfoundry/uaa/tree/master/docs/UAA-Tokens.md" to simply "/docs/UAA-Tokens.md".) This would ensure that links in forked copies of this repository would always point to Markdown files within that same repository instead of linking back to yours.

**Comment by sreetummidi** [comment]
This is currently fixed on master
