### ISSUE TITLE
/token_key requires authentication

### ISSUE THREAD

**Issue by amiri-ge** [cloudfoundry/uaa#318]
I seem to remember this endpoint not requiring authentication. Now it seems that it does. Can someone please confirm that the behavior changed?

Also if it was changed, why require authentication to retrieve a **_public_** key?

**Comment by amiri-ge** [comment]
Nevermind. I'll confirm this myself.

**Comment by fhanik** [comment]
authentication required if you're using symmetric keys, ie private key and public key are the same
