### ISSUE TITLE
Login server session expiration

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#319]
I have some questions regarding the login server session expiration: After a user has logged in using the browser, i.e. to obtain a one time passcode, how long is this session considered valid?

It seems there is no session timeout explicitly declared in the UAA source, so it will fall back to the default 30 minutes session timeout of tomcat. 
And if I understand this timeout correctly, it is an idle timeout - so if the user accesses the login server within these 30 minutes, he could extend the lifetime for another 30 minutes - possibly forever. So there is no "maximum" lifetime.
Is this correct?

I saw there are some efforts to make the lifetime of the session cookie configurable: https://www.pivotaltracker.com/n/projects/997278/stories/113630271
So with this upcoming version, we will be able to set a max-age. Will this be the "idle" session timeout (and "refreshable") or the "overall" session timeout?

**Comment by fhanik** [comment]
The `max-age` specifies the expiration date on the session cookie. While the session on the server can expire earlier, by being idle, or later, the browser will stop sending the cookie, thus making the server side session useless, until it expires. 

https://docs.oracle.com/cd/E17802_01/products/products/servlet/2.1/api/javax.servlet.http.Cookie.html#setMaxAge(int)

**Comment by MatthiasWinzeler** [comment]
Thanks for the explanation - so this `max-age` behaves like a `overall` timeout. Are you planning to add a possibility to change the server side session timeout (i.e. to increase the idle timeout)?

**Comment by fhanik** [comment]
We can, please open a new issue for that.

**Comment by MatthiasWinzeler** [comment]
Thank you very much! See #320
