### ISSUE TITLE
Setting UAA session timeout (backend) in config

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#320]
As described in #319, it is currently not possible to configure the UAA's backend session timeout - it falls back to [Tomcat's default setting of 30 minutes](https://github.com/apache/tomcat/blob/TOMCAT_7_0_42/conf/web.xml#L509).

It would be nice if we could specify this session timeout as part of login.yml or uaa.yml (and the equivalent `uaa-boshrelease` templates so that we can set it in the `cf-release`).

**Comment by sreetummidi** [comment]
@MatthiasWinzeler 
Starting with UAA 3.2.0 & CF - Release 232 setting a session timeout for UAA is now possible.
Please refer to :  https://github.com/cloudfoundry/uaa-release/releases/tag/v7 for more details

**Comment by fhanik** [comment]
@sreetummidi we have implemented cookie timeout, but not session timeout. They are slightly different. The cookie timeout is a hard date. The browser will discard the cookie after that time.

The session timeout is an idle server timeout. If the server hasn't received a request in so long, it will discard the server side session. Unrelated to the cookie.

**Comment by tnwang** [comment]
This had been fixed as part of https://www.pivotaltracker.com/story/show/115829293 in October. Closing.
