### ISSUE TITLE
'uaac' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mamidishetti** [cloudfoundry/uaa#321]
Hi team,

After runing this "gem install cf-uaac" command

when i run "uaac help" we are not able to run this cammand

"'uaac' is not recognized as an internal or external command, operable program or batch file."

getting this error please help me in fixing this issue

Thanks
Divya.M

**Comment by fhanik** [comment]
You will need to find out where the gem is installed

For example: `/Users/fhanik/.rvm/gems/ruby-2.1.6/bin/uaac`

and your PATH variable needs to point to that directory.

**Comment by mamidishetti** [comment]
hi team

i have added path \cf-uaac-master\bin\uaac 
but still  im facing same issue
please help me

**Comment by fhanik** [comment]
You are having general Ruby issues, not related to the UAA.
I would suggest hitting up the mailing list for help. 
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/

The mailing list is your general/open source support forum.
