### ISSUE TITLE
inconsistent UAA user experience in case of invalid route and wildcard route mapping

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#322]
If we use direct routes only like testdomain1.uaa-service.com and user specified wrong route like testdomain2.uaa-service.com user will get HTTP 404 error with message route "testdomain2.uaa-service.com" not found. I assume this error coming from GO Router as it can't find proper route mapping. However if we replace "testdomain1.uaa-service.com" route to wildcard route like following "*.uaa-service.com" if user specifies "testdomain2.uaa-service.com" URL UAA will return "Sad Cloud" page: "Uh oh. Something went amiss." with HTTP 404 error code. It is good that HTTP error codes are consistent, however user experience is different. Would UAA team would consider to mimic Go Router error for this use case?

**Comment by fhanik** [comment]
Work in [progress](https://github.com/cloudfoundry/uaa/commit/9c5a8ba7d955af7a74212361ea9b675f9924b113)
