### ISSUE TITLE
question: what would be required to point uaa at custom database?

### ISSUE THREAD

**Issue by tony-kerz** [cloudfoundry/uaa#323]
is there some discrete set of spring-security(-oauth) repository interfaces that could be implemented to point uaa at an entirely different database?

is there any precedence for this strategy?

we are considering options for using uaa in conjunction with our own database where we would have additional entities and relationships around the "user" entity, things like roles (collections of privileges) and various other "business" level relationships.

one option would be to stick with one of uaa's supported databases (e.g. postgres, mysql, ldap) and maintain a "cross-reference" between the two databases (the business-centric one and the uaa one).

another option we are considering is attempting to merge uaa entities/attributes into our business-centric one and repoint uaa to that one via required repository implementations. 

interested in any guidance or experience around this.

best,
tony.

**Comment by sreetummidi** [comment]
@tony-kerz We don't have plans to support custom external database configuration for UAA.
If you want to to use a custom user store with UAA, it should be front-ended by a SAML 2.0 Identity Provider.
