### ISSUE TITLE
Question: What is best way to customize reset_password link

### ISSUE THREAD

**Issue by yogeshsajanikar** [cloudfoundry/uaa#324]
I have successfully deployed UAA server. However, we would like to have integrated look and feel of our own app, and use UAA as a authorization backend. For this, I have written a small proxy in ruby using cf-uaa-lib. However, reset_password link sent over mail poses a particular challenge, as this link always points to <uaa.url>/reset_password.

Is there a way to customize the reset_password link sent over a mail? So that in my ruby application, I will handle (proxy) it to UAA.  The EmailService takes loginUrl as a context (but does not use it). It might be customize bean for ResetPasswordController. Is this a good idea?

**Comment by cdutra** [comment]
Hi Yogesh,

You can make a call to /password_resets endpoint (
https://github.com/cloudfoundry/uaa/blob/9b5c13d793ebfe358e26559cedc6b528a557b43f/server/src/main/java/org/cloudfoundry/identity/uaa/account/PasswordResetEndpoint.java#L72)
in UAA passing a email address to start the reset password flow. The
response will be a code. With this code you can build the url to your
application and then send it to /password_change endpoint (
https://github.com/cloudfoundry/uaa/blob/9b5c13d793ebfe358e26559cedc6b528a557b43f/server/src/main/java/org/cloudfoundry/identity/uaa/account/PasswordResetEndpoint.java#L97)
with the new password to reset the password.

Sincerely,
Chris Dutra

**Comment by yogeshsajanikar** [comment]
Thanks Chris,

I am starting with password_resets, but does this end point needs a access token? A call to this typically fails with typical "An Authentication object was not found in the SecurityContext"

~Yogesh

**Comment by yogeshsajanikar** [comment]
Worked perfectly.

Just to add, authority - oauth.login is required to access this end point.
