### ISSUE TITLE
question: sso from multiple clients

### ISSUE THREAD

**Issue by tony-kerz** [cloudfoundry/uaa#326]
if i authenticate with uaa via `client-1`, i will get a token with `client_id` of `client-1` with the intersection of scopes for my user and those of `client-1`.

so now what happens if i attempt to authenticate via `client-2`? 

in theory, my existing token would prove i was authenticated, but what about the single `client_id` field in the token and `client-2` relevant scopes?

will the token be replaced?

as i write this, i realize i should just try, but any links to relevant info would be appreciated.

best,
tony.

**Comment by fhanik** [comment]
Better place to ask is on the mailing list
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/

To answer your question:
You can request as many tokens as you want. You can have two tokens, one for client1 and another token for client2

You can not combine two clients into one token.

**Comment by tony-kerz** [comment]
thanks filip, excellent info!

i'll try the mailing-list next time too :innocent:
