### ISSUE TITLE
Question: best way of migrating 4m users into uaa?

### ISSUE THREAD

**Issue by czerwina** [cloudfoundry/uaa#327]
We have a bespoke application with users stored in oracle. The user password are stored as a one way hash with a seed. What would be the best way to migrate to using uaa? We have to move off the current db, but we can't ask all users to reset their passwords.

**Comment by sreetummidi** [comment]
@czerwina  The only way to undergo this migration is to import these users into UAA and force a password reset.

If you are open to federation solutions, you could potentially add a SAML 2.0 IDP in front of the Database and connect to UAA using SAML
