### ISSUE TITLE
ConcurrentModificationException in CachingPasswordEncoder 

### ISSUE THREAD

**Issue by mikeroda** [cloudfoundry/uaa#330]
There is a threading issue in org.cloudfoundry.identity.uaa.util.CachingPasswordEncoder that causes a ConcurrentModificationException under high loads. The issue is on line 105:

`        for (String encoded : cacheValue!=null ? cacheValue : Collections.<String>emptyList()) {
`
The access on Collections.emptyList() is not thread safe and even though it is an empty list, accessing it qualifies as modification (see javadoc) and can result in a ConcurrentModificationException.

**Comment by fhanik** [comment]
hi @mikeroda 
Can you expand a bit more of when there would be a thread issue on the empty list?

    return (List<T>) EMPTY_LIST;

But I do see where the `ConcurrentModificationException` comes into play, on the iterator of the non empty list.

**Comment by mikeroda** [comment]
Sorry I misidentified the problem.  According to the stack trace the issue is with a LinkedHashMap so it must be modification of the cacheValue on that line:

2016-03-04 07:01:15.392 ERROR 8 --- [io-8080-exec-24]
hainPostProcessor$HttpsEnforcementFilter : Uncaught Exception: java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
	at
org.cloudfoundry.identity.uaa.util.CachingPasswordEncoder.internalMatches(CachingPasswordEncoder.java:105)

That is strange because I would think this would prevent such problems:

`        cache.putIfAbsent(cacheKey, Collections.synchronizedSet(new LinkedHashSet<String>()));

**Comment by fhanik** [comment]
I believe this should take care of it

https://github.com/cloudfoundry/uaa/commit/48a47e631f4e3eb1307a949781e9e7ceaf74781b

**Comment by fhanik** [comment]
oops, not a complete commit. I will force push and override that one

**Comment by mikeroda** [comment]
Local copy should do it. Looks good, thanks.

**Comment by fhanik** [comment]
Closing, no issue reported since fix.
