### ISSUE TITLE
SAML - redirect issues with Chrome/Firefox

### ISSUE THREAD

**Issue by rwwohl** [cloudfoundry/uaa#335]
Since upgrading to v231 were having issues with uaa redirecting to the proper url after authenticating through saml to our ping-federate identity. The normal sequence went:  

1. cf login --sso, which would direct them to a passcode link: One Time Code ( Get one at https://login.mydomain.com/passcode )> 

2. user would enter that url into browser which if not authenticated would take them to https://login.mydomain.com where they could click on the linkText field for our saml provider 

3. this would take them to our Ping Identity login page where they would login 

4. After step above, it used to redirect the user back to https://login.mydomain.com/passcode where they could then obtain the passcode to enter into cli. Now, instead it ends up directing them to https://login.cf-cnb.mydomain.com/favicon.ico which throws the error 'Uh-oh. Something went amiss'. I can manuallly reenter https://login.mydomain.com/passcode to get the passcode. 

Seems to only be issue with Chrome/Firefox.  Safari works fine.  I suspect based on inspecting the browser network requests and uaa logs its when Chrome/Firefox tries to get the favicon.ico its throwing off the Redirect strategy.  I noticed if I manually copy a favicon.ico into the root folder of uaa and then try it, it fails one more time but after this even if I remove the favicon.ico (assume because browser has it cached) it redirects without any problem

**Comment by sreetummidi** [comment]
@rwwohl 
We have fixed this issue. This will be available with cf-release 233 (UAA release 3.2.1)
