### ISSUE TITLE
Login Page for CF sends unencrypted form data

### ISSUE THREAD

**Issue by moizkhan2712** [cloudfoundry/uaa#336]
The Login page for Cloud Foundry (part of UAA job) sends form data in unencrypted format (see attached screenshot).

![browser_pwd](https://cloud.githubusercontent.com/assets/7640883/13976920/38dfb998-f0ea-11e5-8dc5-42ff3ca01d56.PNG)

Can the Login page template be modified so that this form data is encrypted and secure?

Example: Yahoo Login Page

![pwd_plaintext](https://cloud.githubusercontent.com/assets/7640883/13976957/a24aa078-f0ea-11e5-8b05-d61a32d6386f.png)

Note; We're using CF release v230 and corresponding UAA Release v3.0.1 currently. If this issue has already been addressed in subsequent releases, feel free to close it. :)

**Comment by fhanik** [comment]
cf-release forces HTTPS,that's the encryption around the plain text data that sends it.

other than that, UAA itself has the `require_https` setting, where it will reject requests that are not sent over https
