### ISSUE TITLE
Trying to use environment variables within custom uaa.yml

### ISSUE THREAD

**Issue by KJoyner** [cloudfoundry/uaa#337]
I was trying to use environment variables within the uaa.yml (e.g. ${DB_URL" within the jdbc url). This did not seem to be working. Does uaa.yml support environment variables?

**Comment by fhanik** [comment]
The UAA does support environment variables, but not as mentioned above. You can't insert an environment variable into the uaa.yml file. 

Instead, you can omit the field in the uaa.yml, and the runtime will pick it up directly from the system environment.
