### ISSUE TITLE
UI Integration Tests out if step with Branding Changes

### ISSUE THREAD

**Issue by RoopGuron** [cloudfoundry/uaa#338]
The Branding capabilities that were added to the UAA in 3.1.0 are not reflected in the Integration Tests.
The following integration tests hard code the title to be 'Cloud Foundry' as opposed to reading it from **the `login.yml `configuration `branding.companyName` as per branding feature recommendations**

`org.cloudfoundry.identity.uaa.integration.feature.LoginIT.java`

 A large number of tests have the assert statement---        `assertEquals("Cloud Foundry", webDriver.getTitle());`

also
`org.cloudfoundry.identity.uaa.integration.feature.CreateAccountIT.java`
`testClientInitiatedSignup` has an assert: 
`Assert.assertEquals("Create your account", webDriver.findElement(By.tagName("h1")).getText());`
which at runtime would evaluate to "Create your Predix account"

also
`org.cloudfoundry.identity.uaa.integration.feature.ResetPasswordIT`
at least 3 tests are doing the assert as follows:
`Assert.assertEquals("Cloud Foundry", webDriver.getTitle());`

also
` org.cloudfoundry.identity.uaa.integration.feature.SamlLoginIT`
at least 3 tests are doing the assert as follows:
`Assert.assertEquals("Cloud Foundry", webDriver.getTitle());`

and also
`org.cloudfoundry.identity.uaa.integration.feature.SamlLoginWithLocalIdpIT`
has the test testLocalSamlIdpLogin with the assert statement:
`Assert.assertEquals("Cloud Foundry", webDriver.getTitle());`

these tests should all be getting the title from the login.yml configuration.

**Comment by fhanik** [comment]
These integration tests would not necessarily have access to the login.yml of the running server.
The integration tests can run against a remotely deployed UAA, such as a cloud foundry acceptance environment.
These tests reflect what a `default` UAA is. 

*BUT...*

Happy to accept a Pull Requests if you see room for improvements.
