### ISSUE TITLE
LDAP Search and bind method : Mail is not stored in the UAA database

### ISSUE THREAD

**Issue by MyGoul** [cloudfoundry/uaa#342]
Hi,

I'm currently connecting my uaa to the company ldap with the search and bind method. With a tcpdump i can see :
- A bind from the technical user which has read access on the LDAP registry 
- A search to find the user, this search brings all the user's data back
- Unbind
- A bind on the LDAP registry with the user trying to login
- A search request
- Unbind

I'm actually surprised that the second phase (called bind) actually does a search. 

Unfortunately for me if technical users has search access on the LDAP, standard users only have bind acess. Consequence is that when i login in CF through the CLI with a new user, authentication is validated with LDAP, user is created in the UAA database but without the mail info for example. Knowing this, i'm a bit puzzled with the search and bind method, i don't understand its real benefit compared with the simple bind as data retrieved by the technical user are not used to create the user in the UAA database.

Recap : If the second search request fails the mail info is not stored in the database whereas this data was available on the first search request made by the technical user.

Thanks in advance for your support.
Sylvain

**Comment by fhanik** [comment]
The problem stems from [Spring Security LDAP ](https://github.com/spring-projects/spring-security/blob/master/ldap/src/main/java/org/springframework/security/ldap/authentication/BindAuthenticator.java#L95-L96) where the first search returns all attributes, and a [second search](https://github.com/spring-projects/spring-security/blob/master/ldap/src/main/java/org/springframework/security/ldap/authentication/BindAuthenticator.java#L125) is initiated after bind is complete.

**Comment by fhanik** [comment]
We have created a pull request with Spring Security LDAP, to get this issue remedied.

**Comment by ramonskie** [comment]
it is now added to 4.1.1
so we can test it with a nightly if we want
