### ISSUE TITLE
Internal Login & XHR Clients, CSRF

### ISSUE THREAD

**Issue by mwdb** [cloudfoundry/uaa#343]
The [internal login](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#internal-login-form-get-login) is broken as the  UAA was changed to requires a CSRF token (which is good).
When logging in as html client, the page includes a hidden field like 

<input type="hidden" name="X-Uaa-Csrf" value="s2WfnW" ...

When logging in as an XHR client, there seems to be no possibility to obtain an CSRF token so that an XHR client can authenticate against the UAA.
I'd like to contribute the following changes:

1) Add an option to give the CSRF token to an XHR client by including a CSRF token in the /login endpoint when called with Accept: application/json
2) After successful authentication, UAA redirects to the url  that the client initially tried to call. As an XHR client can not intercept an HTTP 302 redirect, I'd like to change the spring configuration to add an   
authentication success handler that in case requested with accept: application/json, does not redirect but instead returns the information where the client should be redirected to.

Please provide short feedback if these changes make sense, then I'd contribute them to the develop codeline.

Best Regards,

Martijn de Boer

**Comment by chrisrana** [comment]
Hi I am getting Invalid CSRF token for url ..I have opened the case(348) also for this.Can you Please help me this.
DetailCorsFilter: CORS processing completed for: URI Cf-231 #348

**Comment by sreetummidi** [comment]
Closing , see https://github.com/cloudfoundry/uaa/issues/348
