### ISSUE TITLE
UAA logout.do does not logout of all webapps

### ISSUE THREAD

**Issue by avpavanatge** [cloudfoundry/uaa#352]
We tried using the logout.do API in UAA in order to logout of all the webapps as stated in

"The UAA can act as a Single Sign On server for the Cloud Foundry platform (and possibly user apps as well), so if a user logs out he logs out of all the apps."

However the user is not actually logged out. When I access one of the webapps then user is not logged out.

Thanks

**Comment by mwdb** [comment]
<uaa>/logout.do will trigger a local logout in the UAA but does not inform applications about a logout as UAA does not keep track of sessions in the applications.
As OAuth2 server, UAA issues tokens which usually have a longer validity than the UAA user sessions.

Some approaches for implementing single logout from a technal perspective (I have not yet tested against UAA)
1) Move to the SAML2 protocol as UAA now implements the SAML2 IdP role
2) revoke tokens and use online token validation against the UAA check_token endpoint

**Comment by avpavanatge** [comment]
In regards to 
"2) revoke tokens and use online token validation against the UAA check_token endpoint"

Does not /logout.do or /logout invalidate the UAA token? Does it have to be done by apps?

**Comment by mwdb** [comment]
no, the issued tokens have a longer lifetime than the UAA user session (by intent). This is standard OAuth2 behaviour.

**Comment by nigelelliott75** [comment]
Investigating the single sign out question myself, could we add a new attribute under 'clients' to hold the logout-url of the client application. For each client that has this attribute specified the logout.do will create an iframe with the logout url. It has been mentioned that uaa would need to know which client you are logged into, but if you call the logout url on a client you are not logged into would this not fail silently? This still might have a scale-ability issue, but could be a feature that can be used with said warning.

There maybe a scenario or a technical issue that means that this is not possible, but I think it is worth exploring.

**Comment by sreetummidi** [comment]
Closing this issue as we have started work on the iframe/post message format as part of the OpenID Connect session management spec implementation. Please follow this epic https://www.pivotaltracker.com/epic/show/2869233
