### ISSUE TITLE
Setting autoapprove to true with the /check_token endpoint doesn't work with autoapprove list

### ISSUE THREAD

**Issue by KJoyner** [cloudfoundry/uaa#354]
I am a little confused about autoapprove DB field and the autoapprove list of scopes. When I use autoapprove with true, I am able to get correctly scoped tokens. However, if I then check those with the /check_token endpoint, it doesn't work because of the code in getAutoApprovedScopes.

        Object autoApproved = client.getAdditionalInformation().get(ClientConstants.AUTO_APPROVE);
        Set<String> autoApprovedScopes = new HashSet<>();
        if (autoApproved instanceof Collection<?>) {
            @SuppressWarnings("unchecked")
            Collection<? extends String> approvedScopes = (Collection<? extends String>) autoApproved;
            autoApprovedScopes.addAll(approvedScopes);
        } else if (autoApproved instanceof Boolean && (Boolean) autoApproved || "true".equals(autoApproved)) {
            autoApprovedScopes.addAll(client.getScope());
        }
        if (client instanceof BaseClientDetails && ((BaseClientDetails)client).getAutoApproveScopes()!=null) {
            autoApprovedScopes.addAll(((BaseClientDetails)client).getAutoApproveScopes());
        }

In my case, the getautoApproveScopes near the last line returns true. This then doesn't match any scopes in my list and I end up with an empty list. In the case where the scope list is empty and the autoapprove is true, wouldn't it be better to use client.scopes? Perhaps I am misunderstanding how the autoapprove true is supposed to be used.

**Comment by sreetummidi** [comment]
Fixed as part of https://www.pivotaltracker.com/story/show/120409893
