### ISSUE TITLE
Invalid encoding char %00 causes information leak on postgres queries

### ISSUE THREAD

**Issue by mikeroda** [cloudfoundry/uaa#356]
At least with the /uaa/oauth/authorize endpoint, but probably others, you can include an invalid %00 encoding parameter and the resulting exception from postgres reveals information about the database. For example:

Request:

http://localhost/uaa/oauth/authorize?client_id=%00

Response:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error errorCode="0" httpStatusCode="500"><details><detail>exception: org.springframework.dao.DataIntegrityViolationException</detail><detail>Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding &quot;UTF8&quot;: 0x00</detail><detail>path: /uaa/oauth/authorize</detail></details><message>PreparedStatementCallback; SQL [select client_id, client_secret, resource_ids, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove, lastmodified from oauth_client_details where client_id = ? and identity_zone_id = ?]; ERROR: invalid byte sequence for encoding &quot;UTF8&quot;: 0x00; nested exception is org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding &quot;UTF8&quot;: 0x00</message><version>2</version></error>

Note this example requires an authenticated session (not shown).

**Comment by fhanik** [comment]
I'm unable to reproduce
![image](https://cloud.githubusercontent.com/assets/607429/18521855/9c1f255a-7a62-11e6-84f1-01be7305fcc9.png)

also interesting how you get a XML response, I didn't even know we would return that through a browser.
Please reopen or create a new issue if you can provide a bit more information

**Comment by fhanik** [comment]
Reopening - I need to try with PostgreSQL :)

**Comment by fhanik** [comment]
PostgreSQL returns a 500 error, but no XML
![image](https://cloud.githubusercontent.com/assets/607429/18522065/64dc9c16-7a63-11e6-9383-1c7fcb69780d.png)
