### ISSUE TITLE
Redundant entityId field is required in the payload to add service provider to UAA IdP

### ISSUE THREAD

**Issue by irinaepshteyn** [cloudfoundry/uaa#359]
The entityId field in the payload for POST /saml/service-providers is mandatory and has to match entityID field in service provide metadata.  Otherwise, it causes the following response: 
400 Bad Request: unexpected token at 'Metadata entity id does not match SAML SP entity id: mysp’.

This requirement seems to be redundant.  Users will have to parse service provider metadata to extract entityID value.  It becomes even more difficult if metadata is provided in the form of the URL and not XML.  Since entityID is available in the service provider metadata, it should be read by SamlServiceProviderConfigurator directly from there at the time of creating service provider configuration. It should not be required in the payload as a separate field.

Example:
`
POST http://localhost:8080/uaa/saml/service-providers
REQUEST BODY: "{"entityId":"2c21112d-c76b-4eed-b5d7-76400d3b3dc1.cloudfoundry-saml-login","name":"mysp","config":"{\"metaDataLocation\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><md:EntityDescriptor xmlns:md=\\\"urn:oasis:names:tc:SAML:2.0:metadata\\\" ID=\\\"2c21112d-c76b-4eed-b5d7-76400d3b3dc1.cloudfoundry-saml-login\\\" entityID=\\\"2c21112d-c76b-4eed-b5d7-76400d3b3dc1.cloudfoundry-saml-login\\\">...</md:EntityDescriptor>\\n\",\"nameID\":\"urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified\",\"singleSignOnServiceIndex\":0,\"metadataTrustCheck\":false}","active":true}"
`

**Comment by sreetummidi** [comment]
This story has been picked up and will be available as part of UAA 3.8.0
