### ISSUE TITLE
Adding duplicate service provider to UAA IdP causes 500 Server Error

### ISSUE THREAD

**Issue by irinaepshteyn** [cloudfoundry/uaa#361]
If service provider with the same entityID already exists, POST /saml/service-providers causes 500 Internal Server Error.  
UAA logs: SecurityFilterChainPostProcessor$HttpsEnforcementFilter: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is error="sp_exists", error_description="integrity constraint violation: unique constraint or index violation: ENTITY_IN_ZONE”.  

POST call should then return 409 Conflict instead of 500.  Similar to how it’s done for identity providers or in the original GE implementation of "UAA as saml IdP". 
- https://github.com/GESoftware-CF/uaa/tree/uaa_as_saml_idp_3.0.0
- Pull request: https://github.com/cloudfoundry/uaa/pull/303/files#diff-6f05571741ade271bc64070f20f29992
- https://github.com/GESoftware-CF/uaa/blob/uaa_as_saml_idp_3.0.0/server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfigurator.java line 171-173
 
In the original implementation:
- adding service provider with the same entityID and the same alias would replace existing one with new.
- adding service provider with the same entityID and different alias as the existing one would cause "Duplicate entity id..." MetadataProviderException and result in 409 Conflict response.

**Comment by sreetummidi** [comment]
This story has been picked up and will be available as part of UAA 3.8.0
