### ISSUE TITLE
Can I get OAuth2 token from UAA with SAML user?

### ISSUE THREAD

**Issue by toshiomakiyy** [cloudfoundry/uaa#362]
Hi Team.
I'm trying to integrate SAML authentication(I use OpenAM) on CloudFoundry.
It seems that authentication works good. I can login to uaa with OpenAM's authentication.

By the way, I have an application using UAA OAuth2 Token.
It is used to get data(user/apps/orgs/spaces) from Cloud Foundry.

When I login with UAA user(ex. admin), UAA displays page for authorization, redirect the application when I approved, I can get CloudFoundry data using OAuth2 Token .

But when I login with SAML user, UAA displays root page and I cannot get OAuth2 Token.

How to get OAuth2 token from UAA using SAML user?

**Comment by mwdb** [comment]
UAA keeps the user in the context of an origin. For the internal userstore, the origin is uaa. When configuring an IdP, you specify the origin to be used as part of the the trust configuration.
When the same user identity authenticates once using SAML, once using uaa, these are treated as two different users in the UAA having two different user ids and two different origins.
As the assignment in the cloud controller to e.g. SpaceDeveloper  is based on a user, you need to maintain it again for the SAML user.

**Comment by shinji62** [comment]
"When the same user identity authenticates once using SAML, once using uaa, these are treated as two different users in the UAA having two different user ids and two different origins."
Well I guess the user is not created on fly with the internal store ..
Only with the SAML I guess

**Comment by toshiomakiyy** [comment]
Thank you all.
I can get OAuth2 Token by SAML user by cf-cli.

````
maki@cloudfoundry:~$ cf login --sso                                    
API endpoint: https://api.cf.xxxxxxxxxxx.com                           
                                                                       
One Time Code ( Get one at https://login.cf.xxxxxxxxxxx.com/passcode )>
Authenticating...                                                      
OK                                                                     

maki@cloudfoundry:~$ cf oauth-token                                                                       
bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJmZWJlZTViNC04ZTg2LTQ5ZDktYjcyOC1hNGE0ZDg4OWUyMjQiLCJzdWIiOiI5ODIwNm
UzOC1mMjcxLTQ5YWQtODVlOC0xNzczNDc1NGJiMWYiLCJzY29wZSI6WyJjbG91ZF9jb250cm9sbGVyLnJlYWQiLCJwYXNzd29yZC53cml0
ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJvcGVuaWQiLCJ1YWEudXNlciJdLCJjbGllbnRfaWQiOiJjZiIsImNpZCI6ImNmIiwiYX
pwIjoiY2YiLCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJ1c2VyX2lkIjoiOTgyMDZlMzgtZjI3MS00OWFkLTg1ZTgtMTc3MzQ3NTRiYjFm
Iiwib3JpZ2luIjoic2VpZ2ktb3BlbmFtIiwidXNlcl9uYW1lIjoidG9zaGlvLm1ha2kueXlAaGl0YWNoaS1zb2x1dGlvbnMuY29tIiwiZW
1haWwiOiJ0b3NoaW8ubWFraS55eUBoaXRhY2hpLXNvbHV0aW9ucy5jb20iLCJyZXZfc2lnIjoiODBkYmVlNzYiLCJpYXQiOjE0NjMxMjcx
MDIsImV4cCI6MTQ2MzEyNzcwMiwiaXNzIjoiaHR0cHM6Ly91YWEuY2YuYXp1cmVsb3ZlY2YuY29tL29hdXRoL3Rva2VuIiwiemlkIjoidW
FhIiwiYXVkIjpbImNsb3VkX2NvbnRyb2xsZXIiLCJwYXNzd29yZCIsImNmIiwidWFhIiwib3BlbmlkIl19.SjKdF7wecr5ngsJ8-TFyhtl
jLxw86zP98LA3Gi-iJU6P9Sv8FtD5JBf8h-3XnhfCTJOx7uhR4vVuGPAKMf3gZ-lWXCC2B7fhI5MNtlu1XasvaYwd2NZpPi3zyLcn6eOi8
xuqZv89IMwiAlmettoIA4YX-79qeYGfy0bbMbA6LXk                                                                
````
Currentry I use CFv231, so I will try CFv233 next time.

**Comment by sreetummidi** [comment]
Please try to reproduce the issue and let us know.  I am closing the issue for now

**Comment by kirikak2** [comment]
I solved this problem with @shinji62 's support.

# Cause

I'm using Rails and OmniAuth to get token as follows.

````
module OmniAuth
  module Strategies
    class CloudFoundry < OmniAuth::Strategies::OAuth2
      option :name, :cloud_foundry
      option :client_options, {
        site: "https://uaa.xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        redirect_uri: "https://#{VCAP_APPLICATION.application_uris.first}/users/auth/cloud_foundry/callback"
      }
      option :token_params, { response_type: "token" }
    end
  end
end
````

# Solution
I replaced `site: https://uaa.xxxxxxxxxxx` by `site: https://login.xxxxxxxxxxxx`. and I can get Token by SAML user.

Please teach me what is wrong If anybody can.

**Comment by anitalpatil** [comment]
Hello every one,

Even I am facing the problem while logging in (I am using sso).

I am integrating cf uaa with third party application (using sso), in third party application am unable to get token of uaa. Is there any thing settings needs to be done at uaa? becoz am able to integrate my third party application with git.

can any one help me in solving this issue?
