### ISSUE TITLE
Feature request - support jwt-bearer grant for certificate based authentication

### ISSUE THREAD

**Issue by sanjeevchopra** [cloudfoundry/uaa#364]
This is related to https://github.com/cloudfoundry/uaa/issues/260, however for a different use case. For example: the client could be a industrial device streaming data to a service in the cloud, where it is preferable to use certificates for authentication.  I am filing this issue so it can be tracked separately.

Some key differences:
- There is no user involved
- The JWT in the assertion is used to authenticate only the client (instead of client-secret). The JWT is issued and signed by the client itself. 
- This requires association of a trusted public key with the client on uaa, to be used as the verifying key for the JWT assertion. Or a way to look it up from a distributed trust store.
  - the association of the verifying key must be a privileged operation 

As @sreetummidi pointed out in https://github.com/cloudfoundry/uaa/issues/260, 

> SalesForce has popularized a similar flow, see here https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm

For more details see proposal from @vbanga -  [JWT Bearer Grant Proposal](https://docs.google.com/document/d/1_wZMVk-Ir9WAjin606CGaWehAjj3MX1ytS00bXlK2gs/edit?pref=2&pli=1#heading=h.ys4jqqyfo7fr)

**Comment by sreetummidi** [comment]
Closing this as this is already being tracked as part of UAA roadmap.
