### ISSUE TITLE
Token expiry issue causing problems in CF/broker-registrar/cfoundry gem?

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/uaa#365]
When updating to CF v236, we noticed the following problem in combination with https://github.com/pivotal-cf/broker-registrar and https://github.com/cloudfoundry-attic/cfoundry:
```
[stderr]
E, [2016-05-18T05:19:17.339846 #5378] ERROR -- : can't convert nil into an exact number (TypeError)
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/auth_token.rb:56:in `at'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/auth_token.rb:56:in `expiration'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/auth_token.rb:60:in `expires_soon?'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:137:in `needs_token_refresh?'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:82:in `request'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:66:in `get'
/
```

Can it be that changes introduced to CF v236, specifically bringing https://github.com/cloudfoundry/cf-release/releases#identity -> https://github.com/cloudfoundry/uaa/releases/tag/3.3.0 introduced the issue and therefore https://github.com/cloudfoundry-attic/cfoundry/blob/master/lib/cfoundry/auth_token.rb#L56 (`Time.at(token_data[:exp])`) isn't fitting the bill anymore? Is it a regression on UAA side or a bug on cfoundry gem side?

**Comment by fhanik** [comment]
@vlerenc Are you able to capture the actual token, decode it, and post the claims here?
From the error it says that the `exp` claim is not even present, nil to be exact.

**Comment by sreetummidi** [comment]
@vlerenc Any updates?

**Comment by vlerenc** [comment]
@fhanik Sorry, no. It was failing, but as the CF/broker-registrar/cfoundry gem was only a tiny component, we removed/replaced it to get going again. Feel free to do with the ticket what you see fit.
