### ISSUE TITLE
How to register a "resource server" to UAA

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/uaa#366]
Hi Expert,
I plan to use UAA as Authorization server to protect my “Rest api server”(it is just a standard REST API using spring MVC). My understanding, “DAC rest api server” should work as a “oauth2 resource server” . So, 
1, How can I register  “Rest api server” to PCF UAA as a resource server ?
2, Based on my test,  If I register “rest api server” as “oauth2 client” to UAA with the scope “uaa.resource”. Then the “rest api server” can work as “resource server”. Is this the correct way to register a "resource server"?
Thanks,
David

**Comment by sreetummidi** [comment]
If you are using stand alone UAA, you can add custom roles via the API. Please refer to the API docs here: http://docs.cloudfoundry.com/uaa/#groups
You can also use the UAAC tool (ruby gem) to add resources. https://github.com/cloudfoundry/cf-uaac
The command is uaac group add
