### ISSUE TITLE
Token Client Credentials Grant requires id/secret in Authorization Header

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/uaa#370]
The documentation for [Token/Client Credentials Grant][1] doesn't say that the clientId and clientSecret must be in the authorization header, but if they aren't, specifying them as query/request parameters doesn't work (I get a 401).

The example given uses request parameters, and doesn't show an Authorization header, but I cannot get this form of request to work.

[1]:http://docs.cloudfoundry.com/uaa/#client-credentials-grant

**Comment by fhanik** [comment]
curl -k --data  "client_id=admin&client_secret=xxxx&grant_type=client_credentials&response_type=token" https://login.identity.cf-app.com/oauth/token

works great.

**Comment by Zteve** [comment]
OK. I have discovered that in our own code, we have bearer authorization in the header by default, and this apparently ruins the request; so this was raised in error.  Thank you for your support.
