### ISSUE TITLE
"User does not exist" intermittent UAA failure

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry/uaa#371]
## Issue
Adding a user to a group may fail with error "User does not exist" if a separate user is deleted around the same time.

## Context
This error happens when automated user management happens concurrently. Includes user creation, permissioning, user deletion.

Versions:

* CF v235
* uaa-release 68cf1f1684
* uaa 616e8bcc58
* cf-uaac gem 3.2.0

## Steps to Reproduce
We reproduced it by running continuously [2 instances of a script](https://gist.github.com/saliceti/38109ff695347eaec30110317b4e881a) that:
* creates a user
* adds the user to several groups
* deletes the user

The 2 scripts manage different users.

## Expected result
The first user should be added to the group and the other user should be deleted.

## Current result
This can be observed by enabling trace on `uaac`.

The first process gets the group's details, including the member list:

```
request: get https://uaa.colin-bosh.dev.cloudpipeline.digital/Groups?filter=displayName+eq+%22doppler.firehose%22&startIndex=1
response: "members": ...[{"origin":"uaa","type":"USER","value":"29d7988e-8919-4b7d-a3f1-514add974225"},{"origin":"uaa","type":"USER","value":"2b624ed9-adff-408e-a082-5acd283d6c6f"},{"origin":"uaa","type":"USER","value":"655925c7-13bf-47dd-b10a-dcd68871dbb6"},{"origin":"uaa","type":"USER","value":"c47686a5-7228-48cb-b857-d69992a766e2"},{"origin":"uaa","type":"USER","value":"dafd3422-fc35-4e82-9a63-e6ab54f0b557"}]...
```

Soon after the other process removes its own user `655925c7-*`. We can assume this removes the group membership:

```
request: delete https://uaa.colin-bosh.dev.cloudpipeline.digital/Users/655925c7-13bf-47dd-b10a-dcd68871dbb6
```

Then to add the new user to the group, the first process PUTs the retrieved list, with the addition of the new user `a9d91b2b-*`. But it also includes the delete user `655925c7-*`:

```
request: put https://uaa.colin-bosh.dev.cloudpipeline.digital/Groups/768b5cb9-f5b5-4f5b-bf8b-60d50753b605
body: ..."members":["29d7988e-8919-4b7d-a3f1-514add974225","2b624ed9-adff-408e-a082-5acd283d6c6f","655925c7-13bf-47dd-b10a-dcd68871dbb6","c47686a5-7228-48cb-b857-d69992a766e2","dafd3422-fc35-4e82-9a63-e6ab54f0b557","a9d91b2b-1158-47e7-84ec-4fd93df90389"]...
response: 400
"error_description": "User 655925c7-13bf-47dd-b10a-dcd68871dbb6 does not exist"
```

The list includes a now unknown user and the request fails.

## Possible Fix
Don't rely on uaac to give a list of users as input. Adding a user to a group should be an atomic operation or a transaction.

**Comment by sreetummidi** [comment]
@saliceti I would recommend that you use the API directly to get the latest state instead of relying on UAAC result

**Comment by saliceti** [comment]
@sreetummidi: You mean `uaac` will remain broken?
