### ISSUE TITLE
Clients in same Identity Zone with different Identity Providers

### ISSUE THREAD

**Issue by hyadalam** [cloudfoundry/uaa#381]
Can you please let me know if it is possible to have 2 clients in the same identity zone but have one client use an external SAML IDP for authentication while have the other client to go to a LDAP authentication source.

How do we show the standard UAA login screen for the LDAP authentication source, but show the IDP's login screen for the SAML authentication source.

**Comment by sreetummidi** [comment]
@hyadalam , you can use the allowed identity providers feature for this.
This needs to be set on the client. For LDAP the alias is ldap.
The filed is "allowedproviders":["acme"]
