### ISSUE TITLE
How to  Integration User Account and Authentication LDAP?

### ISSUE THREAD

**Issue by alandchen** [cloudfoundry/uaa#382]
When I config the uaa.yml on uaa server,  then restart the uaa server , all config has resotre, why?

  Anther issue,  can’t   click  the apply change  on OPS Manager dashboard.

**Comment by fhanik** [comment]
It seems you are running a PCF manager. For that, please go through the official support channel.
A standalone UAA would not overwrite its configuration file. 
In a Cloud Foundry environmnent, the configuration files will always be overwritten by the manifest.
