### ISSUE TITLE
Manual update of oauth_client_details/additional_information required to make autoapprove scenarios work

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/uaa#386]
We are creating UAA clients using UAAC including `--autoapprove true`.

During login the oauth token is passed and `/check_token` from the UAA API is called. Just using the client as created above leads to an error like `{"error":"invalid_token","error_description":"<redacted>...."}`.

We figured out we can make the oauth flow work by manually updating the UAA `oauth_client_details` table for the above UAA client by adding autoapprove to the `additional_information` field:

`update oauth_client_details set additional_information='{"autoapprove":true}' where client_id='<our_client_id>';`

Of course, we'd like to solely create our UAA clients using UAAC, avoiding this manual, additional step. Is this something that needs a fix on the UAA and/or UAAC side?

Potentially related to #354?

**Comment by sreetummidi** [comment]
Fixed as part of https://www.pivotaltracker.com/story/show/120409893
