### ISSUE TITLE
UAA not resilient to Postgres connection failures

### ISSUE THREAD

**Issue by HenryTK** [cloudfoundry/uaa#388]
When running CloudFoundry acceptance tests and smoke tests there is an intermittent error:

```
[2016-06-07 11:38:28.36 (UTC)]> cf auth admin [REDACTED] 
API endpoint: [REDACTED]
Authenticating...
FAILED
The targeted API endpoint could not be reached.
```

A search of the logs shows the response code generated by the UAA job:

```
[07/Jun/2016:11:38:30 +0000] "POST /oauth/token HTTP/1.1" 500 137
```

Logs around occurences of this issue indicate Postgres connection errors, due to failed DNS lookup:

```
[2016-06-10 04:43:09.768] uaa - 6500 [http-bio-8080-exec-51] .... DEBUG --- SecurityContextPersistenceFilter: SecurityContextHolder now cleared, as request processing completed
[2016-06-10 04:43:09.768] uaa - 6500 [http-bio-8080-exec-51] .... ERROR --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Uncaught Exception:
org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.postgresql.util.PSQLException: The connection attempt failed.
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:615)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:680)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712)

[...]

Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:152)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125

[...]

Caused by: java.net.UnknownHostException: [REDACTED].[REDACTED].eu-west-1.rds.amazonaws.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
```

The [`minIdle` connections in the default configuration](https://github.com/cloudfoundry/uaa/blob/23e4e93466820617370002ee806624425df68dae/server/src/main/resources/spring/data-source.xml#L21) is set to zero, which seems to imply no pooled connections and so a fresh connection is established every time. This seems to have been [intentionally added here](https://github.com/cloudfoundry/uaa/commit/3ff146ec36424b4fee53f93a182ac01aed764651) - we're not sure of the reasoning behind this. This could possibly be making UAA less resilient to connection failures, whether they be from the above mentioned DNS problem or any other underlying cause.

We think this means UAA is not retrying after failed connection attempts, which should be handled by the connection pool, because there are no connections in the pool when a new db connection is required.

**Comment by fhanik** [comment]
The key problem here are the DNS failures. Regardless of what minIdle is set to, you will see errors if your DNS is unreliable, and you rely on DNS for DB connections.

I'm not sure I understand "not retrying after failed attempts".

You can use a network sniffer, like wireshark or tcpdump, and you can get a full understanding of what the UAA is doing. 

We can assist further on the mailing list, but I don't see a bug or issue here. Closing for now, reopen if you find more evidence.

**Comment by mtekel** [comment]
Hi @fhanik ,

DNS protocol is UDP based (by default). UDP is not a lossless protocol. It is to be expected that DNS resolution can sometimes fail. It is then up to resolving application to implement some logic to handle this case.

In case of UAA, this is handled by the connection pool, but which you set explicitly to 0, telling it no not handle it. What we ask here is:

* what is the reasoning behind such setting? UAA depends on its datastore and should care that it can reach it in an optimal way...
* could this setting be changed to st. else, like 2, 4 or 10 connections?
* could this setting be at least made user configurable via BOSH release? (just like you [let us configure max_idle connections](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L495))

Thanks in advance for your response.

**Comment by fhanik** [comment]
Absolutely

https://www.pivotaltracker.com/story/show/121674835

**Comment by fhanik** [comment]
@mtekel addressing some of the other issues. 
minIdle=0 is to simple ensure that we don't keep connections open for no reason. A connection can keep a server side process alive, and taking up resources. Furthermore, if there is a firewall that drops connections, then neither the client nor the server receive a notification. 

When it comes to DNS failures. Yes, UDP has errors, but the DNS look up component can simply resubmit the request. The fault tolerance aspect of DNS look up would happen at the lower level, and is not something we attempt to guard against at the connection pool level.

**Comment by Jonty** [comment]
@fhanik While some firewalls do that, most people running CF are in control of their infrastructure and know what they can & cannot do. Keeping database connections open is a common strategy to avoid the latency involved in establishing a new connection, often involving a TLS handshake.

We have also observed the database connection failing due to transient network problems (not DNS) on AWS, and retries are the only option for solving that.

Ideally I would like to see UAA actually introduce retries on connection failures, but I would also like to see `minIdle` made configurable in the same manner as `maxActive` and `maxIdle`.
