### ISSUE TITLE
External Identity Providers issuer validation issue

### ISSUE THREAD

**Issue by nigelelliott75** [cloudfoundry/uaa#392]
I have been testing out UAA and have been trying to configure it to use Google OpenId as an External Provider. I managed to get so far and get an issue when UAA is verifying the issuer is correct coming back from Google. The issue is that the UAA code is using the tokenUrl set in uaa.yml as the expected issuer and Google is sending back a different value. 

I made a change to the UAA code to add a new configuration item called "issuer" within login.oauth.providers.<providerName> which can be set to the expected value and will be used if available, otherwise fallback to tokenUrl. Once I did this change UAA was able to work sign me in using a Google account.

I currently have the change locally and still need to do unit tests for the change, however before I submit the change wanted to check if this hasn't already been corrected or if this is the correct way of solving the issue.

I have attached a snippet of the uaa.yml file showing the configuration section the new attribute "issuer" will appear.

[uaa-extIdp-yml.txt](https://github.com/cloudfoundry/uaa/files/316210/uaa-extIdp-yml.txt)

**Comment by sreetummidi** [comment]
@nigelelliott75 Happy to accept a pull request for this issue

**Comment by sreetummidi** [comment]
Fixed by https://www.pivotaltracker.com/story/show/121653769
