### ISSUE TITLE
/userinfo does not provide phone number

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#394]
The `/userinfo` endpoint does not return the user's phone number at the moment: 
https://github.com/cloudfoundry/uaa/blob/3.4.0/server/src/main/java/org/cloudfoundry/identity/uaa/account/UserInfoEndpoint.java#L70

Can this be added?

**Comment by sreetummidi** [comment]
This issue has been addressed starting with UAA 3.5.0
