### ISSUE TITLE
Authorization Code Grant Browser flow response is not documented correctly

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/uaa#395]
[Authorization Code Grant (Browser Flow)](http://docs.cloudfoundry.com/uaa/#browser-flow) documents a response which is not immediate, but the result of further interactions (not described).

If issuing a request with the example form (without an Auth header) the correct response `302 Found` is returned and a `Location` header appears in the response, but this doesn't have a "code" query parameter on it:

```
HTTP/1.1 302 Found..
Cache-Control: no-cache, no-store, max-age=0, must-revalidate..
Content-Length: 0..
Date: Fri, 17 Jun 2016 12:26:05 GMT..
Expires: 0..
Location: https://uaa.local.pcfdev.io/login..
Pragma: no-cache..
Server: Apache-Coyote/1.1..
Set-Cookie: __VCAP_ID__=647a7f59-5b32-4a0d-6266-f460c798ec06; Path=/; HttpOnly; Secure..
Set-Cookie: JSESSIONID=065E4F67B2F3BF7587426FE92A49C3DD; Path=/; Secure; HttpOnly..
Strict-Transport-Security: max-age=31536000 ; includeSubDomains..
X-Content-Type-Options: nosniff..
X-Frame-Options: DENY..
X-Vcap-Request-Id: fb820273-21af-4cd3-7661-eb4e5f7a2187..
X-Xss-Protection: 1; mode=block..
..
```

This does not correspond to the example flow given in the documentation, which (apparently) records the response after further interactions with an authentication protocol (normally handled by a "browser", if there is one).

Please update the doc to specify the correct immediate response.

**Comment by fhanik** [comment]
The presence of the `Authorization` header creates a non browser flow.
Here is the documentation link:
http://docs.cloudfoundry.org/api/uaa/index.html#browser-flow

**Comment by Zteve** [comment]
If I omit the header I don't get a code back (as per the example flow in the docs); I posted what I get back above. The doc you linked me to is what I've been trying to get to work. What am I missing?

**Comment by Zteve** [comment]
By the way, the doc is unclear what it is exactly that characterizes each request.  If it is the absence of an Authorization header, it would be helpful if the doc made that clear.  The Token requests are particularly confusing in this regard.

**Comment by Zteve** [comment]
I can't get this request to work as documented.

I issue the request:
```
GET /oauth/authorize?client_id=ssh-proxy&redirect_uri=http://redirect.to/app&response_type=code HTTP/1.1..
host: uaa.local.pcfdev.io..
Accept: application/x-www-form-urlencoded..
```

and I receive the response:
```
HTTP/1.1 302 Found..
Cache-Control: no-cache, no-store, max-age=0, must-revalidate..
Content-Length: 0..
Date: Mon, 20 Jun 2016 12:07:36 GMT..
Expires: 0..
Location: https://uaa.local.pcfdev.io/login..
Pragma: no-cache..
Server: Apache-Coyote/1.1..
Set-Cookie: __VCAP_ID__=9c7d0536-3054-4faf-6809-31d6cf235b47; Path=/; HttpOnly; Secure..
Set-Cookie: JSESSIONID=1D6C44B10328696435AE7C7F947594CD; Path=/; Secure; HttpOnly..
Strict-Transport-Security: max-age=31536000 ; includeSubDomains..
X-Content-Type-Options: nosniff..
X-Frame-Options: DENY..
X-Vcap-Request-Id: d620ccc6-0802-4d72-7a31-98e575918bce..
X-Xss-Protection: 1; mode=block..
```

in which the `Location` header doesn't include a `code=<value>` query parameter. Also it seems to ignore the `redirect_uri` on the request.

**Comment by fhanik** [comment]
It works as documented. 
The user (browser) is being redirected to the `login` page for authentication. When authentication is complete, you will get a 302 redirect, with a Location header that contains the code.

**Comment by Zteve** [comment]
Having gone to ask a friend I now understand the intended flow, but the documentation is incorrect.  The example response shows a 302 redirect with an authorization `code` (and the supplied redirect uri) in the location header.  This is not what is returned from the `GET` request.

Completing the authentication requires further interactions which are not the subject of this REST request.

I have updated the initial description of the problem.
