### ISSUE TITLE
Create/Update User request does not take Group Information.

### ISSUE THREAD

**Issue by ssrini9** [cloudfoundry/uaa#402]
Create a User: POST /Users
( https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#create-a-user-post-users )
Update a User: PUT /Users/{id}
( https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#update-a-user-put-users-id )

I noticed that the Request Body of above two Requests does not take Group information of User.
Even if it is passed in the Request Body, it is ignored while processing the request and in the return Response Body the Group information is blank. Any reason for the same ?

I would like to Create User and add Groups ( or Update User and add Groups) in a single Request call. Please suggest.

**Comment by sreetummidi** [comment]
@ssrini9 We don't plan on supporting this. User API's following the SCIM standard.
Please refer to the API docs for creating groups

http://docs.cloudfoundry.org/api/uaa/#create60
