### ISSUE TITLE
Doc: List Members confusing language

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#403]
http://docs.cloudfoundry.com/uaa/#list-members contains the following explanation of `value`:

"The globally unique identifier the user or group which is a member of the specified by groupId"

I _think_ it should read something like: "The globally unique identifier _of_ the user or group _that_ is a member of the _group_ specified by groupId"

**Comment by jhamon** [comment]
The docs have been clarified since this ticket was opened 2 years ago.
