### ISSUE TITLE
Doc: Create Groups required fields

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#406]
The Create Groups documentation (http://docs.cloudfoundry.com/uaa/#create60) spells out the requirements for each of the `members` fields individually, but doesn't specify whether the `members` object as a whole is required or optional.

**Comment by Zteve** [comment]
Strange -- at appears to document this now:

```
members			Array	Optional			Members to be included in the group
members[].value	String	Required ...
```
So can we close this?

**Comment by twoseat** [comment]
Thanks for the update!
