### ISSUE TITLE
Expired self-signed certificates

### ISSUE THREAD

**Issue by krolim** [cloudfoundry/uaa#407]
Hi,

In our project we had setup an LDAP server and we are using self-signed certificates for the UAA requests to it. Recently we discovered that our certificate has expired. However this has no impact on execution as we did not encounter any problems with the UAA-LDAP connection. Looking at the configuration properties I couldn't find any related to SSL certificates verification. So my question is if UAA checks the validity of the self-signed certificates at all?

Best regards,
Hristo

**Comment by sreetummidi** [comment]
@krolim 
Have you by any chance set the skipsslverification to true for LDAP?

uaa.ldap.ssl.skipverification:
    description: "Set to true, and LDAPS connection will not validate the server certificate."
    default: false

**Comment by krolim** [comment]
Hi,

I've checked and we don't set this property so it should have the default value assigned. Here is an excerpt from our manifest:

`extensions:

      uaa:
        ldap_security_group: <security group>
        ldap:
          enabled: true
          profile_type: simple-bind
          url: "ldaps://" <url>
          sslCertificateAlias: ldap
          sslCertificate: <certificate>
          userDNPattern: '<pattern>`

We are currently using CF version 238.

Best regards,
Hristo

**Comment by sreetummidi** [comment]
We were able to reproduce this on our side. We will be patching this asap.

**Comment by sreetummidi** [comment]
Fixed in UAA 3.4.2 and above
