### ISSUE TITLE
Documented field types are sometimes incorrect

### ISSUE THREAD

**Issue by wilkinsona** [cloudfoundry/uaa#408]
For example http://docs.cloudfoundry.com/uaa/#update51 documents `emails[].value` as an `Array` when it is, in fact, a `String`. This appears to be due to the [type being explicitly configured in ScimUserEndpointDocs](https://github.com/cloudfoundry/uaa/blob/3.4.1/uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointDocs.java#L111).

If a field is present in the request or response payload, REST Docs will automatically determine its type meaning that the documented type is guaranteed to be in sync with the actual form of the request or response. The only time I'd expect to see a type being explicitly documented is when the field is optional and it isn't in the request or response.

I've opened https://github.com/spring-projects/spring-restdocs/issues/276 so that REST Docs will cause the test to fail if a type has been explicitly documented and it doesn't match the type that can be determined by examining the payload.

**Comment by sreetummidi** [comment]
@wilkinsona 
We have fixed the issuse as part of : https://www.pivotaltracker.com/story/show/123639781
I am closing this one. Also, please note that the doc location has moved to http://docs.cloudfoundry.com/uaa/
