### ISSUE TITLE
OpenID workflow # sign causing issues with flask app, GET cannot obtain parameters

### ISSUE THREAD

**Issue by rudyzhou2** [cloudfoundry/uaa#409]
Hi UAA dev,

I ran into an issue with the OpenID connect with authorization code grant workflow with a Flask application. The url from this workflow appends the number sign (#) directly behind the redirect url after successfull authorization request causing the flask application unable to obtain the code/id_token/state args etc.

example callback url:
`https://localhost/callback#token_type=bearer&id_token=xxx&code=xxx&state=xxx`

I was wondering whether is there any way to disable the use of number sign so I can successfully use GET to obtain the parameters from UAA openid response?

**Comment by sreetummidi** [comment]
@rudyzhou2 This is the standard behavior when using the response type of code id_token on the /authorize end point is that it returns the id_token token along with code.

You should instead do the following

1. Call the /authorize only with response_type of code
2. Call the /token endpoint with response_type of id_token token
