### ISSUE TITLE
Going to UAA login page when already authenticated in UAA returns the 'UAA' home page regardless if the identity zone homeRedirect is configured

### ISSUE THREAD

**Issue by dvuke** [cloudfoundry/uaa#410]
In our scenario, we have a tenant/subdomain defined who is using the UAA identity provider.  Their identity zone is configured with a homeRedirect link pointing to a particular URL.

I authenticated with a user, it redirects me to my application and everything is working fine.  However, if a user were to type in the URL of the login page for UAA in the browser while they're already authenticated, it renders the 'home' view regardless if the homeRedirect property is configured for the identity_zone.

I was wondering if there's a particular reason the LoginInfoEndpoint returns "home" view at the end of the login private method (line 340) instead of redirecting to '/home' which would force it to process the homeRedirect.

**Comment by sreetummidi** [comment]
This issue has been fixed starting with UAA 3.7.0
