### ISSUE TITLE
OIDC code for getting token ignores proxy settings

### ISSUE THREAD

**Issue by DarioAmiri** [cloudfoundry/uaa#411]
During the OIDC flow there is a step where UAA will post an authorization code to an external IdP in order to obtain the user token. Unfortunately, this does not work from behind a proxy because the underlying HttpClient is constructed in such a way that it ignores any proxy settings passed to the JVM. This issue manifests itself in the following integration tests:
- OIDCLoginIT.successfulLoginWithOIDCProvider
- OIDCLoginIT successfulLoginWithOIDCProvider_withClientContext

See

https://github.com/cloudfoundry/uaa/blob/094f75188cc0606c5194cc64cf722c54ec8bfd2b/server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaHttpRequestUtils.java#L31-L34

**Comment by fhanik** [comment]
I agree, we should start reducing the number of classes used to make external HTTP calls and instead consolidate them. The referenced class should probably be consolidated with all other classes that do the same thing. For example, when we fetch meta data for SAML

**Comment by amiri-ge** [comment]
@fhanik Cool, I'll try to submit a pull request for this early next week unless you guys want to address it.

**Comment by amiri-ge** [comment]
@fhanik Unfortunately, the SAML FixedHttpMetaDataProvider and the OIDC UaaHttpRequestUtils use different HttpClient APIs. The SAML stuff uses HttpClient whereas the OIDC stuff uses CloseableHttpClient which are incompatible. Thus, reconciling these to use the same HttpClient would require far more extensive code changes. I will submit a more targeted fix for now.
