### ISSUE TITLE
Required field not supplied on responses

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#414]
http://docs.cloudfoundry.com/uaa/#creating-an-identity-zone says that `config.tokenPolicy.activeKeyId` is "Required if `config.tokenPolicy.keys` are set"

Making requests against CF results in the following output sample, which sets the latter without providing the former.

```
  "tokenPolicy": {
    "accessTokenValidity": 43200, 
    "keys": {
      "<removed long number>": {
        "id": null, 
        "signingKey": "-----BEGIN RSA PRIVATE KEY-----<removed key>-----END RSA PRIVATE KEY-----\n", 
        "signingKeyPassword": null
      }
    }, 
    "refreshTokenValidity": 2592000
  }
```

**Comment by sreetummidi** [comment]
@twoseat this validation is in place starting with UAA Bosh Release v37
