### ISSUE TITLE
OpenID Connect Discovery Support

### ISSUE THREAD

**Issue by whitlockjc** [cloudfoundry/uaa#415]
Are there any plans to implement OpenID Connect _(OIDC)_ Discovery support?  I would like to use UAA for Kubernetes authentication via OIDC.  Kubernetes uses [go-oidc](https://github.com/coreos/go-oidc) for its OIDC integration and it uses the [OpenID Connect Discovery](http://openid.net/specs/openid-connect-discovery-1_0.html) support to gather the OIDC configuration details.  Now I realize that go-oidc could/should be updated to allow for working without OpenID Connect Discovery, I think UAA could benefit as well from providing this support.  Thoughts?

**Comment by whitlockjc** [comment]
**Note:** I have not verified whether go-oidc works without OpenID Connect Discovery yet or whether Kubernetes itself should be updated to allow for working without OpenID Connect Discovery.

**Comment by whitlockjc** [comment]
It looks like go-oidc provides us with what we need to be able to connect to an OIDC Provider without said provider implementing Discovery.  So Kubernetes itself could be written to work without Discovery.  That being said, I still wonder if this is something UAA would consider implementing.

**Comment by sreetummidi** [comment]
This is being addressed as part of https://www.pivotaltracker.com/story/show/130476603 for UAA 3.8.0
