### ISSUE TITLE
User password error message is inconsistent when LDAP backend is enabled

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/uaa#416]
When a user tries to change its password while the UAA account is backed by an LDAP account (configured with [profile_type: search-and-bind](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md#ldap-search-and-bind)), then I observe the UAA responding with a `Old password is incorrect` error message, even through the old password was properly entered.

precisely the http://docs.cloudfoundry.org/api/uaa/#change-user-password endpoint responds with 401 status and `{"error":"unauthorized","error_description":"Old password is incorrect"}` output

As a result, the CF CLI currently displays this apparently misleading error message for a `cf passwd` command

Suggesting instead to display a message such as `User backed by an LDAP account may not change password from UAA`

**Comment by bsekar** [comment]
I confirmed this behavior for all external IDP users

**Comment by sreetummidi** [comment]
We won't be able to get to this anytime soon. PRs welcome
