### ISSUE TITLE
Token Signing Keys are improperly encoded

### ISSUE THREAD

**Issue by whitlockjc** [cloudfoundry/uaa#424]
Per [RFC 7517](https://tools.ietf.org/html/rfc7517), the modulus _(`n`)_, and the exponent _(`e`)_ should both be base64url encoded, not just base64 encoded.  [Appendix A.1](https://tools.ietf.org/html/rfc7517#appendix-A.1) gives an example of this.  Based on my testing, `e` isn't really a problem because its value is a constant and that constant doesn't have values that would encode differently based on base64 vs. base64url.  But for `n`, you often see keys that fail to base64url decode.  I have created a simple Go application that demonstrates this using a modulus value from your documentation: https://play.golang.org/p/rwb8uQSDPP

**Comment by plfx** [comment]
@whitlockjc Thank you for reporting this. A fix is forthcoming in the next version of the UAA, version 3.7.

**Comment by whitlockjc** [comment]
If you agree with the change, I'll gladly submit a PR.  The reason I filed a bug instead of submitting a PR was because I wasn't sure if you'd agree to the change until you tackled OIDC officially.
