### ISSUE TITLE
Adding custom attributes to IDP mapping for SAML flow missing in new documentation

### ISSUE THREAD

**Issue by Bitty9** [cloudfoundry/uaa#429]
There is brief mention in the github documentation (https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#identity-provider-api-documentation) about how to configure custom attributes for an IDP configuration for the SAML flow. However, this is not mentioned at all in the cloud foundry documentation.  https://docs.cloudfoundry.org/api/uaa/#identity-providers. Is the functionality still supported in the latest version of UAA? If so, the documentation could be more clear/obvious about how to add custom attributes to the IDP. An example of creating an IDP with custom attributes in config.attributeMappings field would help.

**Comment by strehle** [comment]
Hi,
colleagues here have some scripts:
https://github.com/PredixDev/uaa-scripts/tree/master/mgmt
This demonstrates the mapping, however I agree with you the standard documentation should contain such examples
regards

**Comment by sreetummidi** [comment]
This is documented here
http://docs.cloudfoundry.org/api/uaa/index.html#saml
