### ISSUE TITLE
Performance problem when accessing group_membership

### ISSUE THREAD

**Issue by mwdb** [cloudfoundry/uaa#436]
We have a system where SAML logon to an identityzone takes two minutes. During logon, the shadow user is updated and the groups and group memebership assigments get updated.
As part of that, the SQL like below is executed.

DELETE FROM group_membership WHERE group_id IN (SELECT id FROM groups WHERE identity_zone_id='demo') AND  (LOWER(member_id) = LOWER('3e716acf-6d3c-444f-8a6f-fff49c8be99d') AND LOWER(origin) = LOWER('useridp'));

As no index like below exists, this runs for 2 minutes.

CREATE INDEX group_membership_member_id_tmp ON group_membership(LOWER(member_id));

Database is postgresql. No database index on group_membership(LOWER(member_id)) has been delivered as part of the uaa.

**Comment by strehle** [comment]
hi @fhanik ,
we could verify with that it speeds up after we created the indexes manually for postgres.
There was a similar issue for users table, see https://github.com/cloudfoundry/uaa/issues/178 where the index for postgres was created with LOWER(.) .
The group member indexes should be re-created with such a LOWER statement (for postgres only) . This solves it .

thanks
markus

**Comment by strehle** [comment]
#178

**Comment by fhanik** [comment]
Thank you, will review today!

**Comment by strehle** [comment]
fixed with UAA 3.9.0, already in develop branch

**Comment by strehle** [comment]
https://github.com/cloudfoundry/uaa/commit/a9d24197c68fe4fe1e6cf0565fde6ebabe577210
