### ISSUE TITLE
Group membership api's possible optimization

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#437]
Current api's for mapping users to groups: http://docs.cloudfoundry.org/api/uaa/#add-member require to download all users mapped to this particular group and then perform single POST request to add member. It is quite problematic flow if list of users assigned to group is pretty large. I was wondering if new api can be introduced just add specific user list to group like PATCH so there is no need to download the whole list. Looks like membership column also not indexed in PSQL at least based on following issue: https://github.com/cloudfoundry/uaa/issues/436

**Comment by sivabalans** [comment]
![image](https://cloud.githubusercontent.com/assets/10453642/19291630/3b3ecec4-8fcb-11e6-8dbb-aff3a48f69cc.png)
![image](https://cloud.githubusercontent.com/assets/10453642/19291634/43a580d0-8fcb-11e6-8ed1-ab4d077891f8.png)
![image](https://cloud.githubusercontent.com/assets/10453642/19291641/4ece2fd4-8fcb-11e6-85c4-0a9315e3a7ec.png)

Attaching screenshots of queries when doing a GET on /Groups. This is a follow-up to the discussion with @sreetummidi .

**Comment by fhanik** [comment]
A patch method for group has been implemented to in the following commit
c2c6c76fdfca7a881343c1e591dcdc2f5f93329e

**Comment by ilipkind** [comment]
thanks @fhanik
