### ISSUE TITLE
unable to find uaac login credentials

### ISSUE THREAD

**Issue by ShradhaSangtani** [cloudfoundry/uaa#438]
i am running uaa server on localhost. I have run following command. 
uaac target http://localhost:8080/uaa
Next, i need to get token using command below.
uaac token get username password.
From where will i get the above username and password?  I read that the credentials are in cloud foundry deployment manifest file. But i don't know where the file is located in the system.

**Comment by sreetummidi** [comment]
@ShradhaSangtani  When you deploy UAA locally, only one user is created out of the box. Its marissa with password as koala

You can create more users through the UI by clicking on Create Account on the login page or by using the API for creating a new user.
http://docs.cloudfoundry.org/api/uaa/#create50

Users can also be created via UAAC.  For this you need be logged in with the Admin Client

Perform uaac token client get admin
The Password is admin-secret and then perform create user command in UAAC
