### ISSUE TITLE
uaa - azure ad integration

### ISSUE THREAD

**Issue by pdarvasi** [cloudfoundry/uaa#440]
As written [here](https://github.com/cloudfoundry/uaa/issues/213), UAA can be integrated to Azure AD as a provider.
However trying so gave me the error:
`[2016-09-12 13:36:51.284] cloudfoundry-identity-server - ???? [http-nio-8080-exec-7] ....  WARN --- LoginSamlDiscovery: org.cloudfoundry.identity.uaa.provider.saml.LoginSamlDiscovery$UnableToFindSamlIDPException: Unable to locate IDP provider for alias:azure-ad`

I have been experimenting with the yaml, but found no example or how-to.
I have attached to UAA.yml and the relevant log file.

Thank you for the help!

[uaa_log.txt](https://github.com/cloudfoundry/uaa/files/467853/uaa_log.txt)
[uaa_yml.txt](https://github.com/cloudfoundry/uaa/files/467854/uaa_yml.txt)

**Comment by sreetummidi** [comment]
Can you please try with metadataTrustCheck: false and let me know the results.
