### ISSUE TITLE
Unable to access /userinfo endpoint when access token does not contain PII

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/uaa#442]
In this scenario, I dont want the access token to contain any PII (personally identifiable information). If required, I want the resource server to get PII using  /userinfo endpoint.
As suggested by @fhanik (see [discussion](http://cf-dev.70369.x6.nabble.com/cf-dev-Intended-UAA-specific-user-identity-fields-in-JWT-access-token-tt4408.html#a4730)), this has been done using UAA configuration option 
```jwt:
  token:
    claims:
      exclude:
      - user_name
      - email
```

But, when passing the access token without PII to the /userinfo endpoint, I get a 500 Internal Server Error.
Stacktrace indicates a null pointer exception while getting principal
```
: Caused by: java.lang.NullPointerException
2016-09-14T15:51:34.16+0200 [APP/0]      OUT [2016-09-14 13:51:34.159] cloudfoundry-identity-server - ???? [http-nio-8080-exec-4] .... ERROR --- HomeController:        at org.cloudfoundry.identity.uaa.account.UserInfoEndpoint.extractUaaPrincipal(UserInfoEndpoint.java:55)
2016-09-14T15:51:34.16+0200 [APP/0]      OUT [2016-09-14 13:51:34.159] cloudfoundry-identity-server - ???? [http-nio-8080-exec-4] .... ERROR --- HomeController:        at org.cloudfoundry.identity.uaa.account.UserInfoEndpoint.loginInfo(UserInfoEndpoint.java:50)
```

Looking at [UaaTokenServices](
https://github.com/cloudfoundry/uaa/blob/5cbf9c1b65598892e6f72966a1288e11f72e793a/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java#L1020-L1035)
```java
[...]
        Authentication userAuthentication = null;
        // Is this a user token?
        if (claims.containsKey(EMAIL)) {
            UaaUser user = userDatabase.retrieveUserById((String)claims.get(USER_ID));
            UaaPrincipal principal = new UaaPrincipal(user);
            userAuthentication = new UaaAuthentication(principal, UaaAuthority.USER_AUTHORITIES, null);
        } else {
            authorizationRequest.setAuthorities(authorities);
        }

        OAuth2Authentication authentication = new UaaOauth2Authentication(accessToken,
                                                                          IdentityZoneHolder.get().getId(),
                                                                          authorizationRequest.createOAuth2Request(),
                                                                          userAuthentication);
        authentication.setAuthenticated(true);
        return authentication;
    }
[...]
```

it seems that if email (ie PII) is not in the access token, then no userAuthentication/principal is set, which whould explain the exception.

Is there a reason why userAuthentication is only set if email (ie PII) is in the token ?

Thanks

**Comment by s-bortolussi** [comment]
Hello @fhanik . Do you have any advice about how to deal with this issue ?

**Comment by fhanik** [comment]
@s-bortolussi it's a bug. email is a required claim, I'm fixing it right now.

**Comment by fhanik** [comment]
Finished via e59544a60a2df62874e07a086bda1cd63d2d789e

**Comment by s-bortolussi** [comment]
Thanks @fhanik for the fix.
However, I am wondering if it would not make more sense to use a more standard claim such as ["sub"](http://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes) to represent user id instead of the non standard "user_id" claim.

**Comment by fhanik** [comment]
@s-bortolussi `sub` is the subject. in case of client credentials, this should be the `client_id`. 
we use the presence of `user_id` to  tell us if it is a user token or not.

**Comment by s-bortolussi** [comment]
Thanks @fhanik for your response
