### ISSUE TITLE
"sub" claim missing in Userinfo Response

### ISSUE THREAD

**Issue by nicolasrueegg** [cloudfoundry/uaa#446]
The Open ID Connect specification declares the _sub_ claim to be mandatory in the UserInfo Response (http://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse):

> The sub (subject) Claim MUST always be returned in the UserInfo Response.

Unfortunately, the UserInfo Response returned by the UAA UnserinfoEndpoint does not contain this claim, which makes integration with other products difficult or even impossible.

**Suggestion**: The _sub_ claim should be added and should contain the exact same value as the non-standard claim "user_id" (as with the ID tokens issued by the UAA server).

Pointers to classes involved:
_org.cloudfoundry.identity.uaa.account.UserInfoEndpoint_
_org.cloudfoundry.identity.uaa.account.UserInfoResponse_

**Comment by nicolasrueegg** [comment]
Thanks for working on this. This will help with the integration with other products.

Judging from the labels, and the fact that this feature branch has been merged into the _develop_ branch, I assume this will also be fixed in one of the upcoming releases.

However, I don't understand in what release. Furthermore, the comment in the pivotaltracker about the feature being "Rejected" due to an unsuccessful integration test is disturbing. Does this mean the feature is broken and will not be integrated into a release?

Is there some sort of document describing the development process, which could answer my questions?

**Comment by sreetummidi** [comment]
This fix will be available in UAA 3.8.0
