### ISSUE TITLE
client config redirect_uri docs need more details

### ISSUE THREAD

**Issue by sanjeevchopra** [cloudfoundry/uaa#448]
http://docs.cloudfoundry.com/uaa/#create88

Current:
"Allowed URI pattern for redirect during authorization"

Needs specifics on what kind of patterns can be used.  There are hints in the example post - 

 `  "redirect_uri" : [ "http://test1.com", "http*://ant.path.wildcard/**/passback/*"]`

Looking at the code,  this field is used as a ant path matcher. However, when not specified the DefaultRedirectResolver is used.

**Comment by sreetummidi** [comment]
Docs updated

**Comment by sanjeevchopra** [comment]
@sreetummidi   the new description doesnt seem accurate, for the case when  redirectUri is not specified.   [AntPathRedirectResolver](https://github.com/cloudfoundry/uaa/blob/616e8bcc58f9bc16f9d9ec806da1b0bf0f5dae85/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/AntPathRedirectResolver.java)  delegates to DefaultRedirectResolver.
