### ISSUE TITLE
Encoding issue in "/token_keys" - JWKS endpoint

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#449]
The current "/token_keys" endpoint (v3.7.0) provides a signed representation of the modulus "n" which may include an additional byte (0x00) in the beginning.
Following RFC 7518 (JWA) which is referenced in RFC 7517 (JWK) the modulus "n" and the exponent "e" must be unsigned:

Excerpt - RFC 7518: 

Base64urlUInt
      The representation of a positive or zero integer value as the
      base64url encoding of the value's unsigned big-endian
      representation as an octet sequence.  The octet sequence MUST
      utilize the minimum number of octets needed to represent the
      value.  Zero is represented as BASE64URL(single zero-valued
      octet), which is "AA".

6.3.1.1.  "n" (Modulus) Parameter

   The "n" (modulus) parameter contains the modulus value for the RSA
   public key.  It is represented as a Base64urlUInt-encoded value.

   Note that implementers have found that some cryptographic libraries
   prefix an extra zero-valued octet to the modulus representations they
   return, for instance, returning 257 octets for a 2048-bit key, rather
   than 256.  Implementations using such libraries will need to take
   care to omit the extra octet from the base64url-encoded
   representation.

6.3.1.2.  "e" (Exponent) Parameter

   The "e" (exponent) parameter contains the exponent value for the RSA
   public key.  It is represented as a Base64urlUInt-encoded value.

   For instance, when representing the value 65537, the octet sequence
   to be base64url-encoded MUST consist of the three octets [1, 0, 1];
   the resulting representation for this value is "AQAB".

Example from https://login.run.pivotal.io/token_keys: The issue is the leading "00" in the HEX representation, which must be omitted.

Modulus (Base64url encoded):

APP2l5hCJqXcFhyZWHOBvNwYGVZsoQncu0gi9JDO8FecQr0SitJOJyox9EFthPtBiCsyI-CUIWFPjHmR6wK3wq37YSF3IqPy5ejb6Ez2O-1wO1OrwRgoi3RmEhqzfMtOuHBdrjPHdwBIE09EcyytxOvPC7at_BsZ6FzlLi2Zl0th3hzXdm1v5OhMnfWd8ppnaVWVzMi8HqTcVN_FkEtmyT2F2L0ZM6Gda7v3XhMcG3nCNfDQnjvxiqd3_G8Crgto9yyhSSAMFt8xaA63AMaQvyQxtkUk4__wkb4bXeyZHkC1ShsiBzbQAmj097RU-rHL1VxxjweX0UywfC6_piuESAc=

Hex:

00 f3 f6 97 98 42 26 a5 dc 16 1c 99 58 73 81 bc dc 18 19 56 6c a1 09 dc bb 48 22 f4 90 ce f0 57 9c 42 bd 12 8a d2 4e 27 2a 31 f4 41 6d 84 fb 41 88 2b 32 20 25 08 58 53 e3 1e 64 7a c0 ad f0 ab 7e d8 48 5d c8 a8 fc b9 7a 36 fa 13 3d 8e d7 03 b5 3a bc 11 82 88 b7 46 61 21 ab 37 cc b4 eb 87 05 da e3 3c 77 70 04 81 34 f4 47 32 ca dc 4e bc f0 bb 6a d0 6c 67 a1 73 94 b8 b6 66 5d 2d 87 78 73 5d d9 b5 bf 93 a1 32 77 d6 77 ca 69 9d a5 56 57 33 22 f0 7a 93 71 53 45 90 4b 66 c9 3d 85 d8 bd 19 33 a1 9d 6b bb f7 5e 13 1c 1b 79 c2 35 f0 d0 9e 3b f1 8a a7 77 1b c0 ab 82 da 3d cb 28 52 48 03 05 b7 cc 5a 03 ad c0 31 a4 2f c9 0c 6d 91 49 38 c2 46 f8 6d 77 b2 64 79 02 d5 28 6c 88 1c db 40 09 a3 d3 de d1 52 b1 cb d5 5c 71 8f 07 97 d1 4c b0 7c 2e a9 8a e1 12 01

**Comment by sreetummidi** [comment]
fixed in 3.7.0

https://www.pivotaltracker.com/n/projects/997278/stories/128229581

**Comment by sebastianGit** [comment]
With version 3.7.0 the encoding of "n" was changed from Base64 to Base64URL. 

However, the value which is encoded still includes an additional byte (0x00) in the beginning (due to the sign bit of signed representations), which must be removed for Base64urlUInt specified in RFC 7518, which is an unsigned representation. 

From the RFC: "The representation of a positive or zero integer value as the
base64url encoding of the value's unsigned big-endian representation as an octet sequence. The octet sequence MUST utilize the minimum number of octets needed to represent the value."

**Comment by xlash** [comment]
This issue has not been fixed. Current version of https://login.run.pivotal.io/token_keys still returns :
```json
{
  "keys": [
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "sig",
      "kid": "sha2-2017-01-20-key",
      "alg": "RS256",
      "value": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyH6kYCP29faDAUPKtei3\nV/Zh8eCHyHRDHrD0iosvgHuaakK1AFHjD19ojuPiTQm8r8nEeQtHb6mDi1LvZ03e\nEWxpvWwFfFVtCyBqWr5wn6IkY+ZFXfERLn2NCn6sMVxcFV12sUtuqD+jrW8MnTG7\nhofQqxmVVKKsZiXCvUSzfiKxDgoiRuD3MJSoZ0nQTHVmYxlFHuhTEETuTqSPmOXd\n/xJBVRi5WYCjt1aKRRZEz04zVEBVhVkr2H84qcVJHcfXFu4JM6dg0nmTjgd5cZUN\ncwA1KhK2/Qru9N0xlk9FGD2cvrVCCPWFPvZ1W7U7PBWOSBBH6GergA+dk2vQr7Ho\nlQIDAQAB\n-----END PUBLIC KEY-----",
      "n": "AMh-pGAj9vX2gwFDyrXot1f2YfHgh8h0Qx6w9IqLL4B7mmpCtQBR4w9faI7j4k0JvK_JxHkLR2-pg4tS72dN3hFsab1sBXxVbQsgalq-cJ-iJGPmRV3xES59jQp-rDFcXBVddrFLbqg_o61vDJ0xu4aH0KsZlVSirGYlwr1Es34isQ4KIkbg9zCUqGdJ0Ex1ZmMZRR7oUxBE7k6kj5jl3f8SQVUYuVmAo7dWikUWRM9OM1RAVYVZK9h_OKnFSR3H1xbuCTOnYNJ5k44HeXGVDXMANSoStv0K7vTdMZZPRRg9nL61Qgj1hT72dVu1OzwVjkgQR-hnq4APnZNr0K-x6JU"
    }
  ]
}
```

The n modulus value, is still the representation of the modulus, with the first octet being 00

```bash
➜  uaa $ cat pivotal_public.key
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyH6kYCP29faDAUPKtei3
V/Zh8eCHyHRDHrD0iosvgHuaakK1AFHjD19ojuPiTQm8r8nEeQtHb6mDi1LvZ03e
EWxpvWwFfFVtCyBqWr5wn6IkY+ZFXfERLn2NCn6sMVxcFV12sUtuqD+jrW8MnTG7
hofQqxmVVKKsZiXCvUSzfiKxDgoiRuD3MJSoZ0nQTHVmYxlFHuhTEETuTqSPmOXd
/xJBVRi5WYCjt1aKRRZEz04zVEBVhVkr2H84qcVJHcfXFu4JM6dg0nmTjgd5cZUN
cwA1KhK2/Qru9N0xlk9FGD2cvrVCCPWFPvZ1W7U7PBWOSBBH6GergA+dk2vQr7Ho
lQIDAQAB
-----END PUBLIC KEY-----

➜  uaa $ PUBKEY=`grep -v -- ----- pivotal_public.key | tr -d '\n'`

➜  uaa $ echo $PUBKEY | base64 -d | openssl asn1parse -inform DER -i -strparse 19
    0:d=0  hl=4 l= 266 cons: SEQUENCE
    4:d=1  hl=4 l= 257 prim:  INTEGER           :C87EA46023F6F5F6830143CAB5E8B757F661F1E087C874431EB0F48A8B2F807B9A6A42B50051E30F5F688EE3E24D09BCAFC9C4790B476FA9838B52EF674DDE116C69BD6C057C556D0B206A5ABE709FA22463E6455DF1112E7D8D0A7EAC315C5C155D76B14B6EA83FA3AD6F0C9D31BB8687D0AB199554A2AC6625C2BD44B37E22B10E0A2246E0F73094A86749D04C75666319451EE8531044EE4EA48F98E5DDFF12415518B95980A3B7568A451644CF4E3354405585592BD87F38A9C5491DC7D716EE0933A760D279938E077971950D7300352A12B6FD0AEEF4DD31964F45183D9CBEB54208F5853EF6755BB53B3C158E481047E867AB800F9D936BD0AFB1E895
  265:d=1  hl=2 l=   3 prim:  INTEGER           :010001
➜  uaa $ openssl rsa -pubin -inform PEM -text -noout < pivotal_public.key
Public-Key: (2048 bit)
Modulus:
    00:c8:7e:a4:60:23:f6:f5:f6:83:01:43:ca:b5:e8:
    b7:57:f6:61:f1:e0:87:c8:74:43:1e:b0:f4:8a:8b:
    2f:80:7b:9a:6a:42:b5:00:51:e3:0f:5f:68:8e:e3:
    e2:4d:09:bc:af:c9:c4:79:0b:47:6f:a9:83:8b:52:
    ef:67:4d:de:11:6c:69:bd:6c:05:7c:55:6d:0b:20:
    6a:5a:be:70:9f:a2:24:63:e6:45:5d:f1:11:2e:7d:
    8d:0a:7e:ac:31:5c:5c:15:5d:76:b1:4b:6e:a8:3f:
    a3:ad:6f:0c:9d:31:bb:86:87:d0:ab:19:95:54:a2:
    ac:66:25:c2:bd:44:b3:7e:22:b1:0e:0a:22:46:e0:
    f7:30:94:a8:67:49:d0:4c:75:66:63:19:45:1e:e8:
    53:10:44:ee:4e:a4:8f:98:e5:dd:ff:12:41:55:18:
    b9:59:80:a3:b7:56:8a:45:16:44:cf:4e:33:54:40:
    55:85:59:2b:d8:7f:38:a9:c5:49:1d:c7:d7:16:ee:
    09:33:a7:60:d2:79:93:8e:07:79:71:95:0d:73:00:
    35:2a:12:b6:fd:0a:ee:f4:dd:31:96:4f:45:18:3d:
    9c:be:b5:42:08:f5:85:3e:f6:75:5b:b5:3b:3c:15:
    8e:48:10:47:e8:67:ab:80:0f:9d:93:6b:d0:af:b1:
    e8:95
```


The following script in python was use to verify the expected result.
```python
import codecs
n="""C87EA46023F6F5F6830143CAB5E8B757F661F1E087C874431EB0F48A8B2F807B9A6A42B50051E30F5F688EE3E24D09BCAFC9C4790B476FA9838B52EF674DDE116C69BD6C057C556D0B206A5ABE709FA22463E6455DF1112E7D8D0A7EAC315C5C155D76B14B6EA83FA3AD6F0C9D31BB8687D0AB199554A2AC6625C2BD44B37E22B10E0A2246E0F73094A86749D04C75666319451EE8531044EE4EA48F98E5DDFF12415518B95980A3B7568A451644CF4E3354405585592BD87F38A9C5491DC7D716EE0933A760D279938E077971950D7300352A12B6FD0AEEF4DD31964F45183D9CBEB54208F5853EF6755BB53B3C158E481047E867AB800F9D936BD0AFB1E895"""


base64.urlsafe_b64encode(codecs.decode(n, 'hex')).decode()
'yH6kYCP29faDAUPKtei3V_Zh8eCHyHRDHrD0iosvgHuaakK1AFHjD19ojuPiTQm8r8nEeQtHb6mDi1LvZ03eEWxpvWwFfFVtCyBqWr5wn6IkY-ZFXfERLn2NCn6sMVxcFV12sUtuqD-jrW8MnTG7hofQqxmVVKKsZiXCvUSzfiKxDgoiRuD3MJSoZ0nQTHVmYxlFHuhTEETuTqSPmOXd_xJBVRi5WYCjt1aKRRZEz04zVEBVhVkr2H84qcVJHcfXFu4JM6dg0nmTjgd5cZUNcwA1KhK2_Qru9N0xlk9FGD2cvrVCCPWFPvZ1W7U7PBWOSBBH6GergA-dk2vQr7HolQ=='
```

While the displayed n version, is the incorrect 00 prefixed hexadecimal :
```python
base64.urlsafe_b64encode(codecs.decode("00" + n, 'hex'))
'AMh-pGAj9vX2gwFDyrXot1f2YfHgh8h0Qx6w9IqLL4B7mmpCtQBR4w9faI7j4k0JvK_JxHkLR2-pg4tS72dN3hFsab1sBXxVbQsgalq-cJ-iJGPmRV3xES59jQp-rDFcXBVddrFLbqg_o61vDJ0xu4aH0KsZlVSirGYlwr1Es34isQ4KIkbg9zCUqGdJ0Ex1ZmMZRR7oUxBE7k6kj5jl3f8SQVUYuVmAo7dWikUWRM9OM1RAVYVZK9h_OKnFSR3H1xbuCTOnYNJ5k44HeXGVDXMANSoStv0K7vTdMZZPRRg9nL61Qgj1hT72dVu1OzwVjkgQR-hnq4APnZNr0K-x6JU='
```


Usage of the incorrect n value, causes issues with other librairies validating the JWT issued and validating with the JWKS service provided, such as Dotnet Framework System.IdentityModel.Tokens.Jwt::JwtSecurityTokenHandler()

JWT.io also returns an error and some other Java tools

This affects VmWare Tanzu Ops Manager 2.9 with UAA version 74.5.21
