### ISSUE TITLE
Doc: /info endpoint incorrectly references http

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#454]
https://docs.cloudfoundry.org/api/uaa/index.html#server-information has a sample request of:

`curl 'http://localhost/info' -i -H 'Accept: application/json'`

Assuming a valid url this will fail with a message that https is required. The sample should have that already.

**Comment by sreetummidi** [comment]
Hello @twoseat 
All the API docs are documented with the HTTP . We don't plan on adding this as an exception. You can use the curl -k option to get information with https
