### ISSUE TITLE
UAA appears to accept URI parameters with POST to /oauth/token when it shouldn't?

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa#462]
Tested against CF release 245 it appears to be possible to get a token by POSTing request uri parameters to /oauth/token.  The way I read the spec https://tools.ietf.org/html/rfc6749#section-4.3.2 it seems to indicate that the oauth server should only accept parameters to this endpoint "in the HTTP request entity-body".

One of the issues with accepting these credentials via uri parameter is that many servers and proxies log request parameters in access logs.  In CF's case both UAA and the router log request parameters in access logs.  It appears that currently request parameters are not logged by the firehose HttpStartStop events.

I think UAA should fail if these parameters are sent in the request URI so help stop users from accidentally using URI parameters in production.

**Comment by sreetummidi** [comment]
Hi @youngm 

We expect the content type to be set to "'Content-Type: application/x-www-form-urlencoded'"
Whether you pass the parameters as a query parameters or in the body eventually everything gets put into the request body during the transport of the request.  The UAA just receives final set of parameters the body and cannot differentiate. 

Thanks,
Sree

**Comment by youngm** [comment]
Thanks for the response @sreetummidi 

So, are you saying that there is no feasible way for you to differentiate between uri parameters and request body parameters?  Or are you saying that, the way you interpret the spec, uri parameters are part of the "HTTP request entity-body"?  Or are you saying both? :)

**Comment by sreetummidi** [comment]
I was saying the former :) in that UAA cannot differentiate

**Comment by youngm** [comment]
@sreetummidi Perhaps you can simply check the request URI in the servlet request for some or all of the request parameters and fail the request if they are in there?  Like password, secret, etc?  I think if the parameter isn't in the request URI then you can assume the parameter came from the body?

**Comment by sreetummidi** [comment]
Being fixed in UAA 4.0 
https://www.pivotaltracker.com/story/show/137401169

**Comment by youngm** [comment]
@sreetummidi Sounds good.  Though to be clear the problem isn't about GET vs POST.  It is about url parameters vs entity body parameters.

**Comment by nebhale** [comment]
We've also made this change in the client, so there shouldn't need to be a huge rush on the change.

**Comment by youngm** [comment]
Exactly.  Lumping it in with a major version change makes sense to me.
