### ISSUE TITLE
/reset_password flow no feedback for user if password policy not matching

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#465]
We have password policy configured on our UAA instance and few users complain that there is no input back to users if entered password not matching password policy and essentially users need to reinitiate password policy reset again and again until policy matching. I know /reset_password policy page can be custom per instance, but it would be nice to present password policy on a default page or at least let customer configure it on default page. Also provide input back to users if policy not match and allow few attempts (configurable I guess) if policy not match. Hope the description is clear. I think it was tested based on UAA open source version 3.3.0.1, so it might be fixed recently.

**Comment by fhanik** [comment]
We suggest to validate this with the latest version, and reopen this issue if it still exists.

**Comment by ilipkind** [comment]
We retested with version 3.7.3 and same issue still present. @fhanik @sreetummidi please take a look
