### ISSUE TITLE
Prevent revocable refresh tokens from filling up the UAA db

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/uaa#466]
We're observing our UAA db grow very fast with the revocable_tokens table having millions of entries for the same ``(client_id, user_id)`` pair, leading to operational issues on the uaa db.
We’ve tracked down this to a bot using the "cf" oauth client and repeatedly creating AT/RT (though normal use of the cf-java-client v1) that resulted in the ``revocable_tokens`` table to grow quickly.
 
I understand that following [story #114249695](https://www.pivotaltracker.com/n/projects/997278/stories/114249695) and https://github.com/cloudfoundry/uaa/commit/610e0c1a6b5a719eadd30e038a62636bbf78de97#diff-a1b562a91683898a367cc534b0d014a8R325 that refresh tokens are systematically stored in db in the ``revocable_tokens`` table and should get removed when the token expires or gets revoked according to 
[design proposals spec](https://docs.google.com/document/d/1tWg5aNGyvibofavHNim6NJvhfcsNt2e1StrVfURI_Ww/edit#) : 
 
> An entry from this storage system will be removed when
> -    A token has expired or 
> -    A token has been revoked
 
Looking at the code and similar UAA DB housekeeping issue previously reported in #182, the expired elements in the DB seem only cleaned up when accessed/updated. I’m suspecting that in our case, the related AT/RT is not accessed, leading to the observed “db leak”.

It would be useful to support a new configurable max number of revocable tokens with the same ``(client_id, user_id)`` pair. This could for instance be checked at the time a new refresh token is created.
 
In terms of workarounds, we tried or are considering for this is issue:
- after reducing the refresh-token-validity for the affected oauth client (from 30 days to 1 day), we did not see the related refresh tokens for this client being removed from the db (with cf-release v242 ). 
- we are considering manually truncating the revocable_tokens table.
- facing the UAA endpoint with a rate limiting system: however this rate limit would need to deal with the uaa requests body in order to limit number of ``/token`` calls for a given ``(client_id, user_id)`` pair: filtering only on source IP might generate false positive rate limits (e.g. corporate users going through a gateway/proxy and appearing as single IP address). 

I'm interested to hear what would be other recommended ways to cope with such high rate UAA token traffic.

**Comment by fhanik** [comment]
Guess the github commit doesn't close this issue. Manually closing based on https://github.com/cloudfoundry/uaa/commit/89ad23a82d3f5ebd48e9727e1a3086732c7ef424

**Comment by gberche-orange** [comment]
great, thanks a lot @fhanik for this fix.

/CC @poblin-orange

**Comment by gberche-orange** [comment]
@fhanik during enquiry with security@cloudfoundry.org prior to submitting this issue, the security team transferred me the following UAA team analysis :

> The (uaa) team has a story to investigate implementing a set of work that will generally make refresh tokens unnecessary. This would prevent the scenario you're asking about.

Is this related to the "Refresh Inactivity Expiration" in https://www.pivotaltracker.com/story/show/118049187, or is this something else ?
