### ISSUE TITLE
Incorrect action name for client...mixed actions

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#467]
I believe the `UPDATE_SECRET` constant on this line:
https://github.com/cloudfoundry/uaa/blob/5cbf9c1b65598892e6f72966a1288e11f72e793a/model/src/main/java/org/cloudfoundry/identity/uaa/oauth/client/ClientDetailsModification.java#L24

should have the value `update_secret`, as documented here:
https://docs.cloudfoundry.org/api/uaa/#mixed-actions

**Comment by sreetummidi** [comment]
https://docs.cloudfoundry.org/api/uaa/version/4.8.0/index.html#mixed-actions
The actions are secret , delete and add
