### ISSUE TITLE
Identity-Zone admin(created with X-Identity-Zone-Id) must have capabilities to dynamically reconfigure the Identity Zone

### ISSUE THREAD

**Issue by RoopGuron** [cloudfoundry/uaa#472]
Use Case:
Each UAA zone is provisioned as a service instance of uaa on cloudfoundry.

To let service instance owners(business clients) administer the instance (Identity-zone) we create 'admin' client for each service instance to go with the service instance(identity-zone).

The way the security filter chain oauthWebExpressionHandler for the /identity-zones/\* endpoint is configured, a zone(service instance) authenticated client token can not access it.

This use case is critical to our needs.

**Comment by ilipkind** [comment]
Per discussion with @sreetummidi  one design option would be providing new api's for zone configuration accessible for zone administrators with new scopes specific to zone configuration to address this issue.

**Comment by RoopGuron** [comment]
I believe we would need the *spring-aop* advice to check the zone in the
token(IdentityZoneHolder already has the zone in the bearer token) is the
same as the *{zone_id}* in the new identity-zone endpoint(if the expression
handler for the endpoints would have a *or* for scopes)

**Comment by sreetummidi** [comment]
The support to administer zone from within the zone has been added in UAA 4.0.0
