### ISSUE TITLE
Doc: Incorrect reference for no group ldap file

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#473]
https://docs.cloudfoundry.org/api/uaa/#ldap contains the following text:

```
The file to be used for group integration. Options are: ldap/ldap-no-groups.xml, ldap/ldap-groups-as-scopes.xml, ldap/ldap-groups-map-to-scopes.xml
```

The first option should be `ldap/ldap-groups-null.xml`

**Comment by fhanik** [comment]
Fixed via 
https://github.com/cloudfoundry/uaa/commit/03816dfff531ddef204f8f8199c189c8c7087faf
