### ISSUE TITLE
/reset_password flow no feedback for user if password policy not matching

### ISSUE THREAD

**Issue by ilipkind** [cloudfoundry/uaa#475]
We have password policy configured on our UAA instance and few users complain that there is no input back to users if entered password not matching password policy and essentially users need to reinitiate password policy reset again and again until policy matching. I know /reset_password policy page can be custom per instance, but it would be nice to present password policy on a default page or at least let customer configure it on default page. Also provide input back to users if policy not match and allow few attempts (configurable I guess) if policy not match. Hope the description is clear. 
Also flow does not allows reset_password if policy don't match and require resending email and again until policy is matching. I don't see a reason to validate user email address multiple times. I hope this would be fixed if user would be notified immediately if entered password not matching the policy. 
This flow is validated now with CF version v243 (UAA version 3.7.3). Same problem as here: [https://github.com/cloudfoundry/uaa/issues/465](url) just tested on recent version.

**Comment by sreetummidi** [comment]
With 3.10 we are adding the ability to retry in case of a password policy error on the Reset Password flow to improve user experience.
