### ISSUE TITLE
Ability to style UAA login pages with Custom CSS

### ISSUE THREAD

**Issue by rashmeetsinghge** [cloudfoundry/uaa#476]
When an IDP is configured on the UAA, the login flow for the user is modified. The first pages collects the email of the user and then of the IDP is not configured for the email, then another page is shown to collect the password for the user. 

The issue is that there is NO way to customize the look and feel of these login pages by configuring a custom css for these pages via the uaa.yml configuration. 

<img width="1347" alt="screen shot 2016-10-26 at 9 12 22 pm" src="https://cloud.githubusercontent.com/assets/10839453/19754299/f9943192-9bc0-11e6-9181-89110eb26143.png">
<img width="1383" alt="screen shot 2016-10-26 at 9 12 08 pm" src="https://cloud.githubusercontent.com/assets/10839453/19754300/f9946d24-9bc0-11e6-8eb3-41d0e2df2daa.png">

The login page that appears when there is NO IDP configured can be styled.

<img width="1385" alt="screen shot 2016-10-26 at 9 15 42 pm" src="https://cloud.githubusercontent.com/assets/10839453/19754343/650da6e2-9bc1-11e6-989d-8d4a5dd48129.png">

**Comment by ilipkind** [comment]
Same request applies to all UAA pages like "client approve", "IdP discovery based on domain" and so on.

**Comment by sreetummidi** [comment]
We don't have plans to support this level of customization in the UI
