### ISSUE TITLE
get authentication for someone else

### ISSUE THREAD

**Issue by bilak** [cloudfoundry/uaa#481]
Hi,
is there some way how to get authentication for some user?
Let's imagine the workflow application:
1. User ABC creates some tasks in client application, which can run at any time (in 1 day or maybe in 10 days, or maybe in 1 month)
2. task is stored in repository and as metadata there is also stored user's ID (ID-ABC-123)
3. task is going to be executed, but it needs to be executed under user ABC because it uses another services which need to know about user context.

Authorization token could expire in meantime and storing the credentials is risky. 

For this there is an option to create some "privileged" client and send some header (X-USER-ID) with user's id to the auth server. Auth server should validate the client and also user. If everything is ok, then try to change authentication. The client should use for this userInfoUri and get re-authenticated user.

Is in uaa implemented something similar?

Thanks

**Comment by sreetummidi** [comment]
@bilak The refresh token serves as an offline token and is meant to be used on the users behalf to get more access tokens in an offline fashion after the original access token has expired.
Please refer to the refresh token flow here :  http://docs.cloudfoundry.org/api/uaa/#refresh-token
