### ISSUE TITLE
Possible to provide client secrets as environment variables?

### ISSUE THREAD

**Issue by zpearce** [cloudfoundry/uaa#483]
I've tried using env var placeholders in uaa.yml with no luck:

```
oauth:
  clients:
    myclient:
      secret: ${CLIENT_SECRET}
```

Then I read that this kind of replacement is not supported, but that I could turn the yml key into an env var spring boot style, so I tried setting the env var ```OAUTH_CLIENTS_MYCLIENT_SECRET=thesecret``` which also doesn't work. 

I would very much like to externalize these secrets. Is there a way to do that that I'm missing?

**Comment by sreetummidi** [comment]
@plfx DO you have any inputs on this. Is this supported when using YML conf?

**Comment by plfx** [comment]
There is no support for placeholders or env references, and the boot-style env value will not work because this is not a property that is read individually; the whole client is bootstrapped at once from the YML.

**Comment by fhanik** [comment]
there is a way, it is a bit convoluted, but it would work. Not sure we recommend it, but it is a solution :)

    export UAA_CONFIG_YAML = '{oauth: {clients: {cf: {secret: testPassword}}}}'

the `UAA_CONFIG_YAML` is essentially a _yaml string_ that we merge into the configuration.
This will not work when using the `default` profile where clients from the Spring XML files override everything, but if you have specified all your clients in one of the Yaml configuration files, then it will work.

**Comment by fhanik** [comment]
Created a simple unit test to validate it in `org.cloudfoundry.identity.uaa.login.BootstrapTests`

    @Test
    public void test_override_from_env() throws Exception {
        System.setProperty("spring.profiles.active","hsqldb");
        context = getServletContext(null, false, new String[] {"login.yml", "uaa.yml", "required_configuration.yml"}, "file:./src/main/webapp/WEB-INF/spring-servlet.xml");
        JdbcTemplate clients = context.getBean(JdbcTemplate.class);
        BCryptPasswordEncoder encoder = context.getBean(BCryptPasswordEncoder.class);
        String cfSecret = clients.queryForObject("select client_secret from oauth_client_details where client_id = 'cf'", String.class);
        assertTrue(encoder.matches("testPassword", cfSecret));
    }

**Comment by Tataraovoleti** [comment]
HI @fhanik ,
I m having this issue even though i incorporated changes what you suggested. 

Here is my client in uaa.yml
```
oauth:
  clients:
    testclient:
      authorized-grant-types: client_credentials,authorization_code
```

I set below env variable. 
`export UAA_CONFIG_YAML = {oauth: {clients: {testclient: {secret: testclient}}}}`

@sreetummidi any other approach, please suggest.

**Comment by fhanik** [comment]
@Tataraovoleti This issue has been closed and will not be worked on anymore. Please open a new issue if you feel there is a bug or try the slack UAA channel or https://stackoverflow.com/questions/tagged/cloudfoundry-uaa
