### ISSUE TITLE
Using placeholders in UAA_CONFIG_YAML

### ISSUE THREAD

**Issue by miclip** [cloudfoundry/uaa#484]
Trying to understand how to use placeholders to set SMTP credentials within the UAA_CONFIG_YAML for a bound service sendgrid on PWS. 

` smtp:
   host: ${vcap.services.smtpdev.credentials.hostname:localhost}
   port: 2525
   user: ${vcap.services.smtpdev.credentials.username:user}
   password: ${vcap.services.smtpdev.credentials.password:password}`

_Caused by: javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 2525;_

auto_reconfig is enabled and it's successfully binding the app to the mysql service.

**Comment by gadginir** [comment]
Even after providing details of new SMTP servers in UAA_CONFIG_YAML, why its picking default values like host:localhost and port:2525?

**Comment by miclip** [comment]
Right, it never used the vcap_services values and always picked the defaults.

**Comment by gadginir** [comment]
I changed the value of it in build.gradle file and it works for me.

**Comment by miclip** [comment]
You changed the value to what? You used the placeholders?

**Comment by gadginir** [comment]
I am just evaluating the software for my case. That's why I hardcoded the actual value. But I think we can put placeholders instead which is the best practice.

**Comment by miclip** [comment]
Agree it's best practice but I don't think it works

**Comment by miclip** [comment]
I tried using placeholders in the Uaa.yml and the uaa_config_yml and it never worked. It takes hard coded values fine but isn't a good idea as the smtp credentials will end up in a repo.

**Comment by sreetummidi** [comment]
@plfx Can you comment?

**Comment by plfx** [comment]
@miclip Are you using UAA's Bosh release (from the `uaa-release` repo), or UAA directly from the`uaa` repo?

**Comment by miclip** [comment]
Directly from the repo.

**Comment by fhanik** [comment]
@miclip We don't support variable substitution in the Yaml configuration files. These contain values.
However, you can set environment variables for almost any variable that we have that is configurable.

For example
 
    smtp:
      host: localhost

Can be written as `smtp.host` system property or `SMTP_HOST` environment variable.

So for a CF application, you can set the env variable `SMTP_HOST` to override the default
