### ISSUE TITLE
Deactivate inactive users

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry/uaa#485]
We would like to deactivate inactive users as a lot of Cloud Foundry accounts may be created but unused and it increases our attack surface greatly.

We have thought about an implementation using the UAA API, keeping track of user tokens and sending warning emails before deactivating the accounts. The complication is that we need to store state externally whether we have seen the user active, because after the secret token expires, it is not retrievable any more and if user doesn't log in again, it is hard to tell when was the last time user has used their account.

Is there any plan to implement this or similar functionality in UAA?

At the moment only [the failed logins are logged in the DB](https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/audit/JdbcFailedLoginCountingAuditService.java). Regular events are [logged to file](https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/audit/event/AuditListener.java). Could this be made configurable? Could the API then expose audit events?

**Comment by CAFxX** [comment]
We were also starting to looking into this, and I would like to bring one additional scenario: in our case we use LDAP for authenticating users and we'd like to deactivate/delete users (and ideally resources owned uniquely by that user) when a user disappears from LDAP.

**Comment by bleach** [comment]
@CAFxX I'm on the same team as @saliceti

**Comment by CAFxX** [comment]
@bleach you are correct, it is pretty different from what you're requesting and should most likely be implemented separately; I was just mentioning it here because UAA has multiple modes of operations (internal vs. shadow users) but the user deactivation problem is common - although policies may differ.

**Comment by bleach** [comment]
We're still interested in this. Any thoughts if it's something you'd be likely to accept?

**Comment by sreetummidi** [comment]
UAA now supports last logon time on the user that should help with this tracking
