### ISSUE TITLE
Doc: Misleading text in Browser Flow Auth

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#494]
The doc at https://docs.cloudfoundry.org/api/uaa/#browser-flow contains the following text for `response_type`:

`either code for requesting an authorization code for an access token, as per OAuth spec`

The 'either' implies that there is another choice, but no detail is given.

**Comment by jhamon** [comment]
Closing this as the strange wording was changed as part of [this story](https://www.pivotaltracker.com/n/projects/625235/stories/147464283).

There are other values that may be passed to the authorize endpoint, but for the specific example linked in this issue (an authcode flow example) it only makes sense to use `response_type=code`. The other valid values (`token` and `id_token`) are used in the implicit grant flow.
