### ISSUE TITLE
Provide User Logout API

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry/uaa#495]
Hi guys,

Currently UAA provides just UI endpoint for user logout - `/logout.do` (as per api [documentation](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#ui-endpoints)). It means that if I have an application with custom login/logout pages which uses UAA oauth server for user authorization, there is no way for a user to revoke itself - there is no such API provided by UAA.

Could you please provide such an API?

Thanks.

**Comment by fhanik** [comment]
Define `revoke itself`?

You wish for a user to deactivate itself using the UI? That would be a self destruct operation, the user could never reactivate itself at that point.

**Comment by fhanik** [comment]
We do have a revoke all tokens API 
https://docs.cloudfoundry.org/api/uaa/#revoke-tokens

**Comment by hannayurkevich** [comment]
I would like to logout a user, which means to invalidate current user session. But if I use UI flow, then I'm unable to get back to my application after /logout.do because redirects are disabled by default.
So I thought, maybe there is an api that can be called to invalidate current user session.

Btw, why do you disable redirects after logout by default?

**Comment by fhanik** [comment]
UI log out does invalidate the HTTP session. The only way to do it, is using the browser.
But this does not invalidate tokens, because I may not wish to be logged out from other applications (like Cloud Foundry `cf` command line interface)

To modify the redirect behavior (enable a redirect parameter and whitelist it)
https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/resources/login.yml#L38-L45

The answer to your question is yes, there is an API to invalidate tokens.

To revoke all user tokens
http://docs.cloudfoundry.org/api/uaa/#revoke-tokens

**Comment by hannayurkevich** [comment]
Thank you for the answer.

But, you are talking about an api for revoking all user tokens, which additionally requires the user to be admin.

I was asking about a possibility to revoke a particular token by a non-admin user. Something like e.g. google provides https://developers.google.com/identity/protocols/OAuth2WebServer#tokenrevoke. So that a user can make its token inactive. Is it possible?

**Comment by fhanik** [comment]
This looks like a documentation bug

http://docs.cloudfoundry.org/api/uaa/#revoke-tokens

states that you need uaa.admin, that is incorrect. 

    <intercept-url 
      pattern="/oauth/token/revoke/user/**" 
      access="#oauth2.hasScope('uaa.admin') or (#oauth2.hasScope('tokens.revoke') and @self.isUserTokenRevocationForSelf(request, 4))" />

If the token you are using to revoke, matches the user_id you are trying to revoke for, matches, then it is permitted.

I'm reopening this issue to fix the documentation.

Note to developer: Fix documentation about what permissions are needed to revoke user tokens.

**Comment by fhanik** [comment]
The permissions needed to revoke a user's token are:

1. uaa.admin OR
2. tokens.revoke
3. the user_id in the token matches the user_id in the URL for tokens to be revoked

**Comment by hannayurkevich** [comment]
Ok, then am I right that in this case user still revokes **all** its tokens, not the provided one?

**Comment by fhanik** [comment]
Not quite, we do have `/oauth/token/revoke/{tokenId}` endpoint, that will work if the token_id in the token is the same as the tokenId in the URL

So a token can revoke itself

**Comment by hannayurkevich** [comment]
@fhanik, thank you!

Could you please also tell me how I can get {tokenId}? Which API should be called to get it?

**Comment by fhanik** [comment]
A token response looks like

    {
        "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImxlZ2FjeSIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4ZTBlODI0NTA2NmU0YzRjOTNkMzViNGIyNTAxNmE3ZiIsInN1YiI6ImFkbWluIiwic2NvcGUiOlsiY2xpZW50cy5yZWFkIiwicGFzc3dvcmQud3JpdGUiLCJjbGllbnRzLnNlY3JldCIsImNsaWVudHMud3JpdGUiLCJ1YWEuYWRtaW4iLCJzY2ltLndyaXRlIiwic2NpbS5yZWFkIl0sImNsaWVudF9pZCI6ImFkbWluIiwiY2lkIjoiYWRtaW4iLCJhenAiOiJhZG1pbiIsImdyYW50X3R5cGUiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJyZXZfc2lnIjoiYjE3ZjJmMzAiLCJpYXQiOjE0ODA2MTA1MzMsImV4cCI6MTQ4MDY1MzczMywiaXNzIjoiaHR0cHM6Ly91YWEuaWRlbnRpdHkuY2YtYXBwLmNvbS9vYXV0aC90b2tlbiIsInppZCI6InVhYSIsImF1ZCI6WyJzY2ltIiwicGFzc3dvcmQiLCJjbGllbnRzIiwidWFhIiwiYWRtaW4iXX0.HD9pqzgMy6TvEsLonU4tk3LJ73vyJc6T14L_xG7bZl0XCkn3mNkjVsxPUA-wRkQtn-0IKTemX8ax9gXwcJncB4PWewowR-zw1_aInxI4eCS2o1thm_brpSlOpbNzj6SUgG5OcciKlnalLFWUx2ez_uUriHB2Dus2cLTWyzn058o",
        "expires_in": 43199,
        "jti": "8e0e8245066e4c4c93d35b4b25016a7f",
        "scope": "clients.read password.write clients.secret clients.write uaa.admin scim.write scim.read",
        "token_type": "bearer"
    }

you have `jti` as a field, that is the token ID. You can also decode the JWT token, and grab the `jti` claim

**Comment by hannayurkevich** [comment]
Thank you!

**Comment by hannayurkevich** [comment]
@fhanik, I have a question regarding https://docs.cloudfoundry.org/api/uaa/#password-grant api .

As far as I understand, I can use this api to get access token for a user by providing his username/password and client details.

So I execute the following query:
```
POST
https://uaa.64.78.234.204.nip.io/oauth/token?client_id=kibana_oauth2_client&client_secret=oauth2_client_secret&grant_type=password&username=admin&password=admin&response_type=token

with headers:
Accept: application/json
Content-Type: application/x-www-form-urlencoded
```

As a result I get 401:
```
Pragma: no-cache, no-cache
Date: Fri, 02 Dec 2016 11:40:31 GMT
Www-Authenticate: Basic realm="UAA/client", error="unauthorized", error_description="No client authentication found. Remember to put a filter upstream of the TokenEndpointAuthenticationFilter."
Server: Apache-Coyote/1.1
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Content-Type: application/json
Access-Control-Allow-Origin: *
X-Vcap-Request-Id: f946dccc-b4b3-41a5-623c-5b1638461d9b
X-Xss-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, no-store
Content-Length: 154
X-Content-Type-Options: nosniff
Expires: 0
```

Am I missing something?

**Comment by fhanik** [comment]
We're going to make a small modification, try this one

    curl -k -H"Accept:application/json" -u "kibana_oauth2_client:oauth2_client_secret" --data "client_id=kibana_oauth2_client&grant_type=password&username=admin&password=admin&response_type=token" https://uaa.64.78.234.204.nip.io/oauth/token

**Comment by hannayurkevich** [comment]
@fhanik, here is what I get:

```
$ curl -k -H"Accept:application/json" -u "kibana_oauth2_client:oauth2_client_secret" --data "client_id=kibana_oauth2_client&grant_type=password&username=admin&password=admin&response_type=token" https://uaa.64.78.234.204.nip.io/oauth/token

{"error":"invalid_client","error_description":"Unauthorized grant type: password"}
```

Though, it appeared that I don't depend on this API anymore, still, It makes sense to update the UAA documentation and make it up-to-date.

Thanks for help!
Hanna

**Comment by hannayurkevich** [comment]
@fhanic,

I also tried to update an identity zone in order to provide redirect after logout settings. But my queries to /identity-zones result in 403 response. Could you please hint me what can be the problem?

query1 - Get list of identity zones
```
GET https://uaa.64.78.234.204.nip.io/identity-zones

Authorization: Bearer eyJhbGciOiJSUz...
```
Response:
```
Status: 403

Pragma: no-cache, no-cache
Date: Mon, 05 Dec 2016 13:10:08 GMT
Www-Authenticate: Bearer error="insufficient_scope", error_description="Insufficient scope for this resource", scope="zones.read zones.uaa.admin"
Server: Apache-Coyote/1.1
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Content-Type: application/json;charset=UTF-8
X-Vcap-Request-Id: 2083f947-d58a-4d1b-7409-aa26c5fe4aec
X-Xss-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, no-store
Content-Length: 126
X-Content-Type-Options: nosniff
Expires: 0
```

It says that the necessary scopes are missing: __zones.read__ and  __zones.uaa.admin__.

But, If I execute a query to see my client details, the necessary scopes are present in the client scopes list.

query2 - Get client details
```
GET https://uaa.64.78.234.204.nip.io/oauth/clients/kibana_oauth2_client

Authorization: Bearer eyJhbGciOiJSUz...
```
Response:
```
Status:     200: OK

{
"scope": [
  "zones.read",
  "scim.userids",
  "cloud_controller.read",
  "openid",
  "oauth.approvals",
  "zones.uaa.admin"
],
"client_id": "kibana_oauth2_client",
"resource_ids": [
  "none"
],
"authorized_grant_types": [
  "refresh_token",
  "authorization_code"
],
"redirect_uri": [
  "https://logs.64.78.234.204.nip.io/login",
  "http://localhost:5061/login",
  "http://logs.64.78.234.204.nip.io/login",
  "https://localhost:5061/login"
],
"autoapprove": [],
"access_token_validity": 43200,
"action": "none",
"authorities": [
  "uaa.none"
],
"lastModified": 1480943392532
}
```

Both __"zones.read"__ and  __"zones.uaa.admin"__ are present in the client's scope list.

Your help would be really appreciated.
Hanna

**Comment by fhanik** [comment]
The token probably doesn't have zones.read (that will happen if the user doesn't have it)

**Comment by hannayurkevich** [comment]
But, from what I posted in the last comment, there is "zones.read" scope listed in response to query `GET https://uaa.64.78.234.204.nip.io/oauth/clients/kibana_oauth2_client`:

```
...
"scope": [
  "zones.read",
...
```
As far as I understand, this is the required scope and it is present.
