### ISSUE TITLE
Do not require SAML Certificates when SAML is not used

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/uaa#497]
Hello,

we are using CF and UAA without usage of an external SAML provider. Beginning with the UAA release included in CF248 you need to manually specify a Certificate and Key for a SAML, since UAA stopped to use a default cert. As we are not using a SAML provider I would like the option to not set the Certificates when no external SAML provider is configured.

**Comment by sreetummidi** [comment]
UAA is being configured at start up time to always act as a SAML Service Provider and we are encountering this flow more than 90% of the time in CF deployments in enterprises.
We had put this in place so that operators don't have to re-deploy UAA for it to be set up as a SAML Service Provider.
