### ISSUE TITLE
Running multiple instances may result in single instance startup failure

### ISSUE THREAD

**Issue by 6palace** [cloudfoundry/uaa#498]
Running a multi-instance app of uaa sometimes results in two instances running ScimGroupBootstrap at the same time, causing one of the instances failing to start with attached stacktrace. Note the IncorrectResultSizeDataAccessException happening in ScimGroupProvisioning.

`ERROR --- DispatcherServlet: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scimGroupBootstrap' defined in ServletContext resource [/WEB-INF/spring/scim-endpoints.xml]: Invocation of init method failed; nested exception is org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
ERROR --- DispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
ERROR --- DispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
ERROR --- DispatcherServlet: 	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.web.RecognizeFailureDispatcherServlet.init(RecognizeFailureDispatcherServlet.java:56)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1140)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1027)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5038)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5348)
ERROR --- DispatcherServlet: 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
ERROR --- DispatcherServlet: 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
ERROR --- DispatcherServlet: 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
ERROR --- DispatcherServlet: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ERROR --- DispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
ERROR --- DispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
ERROR --- DispatcherServlet: 	at java.lang.Thread.run(Thread.java:745)
ERROR --- DispatcherServlet: Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:239)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:217)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:53)
ERROR --- DispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimGroupBootstrap.afterPropertiesSet(ScimGroupBootstrap.java:190)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
ERROR --- DispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
ERROR --- DispatcherServlet: 	... 33 more
ERROR --- RecognizeFailureDispatcherServlet: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scimGroupBootstrap' defined in ServletContext resource [/WEB-INF/spring/scim-endpoints.xml]: Invocation of init method failed; nested exception is org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
ERROR --- RecognizeFailureDispatcherServlet: 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.web.RecognizeFailureDispatcherServlet.init(RecognizeFailureDispatcherServlet.java:56)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1227)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1140)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1027)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5038)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5348)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
ERROR --- RecognizeFailureDispatcherServlet: 	at java.lang.Thread.run(Thread.java:745)
ERROR --- RecognizeFailureDispatcherServlet: Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 0
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:239)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:217)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupProvisioning.update(JdbcScimGroupProvisioning.java:53)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.cloudfoundry.identity.uaa.scim.bootstrap.ScimGroupBootstrap.afterPropertiesSet(ScimGroupBootstrap.java:190)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
ERROR --- RecognizeFailureDispatcherServlet: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
ERROR --- RecognizeFailureDispatcherServlet: 	... 33 more
`

**Comment by sreetummidi** [comment]
@fhanik Can you please comment. Is this something which has already been addressed

**Comment by bsekar** [comment]
This issue has been addressed by #603
