### ISSUE TITLE
Missing required OpenID Connect Discovery fields

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry/uaa#501]
I've been trying to integrate an external system with the UAA OpenID Connect and have had some challenges trying to use it. According to the [OpenID Connect Discovery 1.0 spec](https://openid.net/specs/openid-connect-discovery-1_0.html), there are some REQUIRED [Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) fields that are not returned by the UAA [OpenID Configuration Response](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse).

Specifically, these are the missing fields:
1. `jwks_uri` is REQUIRED but it is NOT returned.
1. `subject_types_supported` is REQUIRED but it is NOT returned.
1. `id_token_signing_alg_values_supported` MUST include `RS256`. Instead, it returns the alias `SHA256withRSA`. This has been previously reported (#282) and a PR (#479) has been submitted.

**Comment by sreetummidi** [comment]
Will be fixed in UAA 3.10.0

**Comment by frodenas** [comment]
Thanks @sreetummidi
