### ISSUE TITLE
serviceProviderKey in login.yml

### ISSUE THREAD

**Issue by ericis** [cloudfoundry/uaa#503]
The instructions in `login.yml` for `serviceProviderKey` suggest that instructions can be found in `README.md`, but I was unable to find any reference.

```
  # SAML Key Configuration
  # The location and credentials of the certificate for this SP
  # See README.md for details on how to create this.
 serviceProviderKey: |
```

**Comment by sreetummidi** [comment]
Please refer to instructions here on how to generate this
https://github.com/cloudfoundry/uaa-release#generating-a-self-signed-certificate

**Comment by ericis** [comment]
@sreetummidi will we plan to update the `uaa` project to point to the `uaa-release` project to help others in the future?
