### ISSUE TITLE
Failed to update UAA Service Provider configuration

### ISSUE THREAD

**Issue by bobhlo** [cloudfoundry/uaa#508]
We are running on CF v243 with UAA v3.7.3. Is there a known issue on UAA to update SP configuration with CF manifest?

The issue is CF deployment completed successfully but failed to update UAA SP configuration (serviceProviderKey, serviceProviderKeyPassword, serviceProviderCertificate) under /var/vcap/jobs/uaa/config/login.yml on UAA VMs.
Followed below link to override default UAA SP configuration - https://github.com/cloudfoundry/uaa/blob/69fc38968ecf6d0748acbfec7aac9ca32cf4ed3d/uaa/src/main/resources/required_configuration.yml to configure UAA SP. Following is an excerpt of the CF manifest. 
cf.yml 
```
... 
properties: 
  login: 
    serviceProviderKey: | 
      -----BEGIN RSA PRIVATE KEY----- 
      <KEY_HERE> 
      -----END RSA PRIVATE KEY----- 
    serviceProviderKeyPassword: <PASSWORD_HER> 
    serviceProviderCertificate: | 
      -----BEGIN CERTIFICATE----- 
      <CERT_HERE> 
      -----END CERTIFICATE-----
```

**Comment by fhanik** [comment]
Use correct namespace
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L647-L668
