### ISSUE TITLE
IDP initiated SAML flow

### ISSUE THREAD

**Issue by ssrini9** [cloudfoundry/uaa#510]
is there any document for IDP initiated SAML flow setup in UAA? please advice.

**Comment by sreetummidi** [comment]
Both IDP and SP Initiated SAML Flows are supported in UAA.
With the IDP Initiated flow we expect the SAMLResponse to be passed to the UAA ACS URL.
Please refer to this doc on how register a SAML Provider
http://docs.cloudfoundry.org/api/uaa/index.html#saml
