### ISSUE TITLE
Fail to use curl to login uaa

### ISSUE THREAD

**Issue by df010** [cloudfoundry/uaa#511]
export TZ

I use the following command to Login
 curl https://login.cf.com/login.do -k -v -X POST -d '{"username":"admin","password":"BtdW9rw-sxl2XPFXskitNVRso_d
41DZa","X-Uaa-Csrf":"IWY9y2"}'  -H "Content-Type:application/x-www-form-urlencoded" 
The X-Uaa-Csrf is get by visiting https://login.cf.com/login

But failed, and response is a login page, with message: 
 <p>Invalid login attempt, request does not meet our security standards, please try again.</p>

**Comment by sreetummidi** [comment]
UAA allows authentication via OpenID Connect and OAuth.
Please make sure you have a client registered and are using one of the support grant types
http://docs.cloudfoundry.org/api/uaa/index.html#authorization
