### ISSUE TITLE
UAADB revocable_tokens table is filled even if uaa.jwt.revocable is set to "false" in the YML file

### ISSUE THREAD

**Issue by aalbanes** [cloudfoundry/uaa#513]
My team is running a huge CF deployment and we noticed that event if the we have uaa.jwt.revocable set to false in the bosh YML file the UAADB table revocable_tokens  is filled with new records.
This was not happening in the previous version we were running (CF 235).

It seems to me that issue is in this class [Link](https://github.com/cloudfoundry/uaa/blob/3.7.4/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java#L713)
which doesn't properly skip token persistence if the uaa.jwt.revocable is false.

This is a problem for us (on DBA side) because revocable_tokens  table contains more than 3M records.

**Comment by fhanik** [comment]
If refresh tokens are requested, they are delivered in a revocable format, always.
There was a bug discovered where we only clean the table if the refresh token is being refresh.
With https://github.com/cloudfoundry/uaa/commit/51780c3c63fc98636f71d778c4fb8a4218ad3a82#diff-fbe33c1f3c5844b8f9482f55eaa64845 we also clean the table when we store tokens

**Comment by gberche-orange** [comment]
@aalbanes  see #466 for additional diagnostics

**Comment by aalbanes** [comment]
@gberche-orange Guillaume thx for reference. 
@fhanik  Filip, as far as I recall in the CF release context, CC are not going to validate if a refresh token expired or not but it it check for expiration field within the JWT itself.
It this still the case ? If so.. which is the reason why we cannot enforce a refresh token to  not be revocable.

**Comment by fhanik** [comment]
@aalbanes I think you can set the following to true

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L362-L364

I don't think the feature was meant to behave that way, but looking at the code, it will not issue refresh tokens if this value is set to true and the client doesn't have the `uaa.offline_token` scope.

**Comment by smoser-ibm** [comment]
@fhanik not having a refresh is not a solution. I think what we *really* need to fix is that refresh tokens are there, BUT it is configurable whether it is revocable. The current design doesn't really work at scale. 
FWIW, OpenStack had the same issues some years ago b/c they were storing too many tokens and then faced issues at scale. 
@sreetummidi let me know if this change will be possible or if you want to discuss this further on a PM level

**Comment by smoser-ibm** [comment]
@fhanik @sreetummidi can you comment please ?

**Comment by fhanik** [comment]
@smoser-ibm Correct, didn't suggest it as a solution, but a work around, until a solution is  in place :)

This issue will be open until a solution is in place.

**Comment by sreetummidi** [comment]
@smoser-ibm We will resurrect this feature for UAA 4.0
https://www.pivotaltracker.com/story/show/138155269

**Comment by ScarletTanager** [comment]
@sreetummidi - why is the Issue closed now?  Has this actually been resolved?  Neither of the related tracker items:

https://www.pivotaltracker.com/n/projects/997278/stories/137028417
https://www.pivotaltracker.com/n/projects/997278/stories/138155269

appear to have been started, so confused why this Issue was closed?

**Comment by fhanik** [comment]
@ScarletTanager Yes, issue has been resolved. And released.
https://github.com/cloudfoundry/uaa-release/releases/tag/v27
