### ISSUE TITLE
Google as IdP not working

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/uaa#515]
I have configured the backend `oauth` settings as documented here: https://github.com/cloudfoundry/uaa/blob/master/docs/google-oidc-provider.md. This configuration is not working and failing with:

`There was an error when authenticating against the external identity provider: Invalid issuer (https://accounts.google.com) for token did not match expected: https://www.googleapis.com/oauth2/v4/token`

I have tried it with a different OIDC provider and got the same result. Is the comparison here the correct: 

https://github.com/cloudfoundry/uaa/blob/5e2f5adb0d14312498a80a2b1e0b2e09f2292a11/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManager.java#L308

Would be happy about any hints. :-)

**Comment by fhanik** [comment]
Change `issuer: https://accounts.google.com` to `issuer: https://accounts.google.com/oauth2/v4/token`

Looks like a token was issued and it failed validation on that part.

**Comment by fhanik** [comment]
Please report back, and if that works, we will use this story to address the documentation

**Comment by jhiemer** [comment]
@fhanik I checked that as well: 

`There was an error when authenticating against the external identity provider: Invalid issuer (https://accounts.google.com) for token did not match expected: https://www.googleapis.com/oauth2/v4/token`

**Comment by jhiemer** [comment]
@fhanik any idea, what is causing the error?
