### ISSUE TITLE
409 Conflict error when deleting groups

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#516]
We've been getting a 409 error when trying to delete a group in the following scenario:

Create two groups, `foo` and `bar`
Make `bar` a member of `foo`
Delete `foo` and `bar` concurrently (in our case we do this when cleaning up our test environment, with a total of ~8-10 groups)

This creates a potential race condition:
`uaa` sees that `bar` is a member of `foo`
`uaa` also receives a request to delete `bar`
`uaa` deletes `bar`
`uaa` attempts to remove `bar` from `foo`
`uaa` throws an exception because it wasn't able to remove the expected number of members from `foo`

The exception appears to be thrown by:
https://github.com/cloudfoundry/uaa/blob/6966bd048e62901bd7153768ce50d0278fc44ade/server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManager.java#L390-L390

and bubbles up to give a `409` at:
https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimGroupEndpoints.java#L419

**Comment by sreetummidi** [comment]
@twoseat This is expected behavior from the the API  as we can't guarantee the order on which concurrent operations are performed
