### ISSUE TITLE
UAA Login Page does not appear within a frame

### ISSUE THREAD

**Issue by abhikco** [cloudfoundry/uaa#526]
While trying to embed an application in an iframe, I find that the UAA login page cannot be hosted within a frame due to an X-Frame-Options header being sent with the value DENY. 
I understand the requirement to prevent clickjacking- however, this seems way too restrictive for certain integration scenarios. 

So, this brings me to two questions:
1. Any immediate way to get around this?
2. Are you already looking at a long-term solution for this? [Note: I did find this epic: [https://www.pivotaltracker.com/n/projects/997278/epics/2869233](https://www.pivotaltracker.com/n/projects/997278/epics/2869233) but I'm not sure if this is related]

**Comment by abhikco** [comment]
Any update on this?

**Comment by sreetummidi** [comment]
@abhikco We don't plan on allowing UAA Login to be embedded within an iframe from a security perspective. Please have a look at the UAA JavaScript SDK . This allows for detection of auth session without the need to re-direct the user. https://github.com/cloudfoundry/uaa-singular

**Comment by naresh33** [comment]
@sreetummidi
 is there any other solution for allowing UAA Login to be embedded within an iframe?

**Comment by jhamon** [comment]
@abh1kg Can you elaborate on the integration scenario you are trying to achieve that you think requires an iframe? There are ways to have the user redirected back to your app after login, if that is your concern.
