### ISSUE TITLE
UAA throws response as FAILURE

### ISSUE THREAD

**Issue by MeiyappanKannappa** [cloudfoundry/uaa#527]
Hi I tried deploying the UAA app in Cloud Foundary. And it is successfully deployed, but when i try to access the deployed UAA URL http://meiuaa.cfapps.io it gives me response as FAILURE. Could someone help me . Many thanks!!!

**Comment by sreetummidi** [comment]
Please attach the logs and UAA YML configuration if you are still seeing the error
