### ISSUE TITLE
Token signing keys are still improperly encoded

### ISSUE THREAD

**Issue by jpduffield** [cloudfoundry/uaa#530]
This is a followup to #424. 

The modulus "n" value in the signing key returned by the token_key URI contains padding that should not be present. This results in the key being rejected by JWK libraries that conform to [RFC7517](https://tools.ietf.org/html/rfc7517). 

RFC7517 specifies that the modulus and exponent of the signing key should be Base64url encoded as defined in [RFC7515](https://tools.ietf.org/html/rfc7515), section 2 of which states (emphasis mine): 

>    Base64url Encoding
      Base64 encoding using the URL- and filename-safe character set
      defined in Section 5 of RFC 4648 [RFC4648], **with all trailing '='
      characters omitted** (as permitted by Section 3.2) and without the
      inclusion of any line breaks, whitespace, or other additional
      characters.  Note that the base64url encoding of the empty octet
      sequence is the empty string.  (See Appendix C for notes on
      implementing base64url encoding without padding.)

**Comment by jpduffield** [comment]
@fhanik 
I'm working with a hosted instance, so I'm not sure of the exact version. It contains the fix for #424 (which introduced the encoding change in the lines you highlighted), so must be 3.7 or newer. 

The encoded "n" value in the key returned by `https://login.identity.cf-app.com/token_keys` happens to be a multiple of 4 bytes already, so you can't tell from that how padding is handled. 

Digging into the code, it looks like the behaviour depends on whether Spring's Base64Utils delegates to org.apache.commons.codec.binary.Base64 (which does strip the padding) or java.util.Base64 (which doesn't by default). 
The latest Base64Utils fixes this inconsistency, but does so by dropping the Apache option, so won't help here.

**Comment by fhanik** [comment]
@jpduffield Thanks John for the clarification. That makes sense. All our stuff runs on Java 8, so I would imagine it picks the Java 8 Base64 class. 

I believe we may simplify the encoding line to do:

    java.util.Base64.getUrlEncoder().withoutPadding()

Let me create a test case that produces the padding, and then I can fix this. Thanks for working with me on this.

**Comment by fhanik** [comment]
Added commit 

https://github.com/cloudfoundry/uaa/commit/8e3d5ea8ed79531839f6e946902567c36292bb9b

**Comment by fhanik** [comment]
Completed via https://github.com/cloudfoundry/uaa/commit/4abb3bba880762863597ee8e7aa490eb10681148
