### ISSUE TITLE
Direct Token Exchange with OIDC Provider

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/uaa#532]
Hi,
this is a feature request, which I have discussed with @sreetummidi in Slack. We currently face the challenge that we have on central OIDC Provider for an infrastructure. This OIDC Provider is independent of the CF installation and issues JWT, which shall be usable at different endpoints. E.g. the token should be usable at an OpenStack installation and CF at the same time.

The current behaviour in context of OS is as follows:

- User logs in at the central IdP
- User gets a token from the IdP and we use this token to authenticate against Keystone with Authorization: Bearer iojrevijoBlaBla
- Token is verified against the IdP and an OS Scoped Token is provided
- With this token we can do REST API Calls and gather information of the OS APIs
- It would be nice to have the same workflow for CF as well

**Comment by meshjoerg** [comment]
This would really be a great feature as it is very important for a seamless integration of user identities.

**Comment by sreetummidi** [comment]
We will be prioritizing it soon

**Comment by JohannesRudolph** [comment]
Agree, would love to see this fixed!

**Comment by strehle** [comment]
Hi @sreetummidi 

is this related to #260 and #364 ? because I wanted ask if there are already contributions in your pipeline and do you know people working on it? otherwise I would start on such a contribution.

regards,
-markus

**Comment by JohannesRudolph** [comment]
https://github.com/cloudfoundry/uaa/issues/533 appears to be related as well. 
Together with https://github.com/cloudfoundry/uaa/issues/552 this would make for a really nice push in UAAs and CFs capabiliities for SSO scenarios.

**Comment by jhiemer** [comment]
@sreetummidi any updates on plans and timelines?

**Comment by sanjeevchopra** [comment]
@sreetummidi  - This is a good use case for implementing https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-07 .

**Comment by sreetummidi** [comment]
@jhiemer We are working on this as part of https://www.pivotaltracker.com/story/show/145414125
This will be delivered with the upcoming feature release of UAA. Most likely 4.4.0

**Comment by jhiemer** [comment]
@sreetummidi I checked out the develop branch and tested it. It is not yet integrated into the application, but the token exchange worked.
