### ISSUE TITLE
UAA as IdP needs to support IdP initiated Web SSO with SAML in addition to SP initiated

### ISSUE THREAD

**Issue by chioleong** [cloudfoundry/uaa#533]
UAA as IdP today only SP initiated SSO with SAML is supported. Applications may need to use the IdP initiated model as users may already have their own token and should be able to make request for a SAML assertion directly from IdP instead of hitting the SP endpoint and redirected back to IdP for authentication again.

**Comment by sreetummidi** [comment]
We support SAML Bearer token flow to allow for token generation based on incoming SAML Assertion.  Please find the details here : https://docs.cloudfoundry.org/api/uaa/index.html#saml2-bearer-grant
