### ISSUE TITLE
request revokable token using client with too many scopes

### ISSUE THREAD

**Issue by 6palace** [cloudfoundry/uaa#535]
getting a revokable token through oauth/token fails with 500 error and prints sql query when a client has scopes with total comma-separated length over 1000 chars. Caused by psql exception when storing revokable token throwing a DataIntegrityViolationException.

Steps to reproduce:
1. create a client with a LOT of scopes/authorities
2. post to oauth/token with client_credentials using client, without specifying scopes and with token_format revokable or opaque.

uncaught exception specifically being thrown in JdbcRevokableTokenProvisioning.create(), the returned 500 is as follows:

{
  "error": "server_error",
  "error_description": "PreparedStatementCallback; SQL [INSERT INTO revocable_tokens (token_id,client_id,user_id,format,response_type,issued_at,expires_at,scope,data,identity_zone_id) VALUES (?,?,?,?,?,?,?,?,?,?)]; data exception: string data, right truncation;  table: REVOCABLE_TOKENS column: SCOPE; nested exception is java.sql.SQLDataException: data exception: string data, right truncation;  table: REVOCABLE_TOKENS column: SCOPE"
}

**Comment by fhanik** [comment]
Fixed via

https://github.com/cloudfoundry/uaa/commit/5b3613b3d62b4904ef6c6ba560e1cadc33c967f9
