### ISSUE TITLE
Minimal UAA setup for OAuth2

### ISSUE THREAD

**Issue by MitchK** [cloudfoundry/uaa#538]
I am trying to deploy UAA in a non-Cloud-Foundry environment. I'm using Docker and deploy UAA as a ```.war``` to a Tomcat. This is my Dockerfile:

```
FROM ubuntu


RUN apt-get update; apt-get install -y git wget tar openjdk-8-jdk


# Download and build UAA
ENV UAA_VERSION=3.10.0
ENV UAA_CONFIG_PATH /uaa
RUN git clone https://github.com/cloudfoundry/uaa.git $UAA_CONFIG_PATH
WORKDIR $UAA_CONFIG_PATH
RUN git checkout $UAA_VERSION
RUN ./gradlew build -x test

# Download Tomcat
ENV TOMCAT_VERSION=8.0.41
ENV CATALINA_HOME /tomcat

RUN wget -q https://archive.apache.org/dist/tomcat/tomcat-8/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
RUN wget -qO- https://archive.apache.org/dist/tomcat/tomcat-8/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz.md5 | md5sum -c -
RUN tar zxf apache-tomcat-$TOMCAT_VERSION.tar.gz
RUN rm apache-tomcat-$TOMCAT_VERSION.tar.gz
RUN mkdir $CATALINA_HOME
RUN mv apache-tomcat-$TOMCAT_VERSION/* $CATALINA_HOME
RUN rm -rf $CATALINA_HOME/webapps/*

# Deploy UAA to tomcat
RUN cp $UAA_CONFIG_PATH/uaa/build/libs/cloudfoundry-identity-uaa-$UAA_VERSION.war /tomcat/webapps/ROOT.war

# Add config
ADD uaa.yml $UAA_CONFIG_PATH/uaa.yml

EXPOSE 8080

CMD $CATALINA_HOME/bin/catalina.sh run
```

If I run the container, I get this error:
```
...
caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'login.serviceProviderKey' in string value "${login.serviceProviderKey}"
```

Obviously, I have not set a configuration key. My ```uaa.yml``` is currently just an empty file. Unfortunately, I could not find any hint in the documentation on what parameters are required. Again, I just want a minimal OAuth flow (perhaps it's fine with hardcoded credentials now) to be working. 

Thanks

**Comment by MitchK** [comment]
If I just run ```./gradlew run``` locally, everything seems to work. What's the difference?

**Comment by fhanik** [comment]
https://github.com/cloudfoundry/uaa/tree/develop#deploy-to-cloud-foundry

First paragraph has a link to the required values. That's should be all you need.
If you generate a manifest (see gradlew manifest) in the same section, it should give you the parameters that you need, including UAA_URL and LOGIN_URL

**Comment by MitchK** [comment]
Thanks , that helped!

**Comment by harpratap** [comment]
@MitchK Can you list out the steps that you performed to solve this? I don't understand what manifest is doing here. Does it generate a sample uaa.yml for us?
