### ISSUE TITLE
register Oauth2 client with UAA CF v247

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry/uaa#541]
My set up is below to make the "simple" client app to be Oauth2-aware.  The test failed because
I was not prompted to approve for the scope.  

1. register a Oauth2 client with UAA CF v247 - registration data is below
  foo-client-id
    scope: cloud_controller_service_permissions.read openid
    resource_ids: none
    authorized_grant_types: refresh_token authorization_code
    redirect_uri: http://localhost:8080
    autoapprove:
    authorities: uaa.none
    name: foo-client-id
    lastmodified: 1487292160153
2. make the client app Oauth2-aware in application.yml
security:
  oauth2:
    client:
      clientId: foo-client-id
      clientSecret: fooclientsecret
      accessTokenUri: https://uaa.abc.com
      userAuthorizationUri: https://login.abc.com
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
3. application code is the simple project
    https://github.com/spring-guides/tut-spring-boot-oauth2/tree/master/simple
4. run the simple application at port 8080 (this is spring-boot app)
5. browser = http://localhost:8080
6. get redirect to authenticate with login.abc.com
7. enter user/pass to authenticate
8. I expect to see the screen where I can approve the client app for the scope it asks, but there is no
   such screen.

**Comment by sreetummidi** [comment]
How did you register the client? UAAC or API. I don't see anything particularly wrong with the set up. Best would be jump on cloud foundry UAA slack channel so that we can have an interactive session.

**Comment by betht1220** [comment]
sreetummidi - Sorry for being late about half of a year haha.  I actually found out that I did not set up SSL correctly (after debugging the app).  It was fixed and worked well.  Again, so sorry for the late reply and thank you so much for your note.
