### ISSUE TITLE
Query users by lastLogonTime does not work

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/uaa#542]
When I issue a query for users by the newly introduced attribute lastLogonTime (e.g. `uaac curl /Users?filter=lastLogonTime%20ge%201487342801125`, I get the following error response:
```
{"error_description":"Invalid filter expression: [lastLogonTime ge 1487342801125] [created]","error":"scim","message":"Invalid filter expression: [lastLogonTime ge 1487342801125] [created]"}
```
I also noticed that lastLogonTime is not mentioned on https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#user-column-names, so I guess it's a known limitation. Are there any plans to support additional filters?

**Comment by fhanik** [comment]
try to use `last_logon_success_time ge 1487342801125`

**Comment by philippthun** [comment]
Hi @fhanik - that's working! Thanks a lot.
