### ISSUE TITLE
Integrate Custom Authentication Provider

### ISSUE THREAD

**Issue by sankarbalu** [cloudfoundry/uaa#544]
I have an existing web service from a legacy system that is used for authentication and it also provides some additional user based information as part of the response. 

I would like to know the following
* Can UAA be configured to use an existing authentication service ?
* Does UAA provide options to capture this additional information returned in the response and return the additional information through /userinfo endpoint or even encode it within the JWT?

**Comment by sreetummidi** [comment]
UAA supports only LDAP/SAML/OIDC based IDPs.
The best is to create a SHIM layer in-front of the legacy system and enable OIDC IDP.

Yes, UAA supports /userinfo and user claims in JWT for all supported IDPs
