### ISSUE TITLE
uaac client update does not change redirect_uri

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/uaa#551]
Hi,

we have tried to update the redirect_uri of an existing UAA client with
```
uaac client update <id> --redirect_uri https://<different url>
```
However, the URL did not change. We had to delete and re-create the client.

Unfortunately, we could not reproduce the problem with newly created test clients. Does anyone have an idea why the redirect URI has not changed? We are using UAA client 3.4.0 and CF 252 with UAA v25.

Thanks and Best Regards,

  Jochen.

**Comment by YDD9** [comment]
I'm trying to update clientqa with 2 redirect_uri, it doesn't work. Updating with 1 redirect_uri works.
```
uaac client update clientqa --redirect_uri http://localhost:3000/callback
```

```
uaac client update clientqa --redirect_uri [http://localhost:3000/callback, https://qa-ui.run.aws-usw02-pr.ice.predix.io/callback]
```


Appreciate your help

**Comment by rboykin** [comment]
@YDD9 Try 
uaac client update clientqa --redirect_uri "http://localhost:3000/callback, https://qa-ui.run.aws-usw02-pr.ice.predix.io/callback"
