### ISSUE TITLE
Add functionality people who must use SSO with CF

### ISSUE THREAD

**Issue by wslack** [cloudfoundry/uaa#552]
#### Issue
Currently, CF's login is primarily built to support logins without SSO. For example, the default error message [doesn't mention the `--sso` flag](https://github.com/cloudfoundry/cli/blob/master/cf/api/authentication/authentication.go#L225). However, no one will ever log into [our instance of CF](https://cloud.gov) with a username/password (2FA is mandatory for our gov't compliance).

#### Proposed Resolution
We would like to be able to change the default behavior in [our deployment of CF](https:///cloud.gov) so that `--sso` is assumed in the login workflow.

#### Possible Implementations
For example, the API server could have a 'default_authenication_method' that can be set to SSO, which would make non-SSO require a different flag. Alternatively, you could suppress the `username` and `password` fields and allow a `passcode` to be the only way of auth without an --sso flag.

Thank you for the consideration.

#### References
https://github.com/cloudfoundry/cli/issues/858#issuecomment-229264018
https://github.com/cloudfoundry/cloud_controller_ng/issues/620

**Comment by cppforlife** [comment]
i think it would be nicer to do what bosh cli v2 does and just show uaa prompts without any flags. then its up to uaa configuration to ask whatever it needs.

**Comment by dkoper** [comment]
@wslack I believe that if you configure your UAA Login server to return only a "passcode" prompt and no "username" and "password" prompts, the `cf login` should behave as `cf login --sso`.
If not, then we (cf CLI team) should investigate this as a bug.

**Comment by mogul** [comment]
We could do that, but we actually do want UAA configured to support username/password login for "service" accounts: Auto-brokered account credentials intended to be used for automated deployment in a particular space, but that we don't ever expect a human to use to log in. 

Is there any way to make the default configurable from the server side, and add a flag to the CLI to explicitly opt into username/password, just as the user can opt into --sso?

**Comment by mogul** [comment]
Or, if we're missing some obvious way to issue robot-oriented credentials that work with the various CI/CD options out there, we'd love to hear about it!

**Comment by dkoper** [comment]
@mogul Configuring the UAA Login server to return only a "passcode" prompt and no "username" and "password" prompts does not prevent `cf auth` and `cf login -u -p` to authenticate your service accounts with a username and password. (If they're for automated, scripted deployment we recommend `cf auth`).
