### ISSUE TITLE
Auth code grant type loses the initial OAuth context once the csrf token expires

### ISSUE THREAD

**Issue by bondugula** [cloudfoundry/uaa#558]
When the Authorization code grant type flow is initiated, if we leave the UAA login page open until the CSRF token expires, the original OAuth context is completely lost and the user finds themselves staring at a login page with the presumption that if they try again and login in successfully they will login in to the application that redirected them. Unfortunately, that's not what happens. When UAA loses the original OAuth context, the subsequent login page is setup as a login into UAA itself.

The current behavior is not a graceful way to fail on CSRF token expiration for logins that originate from an OAuth flow. A better UX would be to redirect the user back to the application that initiated the OAuth authorization code grant request with an OAuth error.

This was discussed during the issue https://github.com/cloudfoundry/uaa/issues/445 . But I guess it got lost in the middle.

**Comment by fhanik** [comment]
@bondugula Thank you for the report. We have to question the root cause on the failure here. The csrf token (cookie) is valid for 30 days. If the failure happens before then, it is probably another cause.

Can you provide the steps to reproduce.
