### ISSUE TITLE
Empty `redirect_uri` and not working `redirectUrl` parameter when using OIDC provider

### ISSUE THREAD

**Issue by paroxp** [cloudfoundry/uaa#562]
## Issue

UAA does not take `login.oauth.providers.<alias>.redirectUrl` configuration into consideration as [it is supposed to](https://github.com/cloudfoundry/uaa/blob/master/docs/google-oidc-provider.md).

When `redirectUrl` is set to `https://login.example.com/uaa` the [`redirect_uri`](https://github.com/cloudfoundry/uaa/blob/3.9.3/model/src/main/java/org/cloudfoundry/identity/uaa/provider/AbstractXOAuthIdentityProviderDefinition.java#L164) query parameter in the URL for our external provider (Google) is `https://login/callback/google`. The domain part is blank, as if an empty string was passed to the [getCompleteAuthorizationURI method](https://github.com/cloudfoundry/uaa/blob/3.9.3/server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java#L441).

## Expected Result

Google would require you to log in and then redirect back to the CF UAA. The redirect URI passed to Google should be `https://login.example.com/login/callback/google`.

## Actual Result

![](https://i.imgur.com/T2hwpvu.png)

## Versions

UAA releases/3.9.3 `565bfebb000034c84d7853d4f9d387a8fc84c4bb`
UAA releases/3.12.0 `011e1b86340db0b9e098e7d1eeaf4b0af8797360 `

**Comment by jm4rc05** [comment]
[Here](https://docs.cloudfoundry.org/api/uaa/#oauth-oidc) the API doesn't have this key! 

Possibly the `http://localhost:8080/uaa` came from [other](uaa/uaa/src/main/resources/uaa.yml) place!

**Comment by henrytk** [comment]
@jm4rc05 how does an external provider, such as Google, know where to redirect the user to after authentication?

**Comment by bleach** [comment]
This is a bug in [GetBaseURL](https://github.com/cloudfoundry/uaa/blob/4e652a6b5279ea99077fcfc46c5b8842267806c8/server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java#L103) 

When it's called from https://login.example.com/login, `getRequestPath == "/login"` so it returns `https:/`.

**Comment by bleach** [comment]
I have a [commit that I think fixes this](https://github.com/bleach/uaa/commit/1851d01a5f5b850074a0d50161d88b19ed977cd1) in a branch. I've not been able to test this when deployed in a CF environment though.

**Comment by fhanik** [comment]
@bleach Thanks, fix the white spaces in your commit (there are tabs), and submit a PR, we can merge it right away.

**Comment by bleach** [comment]
I opened #575 to fix this
