### ISSUE TITLE
Cookie Saved-Account-XXX is not encoded.

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#563]
Hi, 
we tested UAA on tomcat 8.5x and there is an exception, because of a cookie character validation.
In detail the problem we see is in 
https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandler.java#L63
where Cookie "Saved-Account- + uaaPrincipal.getId()" is not encoded.

In same class there is an example of correct cookie encoding.
https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandler.java#L77

Therefore please correct it in
https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/login/AccountSavingAuthenticationSuccessHandler.java#L63

and on
https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java#L249
where cookie is read .

thanks in advance,
-markus

**Comment by fhanik** [comment]
https://github.com/cloudfoundry/uaa/commit/bf922787a1a3799691fa1c46fb72e7e2cccf862f
