### ISSUE TITLE
Using Google as Identity Provider causes org.springframework.security.jwt.crypto.sign.InvalidSignatureException

### ISSUE THREAD

**Issue by jm4rc05** [cloudfoundry/uaa#565]
I followed the instructions [here](https://github.com/cloudfoundry/uaa/blob/develop/docs/google-oidc-provider.md) but got the error above. Had to add this to my custom yml configuration:

```yml
                tokenKeyUrl: https://www.googleapis.com/oauth2/v2/certs
```

If the solution has any merit I think the document should be updated.

Tks in advance.

**Comment by sreetummidi** [comment]
@tnwang Is this the case. Does the doc need to be updated?

**Comment by tnwang** [comment]
We should update the document so that people always use the latest information from `https://accounts.google.com/.well-known/openid-configuration` - it is mentioned but only for two fields. It should always be referenced for all values used, or configured as the discovery URL.

**Comment by tnwang** [comment]
Closing this story as the March 27th merge had actually provided the fix in the specified document.
