### ISSUE TITLE
query users by group id

### ISSUE THREAD

**Issue by appagg** [cloudfoundry/uaa#571]
the user api doesn't support loading a list user for a group, can we have filtering api like:

/Users?filter=groups.value eq '6ee31d5b-eb44-4091-8c5d-754b134c891b'

**Comment by fhanik** [comment]
Isn't this what you are looking for?

https://docs.cloudfoundry.org/api/uaa/#list-members

**Comment by appagg** [comment]
tried the group members api with returnEntities true, but it still returns the simple entity like:
[
  {
    "origin": "uaa",
    "type": "USER",
    "value": "006adf58-8bc0-4145-9e46-07bec22674bf"
  },...]

it doesn't seem to be supported by predix's uaa service?

**Comment by appagg** [comment]
also, if I want to query users for multiple groups, the list-members api probably won't help especially if I also want paging/filtering/sorting supports.

**Comment by sreetummidi** [comment]
We don't plan on adding support beyond list members. PRs are welcome
