### ISSUE TITLE
Identity-zones endpoint always returns default CORS configuration for the default zone (uaa)

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#574]
The identity-zones endpoint always returns default CORS configuration for the default zone (uaa), also in cases when the CORS configuration has been modified in uaa.yml 

Note: The CORS filter is actually working with the configuration provided in uaa.yml

**Comment by sreetummidi** [comment]
Default Zone cors is managed via manifest only.  No plans to address this issue.
Other zones can be managed via API and state is persisted
