### ISSUE TITLE
Base branch in github not develop as specified in README.md

### ISSUE THREAD

**Issue by bleach** [cloudfoundry/uaa#576]
I recently submitted a PR against `master` because that's the base branch in the settings on github.com.

In the README it says:
> Always submit pull requests to the "develop" branch.

When I rebased against `develop` as specified  I had to spend time resolving conflicts. It would be easier to contribute if the base branch in the github settings for this repo was `develop`.

**Comment by sreetummidi** [comment]
This is the standard followed by other repos under cloud foundry like cf-release. We don't have plans at this time to change the default.
