### ISSUE TITLE
Previous logon time in ID token seems to be in milli seconds; whereas other dates are given in seconds

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#578]
Using CF UA v3.13.0 the claim previous_logon_time in the ID token seems to be in milli seconds (sample: previous_logon_time": 1490548889502) whereas iat, exp, and auth_time (sample: "iat": 1490615210) are provided in seconds. Is there a reason for using separate date formats / time units? It would be more convient, if all timestamps could be provided in the same format.

**Comment by sreetummidi** [comment]
iat and auth_time in seconds is governed by the OpenID spec. Coming to previous login time, its not spec driven and we decided to use milliseconds with Unix epoch to make it time zone agnostic. We have to deal with showing this information in the UAA UI and its easier to do the conversions.
