### ISSUE TITLE
Unable to map external group from uaa.yml if external group contains a space character

### ISSUE THREAD

**Issue by Freakin** [cloudfoundry/uaa#585]
uaa.yml contains the following
```
scim:
  external_groups:
  - bosh.admin|cn=admins,ou=user accounts,dc=mydomain,dc=com
  - scim.read|cn=admins,ou=user accounts,dc=mydomain,dc=com
```
The external group is being split on space, with group mappings being inserted by UAA as
```
$ uaac group mappings
resources
    ldap:
    -
      bosh.admin: cn=admins,ou=user
    -
      bosh.admin: accounts,dc=mydomain,dc=com
    -
      scim.read: cn=admins,ou=user
    -
      scim.read: accounts,dc=mydomain,dc=com
```

I have tried the following in uaa.yml

```- bosh.admin|'cn=admins,ou=user accounts,dc=mydomain,dc=com'```
```- bosh.admin|"cn=admins,ou=user accounts,dc=mydomain,dc=com"```
```- bosh.admin|cn=admins,ou=user\ accounts,dc=mydomain,dc=com```
```- bosh.admin|cn=admins,ou=user\saccounts,dc=mydomain,dc=com```
```- bosh.admin|cn=admins,ou=user%20accounts,dc=mydomain,dc=com```
```- bosh.admin|cn=admins,ou=user&nbsp;accounts,dc=mydomain,dc=com```
```- bosh.admin|cn=admins,ou=user\u0020accounts,dc=mydomain,dc=com```

**Comment by fhanik** [comment]
@Freakin 

The pipe delimited format is deprecated.

The new format looks like this
https://github.com/cloudfoundry/uaa/blob/4d5a3d10e21ca68654308ef78f944600710fc102/uaa/src/test/resources/test/bootstrap/all-properties-set.yml#L513-L524

We've added test cases to validate names with spaces. We will not be fixing the old format.
