### ISSUE TITLE
Is it possible to run UAA server in both potsgresql and LDAP profile?

### ISSUE THREAD

**Issue by ozthemagician** [cloudfoundry/uaa#586]
We have **enterprise users** that are authenticated via LDAP for internal services and **website users** that are authenticated via UAA postgresql database for website use. Can we support both authentication mechanism using just one UAA server? Or Do we have to run two separate UAA instances for postgresql and LDAP?

**Comment by sreetummidi** [comment]
No, UAA supports both auth mechanisms being active at the same time.
