### ISSUE TITLE
Disable self-service account creation

### ISSUE THREAD

**Issue by dcarley** [cloudfoundry/uaa#588]
We'd like the ability to disable self-service account creation through the `/create_account` and `/create_account.do` endpoints. We only want existing users to be able to create or invite accounts because controlling the number of people that have authenticated accounts reduces the attack surface of the UAA and Cloud Controller APIs.

This isn't possible with `login.self_service_links_enabled` because the links are hidden from the homepage but the endpoints remain active. I feel like it might have previously been possible with `login.signups_enabled`, but my memory and ability to read the commits is failing me.

Currently the only way we can prevent this is by not providing valid `login.smtp` details so that UAA can't send the emails and the user gets an error, but this seems very fragile. The same is also true of the  `/reset_password` and `/reset_password.do` endpoints.

It would be nice to have more explicit options for these. Is this something you can add or would be willing to accept a patch for?

**Comment by dcarley** [comment]
> Currently the only way we can prevent this is by not providing valid login.smtp details so that UAA can't send the emails and the user gets an error, but this seems very fragile.

We've realised that this isn't actually very good protection because a `verified: false` user still gets created in UAA.

**Comment by sreetummidi** [comment]
@dcarley We will be addressing this UAA 4.0 which the team is actively working on. The story is : https://www.pivotaltracker.com/story/show/141508943

**Comment by dcarley** [comment]
Hi @sreetummidi. I'm not able to comment on that Pivotal story and UAA doesn't have a [cf-tm-bot](https://github.com/cf-tm-bot) thing setup.

I'm unsure about the implementation in that story. We would like to use the reset password functionality without enabling the create account functionality.
