### ISSUE TITLE
check_token end point returnd 400 bad request for token with grant_type = authorization_code

### ISSUE THREAD

**Issue by AmitTeli** [cloudfoundry/uaa#592]
Hi,

Whenever I try to use the check_token end point to validate token obtained with grant_type = authorization_code, it returns "400 Bad request".
The token is valid. (As it was generated just a second back and decodes correctly)

The end point works fine when grant_type=password.

Or is there any additional setting needed for authorization_code tokens which is not documented?

Thenks!
Amit Teli

**Comment by sreetummidi** [comment]
Please follow the docs here : https://docs.cloudfoundry.org/api/uaa/index.html#check-token
