### ISSUE TITLE
/oauth/token end point returns 401 unauthorized for grant_type=password if credentials are incorrect

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/uaa#599]
The endpoint /oauth/token returns 401 unauthorized for grant_type=password if the provided resource owner credentials are incorrect:
HTTP 401 - {"error":"unauthorized","error_description":"Name or password mismatch"}

Sample request from RFC6749:
  POST /token HTTP/1.1
  Host: server.example.com
  Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
  Content-Type: application/x-www-form-urlencoded

  grant_type=password&username=johndoe&password=A3ddj3w

In contrast to the observed behavior, RFC6749 mandates a response status code 400 invalid_grant, see https://tools.ietf.org/html/rfc6749#page-45.

Because the OAuth grant is incorrect (and not the client credentials), I would have expected something like:
HTTP 400 - {"error":"invalid_grant","error_description":"Name or password mismatch"}

**Comment by sreetummidi** [comment]
@torsten-sap I understand the the spec is warranting 400 bad request but from a error usability perspective, invalid grant is misleading.  We decided to side with usability rather than the spec in this case.
