### ISSUE TITLE
Implicit flow: incorrect redirect URL (query params)

### ISSUE THREAD

**Issue by maust** [cloudfoundry/uaa#600]
When using the implicit flow (in the browser) by redirecting the user to: 

http://localhost:7001/uaa/oauth/authorize?response_type=token&client_id=XXX&redirect_uri=http%3A%2F%2Flocalhost%3A8100%2F%23%2Flogin

The user gets redirected back after successful login to:

http://localhost:8100/#/login&token_type=bearer&access_token=eyJhbGci...

As the query parameters are added with an & instead of ? the authenticated application cannot get the query parameters correctly. Shouldn't the first query param be appended with an ? and only the following params with &

So a correct URL would be:

http://localhost:8100/#/login?token_type=bearer&access_token=eyJhbGci...

**Comment by fhanik** [comment]
Anything after the # are no longer query parameters. It is just fragment data. ie, a string of non deterministic characters. 

I'm reviewing the PR right now, https://github.com/cloudfoundry/uaa/pull/601

Can you elaborate what you mean by _the authenticated application cannot get the query parameters correctly_. Is it a server side application?

On the implicit flow, server side applications are not receiving the fragment data. It is there for the user-agent client, like javascript, to parse out.

**Comment by fhanik** [comment]
OAuth 2 Spec shows an example as 

    HTTP/1.1 302 Found
    Location: http://example.com/cb#access_token=2YotnFZFEjr1zCsicMWpAA
               &state=xyz&token_type=example&expires_in=3600

No `?` is needed in the fragment. Parameters in the fragment are delimited by `&`
We believe the UAA to be compliant with the spec.

Please reopen if you feel we have made this decision in error.

Reference
https://tools.ietf.org/html/rfc6749#section-4.2.2
