### ISSUE TITLE
Doc: Links to common operations are not permanent

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/uaa#604]
Links in the doc to common operations such as create, delete, etc. have a numeric suffix to avoid clashes (e.g. https://docs.cloudfoundry.org/api/uaa/#create64). This number increments, making it essentially impossible to retrieve the desired page over time. It should be possible, and would be a great improvement, to have fixed links for each operation.

**Comment by sreetummidi** [comment]
This has been addressed
