### ISSUE TITLE
FAILURE response when accessing url

### ISSUE THREAD

**Issue by sachgit30** [cloudfoundry/uaa#607]
Hi,
I followed instructions at https://docs.cloudfoundry.org/concepts/architecture/uaa.html#cf to deploy UAA onto Bluemix account. 

UAA successfully deployed with Route URL (uaa-sachin.mybluemix.net) but when accessed in browser displays 'FAILURE' as response, please help.

**Comment by sreetummidi** [comment]
@sachgit30 Please provide the UAA Log if you are still seeing errors

**Comment by 3d3n** [comment]
Hi @sreetummidi , I have a similar problem, after deploying UAA onto Bluemix account.

UAA successfully deployed  but when accessed in browser displays 'FAILURE' as response, please help.
[uaa_bluemix log.txt](https://github.com/cloudfoundry/uaa/files/2210357/uaa_bluemix.log.txt)
