### ISSUE TITLE
Update approvals in profile deletes approvals for other client ids

### ISSUE THREAD

**Issue by gwimmel** [cloudfoundry/uaa#611]
Via the /profile view, one gets a page with a form for each client where one can update the assigned approvals. On my installation, if a user has assigned approvals to multiple clients, pressing the update button correctly updates the approvals for the respective client, but also unexpectedly deletes the approvals for all other clients.

I think this is due to
https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/account/ProfileController.java#L99-L106
This iterates over all approvals, instead of only over the approvals with the respective client id.

**Comment by sreetummidi** [comment]
Being fixed with UAA 4.5.0
