### ISSUE TITLE
Map Google User to Cloudfoundry User

### ISSUE THREAD

**Issue by sdoxsee** [cloudfoundry/uaa#613]
I've seen the documentation for adding google as a provider to UAA here: https://github.com/cloudfoundry/uaa/blob/master/docs/google-oidc-provider.md

I tried it and it seems to create a user for me rather than giving me the option to link/map it to an existing UAA account (as an alternative way of signing in) Is this easily possible and is there documentation for that process. Thanks!

**Comment by sreetummidi** [comment]
@sdoxsee Anytime you would like to link existing user accounts to a different provider, you need to perform a database migration where in you set the origin field on each user to be linked to google providers origin aka the google provider alias.
