### ISSUE TITLE
Group membership table authority field causes excessive update calls

### ISSUE THREAD

**Issue by 6palace** [cloudfoundry/uaa#614]
when modifying members of a group, members that are not added/deleted are still triggering a sql update. This call nominally updates the authority field, but this column is not currently being used. Unless we have plans to use 'authorities', we should disable these updates.

Code in question: https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimGroupMembershipManager.java#L352-L357

These updates are wasted sql calls. If the authorities column will be used in future, we should check that authorities of each member have been modified. Otherwise, deleting the entire block will increase performance and have no negative effect.

**Comment by bsekar** [comment]
@6palace I believe this has been addressed by #638
