### ISSUE TITLE
Bootstrap accepts invalid client parameters

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/uaa#616]
Clients defined in `uaa.yml` with certain invalid parameters are accepted, but creating a client with the same parameters via `uaac` fails (as expected). For example, it's possible to load a client from yaml with an invalid `redirect_uri` of `https://**`, but not from `uaac`, leading to confusing situations like this:

```
± uaac client get uaaproxy
  ...
  redirect_uri: https://**
  ...

± uaac client update uaaproxy --redirect_uri 'https://**'
error response:
{
  "error": "invalid_client",
  "error_description": "One of the redirect_uri is invalid: https://**"
}
```

To fix, the code that loads clients from `uaa.yml` should apply the same validation used elsewhere.

h/t @cnelson

**Comment by sreetummidi** [comment]
@jmcarp We added this validation in the UAA Bosh Release because it provides a framework for validation and not applying the spec changes to UAA.yml if the validation fails.  Are you using bosh release or standalone UAA from war file.
