### ISSUE TITLE
SAML Integration for External IDP configuration ACTIVE state not persisted in UAA Database

### ISSUE THREAD

**Issue by karthikduraisamy** [cloudfoundry/uaa#617]
When integrating with SAML for External IDP, the active flag is not persisted, when restarting the application, it resets the value in identity_provider table to false.

select id,name,type,active from identity_provider;
                  id                  |       name        |     type     | active 
--------------------------------------+-------------------+--------------+--------
 b750dca2-ee00-4ada-b9f4-de32088a4f2d | login-server      | login-server | f
 f348fff2-44f0-49b1-a928-04ae01cf0137 | ldap              | ldap         | f
 59aa1ae4-e5df-4e81-afcd-81291e0e42be | keystone          | keystone     | f
 5fa3b153-53db-469d-aff3-eb73c6fc08c6 | idp-admin-sso-dev | saml         | f
 ba9ae379-4c86-44e0-9c6d-92618b9cbc91 | uaa               | uaa          | f

**Comment by fhanik** [comment]
@karthikduraisamy I believe that this can happens if you have removed the provider configuration from your Yaml manifest. Can you check if that is the case here?

**Comment by james-b-thomas** [comment]
@fhanik I am working with @karthikduraisamy.

Here in our application, we are creating IDP based on the UAA API and not through yaml configuration.

I believe UAA shouldn't disable the active IDP's to inactive during startup based on yaml.

**Comment by sreetummidi** [comment]
@james-b-thomas We are working on handling this in a consistent manner. We will fix the issue with provide being deactivated if it no longer exists in the YML

**Comment by karthikduraisamy** [comment]
Can you give us an estimate when this issue will be fixed ?

**Comment by sreetummidi** [comment]
Will be addressed with 4.9.0 shipping next week
