### ISSUE TITLE
Options for obfuscating error messages

### ISSUE THREAD

**Issue by ryancutter** [cloudfoundry/uaa#622]
I've been through the docs and the code and don't see an obvious way to obfuscate error messages returned to the user.  Did I miss it?  For instance:

```
{
  "error": "unauthorized",
  "error_description": "PreparedStatementCallback; SQL [insert into sec_audit (principal_id......."
}
```
Is there a way (hopefully via configuration) to remove the SQL in the error_description which is returned to the user?

**Comment by sreetummidi** [comment]
@ryancutter Please provide the steps that led you see the error mentioned above

**Comment by fhanik** [comment]
I'm unable to reproduce this behavior. If you are able to post the entire error message along with the version of UAA, please reopen the story with that information.
