### ISSUE TITLE
Is there an Html/JavaScript Client Demo?

### ISSUE THREAD

**Issue by jdmr** [cloudfoundry/uaa#623]
I have an uaa identity server configured and running with several spring boot clients authenticating against it. Now I would like to have an Html/JavaScript Client authenticating against it. I can get the code but when I try getting the token it will throw a 400 / Invalid Grant / Redirect URI Mismatch. So was wandering if you have an Html/JavaScript client demo that I could use to see what I'm missing...

**Comment by sreetummidi** [comment]
Please refer to : https://github.com/cloudfoundry/uaa-singular
