### ISSUE TITLE
Documentation for setting token signing key refers to deprecated config params

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#624]
The documentation for setting the token signing key still refers to the deprecated config params (see https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#token-signing).

Following https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec the parameters uaa.jwt.signing_key and uaa.jwt.verification_key are deprecated and uaa.jwt.policy.keys should be used.

This should be also reflected in the documentation on https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#token-signing

**Comment by sreetummidi** [comment]
@sebastianGit We are in the process of re-writing the sysadmin guide as part of the epic here: https://www.pivotaltracker.com/epic/show/3578933 and will capture the new formats there.
