### ISSUE TITLE
Configuration of nesting of groups via "scim.group_membership" in uaa.yml not documented - feature discontinued?

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#625]
The possibility to configure of "scim.group_membership" in uaa.yml not documented. 

Links:
* Configuration option is supported - see scim-endpoints.xml: https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml#L303

* Configuration option misses in: https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec
*  Configuration option misses in: https://github.com/cloudfoundry/uaa/blob/master/uaa/src/test/resources/test/bootstrap/all-properties-set.yml

Being able to bootstrap group nestings is a great feature. Is it discontinued?

**Comment by sreetummidi** [comment]
We don't have plans to support this in the near term
