### ISSUE TITLE
Error messages referring to implementation ("access token") can confuse end-users

### ISSUE THREAD

**Issue by brittag** [cloudfoundry/uaa#627]
In the Cloud Foundry deployment I work on, I noticed that some of our users get confused by login error messages like this one:

https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java#L1039-L1040

It looks like this on the change password page, for example: "Invalid access token (expired): fdslkghfjkghfdkjghjkfhgdkjhfkjghdfkjghfkdjhgfdjhgkfdjhjsghkfjhgfdjhgkfdjhgfjd expired at Tue May 30 18:39:20 UTC 2017"

I'm curious if anyone is working on error messages more like the following, or if something more like this could be considered: "Could not complete your action because your login session expired. Try refreshing or starting over, which may prompt you to log in again, then try your action again." The diagnostic details about the exact token string and expiration date could be included after that human-friendly message.

I'd be happy to make a couple PRs for things like this, but right now it's tricky to figure out how to contribute an improvement like that, since the error strings seem to be tightly integrated into the code, and I'm not sure how to find out the contexts where each string is used.

**Comment by sreetummidi** [comment]
@brittag Are you seeing this on the UI or a response from an API interaction?

**Comment by brittag** [comment]
@sreetummidi I'm seeing this in the UI:

![untitled copy](https://cloud.githubusercontent.com/assets/391313/26808389/39e03ca6-4a11-11e7-863f-c64233668741.jpeg)

**Comment by brittag** [comment]
Closing this up since this actually seems pretty specific to our deployment and how we're using UAA, rather than being a general issue.
