### ISSUE TITLE
UserInfo endpoint under .well-known/openid-configuration not correct

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#628]
The userinfo_endpoint announced under .well-known/openid-configuration is configured to be ".../userInfo" (with capital "I") - see https://github.com/cloudfoundry/uaa/blob/master/model/src/main/java/org/cloudfoundry/identity/uaa/account/OpenIdConfiguration.java#L64

The correct URL of the userinfo_endpoint should be ".../userinfo" (with lower case "i") - see https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/webapp/WEB-INF/spring/openid-endpoints.xml#L21 

This mismatch breaks scenarios where OAuth/OpenID Connect clients rely on the data of the .well-known endpoint as calling ".../userInfo" responds with a 302 redirect.

Backport of the bugfix to UAA 3.x.y would be appreciated.

**Comment by srenatus** [comment]
I think the issuer is probably incorrect, too? Pointing a generic OIDC client at UAA, I just got

```
error: Failed to query provider "http://localhost:8080/uaa": oidc: issuer did not match the issuer returned by provider, expected "http://localhost:8080/uaa" got "http://localhost:8080/uaa/oauth/token"
```

And indeed, that's what the discovery document includes:
```
$ curl -q http://localhost:8080/uaa/.well-known/openid-configuration | jq .issuer
"http://localhost:8080/uaa/oauth/token"
```

Is this `issuer` setting in any way configurable?
