### ISSUE TITLE
UAA not respecting forwarded URL scheme

### ISSUE THREAD

**Issue by libby2cm** [cloudfoundry/uaa#631]
Sometime since v3.12, it appears that UAA stopped 'respecting' the forwarded http schema in a SAML request.  We have UAA behind a reverse proxy, and HTTP is used between reverse proxy and tomcat/uaa, while HTTPS is of course used by incoming connections to proxy.  We have proxy rules that pass the http scheme to the backend service, but UAA is failing the SAML request because it sees a https request in SAML reply, but thinks it's receiving it via http.

I reviewed other issue reports & changes, but didn't see anything that stuck out.

**Comment by fhanik** [comment]
Are you running UAA stand alone or in. CF deployment?

Standalone you would have to configure Tomcat's RemoteIPValve to consume those headers properly. 

CF deployment you'd set the uaa.proxy_ips_regex property with the proxy information.

**Comment by libby2cm** [comment]
@fhanik  thanks for that.. this fixed the issue.  We are running it standalone (well, in docker on tomcat image) and have never had to set that before.  I guess there was a change to UAA recently that checks for it now.

**Comment by libby2cm** [comment]
Oh, for posterity, added this to server.xml at engine level:

<Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="x-forwarded-for" proxiesHeader="x-forwarded-by" protocolHeader="x-forwarded-proto" />

**Comment by burcakulug** [comment]
This answer really helped me a lot to figure out the similar issue. However, this snippet doesn't contain `internalProxies` property. If this is not set, it doesn't really work properly. You need to provide a regex matching the internal proxy IPs.
