### ISSUE TITLE
CLOUD_FOUNDRY_CONFIG_PATH is not being used in 3.2.1

### ISSUE THREAD

**Issue by kannangce** [cloudfoundry/uaa#632]
We are using a forked version of UAA 3.2.1. I have set the environment variable `CLOUD_FOUNDRY_CONFIG_PATH` with the folder location containing custom config files. Also I tried passing `-DCLOUD_FOUNDRY_CONFIG_PATH=<parent folder of uaa.yml>` . But my custom uaa.yml is not picked up.

**Comment by sreetummidi** [comment]
@kannangce Please follow the documentation in UAA readme to achieve this.
