### ISSUE TITLE
API reference wrongly states "response_type" as mandatory parameter for client credentials flow

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#634]
In the UAA API reference, it's documented that the parameter "response_typ" is required for the client credential grant's token request - see: https://docs.cloudfoundry.org/api/uaa/#client-credentials-grant

Yet, the parameter "response_type" is not considered a required parameter in RFC 6749 (see: https://tools.ietf.org/html/rfc6749#section-4.4.2)

Furthermore, the parameter is not required when sending requests to CF UAA nor does it seem to have any influence. Thus, it looks like it just can / should be removed from the documtation.

**Comment by jhamon** [comment]
We are handling this as part of this story with several small doc fixes https://www.pivotaltracker.com/story/show/149450829
