### ISSUE TITLE
Is "not contains" operator available in uaa cloudfoundry?

### ISSUE THREAD

**Issue by KMahesh045** [cloudfoundry/uaa#636]
I have to retrieve all groups except the groups which names are not containing "uaa". 
I can see only contains operator(co), but i cant find for not contains. Is "not contains" operator available in uaa?
I searched in uaa api document also but i cant see anywhere. https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst

If not how can I achieve this?

**Comment by jhamon** [comment]
My read of the scim filtering related code in UAA is that this is not possible today. We rely on [this implementation](https://github.com/pingidentity/scim) of scim filters, so you may want to open an issue with them to discuss plans for negation in filtering. I noticed that [RFC7644](https://tools.ietf.org/html/rfc7644#section-3.4.2.2) mentions a `ne` not equals operator, but it doesn't look like it's been implemented yet.
