### ISSUE TITLE
Cannot request sub-scopes of uaa.admin

### ISSUE THREAD

**Issue by 6palace** [cloudfoundry/uaa#643]
If a client has the uaa.admin scope/authority, but in the authorization request we only request a admin sub-scope such as clients.write or scim.write, those scopes will not be granted and the authorization request will fail. Is this intended behavior? Should uaa.admin clients have to request tokens with full admin scope?

Steps to Reproduce:
1. Create a client with authorization code grant and uaa.admin as scope
2. Create a user that is member of clients.write group.
3. Attempt to perform auth code flow with created client, providing scope parameter of clients.write. Request will fail with invalid scope error.

**Comment by fhanik** [comment]
The proper way to make this work would be to make all sub scope groups be members of the `uaa.admin` group. 

The UAA supports nested groups. This way, the operator has control over which scopes can be issued in the token. 

```
group: uaa.admin
member: clients.write
member: clients.read
```

**Comment by 6palace** [comment]
That's smart. Do we want to add those members to the yaml bootstrap? We have customers getting confused when uaa.admin allows access to all the endpoints but isn't automatically a member of those groups.

**Comment by fhanik** [comment]
I'll leave this issue open so that we can discuss the ability to define this via yaml for the default zone. Currently it is only possible via API.

**Comment by 6palace** [comment]
👍 sounds good, we'll inform them of the sub-group function.

**Comment by sreetummidi** [comment]
No plans to address
