### ISSUE TITLE
Admin users (e.g., with scope uaa.admin) cannot change client secrets (but clients can)

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#645]
We have use cases in which an administrator must be capable of changing a clients secret. Yet, currently this is not possible for users, only for clients, as the ClientAdminEndpoint explicitly checks whether it is invoked by a client (see below). 

Is it possible to change this behavior? What's the reason for the current restriction?

Implementation details: 

Within the ClientAdminEndpoints class (https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/client/ClientAdminEndpoints.java) the method changeSecret in line 504 is called. In this method the private method checkPasswordChangeIsAllowed (line 587) is executed which calls securityContextAccessor.isClient().

The check securityContextAccessor.isClient() is defined within the class DefaultSecurityContextAccessor (https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/security/DefaultSecurityContextAccessor.java). In case the client is authenticated on behalf of a user, it returns false.

**Comment by sreetummidi** [comment]
Also "only the combination of clients.secret and uaa.admin allows for change of a password."

**Comment by andrewedstrom** [comment]
We just fixed this, should come out in next release. Users with adequate permissions can now change client secrets as of https://www.pivotaltracker.com/story/show/167243230
