### ISSUE TITLE
Simplify administration of nested groups by supporting of "memberOf" for SCIM groups

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#646]
Administration of nested group memberships could be greatly simplified if the SCIM API for groups would support an attribute like "memberOf".

Currently only reading & setting the "member" attribute of a SCIM group is possible.

Use case:
I want to have a group "containergroup" and by adding a user to the "containergroup" the user should also become a (indirect) member in "scope.a" and "scope.b".

Currently this requires, that I add "containergroup" as a member to "scope.a" and that I add "containergroup" as a member to "scope.b".

Supporting a "memberOf" attribute in the SCIM API this can be simplified in the way that I only need to change the "memberOf" attribute of the "containergroup" to include "scope.a" and "scope.b" (probably I would have to add id's of those groups, instead of the displayname). (The details of adding the group memberships will be hidden in the implementation behind the API.)

When requesting "containergroup"  and reading the "memberOf" attribute I would also be able to see, that the relation between the "containergroup" and "scope.a" and "scope.b", which is currently not visible from the "containergroup", but requires to call "scope.a" and "scope.b"

**Comment by sreetummidi** [comment]
No plans to add this feature. PR welcome
