### ISSUE TITLE
Missing index on table group_membership for postgres 

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#647]
Hi

we noticed a high SQL execution time for uaa startup on postgress, if there are millions of groups.

The SQL statement causes the high load times is:
      select count(*) from group_membership where group_id in (select id from groups where 
      identity_zone_id='uaa') and LOWER(group_id) = LOWER(?)
was running for several seconds, up to 20 sec.

After we defined an index for it

CREATE INDEX group_membership_group ON group_membership(LOWER(group_id));

the problems get solved and startup times were ok.

Do you noticed similar issues on postgres? Can you please add this index ?

thanks in advance and regards,
-markus

**Comment by fhanik** [comment]
https://www.pivotaltracker.com/story/show/148308021
