### ISSUE TITLE
User exists twice with the same user name in the uaa db.

### ISSUE THREAD

**Issue by gowrisankar22** [cloudfoundry/uaa#648]
Hi Colleagues,

I have experienced an issue that User exists twice with the same user name in the uaa db. is there any script that does detection of ducplicated users and auto removal ?

Thanks,
GS

**Comment by mwdb** [comment]
From uaa perspective a user is unique with the following keys:
- user name
- origin (->identity provider used for authentication)
- identity zone (for cf platform users always uaa)

This is enforced by the DB.

When a user authenticates using different identity providers, this will be different users.
The gap is on the cf controller side. The controller does not differentiate between origins, therefore you may get a perception that a user exists multiple times.
