### ISSUE TITLE
[question] internationalization of UI

### ISSUE THREAD

**Issue by joelmarty** [cloudfoundry/uaa#650]
I have question regarding the internationalization of the UAA server pages (and emails). Is there such a feature that exists today or is it mandatory to proceed by forking the UAA code to change the templates ?

I noticed that UAA uses thymeleaf as a template engine, which natively supports i18n. If any configuration hooks exists for thymeleaf, it should surely be possible to configure thymeleaf to use others template resolvers. Since it is done using the java config class ThymeleafConfiguration, modification could only be done by forking the uaa server repo and changing the code, is this correct ?

I would also require a way to extract the client locale and pass it down to the template engine, unless this is already the case.

**Comment by jhamon** [comment]
I18n is not an existing feature and we currently have no plans to tackle it soon, but we'd be glad to take pull requests adding international language support if you end up implementing that on your fork.
