### ISSUE TITLE
[question]: is there a way to have a default IDP when IDP discovery is enabled?

### ISSUE THREAD

**Issue by patricklunney** [cloudfoundry/uaa#651]
Hi, 

Wondering if there is a way to have a default IDP when IDP discovery is enabled in the zone. 
For example: 
IDP 1: company1.com
IDP 2: company2.net
IDP 3: company3.com 
IDP 4: mycompany.com 

Is there a way to say if the entered email doesn't match 1, 2, and 3, it defaults to 4 rather than showing the IDP discovery screen listing all of the IDPs? 

I tried by doing *.* in the IDP4 emailDomain config but it doesn't seem to work. 

Any tips on what I'm doing wrong?

**Comment by patricklunney** [comment]
Thanks cf-gitbot!

**Comment by sreetummidi** [comment]
@patricklunney It defaults to internal auth if no match is found. Is that the behavior you are seeing?
