### ISSUE TITLE
[question] ZONE_SWITCH_SCOPES do not include idps.write, sps.read, sps.write (similar for UAA_SCOPES)

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#654]
I just came across that ZONE_SWITCH_SCOPES do not include idps.write, sps.read, sps.write.
(see https://github.com/cloudfoundry/uaa/blob/develop/model/src/main/java/org/cloudfoundry/identity/uaa/zone/ZoneManagementScopes.java).

As far as I understand CF UAA this means that writing an IdP configuration or reading/writing an SPS configuration is not possible via the uaa zone and zone-switching header. 

Furthermore, UAA_SCOPES  does not include sps.read, sps.write. Thus, I would assume that it is possible to create restricted clients with sps.read, sps.write.

What's the background for excluding those scopes?

**Comment by jhamon** [comment]
As of the 4.6.0 release, these scopes may now be used with zone switching.
