### ISSUE TITLE
[OIDC] XOAuthAuthenticationManager username/external_id handling violates OIDC spec

### ISSUE THREAD

**Issue by JohannesRudolph** [cloudfoundry/uaa#657]
The XOAuthAuthenticationManager by default uses the OIDC `preferred_username` claim to populate the UAA username field of an UAA User. 

This appears to be in direct violation of the OIDC Spec: 

> The standard claims in an id token include (ref: http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)

- **sub:** Subject - Identifier for the End-User at the Issuer.
- **preferred_username**: Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique, as discussed in Section 5.7.
- **email**: End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed in 

I can understand why this is a reasonable default ([applied here](https://github.com/cloudfoundry/uaa/blob/4.4.0/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManager.java#L122)), however in this case UAA does exactly what the spec forbids, i.e. it relies on the `preferred_username` to be unique. This has multiple manifestations downstream in UAA, e.g. the contstaints on the Users table (as far as I read the code):
```
V2_0_3
ALTER TABLE users ADD UNIQUE KEY `username_in_idp` (`identity_provider_id`,`username`);

V2_0_4
ALTER TABLE users ADD UNIQUE KEY  users_unique_key(origin,username,identity_zone_id);
```

The OIDC spec further goes on to say that: 

> Section 5.7.
5.7.  Claim Stability and Uniqueness
The sub (subject) and iss (issuer) Claims, used together, are the only Claims that an RP can rely upon as a stable identifier for the End-User, since the sub Claim MUST be locally unique and never reassigned within the Issuer for a particular End-User, as described in Section 2. Therefore, the only guaranteed unique identifier for a given End-User is the combination of the iss Claim and the sub Claim.
All other Claims carry no such guarantees across different issuers in terms of stability over time or uniqueness across users, and Issuers are permitted to apply local restrictions and policies. For instance, an Issuer MAY re-use an email Claim Value across different End-Users at different points in time, and the claimed email address for a given End-User MAY change over time. Therefore, other Claims such as email, phone_number, and preferred_username and MUST NOT be used as unique identifiers for the End-User.

Given this wording of the spec, a "safer" default choice appears to be the **sub** claim in an id token.

In any case, I would have expected UAA to at least store the sub claim in the externalId property of the user (as it e.g. does for LDAP), but that doesn't appear to be the case either ([culprit here](https://github.com/cloudfoundry/uaa/blob/4.4.0/server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthAuthenticationManager.java#L238)).

Am I correctly inferring that UAA has the fundamental assumption that (UAA) usernames are unique per origin and a given username remains constant over time? For now I will probably map the "sub" claim to (e.g. via `config.attributeMappings.user_name`) into UAA from OIDC.

So I'd like to request two things for UAA team's consideration: 
- Consider changing the default from `preferred_username` to `sub`
- properly map `sub` to external id in Users table

**Comment by jhamon** [comment]
This work shipped as part of the 4.6.0 release.
