### ISSUE TITLE
Login with a SAML IdP gets significantly slowed down when adding SAML IdPs to a zone

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#660]
Currently I have the following observation when I have a single SAML IdP in an identity zone, is see 18 times the following log entry "NonSnarlMetadataManager: Adding SAML IDP zone[abc] alias[xyz]". The log entries are tiggered by clicking the "Link to the IdP" on the login page.

When I add IdPs (e.g., 50) to one zone, login (more precisly getting the redirect to the next page) is significantly slowed down by this.  It maybe that in the background there happens additionally a 18 times per IdP a download of the metadata, and validation of the metadata,... I did not have the chance to look further into this.

**Comment by sreetummidi** [comment]
Closing. No plans to address this immediately.
