### ISSUE TITLE
Missing index on table group_membership for postgres (2)

### ISSUE THREAD

**Issue by mwdb** [cloudfoundry/uaa#664]
In addition to https://github.com/cloudfoundry/uaa/issues/647 another index is missing on 

delete from group_membership where group_id in (select id from groups where identity_zone_id = ?)

This causes a delete of an identityzone to spend 1.4 seconds in the DB in one of our systems.

**Comment by fhanik** [comment]
@mwdb I'm unable to find the query 

    delete from group_membership where group_id in (select id from groups where identity_zone_id = ?)

We will still add an index to this column, and we will investigate #647 at the same time

**Comment by mwdb** [comment]
this query comes when an identity zone is deleted.

**Comment by fhanik** [comment]
https://www.pivotaltracker.com/story/show/149310593
