### ISSUE TITLE
Spring placeholder in YAML is not processed

### ISSUE THREAD

**Issue by kannangce** [cloudfoundry/uaa#666]
The placeholders in config file is not parsed for all the attributes.
I am able to use placeholders for DB attributes. Ex, `username: ${DB_USERNAME:postgres}` . But I am not able to do the same for `redirect-uri` . The placeholders that I give for the attribute `redirect-uri` is not replaced with the value of the placeholders.
To explain in detail,
I the `yml` block containing a client data, I gave the redirect-uri as `${STANDARD_REDIRECT_URI:http://localhost:8081/testapp}` . I expect this to get the value from the environment variable `STANDARD_REDIRECT_URI`, if it is not available then use the URL `http://localhost:8081/testapp` . But the whole string `${STANDARD_REDIRECT_URI:http://localhost:8081/testapp}` is saved as URL in DB.

**Comment by jhamon** [comment]
Could you give some more details about the exact steps you are following, the behavior you expect, and the behavior you are seeing? There's not enough information in this issue for me to reproduce and troubleshoot.  

If you're only seeing this issue with `redirect-uri`, I suspect it might be related to the specific url you are trying to set; for security reasons, there are some limitations on what URL's may be configured.

**Comment by kannangce** [comment]
@jhamon  Added details to the question.
