### ISSUE TITLE
[Question] Running CF UAA with MySQL vs PostgreSQL

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#671]
Hi,

is there a recommendation for choosing MySQL or PostgreSQL as database for CF UAA? 

For PostgreSQL I've seen a couple of updates in the pull requests (e.g. additional indexes).

Is there any experience w.r.t. performance and stability that you can share?

**Comment by sreetummidi** [comment]
Both are supported and used in commercial deployments of UAA.
