### ISSUE TITLE
[Question] What influences issuer field in generated tokens?

### ISSUE THREAD

**Issue by aleliaert** [cloudfoundry/uaa#675]
We're running UAA instance as an app in CF, and have noticed that generated tokens have the 'iss' field set to `http://localhost:8080/uaa/oauth/token`.  What influences that?  We'd like to change it to something more meaningful and secure, as it appears the issuer field is checked for security purposes.

And when UAA logs its configuration upon startup, is there a way to have it not redact values?

Thanks!  Having fun learning UAA...

**Comment by sreetummidi** [comment]
@aleliaert The issuer field is configurable. The default is {uaa_url}/oauth/token but you can override by setting under

uaa:
     issuer:
         uri: <value>

The values are redacted in the log file for security reasons as we don't want to log the secrets and passwords from the uaa.yml
