### ISSUE TITLE
MySQL db migration script does not support utf8mb4 charset

### ISSUE THREAD

**Issue by adisutanto** [cloudfoundry/uaa#678]
MySQL true UTF-8 charset is not "utf8" but is "[utf8mb4](https://mathiasbynens.be/notes/mysql-utf8mb4)".
With utf8mb4, the maximum length of varchar column index should be 191 instead of 255.
However, [V1_5_5__CreateExpiringCodeStore.sql](https://github.com/cloudfoundry/uaa/blob/master/server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V1_5_5__CreateExpiringCodeStore.sql) has "code" column index with varchar(255) instead of varchar(191):
```sql
code VARCHAR(255) NOT NULL PRIMARY KEY,
```
Issue: If we start uaa with a blank db with utf8mb4 default charset, it will encounter DB error during table creation during Flyway database migration.

**Comment by jhamon** [comment]
This is very interesting and is something I will keep in my for future projects, but changing database encoding seems like something we are unlikely to pursue in the UAA unless we hear from a customer that it is required for their use cases. We have a lot of companies using UAA in production with a variety of databases we don't directly manage or have access to.  So I am reluctant to make changes that could have unforeseen implications leading to downtime or data loss without a compelling use case that demands the change.

The Flyway migration tool does not provide a way to make a change like this to the starting assumptions once old migrations have been deployed.  For example, the `V1_5_5__CreateExpiringCodeStore.sql` migration that you linked to cannot be changed without breaking the ability of users with existing UAA deployments to upgrade; if we edited that file to accommodate new deployments with utf8mb4 encoding enabled, when our existing users upgrade UAA Flyway would detect a checksum mismatch in that migration file and refuse to let their application start. The Flyway migration builds in the assumption that the arrow of time points in one direction and does not allow for changing starting assumptions like character encoding.

**Comment by adisutanto** [comment]
Thank you for the comment, it makes sense.
This is one of the reason why I personally prefers PostgreSQL over MariaDB/MySQL, but my company decided to use MariaDB/MySQL, so I just have to accept it.
