### ISSUE TITLE
README Quickstart is difficult to understand

### ISSUE THREAD

**Issue by Buddikawidu** [cloudfoundry/uaa#682]
Please make below paragraph more understandable "

NOTE: Recent changes removed default keys and default users from the UAA. We currently enable default keys using the LOGIN_CONFIG_URL variable and load default sample data is loaded using the default spring profile (spring.profiles.active). In the gradle script we set LOGIN_CONFIG_URL=file://$PWD/uaa/src/main/resources/required_configuration.yml 

any one please explain how can i follow above steps

**Comment by sreetummidi** [comment]
If you are running locally as ./gradlew run, the required properties will automatically be applies from the YML

When running in production make sure that you specify valid cert and key values in the UAA.yml for SAML Cert, Key and JWT Key
