### ISSUE TITLE
[Question] Client validation kicks in if a client (here: resource server) does not have a grant type

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#685]
I have the use case that I have OAuth resource servers which should be able to call the token introspection endpoint of CF UAA (/check_token). 

This requires that the resource source server must be registered at CF UAA as a client - in order to have a client-id and client-secret for authentication at the /check_token endpoint  and uaa.resource as authority.

With CF UAA 4.x validation of the client configuration was introduced, and CF UAA does not start up in case my client (actually a resource server) does not have a grant_type configured (which I should not need in this case).

How do you typically handle this situation? Is there better option than configuring a grant_type (e.g. "authorization_code") plus scope "uaa.none"?

**Comment by jhamon** [comment]
Hey, thanks for your question. Right now, yes, I think the only way to call `/check_token` is to register a client for your resource server with some authorized_grant_type even though you will not be obtaining tokens.  I think `client_credentials` makes the most sense here, even though you aren't using the client to obtain tokens; conceptually, you are making a call on your server's behalf and not on behalf of a user. 

It does seem like a strange consequence of our decision to validate  client configurations that now the resource server must specify grant types it will never use. We may discuss other approaches to this in the future.
