### ISSUE TITLE
Public clients & PKCE

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#688]
Is it planned that CF UAA supports public clients (clients without any secret) using "token_endpoint_auth_method"="none" (RFC 7591) and PKCE (RFC 7636) ?

Thanks,
Sebastian

**Comment by jhamon** [comment]
We have implemented some parts of RFC 7591 (specifically the `urn:ietf:params:oauth:grant-type:jwt-bearer` and `urn:ietf:params:oauth:grant-type:saml2-bearer` grant types) but we do not currently have plans to tackle the `token_endpoint_auth_method` soon. We'll take this as a feature request.

The workaround you can do today is to create a second non-public client that will only be used for calling the check_token endpoint.
