### ISSUE TITLE
Changing user password invalidates refresh tokens, can be disabled?

### ISSUE THREAD

**Issue by theomega** [cloudfoundry/uaa#689]
Changing the user password invalidates all the refresh tokens (as the access tokens) for this user. I assume this is an intended behaviour (which makes sense in most cases). According to the code, the same is actually also true when changing the email-address.

We are relying on the refresh tokens to last infinite, so we are running into a road block here. Is there any thing we can do to disable this behaviour? Maybe a configuration option?

Or any other possibility? We are using opaque tokens in case that helps.

Would CF accept a PR to make this behaviour configurable? I looks like [`UaaTokenUtils. getRevocableTokenSignature`](https://github.com/cloudfoundry/uaa/blob/fe946fdc871027fcea9278e97c09cbf270831cf4/server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaTokenUtils.java#L155) is the place where this is checked.

**Comment by jhamon** [comment]
Hey, we discussed this as a team today and think the current behavior is the only behavior that should be allowed. Changing passwords is often done in response to a security incident where a user believes the password may have been compromised. You can imagine a scenario where an attacker has used stolen user credentials to obtain a refresh token; it would be inappropriate to continue granting new access tokens forever after the user changes email/password without the user re-authing in that case.

If having the user re-auth is a problem, that suggests you're doing things asynchronously when the user is not actively using your client app. We recommend you consider whether a `client_credentials` grant type is appropriate for your use case.
