### ISSUE TITLE
Incorrectly derived base URLs in openID configuration when uaa is behind a proxy

### ISSUE THREAD

**Issue by easeway** [cloudfoundry/uaa#692]
In my deployment, I want HTTPS termination on proxy, and uaa is running on HTTP. While getting openid configuration via https://external-dns/uaa/.well-known/openid-configuration, the returned URLs containing internal http hostname and port:

e.g. the external dns name mapped to proxy is uaa.mydomain.com, so the client is talking to
https://uaa.mydomain.com

and the openid configuration from https://uaa.mydomain.com/uaa/.well-known/openid-configuration is

```
{
  "issuer": "https://uaa.mydomain.com/uaa/oauth/token",
  "authorization_endpoint": "http://172.16.118.17:8080/uaa/oauth/authorize",
  "token_endpoint": "http://172.16.118.17:8080/uaa/oauth/token",
  "userinfo_endpoint": "http://172.16.118.17:8080/uaa/userinfo",
  "jwks_uri": "http://172.16.118.17:8080/uaa/token_keys",

  ...
}
```
The `issuer` is correct because I specify the value in `uaa.yml`.

while the expected configuration is like

```
{
  "issuer": "https://uaa.mydomain.com/uaa/oauth/token",
  "authorization_endpoint": "https://uaa.mydomain.com/uaa/oauth/authorize",
  "token_endpoint": "https://uaa.mydomain.com/uaa/oauth/token",
  "userinfo_endpoint": "https://uaa.mydomain.com/uaa/userinfo",
  "jwks_uri": "https://uaa.mydomain.com/uaa/token_keys",

  ...
}
```

If I configure the proxy to write Host header with the value from original client request, the configuration is still incorrect as it always uses `http` instead of `https`, like:

```
{
  "issuer": "https://uaa.mydomain.com/uaa/oauth/token",
  "authorization_endpoint": "http://uaa.mydomain.com/uaa/oauth/authorize",
  "token_endpoint": "http://uaa.mydomain.com/uaa/oauth/token",
  "userinfo_endpoint": "http://uaa.mydomain.com/uaa/userinfo",
  "jwks_uri": "http://uaa.mydomain.com/uaa/token_keys",

  ...
}
```

**Comment by easeway** [comment]
After investigating the source code, I found the issue sits in `org.cloudfoundry.identity.uaa.account.OpenIdConnectEndpoints#getServerContextPath`

```
    private String getServerContextPath(HttpServletRequest request) {
        StringBuffer requestURL = request.getRequestURL();
        return requestURL.substring(0, requestURL.length() - request.getServletPath().length());
    }
```

deriving base URL from the request is a bad idea, and it makes uaa work improperly behind a proxy.
Why not constructing these URLs using `issuer` as base URL? Then we can get consistent behavior.

**Comment by sreetummidi** [comment]
The OpenID Connect well known configuration is also available @ https://{uaa_base_url}/oauth/token/.well-known/openid-configuration. This makes the required derivation if issuer possible.

**Comment by hanswieheiri** [comment]
I am also using this patch (I run UAA with Docker and NGINX). Don't know why @easeway's change never made it to master.
