### ISSUE TITLE
error initializing uaa app on pivotal cloud foundry: KeyManager must be set

### ISSUE THREAD

**Issue by restjohn** [cloudfoundry/uaa#694]
I am attempting to deploy the UAA app to an enterprise instance of Pivotal Cloud Foundry.  I followed the [instructions](https://docs.pivotal.io/pivotalcf/1-10/concepts/architecture/uaa.html) for building and deploying the UAA app to PCF, building from the master branch.  When the app starts, the log shows an initialization error:
```
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'idpMetadataManager' defined in ServletContext resource [/WEB-INF/spring/saml-idp.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: KeyManager must be set
```
See the attached log for the entire exception chain.  Am I missing something in my PCF instance required to run the UAA server?

[cloud_foundry_uaa_error.log.txt](https://github.com/cloudfoundry/uaa/files/1290221/cloud_foundry_uaa_error.log.txt)

**Comment by sreetummidi** [comment]
Have you considered using Pivotal Single Sign-On Service which provides UAA on demand.
https://docs.pivotal.io/p-identity/1-4/index.html

This is the supported path when using PCF

**Comment by jamelseagraves** [comment]
I get a very similar error log output when I deploy the latest UAA version to a Tomcat server in a Docker container. In my Dockerfile, I do not use `./gradlew run`; instead, I use `./gradlew build -x test`, and then I replace the default Tomcat webapp (ROOT.war) with the newly built cloudfoundry-identity-uaa-[version].war and execute `/bin/catalina.sh run` to start the Tomcat server. Not sure why this does not work.

**Comment by pharout** [comment]
I see this same error running locally as per quick start, see https://github.com/cloudfoundry/uaa/issues/717

**Comment by hpham** [comment]
@pharout  can you post your required_configuration.yml file for running on local machine?

**Comment by pharout** [comment]
the minimal fix was simply to re-enable the defaults in the uaa.yml file (this is from 4.6.1 release)
[uaa.yml.txt](https://github.com/cloudfoundry/uaa/files/1398532/uaa.yml.txt)

**Comment by pharout** [comment]
Apologies for the spam but I also (I am using windows) had to change the LOGIN_CONFIG_URL jvm arg to include a third slash before the path:

jvmArgs = "-javaagent:${jacocoLocation}=output=file,dumponexit=true,append=false,destfile=${integrationTestCoverageExecutionData} -DLOGIN_CONFIG_URL="+new File("./uaa/src/main/resources/required_configuration.yml").toURI().toURL()

**Comment by systemview2018** [comment]
Just try to solve it:

Please modify the  WEB-INF/spring/saml-idp.xml

    <bean id="idpMetadataManager"
          class="org.cloudfoundry.identity.uaa.provider.saml.idp.NonSnarlIdpMetadataManager"
          depends-on="spMetaDataProviders" destroy-method="destroy">
        <constructor-arg name="configurator" ref="spMetaDataProviders" />
        <property name="refreshCheckInterval" value="${login.saml.metadataRefreshInterval:0}" />
        <property name="generator" ref="zoneAwareIdpMetadataGenerator"/>
        <property name="keyManager" ref="idpZoneAwareSamlKeyManager"/>
    </bean>

**Comment by saumilsdk** [comment]
As mentioned, adding this line in saml-idp.xml solves the issue
 <property name="keyManager" ref="idpZoneAwareSamlKeyManager"/>

**Comment by berndgoetz** [comment]
I tried to do that, but it didn't work for me. Anybody else with the same problem?

**Comment by c4milo** [comment]
I don't know why it doesn't happen when using Gradle. With Tomcat, I fixed by adding extra saml configuration to my own `login.yml` file: 

```yml
login: 
  saml:
    activeKeyId: key-1
    keys:
      key-1:
        key: |
          -----BEGIN RSA PRIVATE KEY-----
         <PEM ENCODED CONTENT>
          -----END RSA PRIVATE KEY-----
        passphrase: password
        certificate: |
          -----BEGIN CERTIFICATE-----
          <PEM ENCODED CONTENT>
          -----END CERTIFICATE-----
```

**Comment by rayson1223** [comment]
> Just try to solve it:
> 
> Please modify the WEB-INF/spring/saml-idp.xml
> 
> ```
> <bean id="idpMetadataManager"
>       class="org.cloudfoundry.identity.uaa.provider.saml.idp.NonSnarlIdpMetadataManager"
>       depends-on="spMetaDataProviders" destroy-method="destroy">
>     <constructor-arg name="configurator" ref="spMetaDataProviders" />
>     <property name="refreshCheckInterval" value="${login.saml.metadataRefreshInterval:0}" />
>     <property name="generator" ref="zoneAwareIdpMetadataGenerator"/>
>     <property name="keyManager" ref="idpZoneAwareSamlKeyManager"/>
> </bean>
> ```
@systemview2018  may I know how can I create idpZoneAwareSamlKeyManager? Because currently I'm stuck and unable to deploy to production on the latest develop branch version for a week already. Thank you
