### ISSUE TITLE
Creating a user through java-client with email id as " " passes on UAA but fails on doing a cf login with that user

### ISSUE THREAD

**Issue by Affy01** [cloudfoundry/uaa#702]
I'm creating a user in root UAA through java-client with a space as email id. I can successfully create a user but when I try to login on the UI it fails with this message. 

![image](https://user-images.githubusercontent.com/12614472/30763212-29d728b8-9fb3-11e7-92f9-7a7e4071b101.png)

It fails while running a cf login command with a message 
Authenticating...
The targeted API endpoint could not be reached.

My UAA version is 3.14.0

**Comment by sreetummidi** [comment]
Unable to reproduce
error response:
{
  "error_description": "Exactly one email must be provided.",
  "error": "invalid_scim_resource",
  "message": "Exactly one email must be provided."
}
