### ISSUE TITLE
Better error message for failing SAML authentication

### ISSUE THREAD

**Issue by D031121** [cloudfoundry/uaa#703]
Hi,

in our CF setup, we have connected the CF UAA to an IdP, which again is backed by another IdP instance.
Authentication is done via SAML. CF UAA only knows the first IdP, the second re-direct is outside the UAA.
The second IdP has a broader user base, and we use the first one known to UAA to "filter" users.
In this setup following scenario can happen:
A user opens the CF login page, follows the link to the IdP, this one redirect to the second IdP and the user enters her credentials.
The credentials are accepted by the second IdP, but the user is not in the first IdP.
The login call is sent back the CF UAA which display following very technical error message:

_Response has invalid status code urn:Oasis:names:tc:SAML:2.0:Status:Responder, status message is Failed to authenticate user_.

Although the error is correct, an end user will likely have difficulties understanding what is wrong.
It would be helpful, if UAA would allow to customize this error message, so that instead of this error message, another more specific one can be displayed.

**Comment by sreetummidi** [comment]
We won't be able to address this. We are bubbling up all SAML errors for troubleshooting purposes and documentation and this case cannot be handled in a special manner.
