### ISSUE TITLE
external OIDC providers

### ISSUE THREAD

**Issue by scizeron** [cloudfoundry/uaa#706]
Hi,

With the 4.6.0, I use UAA with some external OIDC providers. My concern is about retrieving user's info. UAA only tries to get them from the id_token.

Some providers return only the sub claim in the id_token and the user's info are only accessible though a /userinfo endpoint.

Although the OIDCIdentityProviderDefinition class contains a field userInfoUrl, it is never used, there is no additional /userinfo request, so ...

Regards
Stéphane

**Comment by scizeron** [comment]
Here is a patch of XOAuthAuthenticationManager.java including the /userInfo request if it's specified in the related OIDC configuration.

[XOAuthAuthenticationManager.txt](https://github.com/cloudfoundry/uaa/files/1341393/XOAuthAuthenticationManager.txt)

**Comment by sreetummidi** [comment]
Could you please submit a PR for this feature
