### ISSUE TITLE
How to automatically add group user_attributes to users that are added via addShadowUserOnLogin

### ISSUE THREAD

**Issue by patricklunney** [cloudfoundry/uaa#715]
### How are you deploying the UAA?

I am deploying the UAA
- as part of a commercial Cloud Foundry distribution

### What did you do?

I've created a SAML IDP and tied a client to that IDP. When authenticating for the first time with a user 
`uaac token authcode get -c apphub-saml2 -s test123test --scope 'openid user_attributes'`
it creates the user, but it does not add the user_attributes group to the user, so I cannot see the external attributes mapped. 

When I manually add user_attributes to the user and re authenticate I am able to see the additional attributes I have mapped. 

How can I automatically add user_attributes as a group to the user upon auto provisioning. 

IDP Configuration: 
...
`"nameID":"urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
"attributeMappings":{
	"email":"mail",
	"given_name":"firstname",
	"family_name":"lastname",
	"phone_number": "telephonenumber",
	"user.attribute.title": "title",
	"user.attribute.gevdsGroupIDmemberOf": "gevdsGroupIDmemberOf",
	"user.attribute.street": "street",
	"user.attribute.city": "city",
	"user.attribute.st": "st",
	"user.attribute.c": "c",
	"user.attribute.company": "company"
},
"storeCustomAttributes": "true",
"showSamlLink":true,
"linkText":"Login with your GE Provided ID",
"assertionConsumerIndex":0,
"metadataTrustCheck":false,
"socketFactoryClassName":"org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory",
"iconUrl":null,
"addShadowUserOnLogin":true}'
`

**Comment by ilipkind** [comment]
@patricklunney you can set it using zone configuration: http://docs.cloudfoundry.org/api/uaa/version/4.6.0/index.html#updating-an-identity-zone userConfig.defaultGroups

**Comment by tnwang** [comment]
Yes ilipkind is right - starting in 4.5.0 you can set default groups via the update identity zone API or the UAA manifest: https://github.com/cloudfoundry/uaa/releases/tag/4.5.0

ilipkind has the links to the API, and the manifest value is here: 
uaa.yml: https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/resources/uaa.yml#L196-L210
uaa release spec: https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L509-L526
