### ISSUE TITLE
FAILURE on trying to startup UAA locally

### ISSUE THREAD

**Issue by dny27** [cloudfoundry/uaa#717]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
we have pulled down commit: 754f2716d3d8f2e227952f74adcfde5378b17b96

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
FAILURE

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?

git clone git://github.com/cloudfoundry/uaa.git
cd uaa
gradlew run

curl -H "Accept: application/json" localhost:8080/uaa/login

### What did you expect to see? What goal are you trying to achieve with the UAA?
We expect UAA to startup

### What did you see instead?
FAILURE
Please include UAA logs if available.
[uaa-server.log](https://github.com/cloudfoundry/uaa/files/1377299/uaa-server.log)

**Comment by pharout** [comment]
We got past this (it was an issue with configuring the SAML and signing keys incorrectly) by looking at the Readme for 3.9.2 ( https://github.com/cloudfoundry/uaa/releases/tag/3.9.2 ). Documentation could be improved. Please close.

**Comment by berndgoetz** [comment]
That readme from 3.9.2 isn't very helpful. setting that env variable doesn't help. I checked the source code, and could not find any production code reference to that required_configuration.yml file. But in my uaa.log startup logs, I find this entry:

`YamlProcessor: Could not load map from URL [file://C:/Users/srzgob/workspaces/cf-uaa/uaa/./uaa/src/main/resources/required_configuration.yml]: C`

Really strange. Any insights appreciated.

**Comment by BloodWorkXGaming** [comment]
I'm sorry for answering to such an old issue, however I just wanted to help anyone out running into the same issue and stumbling onto this issue:
 replacing: `-DLOGIN_CONFIG_URL=file://" + new File(".").absolutePath + "/uaa/sr...` by `-DLOGIN_CONFIG_URL=file:///" + new File(".").absolutePath + "/uaa/sr`  (tripple ///) fixed the issue for me due to reasons described here: https://stackoverflow.com/questions/2680837/java-net-unknownhostexception-on-file-method
The line to change is located here: https://github.com/cloudfoundry/uaa/blob/85d5c483ceb2d21cfafb3ed982fc011102ac2d62/build.gradle#L310

**Comment by dev-indb** [comment]
@BloodWorkXGaming  
Same issue. 
I replaced in build.gradle file `-DLOGIN_CONFIG_URL=file://"` by `-DLOGIN_CONFIG_URL=file:///" ` according to your solution and everything works now
Thanks for your help !

**Comment by parvathalap** [comment]
> I'm sorry for answering to such an old issue, however I just wanted to help anyone out running into the same issue and stumbling onto this issue:
> replacing: `-DLOGIN_CONFIG_URL=file://" + new File(".").absolutePath + "/uaa/sr...` by `-DLOGIN_CONFIG_URL=file:///" + new File(".").absolutePath + "/uaa/sr` (tripple ///) fixed the issue for me due to reasons described here: https://stackoverflow.com/questions/2680837/java-net-unknownhostexception-on-file-method
> The line to change is located here:
> 
> [uaa/build.gradle](https://github.com/cloudfoundry/uaa/blob/85d5c483ceb2d21cfafb3ed982fc011102ac2d62/build.gradle#L310)
> 
> Line 310 in [85d5c48](/cloudfoundry/uaa/commit/85d5c483ceb2d21cfafb3ed982fc011102ac2d62)
> 
>  jvmArgs = "-javaagent:${jacocoLocation}=output=file,dumponexit=true,append=false,destfile=${integrationTestCoverageExecutionData} -DLOGIN_CONFIG_URL=file://" + new File(".").absolutePath + "/uaa/src/main/resources/required_configuration.yml"

Thanks for saving my day
