### ISSUE TITLE
Unable to request oauth token for client in non-default identity zone

### ISSUE THREAD

**Issue by jamelseagraves** [cloudfoundry/uaa#719]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

```
{
  "app": {
    "version": "3.6.5"
  },
  "links": {
    "uaa": "http://localhost:8080/uaa",
    "passwd": "/forgot_password",
    "login": "http://localhost:8080/uaa",
    "register": "/create_account"
  },
  "zone_name": "uaa",
  "entityID": "cloudfoundry-saml-login",
  "commit_id": "83e1370",
  "idpDefinitions": {
    
  },
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ]
  },
  "timestamp": "2016-11-30T18:58:56+0100"
}
```

### How are you deploying the UAA?

I am deploying the UAA on a remote server with the public hortonworks/cloudbreak-uaa:3.6.5 Docker image.

### What did you do?

I created a new identity zone with Postman:

```
POST /identity-zones HTTP/1.1
Host: <ip address>:<port>
Content-Type: application/json
Authorization: Bearer <token>

{
  "id": "testzone1",
  "subdomain": "testzone1",
  "name": "Test Zone"
}
```
I received a success `201 Created`. Then I created a client in that identity zone with Postman:

```
POST /oauth/clients HTTP/1.1
Host: <ip address>:<port>
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>
X-Identity-Zone-Id: testzone1

{
  "scope": [
    "password.write"
  ],
  "client_id": "testclient",
  "client_secret": "testsecret",
  "authorized_grant_types": [
    "client_credentials",
    "password",
    "refresh_token"
  ],
  "redirect_uri": [],
  "authorities": [
    "zones.testzone1.scim.read",
    "zones.testzone1.scim.write",
    "uaa.user"
  ]
}
```
I received a success `201 Created`. Finally I tried to request a client credentials OAuth token also with Postman:

```
POST /oauth/token HTTP/1.1
Host: <ip address>:<port>
Content-Type: application/x-www-form-urlencoded
Accept: application/json
X-Identity-Zone-Id: testzone1

client_id=testclient&client_secret=testsecret&grant_type=client_credentials&token_format=opaque&response_type=token
```
I receive the following `401 Unauthorized` response:
```
{
    "error": "unauthorized",
    "error_description": "Bad credentials"
}
```
I even tried including the zone filter header `X-Identity-Zone-Id: testzone1`, but the response is the same.

I actually tried to request a client token with the CLI as well using the -z option and received the same response:
```
$ uaac token client get testclient -z testzone1
Client secret:  ****

error response:
{
  "error": "unauthorized",
  "error_description": "Bad credentials"
}
```

### What did you expect to see? What goal are you trying to achieve with the UAA?
I expected to see a `200 OK` response along with a payload containing the OAuth token. My goal is to use the client credentials token to then create users within the same "testzone1" zone. If I re-create the client in the default "uaa" identity zone, my client token requests work just fine.

My assumption is that the `/oauth/token` endpoint currently has no way to authenticate clients/users in different identity zones that are not the default, because I see in the logs (pasted below) it is looking to authenticate the client in the "uaa" zone.

### What did you see instead?

Here are the UAA logs:
```
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.709] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginAuthenticateRequestMatcher] Checking match of request : '/oauth/token'; '/authenticate' with parameters={} and headers {Authorization=[bearer ], accept=[application/json]}
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.709] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginAuthorizeRequestMatcher] Checking match of request : '/oauth/token'; '/oauth/authorize' with parameters={source=login} and headers {accept=[application/json]}
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.710] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginTokenRequestMatcher] Checking match of request : '/oauth/token'; '/oauth/token' with parameters={source=login, grant_type=password, add_new=} and headers {Authorization=[bearer ], accept=[application/json]}
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.710] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [loginAuthorizeRequestMatcherOld] Checking match of request : '/oauth/token'; '/oauth/authorize' with parameters={login={} and headers {accept=[application/json]}
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.710] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- UaaRequestMatcher: [passcodeTokenMatcher] Checking match of request : '/oauth/token'; '/oauth/token' with parameters={grant_type=password, passcode=} and headers {accept=[application/json, application/x-www-form-urlencoded]}
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.711] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- CorsFilter: CORS Processing request: URI: /oauth/token; Scheme: http; Host: <ip address>; Port: <port>; Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop; Method: POST
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.711] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- CorsFilter: Request cross origin request has passed validation.
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.711] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- IdentityZoneResolvingFilter: No root domains configured, UAA is catch-all domain for host:<ip address>
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.717] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: Processing id_token disable filter
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.717] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: pre id_token disable:false pathinfo:null request_uri:/oauth/token response_type:token
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.718] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: post id_token disable:false pathinfo:null request_uri:/oauth/token response_type:token
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.718] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Filter chain 'tokenEndpointSecurity' processing request POST /oauth/token
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.815] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] ....  INFO --- Audit: PrincipalAuthenticationFailure ('null'): principal=testclient, origin=[10.42.0.1], identityZoneId=[uaa]
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.815] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] ....  INFO --- Audit: ClientAuthenticationFailure ('Bad credentials'): principal=testclient, origin=[remoteAddress=<ip address>, clientId=testclient], identityZoneId=[uaa]
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.816] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- ClientParametersAuthenticationFilter: Could not authenticate with client credentials.
10/14/2017 2:30:02 PM[2017-10-14 21:30:02.818] cloudfoundry-identity-server - ???? [http-nio-8080-exec-2] .... DEBUG --- CorsFilter: CORS processing completed for: URI: /oauth/token; Scheme: http; Host: <ip address>; Port: <port>; Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop; Method: POST Status:401
10/14/2017 2:30:24 PM[2017-10-14 21:30:24.034] cloudfoundry-identity-server - ???? [ZoneAwareMetadataManager.Refresh[idpMetadataManager]] .... DEBUG --- ZoneAwareIdpMetadataManager: Running SAML SP refresh[ZoneAwareMetadataManager.Refresh[idpMetadataManager]-1859833227] - ignoreTimestamp=false
```

**Comment by jamelseagraves** [comment]
Ended up resolving my own issue. Sorry to bother. :)

**Comment by saumilsdk** [comment]
Hi @jamelseagraves can you please provide details how did you solve it? I am facing the same issue.

**Comment by jamelseagraves** [comment]
@saumilsdk sorry the late reply. Your message got lost in my inbox. UAA is set up to rely on subdomains in order to resolve for which identity zone you are requesting. In the build configuration file `uaa.yml`, there should be a list of hostnames that you define for the server. Here is an example configuration:
```
# A comprehensive list of hostnames routed to the UAA default zone. The UAA uses this to resolve subdomains for Identity Zones.
# Defaults to 'localhost'
zones:
  internal:
    hostnames:
      - localhost
      - example.com
```
When you make a request, UAA looks for a subdomain attached to one of those hostnames in that list. So using the example configuration, if the hostname of your request is `testzone.example.com`, then UAA tries to find an identity zone with `zone_id=testzone`. Otherwise if the hostname of your request is only `example.com`, then it will assume you are referencing the default identity zone `uaa`.

If the requesting client credentials have scope `uaa.admin` or zones.<zone_id>.admin`, then you can use one of the identity zone switching headers: `X-Identity-Zone-Id` or `X-Identity-Zone-Subdomain` as long as the request hostname matches one of those in your configuration list.

Hope this helps!

**Comment by saumilsdk** [comment]
Great help. After adding my domain in the zones -> Internal -> hostnames it solved the issue. Now it uses specific zone i mentioned in X-Identity-Zone-Id. Thanks

**Comment by singh-gurpreet** [comment]
@jamelseagraves I did tried everything but somehow i am not able to make it work still getting 100% same issue that you faced. My target it to make it working using X-Identity-Zone-Id not using Subdomain in URL. I did added uaa.admin and zones.testzone1.admin all kind of permission sto client but still getting 401 and same log as yours 

please help

**Comment by kurry786** [comment]
@jamelseagraves Hi, tried all scenarios. It would be grate if you can share the yml files and commands you have executed to fetch the token of a client from different identity zone.
Also, the unable to execute other apis of users in different identity zones . Your help will be highly appreciated

**Comment by jamelseagraves** [comment]
@kurry786 Hi, I am happy to help! Would you mind posting what steps you are taking (preferably with yml files and api calls/commands)? That way we can trace down what might be the issue.

**Comment by kurry786** [comment]
@jamelseagraves The steps I followed are creating identity zone and then creating a client for it and then fetching it. The yml file is as original with change for database.


1)uaac target http://localhost:8080/uaa



2)uaac token client get admin -s adminsecret

3)uaac client update admin --authorities "uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin,zones.testzone1.admin,zones.write"

4)uaac token client get admin -s adminsecret

5)uaac -t curl -XPOST -H"Content-Type:application/json" -H"Accept:application/json" --data '{ "id":"testzone1", "subdomain":"testzone1", "name":"The Twiglet Zone[testzone1]", "version":0, "description":"Like the Twilight Zone but tastier[testzone1]."}' /identity-zones


6)uaac -t curl -H"X-Identity-Zone-Id:testzone1" -XPOST -H"Content-Type:application/json" -H"Accept:application/json" --data '{ "client_id" : "admintestzone", "client_secret" : "admintestzonesecret", "scope" : ["uaa.none"], "resource_ids" : ["none"], "authorities" : ["uaa.admin","clients.read","clients.write","clients.secret","scim.read","scim.write","clients.admin"], "authorized_grant_types" : ["client_credentials"]}' /oauth/clients

7)uaac target http://testzone1.localhost:8080/uaa

8)uaac token client get admintestzone -s admintestzonesecret

error response:
{
  "error": "unauthorized",
  "error_description": "Bad credentials"
}
attempt to get token failed

**Comment by jamelseagraves** [comment]
@kurry786 okay. could you try using a direct api call (or curl) for steps 7+8 to get the client token in the new identity zone? Also, can you include the UAA server logs? Just helps to see a bit more what is happening under the hood. 😄

**Comment by jamelseagraves** [comment]
Also @kurry786 is your UAA server actually reachable at the url `testzone1.localhost:8080/uaa`?

**Comment by kurry786** [comment]
@jamelseagraves i have pasted this for reference . I have it running at localhost:7777. 
Well I have tried doing it and I get same errors

**Comment by jamelseagraves** [comment]
@kurry786 not sure if you meant to paste something else in your message?

**Comment by kurry786** [comment]
@jamelseagraves i have tried running the api calls but I get the same error but for default zone everything works well.
I was trying the autologin api . That also works only for default zone I am Able to fetch the code but for other zones it doesn’t work and says ‘ Bad-credentials’ error.

I believe the fix would be same for both

**Comment by kurry786** [comment]
Here are the logs 

[2020-02-20 10:34:57.734] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- UaaMetricsFilter: Successfully matched URI: /oauth/token to a group: /oauth-oidc
[2020-02-20 10:34:57.755] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- DisableIdTokenResponseTypeFilter: Processing id_token disable filter
[2020-02-20 10:34:57.755] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- DisableIdTokenResponseTypeFilter: pre id_token disable:false pathinfo:null request_uri:/oauth/token response_type:null
[2020-02-20 10:34:57.756] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- DisableIdTokenResponseTypeFilter: post id_token disable:false pathinfo:null request_uri:/oauth/token response_type:null
[2020-02-20 10:34:57.756] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Filter chain 'tokenEndpointSecurity' processing request POST /oauth/token
[2020-02-20 10:34:57.761] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- ClientBasicAuthenticationFilter: No client with requested id: test
[2020-02-20 10:34:57.762] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- ClientBasicAuthenticationFilter: Basic Authentication Authorization header found for user 'test'
[2020-02-20 10:34:57.846] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- ClientDetailsAuthenticationProvider: User 'test' not found
[2020-02-20 10:34:57.846] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] ....  INFO --- Audit: PrincipalAuthenticationFailure ('null'): principal=test, origin=[0:0:0:0:0:0:0:1], identityZoneId=[uaa]
[2020-02-20 10:34:57.847] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] ....  INFO --- Audit: ClientAuthenticationFailure ('Bad credentials'): principal=test, origin=[remoteAddress=0:0:0:0:0:0:0:1, clientId=test], identityZoneId=[uaa]
[2020-02-20 10:34:57.847] cloudfoundry-identity-server - ???? [http-nio-7777-exec-3] .... DEBUG --- ClientBasicAuthenticationFilter: Authentication request for failed: org.springframework.security.authentication.BadCredentialsException: Bad credentials
<img width="692" alt="testclient" src="https://user-images.githubusercontent.com/61245045/74927056-daf3ca80-53ce-11ea-82a5-713ebc5744c0.PNG">

**Comment by jamelseagraves** [comment]
@kurry786 do you see a line in your logs (probably just before what you pasted above) that contains `IdentityZoneResolvingFilter`? This filter is what should identify the subdomain and match it to an identity zone you have created. Please see if you can find that line in the logs and paste it here.

**Comment by kurry786** [comment]
@jamelseagraves No there is no such log for this operation. I just cleared the logs and ran this operation with client_id as 'hipc' and mt identityzone and sub domain is 'pc'

[2020-02-20 16:35:35.408] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] .... DEBUG --- UaaMetricsFilter: Successfully matched URI: /oauth/token to a group: /oauth-oidc
[2020-02-20 16:35:35.431] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] .... DEBUG --- DisableIdTokenResponseTypeFilter: Processing id_token disable filter
[2020-02-20 16:35:35.431] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] .... DEBUG --- DisableIdTokenResponseTypeFilter: pre id_token disable:false pathinfo:null request_uri:/oauth/token response_type:token
[2020-02-20 16:35:35.433] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] .... DEBUG --- DisableIdTokenResponseTypeFilter: post id_token disable:false pathinfo:null request_uri:/oauth/token response_type:token
[2020-02-20 16:35:35.433] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Filter chain 'tokenEndpointSecurity' processing request POST /oauth/token
[2020-02-20 16:35:35.596] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] .... DEBUG --- ClientDetailsAuthenticationProvider: User 'hipc' not found
[2020-02-20 16:35:35.597] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] ....  INFO --- Audit: PrincipalAuthenticationFailure ('null'): principal=hipc, origin=[0:0:0:0:0:0:0:1], identityZoneId=[uaa]
[2020-02-20 16:35:35.597] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] ....  INFO --- Audit: ClientAuthenticationFailure ('Bad credentials'): principal=hipc, origin=[remoteAddress=0:0:0:0:0:0:0:1, clientId=hipc], identityZoneId=[uaa]
[2020-02-20 16:35:35.597] cloudfoundry-identity-server - ???? [http-nio-7777-exec-6] .... DEBUG --- ClientParametersAuthenticationFilter: Could not authenticate with client credentials.

**Comment by jamelseagraves** [comment]
@kurry786 if you are not seeing that in your logs, that is why the zone switch is not happening. Without knowing more about your setup and configuration, it will difficult to know why that filter is not running. What version are you using? Did you clone and build from the GitHub repo? And can you provide the steps you took to set up, configure, and run the server?

**Comment by kurry786** [comment]
@jamelseagraves I am using version 4.2 May I know from which version the zone switching is supported

**Comment by jamelseagraves** [comment]
@kurry786 it should work for that version. Here is the file that sets the filters to be run [https://github.com/cloudfoundry/uaa/blob/4.2.0/uaa/src/main/webapp/WEB-INF/spring-servlet.xml](https://github.com/cloudfoundry/uaa/blob/4.2.0/uaa/src/main/webapp/WEB-INF/spring-servlet.xml)

Can you request a token from a client in the default `uaa` zone, and then share the logs? I am curious if the `IdentityZoneResolvingFilter ` runs when you do that.

**Comment by kurry786** [comment]
No, I dont see that. 

2020-02-20 19:01:00.138] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] .... DEBUG --- UaaMetricsFilter: Successfully matched URI: /oauth/token to a group: /oauth-oidc
[2020-02-20 19:01:00.412] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: Processing id_token disable filter
[2020-02-20 19:01:00.412] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: pre id_token disable:false pathinfo:null request_uri:/oauth/token response_type:token
[2020-02-20 19:01:00.413] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] .... DEBUG --- DisableIdTokenResponseTypeFilter: post id_token disable:false pathinfo:null request_uri:/oauth/token response_type:token
[2020-02-20 19:01:00.413] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Filter chain 'tokenEndpointSecurity' processing request POST /oauth/token
[2020-02-20 19:01:00.902] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] ....  INFO --- Audit: ClientAuthenticationSuccess ('Client authentication success'): principal=admin, origin=[remoteAddress=0:0:0:0:0:0:0:1, clientId=admin], identityZoneId=[uaa]
[2020-02-20 19:01:00.903] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] .... DEBUG --- BackwardsCompatibleTokenEndpointAuthenticationFilter: Processing token user authentication for grant:client_credentials
[2020-02-20 19:01:01.023] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] ....  INFO --- Audit: TokenIssuedEvent ('["clients.read","clients.secret","clients.write","uaa.admin","clients.admin","scim.write","scim.read"]'): principal=admin, origin=[client=admin], identityZoneId=[uaa]
[2020-02-20 19:01:01.112] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] ....  INFO --- JdbcRevocableTokenProvisioning: Removed 1 expired revocable tokens.
[2020-02-20 19:01:01.146] cloudfoundry-identity-server - ???? [http-nio-7777-exec-2] ....  INFO --- JdbcRevocableTokenProvisioning: Removed 0 expired revocable tokens.

**Comment by kurry786** [comment]
@jamelseagraves I have compared the files the one I have is a bit different including mfa providers . Can you call out specific line numbers which would enable the zone filters

**Comment by jamelseagraves** [comment]
@kurry786 so how did you get the build that you are using? did you clone and build it from the official github repo?

**Comment by kurry786** [comment]
@jamelseagraves Well, I had a jar file of it given to me by my colleagues on which I started to work on.

**Comment by kurry786** [comment]
@jamelseagraves i have tried to use the xml you shared. But the server starts with lot of exceptions.

**Comment by jamelseagraves** [comment]
@kurry786 Hmm... so my guess is your colleagues modified something in the server configuration that has caused the `IdentityZoneResolvingFilter` not to run. You may want to find out from them what changes they made that could be causing the issue. If they cannot help, your best bet would be to start with a fresh clone and build from the official github repo. The fix I outlined at the top of this thread works on the official build.

**Comment by kurry786** [comment]
@jamelseagraves  I have the IdentityZoneResolvingFilter in the xml and I have upgraded to the file resolving all errors. But I still see the same issue :-(

**Comment by kurry786** [comment]
> @kurry786 Hmm... so my guess is your colleagues modified something in the server configuration that has caused the `IdentityZoneResolvingFilter` not to run. You may want to find out from them what changes they made that could be causing the issue. If they cannot help, your best bet would be to start with a fresh clone and build from the official github repo. The fix I outlined at the top of this thread works on the official build.

@jamelseagraves I have taken the official build and ran the api. No luck. Then I have replaced with spring-servlet.xml which you have posted in thread. When I run api to get token for client present in default zone itself. I get so many class not found exceptions? Do I still need to use the xml when I am making the war from latest build

**Comment by kurry786** [comment]
> > @kurry786 Hmm... so my guess is your colleagues modified something in the server configuration that has caused the `IdentityZoneResolvingFilter` not to run. You may want to find out from them what changes they made that could be causing the issue. If they cannot help, your best bet would be to start with a fresh clone and build from the official github repo. The fix I outlined at the top of this thread works on the official build.
> 
> @jamelseagraves I have taken the official build and ran the api. No luck. Then I have replaced with spring-servlet.xml which you have posted in thread. When I run api to get token for client present in default zone itself. I get so many class not found exceptions? Do I still need to use the xml when I am making the war from latest build

@jamelseagraves I have put logs in  IdentityZoneResolvingFilter and when getSubdomain is called its going to the below if condition always where my hostname is always "localhost" and defaultZoneHostnames size is 2 which is testzone1.localhost and localhost itself. this condition is satisfied it is returning blank and its always picking up default zone . 
 if (defaultZoneHostnames.contains(hostname)) {
            return "";
        }

**Comment by jamelseagraves** [comment]
@kurry786 okay. so you have now built some version from the official repo? You should not have needed to replace any xml. Did you change anything with the hostnames in the build configuration file uaa.yml?
```# A comprehensive list of hostnames routed to the UAA default zone. The UAA uses this to resolve subdomains for Identity Zones.
# Defaults to 'localhost'
zones:
  internal:
    hostnames:
      - localhost```

**Comment by kurry786** [comment]
Yes I did . I added my zones. Yes, it defaults to localhost and getservername returns localhost so it satisfies first if condition and going gets default domain

**Comment by jamelseagraves** [comment]
@kurry786 Did you add `testzone1.localhost` to that list?

**Comment by kurry786** [comment]
> @kurry786 Did you add `testzone1.localhost` to that list?

Yes I did add.
But because it picks localhost by default . So the no.of zones is 2  and getservername returns localhost and it always goes to first if condition.

**Comment by kurry786** [comment]
Let’s take a case which is not localhost which has valid server name . I am not sure if I made any mistake in configuration . Because I infer this from logs 

Url of UAA http://myserver:7777
In yml file I have testzone1.myserver , testzone2.myserver.
Getservername returns myserver.
In this case it doesn’t satisfy first if condition. Goes into for loop and fails the second if condition as well and sub domain  returns null.

If I add myserver in the zones list . I end up going to default zone only

**Comment by jamelseagraves** [comment]
@kurry786 are you defining `testzone1.localhost` in your machine's hosts file to route to the local IP address of your UAA server? It needs to be a resolvable hostname for things to work properly.

**Comment by jamelseagraves** [comment]
Or if you are sending a curl or Postman request, you can use the Host header to overwrite the hostname of your request.

**Comment by kurry786** [comment]
> @kurry786 are you defining `testzone1.localhost` in your machine's hosts file to route to the local IP address of your UAA server? It needs to be a resolvable hostname for things to work properly.

Yes I have it done

**Comment by kurry786** [comment]
> Or if you are sending a curl or Postman request, you can use the Host header to overwrite the hostname of your request.

I can by-pass the first if , but when it goes to for loop the string operation is hostname.endswith(.+zone)...

Don’t u think it should be other way around which is zone.endwith(.+hostname) this satisfies the condition and gets the sub domain

**Comment by kurry786** [comment]
> Or if you are sending a curl or Postman request, you can use the Host header to overwrite the hostname of your request.

I can by-pass the first if , but when it goes to for loop the string operation is hostname.endswith(.+zone)...

Don’t u think it should be other way around which is zone.endwith(.+hostname) this satisfies the condition and gets the sub domain
