### ISSUE TITLE
Single character in domain invitation issue

### ISSUE THREAD

**Issue by LeePorte** [cloudfoundry/uaa#720]
### What version of UAA are you running?

v50 as per cf-release v275

### How are you deploying the UAA?

I am deploying the UAA using cf-release

### What did you do?

I attempted to add a user with the email format of `firstname.lastname@organisation.x.service.gov.uk`  using our create_user script located at https://github.com/alphagov/paas-cf/blob/master/scripts/create-user.sh

When using the same script with the email address format of `firstname.lastname@organisation.service.gov.uk` this succeeded. 

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected to see that the user invitation had been sent

### What did you see instead?

{"new_invites":[],"failed_invites":[{"email":"firstname.lastname@organisation.x.service.gov.uk","userId":null,"origin":null,"success":false,"errorCode":"provider.non-existent","errorMessage":"No authentication provider found.","inviteLink":null}]}ERROR: Error creating invite for firstname.lastname@organisation.x.service.gov.uk

This looks to be a domain validation issue where the hibernate domain validator is expecting at least two characters in each part of the domain.

**Comment by sreetummidi** [comment]
The error here is that there is not provider mapped to the domain : organisation.x.service.gov.uk
provider.non-existent is present in the error message
Please map the email domain on the identity provider: 

For LDAP : https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L779
For any other provider like SAML or OIDC please add the emailDomain property under the provider configuration

**Comment by tnwang** [comment]
A subsequent separate issue has helped identiy that by default the UAA internal user store will handle `*.*`, `*.*.*`, and `*.*.*.*` for the email domain matchers for invitations.

You should be able to configure `emailDomain` to further extend beyond that for `*.*.*.*.*` if required (http://docs.cloudfoundry.org/api/uaa/version/4.11.0/#update).

**Comment by richardTowers** [comment]
(I work on the same team as Lee) - we've just run into this for a 5 level subdomain email (because government). We'll be trying out adding the `*.*.*.*.*` pattern on Monday 🤣
