### ISSUE TITLE
User information from LDAP seems to be added to UAA/SCIM data model only once (when first logged in) and will not be updated afterwords.

### ISSUE THREAD

**Issue by martinsubash** [cloudfoundry/uaa#723]
**In CloudFoundry UAA-LDAP integration environment. I have faced the below issue.**

**User information from external security providers(LDAP) seems to be added to UAA/SCIM data model only once (when first logged in) and will not  be updated afterwords.**

Concrete Examples:
1.User data will be retrived during first login from LDAP. If, for instance, the surname is not set, it apperars as "unkown" in the UAA. Fixing that problem in the LDAP by correctly setting the user's surname is not reflected in the UAA. It still appears as "unkown" 
2.When deleting a user account in LDAP, this account appears still in UAA!

**UAA Version : 3.10.0**
**Run by Apache  server using uaa.yml configuration**

**Comment by tnwang** [comment]
Hi Martin,

This is expected behavior as UAA performs just-in-time provisioning for user accounts from the identity provider.

The user will not be able to authenticate or login to any applications as when they attempt to, it will update with LDAP status and lock the user out.

If you have an enterprise Identity Management system or scheduled scripts for LDAP, you can have it clean accounts out of UAA using the UAA APIs.

Regards,

Tian

**Comment by martinsubash** [comment]
As per your comment, UAA will sync user account only during the first request and there after any changes to the account in LDAP can be synchronized using a separate scripts independently. Is this the proposed workaround? is there a plan in future to have an auto synchronization in UAA itself.?

**Comment by tnwang** [comment]
Hi Martin,

I was unclear before. UAA will sync user accounts during the first request, and also during any subsequent login.

During the subsequent logins, all user attributes are updated again, and if the user was disabled, login will be rejected. So we have automatic synchronization via just-in-time provisioning.

If you wish to perform additional synchronization, the user APIs are available based on SCIM standard for identity management systems to integrate with (https://docs.cloudfoundry.org/api/uaa/version/4.7.1/index.html#update-3).
