### ISSUE TITLE
No Status Information for LDAP Connection.

### ISSUE THREAD

**Issue by martinsubash** [cloudfoundry/uaa#724]
In CloudFoundry UAA-LDAP integration environment.
How i will show the  status information for the current LDAP-Connection configured in the UAA by LDAP identity provider. 

**UAA Version : 3.10.0
Run by Apache server using uaa.yml configuration - Search and Bind authentication**

**Comment by tnwang** [comment]
LDAP calls are issued on user authentication to LDAP. You can find the information about individual LDAP calls in the UAA logs. 

Feel free to reopen this if you have a specific error or issue you'd like more info about.
