### ISSUE TITLE
Missing index on table groups for postgres

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#725]
### What version of UAA are you running?
4.7 from master branch

### How are you deploying the UAA?
I am deploying the UAA
- using cf-deployment
- into SAP Cloud Platform

### What did you do?

SQL monitor to check performance there

### What did you see ?
SQL with bad performance in postgres
select count(*) from groups where ((LOWER(displayName) = LOWER(?) and LOWER(identity_zone_id) = LOWER(?)))

### Workaround
We created a temp index

CREATE UNIQUE INDEX TMP_group__perf_group_lower_idx ON groups(LOWER(displayname),LOWER(identity_zone_id));

This increased performance significantly esp. if many groups entries exist.

Obviously only needed for postgres, because of
https://github.com/cloudfoundry/uaa/blob/master/server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V2_5_2__Zonify_Groups.sql

**Comment by strehle** [comment]
similar to #647

**Comment by strehle** [comment]
hi, @fhanik , should I create a PR for this ? because this hurt us very much on postgres

**Comment by sreetummidi** [comment]
Could you please submit a PR

**Comment by strehle** [comment]
@sreetummidi  see https://github.com/cloudfoundry/uaa/pull/736 however not yet delivered, but we can close it ;)

**Comment by 6palace** [comment]
Hi @strehle and @tack-sap , out of curiosity, when does `select count(*) from groups where ((LOWER(displayName) = LOWER(?) and LOWER(identity_zone_id) = LOWER(?)))` run on startup, and why is the lowercase index necessary? Also, have you guys run into problems with some group displaynames being only differentiated by upper/lowercase?

**Comment by strehle** [comment]
the lower index is something that is postgres specific. we found several of such issues with dynatrace monitoring and if we add the lower index (often in addition to existing index) then it speeds up.
