### ISSUE TITLE
many SQL requests to identity_provider table 

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#726]
### What version of UAA are you running?
4.7 from master branch

### How are you deploying the UAA?
I am deploying the UAA
- using cf-deployment
- into SAP Cloud Platform

### What did you do?

SQL monitor to check performance there

### What did you see ?
Many SQLs like
select id,version,created,lastmodified,name,origin_key,type,config,identity_zone_id,active from identity_provider where identity_zone_id=? and active=?

We use SAML2 for technical communication and therefore we have many SAML2 providers in each zone.

We created a temp. index 
CREATE INDEX active_in_zone ON identity_provider (identity_zone_id,active);

**Comment by tack-sap** [comment]
Introduced Index via f51616e
