### ISSUE TITLE
Internal hostnames not case-insensitive matched

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#730]
### What version of UAA are you running?
4.7.1 or develope

### How are you deploying the UAA?
cf push into own space

### What did you do?

created an own domain and defined in own YAML.
      zones:
        internal:
          hostnames:
            - uaa.domain.com

### What did you expect to see? What goal are you trying to achieve with the UAA?

curl -k https://uaa.domain.com/info  -> OK
curl -k https://UAA.DOMAIN.COM/info -> OK

### What did you see instead?

curl -k https://uaa.domain.com/info  -> OK
curl -k https://UAA.DOMAIN.COM/info -> cannot resolve zones exception

### Workaround
      zones:
        internal:
          hostnames:
            - uaa.domain.com
            - UAA.DOMAIN.COM

However the names should be matched case insensitive, https://tools.ietf.org/html/rfc4343
The zone resolution does a lower convert always, but the internal hostnames are matched as string.
Browser also convert names to lower case therefore there you cannot see it, but with curl

**Comment by tnwang** [comment]
Hi @strehle we see there's an extra O at the end of COM in https://UAA.DOMAIN.COMO/info

When we try upper casing, we see the response come back correctly. Could that be the cause?

**Comment by strehle** [comment]
HI @tnwang no I can see this issue with curl commands from a linux console, e.g.

curl -k https://UAA.DOMAIN.COM/info . I can see this also with a local running UAA with curl because of

https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneResolvingFilter.java#L74
instead of case ignore match

**Comment by sreetummidi** [comment]
@strehle PRs welcome :)
We won't be able to get to it anytime soon

**Comment by strehle** [comment]
@sreetummidi ok, I will do that, but please reopen it, I will assign this ticket to a PR and then it goes the standard way of a usual correction

**Comment by strehle** [comment]
hi @sreetummidi  , you mentioned PR is welcome, see #769
