### ISSUE TITLE
Find out if a token is a refresh or an access token

### ISSUE THREAD

**Issue by theomega** [cloudfoundry/uaa#737]
### What version of UAA are you running?
4.6.1
What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
```{"app":{"version":"4.6.1"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"04c8408","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2017-10-02T00:01:33+0000"}```

### How are you deploying the UAA?
Docker container built by us from the default JAR

### What did you do?
I have a string in my hands and want to know if it is
a) a valid access token
b) a valid refresh token
c) neither of the two

I can use the /check_token endpoint to check if a token is valid, but that will silently accept both access and refresh tokens and not tell the difference. The only solution which came to my minds was detecting the `-r` ending on refresh tokens, but that seems like a design-choice and could be changed with any update of the UAA. Is there any other possibility?

**Comment by jhamon** [comment]
I don't think there is any way to do this today apart from the `-r` suffix. The tokens are clearly labeled when they are issued to clients from the `/oauth/token` endpoint. Refresh tokens are usually kept secret by the client and used to get fresh access tokens on a periodic basis.

What is the usecase you're working on where you're not sure what kind of token you have?

**Comment by theomega** [comment]
We have services which talk with the UAA, these services are provided by the user with a string which the user pretends to be a token. For the service to validate that the token is really a token it is calling the /check_token endpoint. And then I run into the issue described above: If the user of the service mixes up some stuff and sends us a refresh-token instead of an access token, we can only distinguish between that by checking if the string ends with an `-r`.

**Comment by theomega** [comment]
For now we took the approach of detecting the `-r` at the end, we would be happy to have a better solution though.
