### ISSUE TITLE
Refreshing tokens leads into a "duplicate key value violates" on postgres

### ISSUE THREAD

**Issue by theomega** [cloudfoundry/uaa#743]
### What version of UAA are you running?
4.8.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
```{"app":{"version":"4.8.0"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"391163e","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2017-12-04T18:33:28+0000"}```

### How are you deploying the UAA?
Docker container containing the official JAR from Maven

### What did you do?
Refreshing a token

### What did you expect to see? What goal are you trying to achieve with the UAA?
I expect to not get any errors in the postgres log.

### What did you see instead?
The requests work fine, but I'm getting the following error in the postgres logs:
```
2017-12-07 15:58:34 UTC:10.3.88.28(60268):cloud_uaa@cloud_uaa:[29756]:ERROR: duplicate key value violates unique constraint "revocable_tokens_pkey"
2017-12-07 15:58:34 UTC:10.3.88.28(60268):cloud_uaa@cloud_uaa:[29756]:DETAIL: Key (token_id)=(1111111111111111111111111111111-r) already exists.
2017-12-07 15:58:34 UTC:10.3.88.28(60268):cloud_uaa@cloud_uaa:[29756]:STATEMENT: INSERT INTO revocable_tokens (token_id,client_id,user_id,format,response_type,issued_at,expires_at,scope,data,identity_zone_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
```

We traced this down to [UaaTokenServices.persistRevocableToken](https://github.com/cloudfoundry/uaa/blob/d80de75200dac005bb250edc0b9fb61b69247622/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServices.java#L762) which already contains a comment that this is a known bug. The code basically tries to insert the refresh token again into the database despite it being already there leading into the error above. Would it be possible to fix this error? I suggest that we pass into the persistRevocableToken whether is chould `create` or `update` to avoid the error. It is well known if the token should be already in the database or not.

Am I overlooking something?

The whole thing is quite a show-stopper for us because we are getting ERRORs in postgres which appear on our alerting. We could try to ignore them but I would rather try to fix the bug.

**Comment by theomega** [comment]
Any idea on this? Thanks!

**Comment by sreetummidi** [comment]
@jhamon or @fhanik can you comment on this

**Comment by DennisDenuto** [comment]
@tnwang  PostgreSQL since version 9.5 has `UPSERT` syntax that we *could* use to handle this. Alternatively we could explicitly have uaa query the  `revocable_tokens` table to determine whether a revocable token already exists to determine whether to `create` vs `update` (this approach would need to row locking to prevent race conditions)

**Comment by cppforlife** [comment]
common pattern that we use on bosh that works on all common dbs is to have
unique index on some column and catch exception for the update case.

**Comment by DennisDenuto** [comment]
@cppforlife Thanks for that. Also If this is a common pattern then it is likely other jobs will also generate similar errors in Postgres. 

@theomega, @jhamon and I think filtering out these `ERROR: duplicate key value violates` errors in your monitoring system is the preferred approach.

Also this also makes sense from a maintenance perspective, as this approach works across different db providers.
