### ISSUE TITLE
UAA database upgrade fails

### ISSUE THREAD

**Issue by martjarvi** [cloudfoundry/uaa#744]
### What version of UAA are you running?

4.7
### How are you deploying the UAA?

I am deploying the UAA to cloud foundry and building with Gradlew

### What did you do?

Deployed to cloud foundry from previous version 3.8 with SPRING_PROFILES_ACTIVE: ldap,default,postgresql

### What did you expect to see? What goal are you trying to achieve with the UAA?
Start the new version.

### What did you see instead?

Migration V3_10_0__UserInfo.sql failed, Location   : org/cloudfoundry/identity/uaa/db/hsqldb/V3_10_0__UserInfo.sql.

**Comment by sreetummidi** [comment]
If you are still seeing this error can you try upgrading to 3.14 first and then to the latest.
