### ISSUE TITLE
Highlight link for one-time passcodes

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/uaa#751]
### What version of UAA are you running?

4.7.2

### What did you do?

```
$ cf login -a api.cloud.world --sso
API endpoint: api.cloud.orld

One Time Code ( Get one at https://login.cloud.world/passcode )>
```

The `API endpoint: URL` is in bold and bright color, but the link our users actually need, https://login.cloud.world/passcode, is just regular text.

So our users copy/paste the API URL and wonder why they can't log in.

### What did you expect to see? What goal are you trying to achieve with the UAA?

The passcode URL should be clearly visible and obvious link to use.

![image](https://user-images.githubusercontent.com/1211146/34135817-db15bcd6-e430-11e7-8d34-324e996e135b.png)

**Comment by jhamon** [comment]
@pburkholder Please open this feature request on the [cf cli](https://github.com/cloudfoundry/cli) repo.
