### ISSUE TITLE
Release the 4.8.1 war to maven

### ISSUE THREAD

**Issue by theomega** [cloudfoundry/uaa#755]
The 4.8.1 war file is currently not released to maven. This was for previous released done by CF, can this be done again? Maybe this can be even automated...

**Comment by strehle** [comment]
@fhanik can you please deploy this and also 4.7.3 to maven central.e.g. 
http://central.maven.org/maven2/org/cloudfoundry/identity/cloudfoundry-identity-server/
thanks in advance,
-markus

**Comment by theomega** [comment]
Or at least the 4.8.3 now?

**Comment by sreetummidi** [comment]
4.7.x latest is available now
