### ISSUE TITLE
How can i change context root path?

### ISSUE THREAD

**Issue by mmielko** [cloudfoundry/uaa#756]
By default context root path is /uaa. I would like to change it to /. How can i achive this?

**Comment by strehle** [comment]
hi,
typically this /uaa context comes from the fact that you copy uaa.war into Tomcat webapps folder. Tomcat extracts this into folder /uaa and therefore you access the app via this context path.
If you copy uaa.war to ROOT.war then Tomcat starts this app under / (root) context.

if you use gradle the context is set in 
https://github.com/cloudfoundry/uaa/blob/master/build.gradle#L295
So you can use here also ROOT.
regards
markus

**Comment by mmielko** [comment]
Thanks Strehle. Everything is clear now.
