### ISSUE TITLE
Update to Javaconfig and Spring Boot

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/uaa#76]
Spring Boot should simplify some of the config (maybe with some name changes), and also make the app deployable from the war file trivially (great for devs that depend on UAA - no need for Maven or Tomcat installation). It would also be good to get the UAA onto to the "modern" standards for Spring apps. I've been doing some work here (see https://github.com/dsyer/uaa/tree/feature/bootify).

**Comment by fhanik** [comment]
Closing. This may be something we evaluate for a future endeavor

**Comment by talksinmath** [comment]
Is this issue closed for good? We'd actually be very interested in a Spring Bootfied version of UAA...

**Comment by fhanik** [comment]
the original fork has strayed way too far. It's not closed for good, but it is not imminent either.

**Comment by magaton** [comment]
I am also interested for the spring-boot version of UAA. Do you maybe have the list of the most notable features developed in UAA since Dave's fork, since we'd prefer to use that.

**Comment by bisbos** [comment]
I am also interested for the spring-boot version of UAA. Your help is very much appreciated

**Comment by tony-kerz** [comment]
+1 for [the boot](http://www.imdb.com/title/tt0082096/)

**Comment by adityaburra** [comment]
Eagerly waiting for the bootified UAA. Any plan of implementing this any time soon?

**Comment by Zenedith** [comment]
:+1:

**Comment by mor-anshuman** [comment]
@dsyer , What was the approach you were following to migrate this to Spring boot in terms of configurations, components, starter, security etc? Were you thinking to align things also as par boot design principles?

**Comment by dsyer** [comment]
Yes to the first question. Not sure what you mean by the second.

**Comment by isis-github** [comment]
I am also interested for the spring-boot version of UAA . Your help is very much appreciated!!!
