### ISSUE TITLE
UAA Shibboleth integration

### ISSUE THREAD

**Issue by Chaitanya0315** [cloudfoundry/uaa#760]
We are having a setup where Shibboleth acts as an IDP and UAA as SP. The authentication happens fine but the attribute sync up has been a problem.

The configuration we have on UAA : 
    shib-auth:
        idpMetadata: https://************/shibboleth
        nameID: urn:oasis:names:tc:SAML:1.1:nameid-unspecified
        assertionConsumerIndex: 0
        metadataTrustCheck: true
        showSamlLoginLink: true
        signatureAlgorithm: SHA256
        linkText: 'TEST'
        **attributeMappings: 
            email: email
            given_name: firstName**
        addShadowUserOnLogin: true
        emailDomain:
          - example.com
        providerDescription: '................'

Shibboleth IDP provides the following response : 
        <saml2:AttributeStatement>
            <saml2:Attribute FriendlyName="displayName"
                Name="urn:oid:2.16.840.1.113730.3.1.241" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>alpha</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="firstName"
                Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>alpha</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="userID"
                Name="urn:oid:0.9.2342.19200300.100.1.1" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>ALPHA</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="email"
                Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>alpha@alpha.com</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>

Why is UAA SP not able to read the email and other attributes from the SAML response?
Any inputs will be very helpful. Thanks.

**Comment by sreetummidi** [comment]
Can you please verify that you SAML Response contains these attributes

**Comment by sreetummidi** [comment]
I don't see anything visibly wrong with the set up. Can you get the user from the /Users endpoint and paste the response?

**Comment by Chaitanya0315** [comment]
We have one wrapper on top of UAA. Posting response from that service whihc gets the list of users from UAA

{
    "result": [
        {
            "id": "90137cdf-85f5-4626-8940-fdbf839fd855",
            "schemas": [
                "urn:scim:schemas:core:1.0"
            ],
            "userName": "uaaadmin",
            "name": {
                "familyName": "User",
                "givenName": "Admin"
            },
            "groups": [
                {
                    "value": "d7fc3bb3-550f-47a6-b9b9-5a95850ff9bb",
                    "display": "profile",
                    "type": "DIRECT"
                },
                {
                    "value": "c1ad8a7f-76a2-445a-9915-60c1af736738",
                    "display": "roles",
                    "type": "DIRECT"
                },
                {
                    "value": "6f5f4d6f-9ae3-4007-a1d2-169ddfa910f3",
                    "display": "scim.me",
                    "type": "DIRECT"
                },
                {
                    "value": "875f0a80-4fe3-44b2-b1bd-8bdfd5e6fbf3",
                    "display": "uaa.offline_token",
                    "type": "DIRECT"
                },
                {
                    "value": "ce756c23-c78e-4314-9dfb-e76360d6d839",
                    "display": "oauth.approvals",
                    "type": "DIRECT"
                },
                {
                    "value": "ad893754-2800-4525-86ac-18a29bd06eaf",
                    "display": "groups.update",
                    "type": "DIRECT"
                },
                {
                    "value": "9389726c-9fe6-4ea8-964b-4b95492ed223",
                    "display": "user_attributes",
                    "type": "DIRECT"
                },
                {
                    "value": "6a3bb7f5-6256-467a-b4e8-89cd5d84dd62",
                    "display": "uaa.admin",
                    "type": "DIRECT"
                },
                {
                    "value": "ef9ea493-f0d8-4a8d-bfba-780d9f1e7a08",
                    "display": "password.write",
                    "type": "DIRECT"
                },
                {
                    "value": "5542cb80-e046-4c6f-a5e2-1c7918b47641",
                    "display": "scim.read",
                    "type": "DIRECT"
                },
                {
                    "value": "06fcd39f-8903-4a90-a74a-8b2e2c80ada5",
                    "display": "openid",
                    "type": "DIRECT"
                },
                {
                    "value": "e47144cd-9740-438f-a4ec-9e16850c648d",
                    "display": "scim.write",
                    "type": "DIRECT"
                },
                {
                    "value": "08b43276-138f-4634-b711-ee651f8e6892",
                    "display": "approvals.me",
                    "type": "DIRECT"
                },
                {
                    "value": "0b601c3b-1bf2-44e4-8d0b-c2ed25e56408",
                    "display": "scim.userids",
                    "type": "DIRECT"
                },
                {
                    "value": "c8d4cabd-5303-464d-b55c-6a742d6555fe",
                    "display": "client.admin",
                    "type": "DIRECT"
                },
                {
                    "value": "303cba8a-8a13-4c96-a2b3-b122f9c961be",
                    "display": "scim.zones",
                    "type": "DIRECT"
                },
                {
                    "value": "14d03039-94f6-43b6-b7c8-d141d6ca0716",
                    "display": "uaa.resource",
                    "type": "DIRECT"
                },
                {
                    "value": "1bdb0c2c-47e7-401f-8151-0e8061e6d6eb",
                    "display": "uaa.user",
                    "type": "DIRECT"
                },
                {
                    "value": "b49e5099-9c0a-4148-802f-4364abb939d1",
                    "display": "scim.create",
                    "type": "DIRECT"
                }
            ],
            "emails": [
                {
                    "value": "admin@abcd.com",
                    "primary": false
                }
            ],
            "active": true,
            "verified": true,
            "origin": "uaa",
            "zoneId": "uaa"
        },
        {
            **"id": "8756e177-ccf2-4b66-861f-7af6004287ed",
            "externalId": "ALPHA",
            "schemas": [
                "urn:scim:schemas:core:1.0"
            ],
            "userName": "ALPHA",
            "name": {
                "familyName": "unknown.org",
                "givenName": "ALPHA"
            },**
            "groups": [
                {
                    "value": "9389726c-9fe6-4ea8-964b-4b95492ed223",
                    "display": "user_attributes",
                    "type": "DIRECT"
                },
                {
                    "value": "d7fc3bb3-550f-47a6-b9b9-5a95850ff9bb",
                    "display": "profile",
                    "type": "DIRECT"
                },
                {
                    "value": "06fcd39f-8903-4a90-a74a-8b2e2c80ada5",
                    "display": "openid",
                    "type": "DIRECT"
                },
                {
                    "value": "c1ad8a7f-76a2-445a-9915-60c1af736738",
                    "display": "roles",
                    "type": "DIRECT"
                },
                {
                    "value": "1bdb0c2c-47e7-401f-8151-0e8061e6d6eb",
                    "display": "uaa.user",
                    "type": "DIRECT"
                },
                {
                    "value": "6f5f4d6f-9ae3-4007-a1d2-169ddfa910f3",
                    "display": "scim.me",
                    "type": "DIRECT"
                },
                {
                    "value": "875f0a80-4fe3-44b2-b1bd-8bdfd5e6fbf3",
                    "display": "uaa.offline_token",
                    "type": "DIRECT"
                },
                {
                    "value": "ce756c23-c78e-4314-9dfb-e76360d6d839",
                    "display": "oauth.approvals",
                    "type": "DIRECT"
                },
                {
                    "value": "08b43276-138f-4634-b711-ee651f8e6892",
                    "display": "approvals.me",
                    "type": "DIRECT"
                },
                {
                    "value": "0b601c3b-1bf2-44e4-8d0b-c2ed25e56408",
                    "display": "scim.userids",
                    "type": "DIRECT"
                },
                {
                    "value": "ef9ea493-f0d8-4a8d-bfba-780d9f1e7a08",
                    "display": "password.write",
                    "type": "DIRECT"
                }
            ],
            "emails": [
                {
                    "value": "alpha@unknown.org",
                    "primary": false
                }
            ],
            "active": true,
            "verified": true,
            "origin": "shib-auth",
            "zoneId": "uaa"
        }
    ]}

**Comment by Chaitanya0315** [comment]
This debug log indicates that the yml settings are not being picked up.

[2018-01-18 00:12:37.757] cloudfoundry-identity-server - ???? [http-nio-8888-exec-9] .... DEBUG --- ScimUserBootstrap: Registering new user account: [UaaUser {id=NaN, username=ALPHA, email=ALPHA@unknown.org, givenName=ALPHA, familyName=unknown.org}]

Pl let me know if there are any alternative solutions for this.

**Comment by Chaitanya0315** [comment]
My other surprise was the field
**emailDomain:
- example.com**

Ideally this should be picked up irrespective of what SAML returns(unless the attribute is tied up only to LDAP settings), but ....

**Comment by Chaitanya0315** [comment]
/users response

{
    "app": {
        "version": "3.13.0"
    },
    "showLoginLinks": true,
    "links": {
        "uaa": "http://localhost:8080/uaa",
        "passwd": "/forgot_password",
        "login": "http://localhost:8080/uaa",
        "register": "/create_account"
    },
    "zone_name": "uaa",
    "entityID": "cloudfoundry-saml-login",
    "commit_id": "5ceabd7",
    "idpDefinitions": {
        "shib-auth": "http://localhost:8080/uaa/saml/discovery?returnIDParam=idp&entityID=cloudfoundry-saml-login&idp=shib-auth&isPassive=true"
    },
    "prompts": {
        "username": [
            "text",
            "Email"
        ],
        "password": [
            "password",
            "Password"
        ],
        "passcode": [
            "password",
            "One Time Code ( Get one at https://*********************/uaa/passcode )"
        ]
    },
    "timestamp": "2017-03-07T01:07:30+0000"
}

**Comment by sreetummidi** [comment]
We do a strict match on the emaildomain. If all users in your IDP don't have a consistent email domain, please don't set that value. Remove that and try again.

Please re-open the issue if its still not addressed
