### ISSUE TITLE
GDPR extension for UAA ??

### ISSUE THREAD

**Issue by smoser-ibm** [cloudfoundry/uaa#771]
Hi UAA-Team, 

I have a question for y'all: I am not sure that you are aware about GDPR (https://en.wikipedia.org/wiki/General_Data_Protection_Regulation).

GDPR is a law in Europe that will become effective mid-year 2018, and it includes a section about the "right to be forgotten" for Personal Information (PII). 
Now one could consider an email address stored in UAA as "PII", and therefore CF might be required to implement a "Right to be forgotten" in order to accomplish GDPR compliance. 
Today, UAADB stores records for deleted user marking them `inactive`, however in order to be GDPR compliant we believe we need to remove these records from live UAADB.

We have been thinking that UAA should expose an API for delete with a configurable deferred time, so that `DELETE /user/abc`  will mark a flag into UAADB to be removed in `x` days (graceful period to recover unwanted delete) and after x days UAA will purge the expired records. 

Can I get your viewpoint on this request ?

**Comment by smoser-ibm** [comment]
FWIW, this is not a EU-only issue, meaning that even a public service like PWS in the US that is storing data from European people will fall under that rule.

**Comment by sreetummidi** [comment]
Hello @smoser-ibm ,
Currently delete a user removes the entire user record along with any group memberships they may have. Can you elaborate on your user deletion flow.

Thanks,
Sree

**Comment by jhamon** [comment]
Just did a bit of investigation on this. It seems that user deletion only [deactivates the user](https://github.com/cloudfoundry/uaa/blob/ec713f0b4ea0da2f2f67252c8c811e073bf91cf8/server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java#L345) when you have [configured a standalone UAA instance](https://github.com/cloudfoundry/uaa/blob/ddea1e4e490348f5737a85e8b804276fd1b2632f/uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml#L28) with the `scim.delete.deactivate`. If you have not configured that property, we remove the user from the db. We don't expose this configuration through the uaa-release manifest properties, so I expect all running CF deployments to have delete behavior that complies with the expectations of the law.

**Comment by smoser-ibm** [comment]
@jhamon is it possible that this might get set in case we use a loginServer somehow ? I have to dig deeper on this next week, but I am positive that in our case the user is not deleted but marked inactive (so maybe we have scim.delete.deactivate configured somehow, as this would explain this)

**Comment by sreetummidi** [comment]
@smoser-ibm We are planning to get rid of Login Server in the next major version of UAA. We want to maintain only standards based integration via SAML/LDAP/OIDC

I suggest we have a discussion on this topic and have all stakeholders from IBM involved.  I will send an email with more details

**Comment by smoser-ibm** [comment]
@sreetummidi fair enough, please include Martin Smolny in that discussion.

**Comment by jhamon** [comment]
I'm going to close this issue as it seems the `scim.delete.deactivate` behavior is configurable and defaulting to the proper behavior. The future fate of the login server is unrelated to concerns about GDPR.

@smoser-ibm If you find you are not configuring `scim.delete.deactivate=true` in either `uaa.yml` or `login.yml` and you're still seeing the deactivation behavior, please open an issue with more details your configuration and reproduction steps and we will tackle it as a bug.

**Comment by smoser-ibm** [comment]
@sreetumidi @jhamon indeed I agree the "issue" is more on how our login flow works, so this ticket can be closed. Sorry for bothering. However, the concerns around login server remain and we need to talk about that - I will set up a phone call on that
