### ISSUE TITLE
failed to deploy uaa app to cloud foundry

### ISSUE THREAD

**Issue by GARENFEATHER** [cloudfoundry/uaa#783]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

- master branch the latest commit

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

- FAILURE

### How are you deploying the UAA?

I am deploying the UAA

- deploy to cloudfoundry as web service

### What did you do?

- cf login -a api.run.pivotal.io
- git clone git://github.com/cloudfoundry/uaa.git
- cd uaa
-  ./gradlew :cloudfoundry-identity-uaa:war
- cf push myuaarhine -m 1024M -p uaa/build/libs/cloudfoundry-identity-uaa-4.10.0.war --no-start
- cf set-env myuaarhine SPRING_PROFILES_ACTIVE default
- cf start myuaarhine
- curl -H "Accept: application/json" myuaarhine.cfapps.io/login

### What did you expect to see? What goal are you trying to achieve with the UAA?

- expect to see like this:

{ "timestamp":"2014-09-15T18:25:04+0000", "app":{"version":"1.8.3"}, "commit_id":"git-metadata-not-found", "prompts":{"username":["text","Email"], "password":["password","Password"] } }

- my goal is to create an admin account and enable diego_docker flag for a docker-base app
### What did you see instead?

- FAILURE

Please include UAA logs if available.

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jhamon** [comment]
Can you share application logs from this crash?

**Comment by GARENFEATHER** [comment]
@jhamon where are the log files?

**Comment by letkemanpete78** [comment]
@GARENFEATHER you can get to the logs by using the following command from the Cloud Foundry command line interface `cf logs NameOfApp --recent`. This will give you up to the last 150 lines of the log for that NameOfApp

Alternatively you can run `cf logs NameOfApp` while before and during the application request to get a live stream of the logs to get more log lines from your log

**Comment by raphaelschmitz** [comment]
Hi @letkemanpete78 

I have the same issue and here is the log: 

`   2018-03-15T17:22:30.12+0100 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2018-03-15T17:22:30.12+0100 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2018-03-15T17:22:30.12+0100 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2018-03-15T17:22:30.12+0100 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2018-03-15T17:22:30.12+0100 [RTR/1] OUT uaa.cfapps.sap.hana.ondemand.com - [2018-03-15T16:22:30.123+0000] "GET /favicon.ico HTTP/1.1" 503 0 7 "https://uaa.cfapps.sap.hana.ondemand.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "10.0.136.0:51630" "10.0.138.39:65528" x_forwarded_for:"155.56.44.143, 10.0.136.0" x_forwarded_proto:"https" vcap_request_id:"7c2d1173-77b9-495f-5009-eed8c422f9e7" response_time:0.003633976 app_id:"b710ee17-2a73-4f42-adb9-0ed203ec6a15" app_index:"0" x_b3_traceid:"c6676f08093bf59e" x_b3_spanid:"c6676f08093bf59e" x_b3_parentspanid:"-"
   2018-03-15T17:22:30.12+0100 [RTR/1] OUT `
best regards
Raphael

**Comment by raphaelschmitz** [comment]
Hi @letkemanpete78 

I have the same problem, but the logs looks normal. 

   2018-03-15T17:29:59.52+0100 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748)
   2018-03-15T17:29:59.53+0100 [RTR/2] OUT uaa.cfapps.sap.hana.ondemand.com - [2018-03-15T16:29:29.532+0000] "GET /favicon.ico HTTP/1.1" 503 0 7 "https://uaa.cfapps.ondemand.com/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "10.0.72.0:51254" "10.0.138.29:65528" x_forwarded_for:"155.56.44.143, 10.0.72.0" x_forwarded_proto:"https" vcap_request_id:"0198a331-f383-4067-7785-5e3f589d326c" response_time:0.004803803 app_id:"b710ee17-2a73-4f42-adb9-0ed203ec6a15" app_index:"0" x_b3_traceid:"74e43b258bede6d5" x_b3_spanid:"74e43b258bede6d5" x_b3_parentspanid:"-"

I followed this procedure: 
https://docs.cloudfoundry.org/concepts/architecture/uaa.html#custom-configuration

-> Deploy UAA to Cloud Foundry

best regards
Raphael

**Comment by letkemanpete78** [comment]
I still was unable to get this to work, so I moved on to the other lessons
which do not need these project setup.
However I would still very much like to know what the solution to this
problem is.

**Comment by raphaelschmitz** [comment]
HI @jhamon,

any updates or findings from your side?

best regards
Raphael

**Comment by letkemanpete78** [comment]
Sorry, I should clarify. I happened upon this and spoke up to let GARENFEATHER know how to get the logs.

I am experiencing an issue, but with a different UAA package which I'm going through on a training site.

**Comment by DennisDenuto** [comment]
From the logs you attached it looks like your spring web context failed to initialize correctly. `java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener or DispatcherServlet registered?`

Can you follow the instructions from https://github.com/cloudfoundry/uaa#deploy-to-cloud-foundry?
A couple of points to keep in mind when following the above instructions:
- Before pushing your app, please remember to update your [uaa config](https://github.com/cloudfoundry/uaa/blob/master/uaa/src/test/resources/sample-manifests/uaa-cf-application.yml#L63-L65) with your database url + username + password.
- Based on your log output, I think the command to generate your `cf` manifest will be: `./gradlew manifests -Dapp=uaa -Dapp-domain=cfapps.sap.hana.ondemand.com`

**Comment by GARENFEATHER** [comment]
sorry for the too-late response @DennisDenuto 
you said that I should update my database url + username + password, which means  an independent database is necessary for default UAA server?

**Comment by DennisDenuto** [comment]
Hi @GARENFEATHER yup that should work.

**Comment by GARENFEATHER** [comment]
@DennisDenuto If so I would prefer run it locally cz I have no server resources online now.... then I got error like this:

```
......
> Task :cloudfoundry-identity-server:jar UP-TO-DATE
:cloudfoundry-identity-server:jar took 43ms

> Task :cloudfoundry-identity-server:javadoc FAILED
:cloudfoundry-identity-server:javadoc took 31046ms


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloudfoundry-identity-server:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/garen/Desktop/uaa/server/build/tmp/javadoc/javadoc.options'
......
```

**Comment by shivansh** [comment]
> From the logs you attached it looks like your spring web context failed to initialize correctly. `java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener or DispatcherServlet registered?`
> 
> Can you follow the instructions from https://github.com/cloudfoundry/uaa#deploy-to-cloud-foundry?
> A couple of points to keep in mind when following the above instructions:
> 
> * Before pushing your app, please remember to update your [uaa config](https://github.com/cloudfoundry/uaa/blob/master/uaa/src/test/resources/sample-manifests/uaa-cf-application.yml#L63-L65) with your database url + username + password.
> * Based on your log output, I think the command to generate your `cf` manifest will be: `./gradlew manifests -Dapp=uaa -Dapp-domain=cfapps.sap.hana.ondemand.com`

@DennisDenuto

I have a locally running postgresql instance (`localhost:5432`), and the corresponding [db url](https://gist.github.com/shivansh/eea862e1dcb28019da69b2d2d7ecf301#file-uaa-cf-application-yml-L68) in the manifest is `jdbc:postgres://localhost:5432/postgres`. However when deployed, the cloud foundry instance will look for postgres in it's own (VM) localhost instead of my system's localhost. The obvious fix for this will be to specify the url of a remotely deployed postgresql instance. Although just for curiosity, is there some way to make this work with a local db instance ?

For reference, our cf manifest is located [here](https://gist.github.com/shivansh/eea862e1dcb28019da69b2d2d7ecf301).
