### ISSUE TITLE
JAR for 4.11 not pushed to Maven Central

### ISSUE THREAD

**Issue by theomega** [cloudfoundry/uaa#789]
The current version 4.11 is not available on Maven Central:
https://repo1.maven.org/maven2/org/cloudfoundry/identity/cloudfoundry-identity-uaa/

Can you please push the recent version there so we have an authoritative build?

And maybe, this can be done automatically?

@fhanik you did that previously, maybe you can help..

**Comment by DennisDenuto** [comment]
Closing as Filip has uploaded to https://repo1.maven.org/maven2/org/cloudfoundry/identity/cloudfoundry-identity-uaa/4.11.0/

We have a story to automate publishing to maven central as part of our 'ship it' pipeline epic. https://www.pivotaltracker.com/story/show/155158903
