### ISSUE TITLE
uaa.url shouldn't be case sensitive

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry/uaa#797]
### What version of UAA are you running?

```
{"version":"4.8.3"}
```

### How are you deploying the UAA?

Using the BOSH release via [fissile](https://github.com/suse/fissile)

### What did you do?

Used uppercase letters in `uaa.url` (the bosh property).

### What did you expect to see? What goal are you trying to achieve with the UAA?

UAA to function normally.

### What did you see instead?

404 responses when browsing/curl-ing the lowercase domain

**Comment by strehle** [comment]
hi, I think it is related to issue #730 and will be fixed with release of pull request #769

**Comment by viovanov** [comment]
@strehle good to know, thanks
