### ISSUE TITLE
How to deploy to production? 

### ISSUE THREAD

**Issue by harpratap** [cloudfoundry/uaa#799]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
4.11.0

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?

ran ./gradlew run

### What did you expect to see? What goal are you trying to achieve with the UAA?

Sorry, I am a noob at gradle and Java in general. But I cannot seem to find an easy way to generate output to deploy to production. From what I see, ./gradlew run will compile and run EVERYTHING, including samples, docs and tests. I just want the minimal way to start using uaa as a microservice (maybe a war to just deploy it on tomcat server and have all the APIs working or is there is a better and more efficient way people are using uaa in production?). I intend to deploy this as a docker container eventually (I know it is not supported officially as of now), but docker.gradle seems to run EVERYTHING too.  

### What did you see instead?

It runs EVERYTHING.

**Comment by jhamon** [comment]
For testing and running locally, we mostly use the `cargoRunLocal` task. You can also exclude unwanted intermediate tasks with the `-x` flag. For example:

```
./gradlew cargoRunLocal -x :cloudfoundry-identity-samples:assemble -x javadoc -x javadocJar
```

After about two minutes you should be able to visit the UAA at `http://localhost:8080/uaa/`. This local uaa is configured by editing values in the `uaa.yml` file. There should be a default administrative client called `admin` with client secret `adminsecret`.

As far as deploying to production, that is a large topic. You can build wars with `./gradlew war` and find them with `find . -name "*.war"`. But the recommended way of running UAA in production is using the [bosh release](https://github.com/cloudfoundry/uaa-release). You can learn more about using bosh from the quickstart guide [here](http://mariash.github.io/learn-bosh/).
