### ISSUE TITLE
Possibility to disable UAA redirect uri enforcement?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#803]
### What version of UAA are you running?
We're running UAA with the latest 3.x branch.

### How are you deploying the UAA?
We're deploying UAA as an app to CF.

### What did you do?

We're running a UAA as a Service offering (in our CF marketplace) that allows developers to obtain UAA clients for single-sign-on in their apps (the UAA is connected to our company's SAML IDP).

With UAA version 3 that we're currently running, we allow redirect url of clients with authorization code grant type to be `NULL`. We recently tried to upgrade it to UAA version 4, but figured out that would break a lot of clients that have no redirect url since [starting with 4.0.0, UAA enforces a redirect url to be set](https://github.com/cloudfoundry/uaa/releases/tag/4.0.0).

We would like to upgrade to version 4.0 to get the new features, but we unfortunately can't enforce clients to have a redirect url - there are about 200 clients that have no redirect url, and they are not in our (service provider's) control.

Could we have a flag that disables UAA redirect uri enforcement?

The only alternative is to provide a second service with UAA version 4.0.0 in parallel and slowly phase out the first, forcing all our users to migrate.

**Comment by tnwang** [comment]
Hi Matthias,

Open redirects are specifically warned against by the Oauth 2.0 spec (https://tools.ietf.org/html/rfc6749#section-10.15). We recommend doing the exercise clean-up, for the same reasons specified in the spec.

Some thoughts on how to perform the exercise:
1. If clients are already tied to these applications, you can have the people who own those clients add client specific redirect URIs.
2. If you know a set of known domains, you can whitelist those, or grab a list of them from the corporations/partners that own those domains. We allow wildcarding of paths within a domain, and I believe we also allow wildcarding of subdomains, so you don't have to individually wildcard every URL.
3. Looking through logs may provide some insight but may not be comprehensive. 

Thanks,

Tian

**Comment by MatthiasWinzeler** [comment]
@tnwang Thanks for your answer & the suggestions, we will work in this direction.
