### ISSUE TITLE
No validation of email for user API

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#804]
### What version of UAA are you running?

4.11.0 (or from dev)

### How are you deploying the UAA?

I am deploying the UAA
- locally only using gradlew
- using a bosh release I downloaded from bosh.io
- using cf-deployment
- as part of a commercial Cloud Foundry distribution

### What did you do?

-  create a new user, e.g. uaac user add testuser --emails i_like_snail_mail
- select a new pwd of your choice
-  uaac user get testuser

result
.....  
emails:
  -
    value: i_like_snail_mail
    primary: false
.....

### What did you expect to see? What goal are you trying to achieve with the UAA?

An exception or error (meaningful or generic)

### What did you see instead?

Any input is accepted for Email 

Please include UAA logs if available.
na.

**Comment by jhamon** [comment]
We reproduced this.
