### ISSUE TITLE
Unable to change a user's `origin` via the API

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/uaa#808]
### What version of UAA are you running?

4.11.0

### How are you deploying the UAA?

I am deploying the UAA using cf-deployment

### What did you do?

Migrate our users from UAA to a UAA IDP.

```bash
uaac user update user@example.com --origin idp-uaa
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected it to change the `origin` to 'idp-uaa'.

### What did you see instead?

```bash
CF::UAA::NotFound: CF::UAA::NotFound
```

The user does exist, as confirmed by running `uaac user get user@example.com`.

### The problems

There are two problems:

1. I am aware the API probably has to use this to identify the user, given a 'user' is uniquely identified by an aggregation of name, origin, and zone. However, we need to change the origin of all our users and would need to do this via the API, not via database hackery. Is there any way to do this via the API? If not, could you allow the changing of the `origin` via the API?
1. The documentation for the API does not state what the `origin` field is actually used for.

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. I think you are correct in that the uaa cli does not allow changing a user's origin.

I think one approach you can take to change the users origin is to the `/Users` API to [list](http://docs.cloudfoundry.org/api/uaa/version/4.12.0/#list-3) all the users (keep in mind this api uses pagination)

i.e. to list users with origin = uaa, and then use jq to 'map' each user to have a different origin ("new-origin")
```
uaac curl -k '/Users?filter=origin+eq+%22uaa%22'  | awk '/RESPONSE BODY/,0'  | grep -v 'RESPONSE BODY'  | jq '.resources[]' | jq '{
  "id" : "\(.id)",
  "userName" : "\(.userName)",
  "name" : {
    "familyName" : "\(.name.familyName)",
    "givenName" : "\(.name.givenName)"
  },
  "emails" : (.emails),
  "groups" : (.groups),
  "approvals" : (.approvals),
  "phoneNumbers" : (.phoneNumbers),
  "active" : (.active),
  "verified" : (.verified),
  "origin" : "new-origin",
  "zoneId" : "\(.zoneId)",
  "passwordLastModified" : "\(.passwordLastModified)",
  "schemas": (.schemas)
}'
```

You would then have to for every user mapped in the previous step, use the `/Users` api to [update](http://docs.cloudfoundry.org/api/uaa/version/4.12.0/#update-4) the user with the new origin

i.e. to update a single user
```
 uaac curl -X PUT -k '/Users/<<your user id goes here>>'  -H 'Accept: application/json'  -H 'Content-Type: application/json'  \
   -H 'If-Match: *' -d '<<your user json payload goes here>>
```

wrt documentation about the origin, the [api docs](http://docs.cloudfoundry.org/api/uaa/version/4.12.0/#get-3) states for the origin field: `The alias of the Identity Provider that authenticated this user. The value uaa indicates a user from the UAA's internal user store.`. Is this something you were aware of (is this a problem of discoverability of uaa docs)? , or does the above description about a users origin need expanding / clarification?

**Comment by DennisDenuto** [comment]
ping @henrytk

**Comment by henrytk** [comment]
@DennisDenuto thanks for the detailed response which solves the problem. I made a false assumption about the API based on the CLI, so really I should have raised this issue on the CLI repository. If it still causes pain in the future I shall raise an issue there.

> Is this something you were aware of (is this a problem of discoverability of uaa docs)?

No.

Closing this issue.
