### ISSUE TITLE
Could not find UaaMetrics object on MBean server. Please deploy UAA in the same JVM

### ISSUE THREAD

**Issue by JiaHaoJerry** [cloudfoundry/uaa#814]
### What version of UAA are you running?

UAA version: 4.12.1

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

 FAILURE

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?

I use command "gradlew run" to deploy UAA on my local machine. below is the error

```
> Task :assemble 
:assemble took 0ms

> Task :cleanCargoConfDir UP-TO-DATE
:cleanCargoConfDir took 0ms
<============-> 97% EXECUTING [1m 12s]
> :cargoRunLocal
```

And I check uaa-server.log under uaa/build/reports/tests/   Error as below:

```
Caused by: java.lang.IllegalArgumentException: KeyManager must be set
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.security.saml.metadata.MetadataManager.afterPropertiesSet(MetadataManager.java:156)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 111 more
2018-05-04 12:53:09.694  INFO 10996 --- [pool-2-thread-1] o.c.identity.statsd.UaaMetricsEmitter    : Could not find UaaMetrics object on MBean server. Please deploy UAA in the same JVM.
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

Expect to deploy UAA using gradlew on local successful.

### What did you see instead?

uaa log as attachment
[uaa-server.log](https://github.com/cloudfoundry/uaa/files/1973848/uaa-server.log)

**Comment by DennisDenuto** [comment]
Hello @JiaHaoJerry Thanks for creating this issue, unfortunately I am unable to reproduce. 
```
 git co 4.12.1
./gradlew run --info
Tomcat 8.x started on port [8080]
[ant:cargo] Press Ctrl-C to stop the container...
Press Ctrl-C to stop the container...
```

Can you please provide some information on your environment (OS/ java version)?

**Comment by JiaHaoJerry** [comment]
Hello @DennisDenuto Thanks for your reply. 
I use Windows10 to run UAA and  my java version is 1.8.0_131. 

I modify _uaa/webapp/WEB-INF/spring/saml-idp.xml_ to add <property name="keyManager" ref="idpZoneAwareSamlKeyManager"/> to bean "idpMetadataManager".
After do this the error _java.lang.IllegalArgumentException: KeyManager must be set_ did not appear . But the process still stop on 97%. The log as attachment
[uaa-server.log](https://github.com/cloudfoundry/uaa/files/1982451/uaa-server.log)

**Comment by DennisDenuto** [comment]
@JiaHaoJerry thanks for providing that information. Can you show the `git diff` of what you changed in `uaa/webapp/WEB-INF/spring/saml-idp.xml to add to bean "idpMetadataManager"`

**Comment by JiaHaoJerry** [comment]
@DennisDenuto 
uaa/webapp/WEB-INF/spring/saml-idp.xml 
Before edit the code as below:
 ```
  <bean id="idpMetadataManager"
          class="org.cloudfoundry.identity.uaa.provider.saml.idp.NonSnarlIdpMetadataManager"
          depends-on="spMetaDataProviders" destroy-method="destroy">
        <constructor-arg name="configurator" ref="spMetaDataProviders" />
        <property name="refreshCheckInterval" value="${login.saml.metadataRefreshInterval:0}" />
        <property name="generator" ref="zoneAwareIdpMetadataGenerator"/>
       
    </bean>
```

After edit:
  ```
 <bean id="idpMetadataManager"
          class="org.cloudfoundry.identity.uaa.provider.saml.idp.NonSnarlIdpMetadataManager"
          depends-on="spMetaDataProviders" destroy-method="destroy">
        <constructor-arg name="configurator" ref="spMetaDataProviders" />
        <property name="refreshCheckInterval" value="${login.saml.metadataRefreshInterval:0}" />
        <property name="generator" ref="zoneAwareIdpMetadataGenerator"/>
        <property name="keyManager" ref="idpZoneAwareSamlKeyManager"/>
    </bean>
```

**Comment by DennisDenuto** [comment]
Ping @JiaHaoJerry

**Comment by JiaHaoJerry** [comment]
@DennisDenuto It works. Thanks a lot.
