### ISSUE TITLE
Issue while running gradle run

### ISSUE THREAD

**Issue by navi2581** [cloudfoundry/uaa#816]
I am getting the below issue while executing gradle run

Could not GET 'https://plugins.gradle.org/m2/io/spring/gr
adle/propdeps-plugin/0.0.9.RELEASE/propdeps-plugin-0.0.9.RELEASE.pom'.
               > sun.security.validator.ValidatorException: PKIX path b
uilding failed: sun.security.provider.certpath.SunCertPathBuilderException: unabl
e to find valid certification path to requested target

**Comment by DennisDenuto** [comment]
Hi @navi2581 it looks like the [jdk truststore](https://docs.oracle.com/cd/E19830-01/819-4712/ablqw/index.html) you have installed on your local workstation is missing the CA certificate for 'https://plugins.gradle.org'.  Please refer [here](https://discuss.gradle.org/t/ssl-problem-when-downloading-plugin-from-openjdk-1-7/23430/4) for a discussion related to what you are experiencing. I think this issue belongs in https://discuss.gradle.org
