### ISSUE TITLE
Followed quickstart, got illegalargumentException

### ISSUE THREAD

**Issue by crizo23** [cloudfoundry/uaa#818]
### What version of UAA are you running?
4.13 (current)

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
nothing

### How are you deploying the UAA?
- locally only using gradlew

### What did you do?
./gradlew run from uaa root directory

### What did you see instead?

Please include UAA logs if available.
[uaa.log](https://github.com/cloudfoundry/uaa/files/1993381/uaa.log)

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. Hmm I am unable to reproduce this error.
I have tried:
```
git clone git@github.com:cloudfoundry/uaa.git
git co 4.13.0
./gradlew run -i
Tomcat 8.x started on port [8080]
[ant:cargo] Press Ctrl-C to stop the container...
Press Ctrl-C to stop the container...
```

Can you please confirm that you do not have any local changes in your uaa repo. Can you confirm that `./uaa/src/main/resources/required_configuration.yml` contains [the following properties](https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/resources/required_configuration.yml#L4-L8)

**Comment by crizo23** [comment]
@DennisDenuto Thanks for the reply.
The only local change I made was specifiying jdk 1.8 in gradle.properties. I added this:
org.gradle.java.home=C:/Program Files/Java/jdk1.8.0_92

And yes, I confirmed that required_configuration.yml exists and has those properties.
I also tried deleting all local maven and gradle caches but that had no affect.

**Comment by crizo23** [comment]
That patch works. Thanks @DennisDenuto !

**Comment by DennisDenuto** [comment]
Added a chore to fix it properly https://www.pivotaltracker.com/story/show/157576068
