### ISSUE TITLE
Secure flag for the X-Uaa-Csrf cookie

### ISSUE THREAD

**Issue by bandesz** [cloudfoundry/uaa#834]
### What version of UAA are you running?

UAA version: 4.12.1

### How are you deploying the UAA?

I am deploying the UAA using cf-deployment.

### What did you do?

```
curl -I <uaa url>/login
[...]
Set-Cookie: X-Uaa-Csrf=Ohd4coh4ceilucheengo0u; Max-Age=86400; Expires=Fri, 25-May-2018 09:39:20 GMT; Path=/; HttpOnly
[...]
```

This came up during our latest pentest as a low severity issue. If there is no specific reason to not to have the secure flag then it might be worth adding it as this could regularly come up in any pentest. 
To my understanding this doesn't pose any security risk.

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected to have the secure flag set on the `X-Uaa-Csrf` cookie.

**Comment by c4milo** [comment]
I was able to get this working in Tomcat by setting this Valve in server.xml and setting `require_https: true` in login.yml. I'm not using `cf-deployment` though. 

```
 <Valve className="org.apache.catalina.valves.RemoteIpValve"
        internalProxies="{{ id_api_proxy_ip }}"
        remoteIpHeader="x-forwarded-for"
        proxiesHeader="x-forwarded-by"
        protocolHeader="x-forwarded-proto"
        requestAttributesEnabled="true"
        httpsServerPort="{{ id_api_external_port }}"
        protocolHeaderHttpsValue="https" />
```

**Comment by bandesz** [comment]
@c4milo thanks for the response, you're right, the secure flag is added when we enabled `uaa.require_https` in UAA release.

I'm closing this issue.
