### ISSUE TITLE
Expose mail.debug config through uaa.yml 

### ISSUE THREAD

**Issue by c4milo** [cloudfoundry/uaa#836]
This is very useful when dealing with SMTP issues.

**Comment by DennisDenuto** [comment]
Hi @c4milo Thanks for creating this issue. It sounds like you are proposing a change to the uaa to improve debugging SMTP issues? (We are all for improving error messages and debugging uaa!)

Can you please provide details about the proposed change and what kind of issues you have faced with SMTP/uaa?
I am also not sure what you mean by exposing `mail.debug`.

**Comment by c4milo** [comment]
@DennisDenuto, I did until I realized UAA doesn't actually send any emails. The API and docs are pretty lacking in this regard.

**Comment by DennisDenuto** [comment]
@c4milo Fair enough. Improving uaa docs is definitely on the team radar. If you would like to have a go at improving docs we love PRs that improve docs :-)
