### ISSUE TITLE
Authorization Code Grant(Api flow)

### ISSUE THREAD

**Issue by JoshuaAndrew** [cloudfoundry/uaa#840]
### What version of UAA are you running?
What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
```
{
  "app": {
    "version": "4.13.0"
  },
  "links": {
    "uaa": "http://192.168.1.254:8080/uaa",
    "passwd": "/forgot_password",
    "login": "http://192.168.1.254:8080/uaa",
    "register": "/create_account"
  },
  "zone_name": "uaa",
  "entityID": "cloudfoundry-saml-login",
  "commit_id": "edc370f",
  "idpDefinitions": {},
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ]
  },
  "timestamp": "2018-05-04T06:14:22+0800"
}
```

### How are you deploying the UAA?
I am deploying the UAA with docker

### Questions
http://docs.cloudfoundry.org/api/uaa/version/4.13.0/#api-flow

**I found this document, but what puzzles me is that How can I obtain this bearer token within header??**

```
curl 'http://localhost/oauth/authorize?response_type=code&client_id=login&redirect_uri=http%3A%2F%2Flocalhost%2Fredirect%2Fcf&state=UwwAUV' -i   \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsIIADO5RgP4xLLFm88K16abwm-33AP4gwvVo1tkLSM8'
```

**If anyone can answer my question, I will be very grateful.**

**Comment by JoshuaAndrew** [comment]
@fhanik 
Can you give me some advice ?

**Comment by fhanik** [comment]
Any user token containing uaa.user scope. In the documentation it uses the token from a `cf login`

https://github.com/cloudfoundry/uaa/blob/7e83f4cb6c1d550422d567541892e6a95befb037/uaa/src/test/java/org/cloudfoundry/identity/uaa/login/TokenEndpointDocs.java#L133-L150

**Comment by JoshuaAndrew** [comment]
@fhanik 
Thanks,  I appreciate it
