### ISSUE TITLE
Docker/kubernetes deployment of UAA

### ISSUE THREAD

**Issue by agentgonzo** [cloudfoundry/uaa#842]
### How are you deploying the UAA?

I am _wanting to deploy_ the UAA

- other (please explain)
I want to be able to deploy UAA using docker (for me on kubernetes, but even a docker container would be fine). There are a few third-party images that people have build, but it would be ideal if we could have an official docker image

**Comment by JoshuaAndrew** [comment]
@agentgonzo 

**step 1  generate docker image**
```
root@k8s:~/workspace/uaa# export DOCKER_REPO_URL=index.tenxcloud.com
root@k8s:~/workspace/uaa# export DOCKER_REPO_USER=username
root@k8s:~/workspace/uaa# export MAINTAINER_EMAIL=someone@company.com

root@k8s:~/workspace/uaa# ./gradlew -x javadocJar -x sourceJar  clean buildImage
BUILD SUCCESSFUL in 52s
38 actionable tasks: 38 executed
Task timings:
    974ms  :cloudfoundry-identity-model:compileJava
  15024ms  :cloudfoundry-identity-server:compileJava
    706ms  :cloudfoundry-identity-statsd:compileJava
    960ms  :cloudfoundry-identity-statsd:war
   7541ms  :cloudfoundry-identity-uaa:war
   3267ms  :cloudfoundry-identity-samples:cloudfoundry-identity-api:war
   3361ms  :cloudfoundry-identity-samples:cloudfoundry-identity-app:war
  15854ms  :buildImage
Test timings:
```

**step 2 run uaa in docker**

```
root@k8s:~#  docker run -p 8080:8080 --name uaa -d --restart=always \
       -v /opt/uaa.yml:/uaa/uaa.yml                   \
       index.tenxcloud.com/username/uaa:4.14.0
```

**Comment by w7089** [comment]
@JoshuaAndrew 
does it mean that some 3rd party docker image belonging to _index.tenxcloud.com_ is used?

**Comment by JoshuaAndrew** [comment]
@w7089 
DOCKER_REPO_URL  can by any  docker image repo, It happened that I used _index.tenxcloud.com_ here

**Comment by w7089** [comment]
But there's no official docker repository of cloud foundry where image of uaa can be downloaded from, correct?

**Comment by DennisDenuto** [comment]
@w7089 The gradle task that builds a docker image (`./gradlew -x javadocJar -x sourceJar  clean buildImage`) was contributed by the community. The intent was for development usage only (it hardcodes private keys etc). However we have discovered that it has been used in the wild for production purposes. This plugin is considered by the team deprecated. We do not test this image in our pipeline, and thus we are not sure if it works. We have a plan to remove this plugin.

To answer your initial question, we do *not* have an official docker image published to run `uaa`.

We *do* have a recommended way to run the `uaa` which is via its [bosh release](https://github.com/cloudfoundry/uaa-release). bosh is a way to run software in different IaaSes (AWS, GCP, Vsphere, Docker etc). We would recommend to run uaa using bosh targeting docker as your Iaas.

If this approach interests you, then you can [look at our `uaa` acceptance tests](https://github.com/cloudfoundry/uaa-release/blob/develop/src/acceptance_tests/uaa-release_test.go) that runs uaa inside docker and runs tests against that deployment. This is the [bosh manifest that we use in our bosh docker deployment](https://github.com/cloudfoundry/uaa-release/blob/develop/src/acceptance_tests/uaa-docker-deployment.yml).

A quick way to create a bosh that targets a docker host would be to follow this [test script]( https://github.com/cppforlife/bosh-docker-cpi-release/blob/master/tests/run.sh). To target a docker host update https://github.com/cppforlife/bosh-docker-cpi-release/blob/master/tests/run.sh#L56
