### ISSUE TITLE
Feature request: time line for spring 5.x upgrade 

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#848]
Spring Framework 5 is out a while now and therefore the question is:
Are you planning an upgrade of usage in uaa ?

Some refactoring have to be done
https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x
e.g. guava , velocity

**Comment by jhamon** [comment]
We don't have a specific timeline. Are there features in Spring 5 you think we should be excited about?

**Comment by guptaarun111** [comment]
@cf-gitbot Guys, do we have any common channel where I can ask some question regarding UAA setup on my local machine.

**Comment by andrewedstrom** [comment]
We have now updated to Spring 5! Closing this out
