### ISSUE TITLE
Why does Change password redirect to "Profile"?

### ISSUE THREAD

**Issue by KMahesh045** [cloudfoundry/uaa#851]
I am trying to change my password in UAA using the URL: "uaa/change_password"

After successful password changes the change password dialog is automatically redirected to "uaa/profile". But after successful password changes how can I redirect to "uaa/login"?

**Comment by DennisDenuto** [comment]
@KMahesh045 Thanks for creating this issue. There is no configuration in the `uaa` to change where a user gets redirected after they change their password. 
It is hardcoded to go to 'uaa/profile' https://github.com/cloudfoundry/uaa/blob/fef6a0467e26737c94deb531f405a0c96df14b35/server/src/main/java/org/cloudfoundry/identity/uaa/account/ChangePasswordController.java#L79-L79

**Comment by KMahesh045** [comment]
@DennisDenuto Will it be taken as a feature request? or is there a issue available in backlog to make this as configurable? thanks.

**Comment by KMahesh045** [comment]
Hi @DennisDenuto Will it be reopened for the above comments? because the label shows "accepted" but the issue is still in closed state.
