### ISSUE TITLE
[docs] update sysadmin-guide for new JWT signing keys system

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/uaa#859]
https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#id8 documents the deprecated configuration for JWT signing keys; could this section be upgraded to the new syntax and also include a discussion on when/how to rotate keys?

**Comment by andrew-edgar** [comment]
We also need to know how the keys are rotated.  I attempted to rotate keys and it failed.  How can we get this documentation or instructions on how to perform the jwt key rotation?

**Comment by andrew-edgar** [comment]
why is this still not worked on.  We need to know how to rotate those keys as when I tried it it failed and caused an outage with UAA.  can somebody please let us know if and when this will be updated?

**Comment by joshuatcasey** [comment]
Hi @andrew-edgar - sorry for the issues. I'll be able to take a look at this once we get into Pacific time working hours. For now, any writeup you could provide with the steps you followed would be helpful.

**Comment by andrew-edgar** [comment]
That's the thing.  I do NOT have steps.  I need the UAA team to provide the steps on how to do the update with no downtime.
