### ISSUE TITLE
[api-docs] GET /Users/ID requires scim.read not scim.write

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/uaa#862]
TL;DR - I'm happy to fix the API docs - where are they?

The [current api docs for "Get a user"](http://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#get-3) say that `scim.write` or `uaa.admin` is required; but instead it is `scim.read`, `zones.uaa.admin`, or `uaa.admin`.

Demonstration:

```
uaa create-client user-lookup -s user-lookup \
  --authorized_grant_types client_credentials \
  --authorities "scim.read" \
  --scope "uaa.none"

uaa get-client-credentials-token user-lookup -s user-lookup
uaa curl /Users
```

This works.

If we change it to `scim.write` it does not work:

```
uaa get-client-credentials-token <admin> -s <admin secret>

uaa update-client user-lookup \
  --authorities "scim.write"
uaa get-client-credentials-token user-lookup -s user-lookup
uaa curl /Users --verbose
```

The error shows the three scopes:

```
{
  "error": "insufficient_scope",
  "error_description": "Insufficient scope for this resource",
  "scope": "uaa.admin scim.read zones.uaa.admin"
}
```

I'm happy to fix the API docs - where are they?

**Comment by DennisDenuto** [comment]
Hi @drnic, Thanks for creating this issue.

These docs are generated via 'test' code. 

https://github.com/cloudfoundry/uaa/blob/8bf1c4da49648f70de29645d5d5360e25ef82c3c/uaa/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointDocs.java#L681-L681

To run the test code and generate the [slate](https://github.com/lord/slate) markdown files you can use the gradle command: `./gradlew generateDocs`
