### ISSUE TITLE
Cannot get /token_key or /token_keys to return symmetric keys

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/uaa#867]
### What version of UAA are you running?

uaa-release v60 

### How are you deploying the UAA?

I am deploying UAA via uaa-release in virtualbox using https://github.com/starkandwayne/uaa-deployment

```
git clone https://github.com/starkandwayne/uaa-deployment
cd uaa-deployment
source <(bin/uaa-deployment env)
uaa-deployment up
source <(bin/uaa-deployment env)
uaa-deployment auth-client
```

### What did you do?

The UAA API docs say that `/token_key` should return symmetric keys if I provide `-u client:secret` for a client that has `uaa.resource` authority http://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#symmetric

I'm only getting asymmetric public key afaict.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Create a client:

```
uaa create-client symmetric-keys -s symmetric-keys-secret --authorized_grant_types client_credentials --authorities uaa.resource
```

Curl the endpoint:

```
curl -s --cacert $UAA_CA_CERT_FILE $UAA_URL/token_keys -H 'Accept: application/json' -u symmetric-keys:symmetric-keys-secret
```

The formatted output shows "BEGING PUBLIC KEY":

```json
{
  "keys": [
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "sig",
      "kid": "uaa-jwt-key-1",
      "alg": "RS256",
      "value": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8UNioYHjhyi1qSHrnBZ9\nKE96/1jLBOX2UTShGBo8jP7eDD6zUh5DNHNPAwD1V8gNI4wvNAm+zL1MrSEDWzn2\nPvCANd+XydoNVZU1zhqxvGhoxHmgAA3JbgSS3oLLNDG/HH8wEnjAxb+G1uh2EVSF\nAe/euQ/fEmY4e7uOG34h9WMX84tD1Sf/xvVoNGAL8bTwotzBLFZ12M3P70hrKDi5\n9wEBbY5bllvvNFyjZTYwMbw97RIOdg3FQkOABu8ENCqbPks5gqSpNV33ekaX4rAd\nwYdEX5iUzDBdMyD8jqUopuqTXqBKg2/ealGitXdbSIEAvcBgZWnn1j2vFp6OEYBB\n7wIDAQAB\n-----END PUBLIC KEY-----",
      "n": "APFDYqGB44cotakh65wWfShPev9YywTl9lE0oRgaPIz-3gw-s1IeQzRzTwMA9VfIDSOMLzQJvsy9TK0hA1s59j7wgDXfl8naDVWVNc4asbxoaMR5oAANyW4Ekt6CyzQxvxx_MBJ4wMW_htbodhFUhQHv3rkP3xJmOHu7jht-IfVjF_OLQ9Un_8b1aDRgC_G08KLcwSxWddjNz-9Iayg4ufcBAW2OW5Zb7zRco2U2MDG8Pe0SDnYNxUJDgAbvBDQqmz5LOYKkqTVd93pGl-KwHcGHRF-YlMwwXTMg_I6lKKbqk16gSoNv3mpRorV3W0iBAL3AYGVp59Y9rxaejhGAQe8"
    }
  ]
```

**Comment by DennisDenuto** [comment]
Hi @drnic Thanks for creating this issue. It looks like you have only configured an `rsa-sha256` key in your deployment (https://github.com/starkandwayne/uaa-deployment/blob/master/ops/2-uaa.yml#L43-L44)

If you want to see the 'symmetric' key you will need to create a `hmac-sha256` key. (Use any value *not* beginning with [`-----BEGIN`](https://github.com/cloudfoundry/uaa/blob/master/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/KeyInfo.java#L176-L185) as the [signingKey](https://github.com/starkandwayne/uaa-deployment/blob/master/ops/2-uaa.yml#L43).
