### ISSUE TITLE
Does UAA support email configuration for AWS SES? 

### ISSUE THREAD

**Issue by saumilsdk** [cloudfoundry/uaa#877]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew
- using a bosh release I downloaded from bosh.io
- using cf-release
- using cf-deployment
- as part of a commercial Cloud Foundry distribution
- other (please explain)

### What did you do?

If possible, provide a recipe for reproducing the error. Exact `curl` or `uaac` commands with verbose output are helpful. If your problem is configuration-related, please include portions of your uaa.yml or bosh deployment manifest that you believe may be relevant (but do not divulge secrets!)

### What did you see instead?

Please include UAA logs if available.

**Comment by drnic** [comment]
What did you try that didn’t work as expected? (You’ve not filled in the template for new issues - so it’s not possible to help specifically yet)

**Comment by saumilsdk** [comment]
Hi @drnic I couldn't try anything to integrate AWS Simple Email Service as there is no documentation as such. Does UAA support such extension?

**Comment by drnic** [comment]
I’ve not user SES but the configuration ropions for SMTP are demonstrated at 
https://github.com/cloudfoundry/uaa/blob/master/uaa/src/main/resources/uaa.yml#L628-632

**Comment by saumilsdk** [comment]
I have tried following configuration of uaa.yml and seems working fine. Closing the issue:
smtp:
  host: email-smtp.us-east-1.amazonaws.com
  port: 587
  username: <usernameOfSES>
  password: <passwordOfSES>
  auth: true
  starttls: true
