### ISSUE TITLE
cargoRunLocal was stuck

### ISSUE THREAD

**Issue by tirom** [cloudfoundry/uaa#885]
> Task :cargoRunLocal
Putting task artifact state for task ':cargoRunLocal' into context took 0.0 secs.
Up-to-date check for task ':cargoRunLocal' took 0.029 secs. It is not up-to-date because:
  Task.upToDateWhen is false.
Deployable artifacts = [E:\Learning\netcore\git\uaa_test\uaa\statsd\build\libs\cloudfoundry-identity-statsd-4.20.0-SNAPSHOT.war, E:\Learning\netcore\git\uaa_test\uaa\samples\api\build\libs\cloudfoundry-identity-api-4.20.0-SNAPSHOT.war, E:\Learning\netcore\git\uaa_test\uaa\samples\app\build\libs\cloudfoundry-identity-app-4.20.0-SNAPSHOT.war, E:\Learning\netcore\git\uaa_test\uaa\uaa\build\libs\cloudfoundry-identity-uaa-4.20.0-SNAPSHOT.war]
Config files = [E:\Learning\netcore\git\uaa_test\uaa\scripts\travis\tomcat-conf\context.xml -> conf]
Starting action 'run' for local container 'tomcat8x'
Container properties = [:]
System properties = [spring.profiles.active:default, metrics.perRequestMetrics:true, smtp.host:localhost, smtp.port:2525]
Downloading container from [https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/8.5.32/tomcat-8.5.32.tar.gz] to [E:\Learning\netcore\git\uaa_test\uaa\build\download\tomcat-8.5.32.tar.gz]
Installing container in [E:\Learning\netcore\git\uaa_test\uaa\build\extract\tomcat-8.5.32]
Tomcat 8.x starting...
Deploying [E:\Learning\netcore\git\uaa_test\uaa\statsd\build\libs\cloudfoundry-identity-statsd-4.20.0-SNAPSHOT.war] to [C:\Users\phong.nhu\AppData\Local\Temp\cargo\conf/webapps]...
Deploying [E:\Learning\netcore\git\uaa_test\uaa\samples\api\build\libs\cloudfoundry-identity-api-4.20.0-SNAPSHOT.war] to [C:\Users\phong.nhu\AppData\Local\Temp\cargo\conf/webapps]...
Deploying [E:\Learning\netcore\git\uaa_test\uaa\samples\app\build\libs\cloudfoundry-identity-app-4.20.0-SNAPSHOT.war] to [C:\Users\phong.nhu\AppData\Local\Temp\cargo\conf/webapps]...
Deploying [E:\Learning\netcore\git\uaa_test\uaa\uaa\build\libs\cloudfoundry-identity-uaa-4.20.0-SNAPSHOT.war] to [C:\Users\phong.nhu\AppData\Local\Temp\cargo\conf/webapps]...
Tomcat 8.x started on port [8080]
[ant:cargo] Press Ctrl-C to stop the container...
Press Ctrl-C to stop the container...
<============-> 97% EXECUTING [44m 18s]
> :cargoRunLocal

**Comment by jhamon** [comment]
What you are seeing is the expected behavior; this task does not complete or exit until manually killed. The log shows Tomcat has started on port 8080 so you should find UAA running at http://localhost:8080/uaa
