### ISSUE TITLE
Ability to publish event when user is created or updated

### ISSUE THREAD

**Issue by pratikkumar90** [cloudfoundry/uaa#886]
### What version of UAA are you running?

4.12

### How are you deploying the UAA?

I am deploying the UAA locally by deploying the war file (downloaded from maven repository) in a tomcat server (8.0+). 

### What did you do?

Trying to create users in UAA by invoking the "/Users" endpoints. 
Successfully able to create create/update users in UAA.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Once the user is created in UAA, is there a mechanism where an event can be triggered and published to another application (say an endpoint with the user information) so that we can create user in that application or carry out some other tasks.

**Comment by DennisDenuto** [comment]
@pratikkumar90 Thanks for creating this issue. AFAIK the UAA does not currently have an event based notification for when users are created.

In lieu of this feature you could however build a notification system from the existing APIs:
1) [list all the Users](https://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#list-3) sortBy `createdDate`, orderBy `descending` and count `1`. 
2) keep a reference to the only result.
3) Periodically [list all the Users](https://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#list-3) sortBy `createdDate`, orderBy `descending`
3.1) Iterate until you find the user referenced in step 2. These are all 'new' users that have been created 'recently'
3.2) save reference to the 1st user returned in step 3.
