### ISSUE TITLE
UAA not sending verification email on create user API

### ISSUE THREAD

**Issue by saumilsdk** [cloudfoundry/uaa#889]
I am creating a user in uaa zone. I am providing email with primary = true and verified = false. When i call the API user gets created but no email is sent out for verification.

**Comment by DennisDenuto** [comment]
@saumilsdk  Thanks for creating this issue, It looks like you haven't configured UAA's smtp server configuration. https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/resources/uaa.yml#L652-L656

**Comment by saumilsdk** [comment]
hey @DennisDenuto i have configured SMTP and verification email going if i do sign-up on webpage. But if I use API to create user, it doesn't send any verification email.

**Comment by DennisDenuto** [comment]
Hey @saumilsdk  Currently in the UAA the logic for when you create a user via the API is that a verification email is not sent. (This is true regardless if you set `verified` to true or not).

As you pointed out, using `uaa` self-service does send a verification email with a code that expires in an hour. One reason for this difference in behavior is you do not have to be authenticated/authorized to 'create a user' using self-service (Whereas to use the API you do)

Can you please share your use case / why you were hoping to have API create user send a verification email?

**Comment by saumilsdk** [comment]
The use case is we have set of users for which we want to generate the verification link via API. We don't want those users to go to webpage and do signup individually. So using API we want to add bulk user with verified=false until they verify the email.

**Comment by DennisDenuto** [comment]
Thanks for explaining @saumilsdk 

We are of the opinion that the create user api should only do a single action (without any side effects such as also sending an email). 

For your specific use case you might want to consider using the [invite users API](https://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#invite-users). You can specify multiple email address. The API generates an 'invite url' for each of the email addresses provided. It is then up to you to send an email containing the 'invite url' to the correct email address.

**Comment by rogeruiz** [comment]
Hey @DennisDenuto, I'm having an issue with shadow-user creation. Do these users still need to be `verified`? I'm not sure how to verify these users properly since all users created through our SAML integration are all added to UAA during their initial login. Is their a property to auto-verify users who've gone through the initial login? or possibly some other way?

**Comment by wc22222** [comment]
Hi @rogeruiz, may I know what's your use cases here? What are you trying to achieve here and what's the problem?

**Comment by gryffindor-001** [comment]
> hey @DennisDenuto i have configured SMTP and verification email going if i do sign-up on webpage. But if I use API to create user, it doesn't send any verification email.

What is the SMTP configuration you added, did you had a SMTP server? I am having the same issue, can you please help?

**Comment by gryffindor-001** [comment]
> hey @DennisDenuto i have configured SMTP and verification email going if i do sign-up on webpage. But if I use API to create user, it doesn't send any verification email.

What is the SMTP configuration you added, did you had a SMTP server? I am having the same issue, can you please help? @saumilsdk
