### ISSUE TITLE
Question: Need to understand flow of the client and user access tokens

### ISSUE THREAD

**Issue by saumilsdk** [cloudfoundry/uaa#891]
I have multi-tenant application. Where I wanted to have clients and users to be part of different tenants. I want to understand what is the sequence of creating client and user and tokens in the new identity zone to access the resources. Also provide what scope to use when. I could not find any documentation to provide such sequence diagram.

**Comment by jhamon** [comment]
This is not a use case we get asked about often. If you think of the tenants as virtual UAA's, you can probably see why the mainstream use case is for clients to get tokens for users residing in the same zone. 

It sounds like your scenario is:

You would like to obtain tokens for
Users in Zone A with a 
Client in Zone B

In that situation I would [create an OIDC **Identity Provider**](https://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#oauth-oidc) in **Zone B** that refers to **Zone A**. From there you should be able to log in as the **Zone A** user through **Zone B** and perform other token-related interactions.

**Comment by jhamon** [comment]
If you need help getting certain scopes to appear in the token, I need more details about your goals and client configuration. There's nothing too surprising here. A scope will appear in the token issued by UAA if 1) the client registration includes that scope in its registration 2) the user has group membership in the group with that name and 3) the user has approved the client's usage of that scope (or the client was configured with `autoapprove: true`).

**Comment by saumilsdk** [comment]
Hi @jhamon use case is simple where as admin (ops) i want to create as many tenants as my different org. And i want to create users, clients and all things under that. What i understood is this flow:
1. Create a zone admin client using "admin" client.
2. Using zone admin client, create as many users as needed.
3. Create a different client with required scope in that zone.
4. Use password grand_type passing client and user creds and get access token. 

Let me know if this flow is correct.

**Comment by jhamon** [comment]
That sounds like a reasonable approach to me. 👍
