### ISSUE TITLE
Implement PATCH /identity-zones/{id}

### ISSUE THREAD

**Issue by adamdyga** [cloudfoundry/uaa#894]
### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

```
{"app":{"version":"4.20.0-SNAPSHOT"},"showLoginLinks":true,"links":{"uaa":"http://<hidden>","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"api","entityID":"api-saml-login","commit_id":"ed8120b","idpDefinitions":{"api":"http://localhost:8080/uaa/saml/discovery?returnIDParam=idp&entityID=api-saml-login&idp=api&isPassive=true"},"prompts":{"username":["text","Email"],"password":["password","Password"],"passcode":["password","Temporary Authentication Code (Get on at /passcode)"]},"timestamp":"2018-08-19T04:01:49+0200"}
```

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew
- other (please explain) - by building Docker image and running it in Kubernetes

### What did you do?

Created identity zone and wanted to update some of it properties afterwards.

### What did you expect to see? What goal are you trying to achieve with the UAA?

I'm trying to update certain properties of an existing identity zone using the `/identity-zones` endpoint. Currently this endpoint only supports PUT and GET methods. PUT replaces the entire identity zone definition. Because of that it's not possible to update a single field in the zone. It's especially hard to use because you can't even execute `GET /identity-zone/{id}` followed by PUT, because GET doesn't return all the information. For instance, it doesn't return keys certificates in `config.samlConfig` or `config.tokenPolicy`, which is probably fine because for security reasons. Unfortunately this forces the user to keep the entire identity-zone definition, including the keys, somewhere on a side, just in case they want to change a single field.

### Possible solution

Implement `PATCH /identity-zone/{id}` where the user is allowed to update only a subset of properties.

**Comment by DennisDenuto** [comment]
@adamdyga Thanks for creating this issue. This is currently a known limitation with our api. We currently have a story in our [public backlog that captures this issue](https://www.pivotaltracker.com/story/show/155481815) for the identity zone resource as well as other endpoints to be PATCHable. 

Closing as this is a duplicate.
