### ISSUE TITLE
JWT header includes parameter cty with null value

### ISSUE THREAD

**Issue by mwdb** [cloudfoundry/uaa#914]
https://github.com/cloudfoundry/uaa/blob/5c9fb47e34de30df97fdd6670e055423e0023e0f/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwt/HeaderParameters.java#L26

With change https://www.pivotaltracker.com/n/projects/997278/stories/161025678 the parameter cty is included with a null value, e.g.
{
"alg": "RS256",
"kid": "key-1",
"typ": "JWT",
"cty": null
}

In contrast to that, the specification https://tools.ietf.org/html/rfc7519#page-11 recommends the cty parameter only to be included for non-null

5.2.  "cty" (Content Type) Header Parameter

   The "cty" (content type) Header Parameter defined by [JWS] and [JWE]
   is used by this specification to convey structural information about
   the JWT.

  In the normal case in which nested signing or encryption operations
   are not employed, the use of this Header Parameter is NOT
   RECOMMENDED.  ...

We have received reports that the cty with null value breaks with some client implementations.

**Comment by jspawar** [comment]
@mwdb Thank you for filing this, it has been closed with #915
