### ISSUE TITLE
UAA - DB Script

### ISSUE THREAD

**Issue by kumarjeyaprakasam** [cloudfoundry/uaa#918]
Is there a way to avoid Flyway db migrated and do DB setup prior to starting UAA? And as UAA starts up it updates the DB with UAA.yml and Login.yml information.

**Comment by DennisDenuto** [comment]
@kumarjeyaprakasam The UAA only supports running DB migrations during startup.
There is currently no way to run these migrations in a different part of its lifecycle.

May I know what problem you are trying to solve? What is the use case for being able to control when to run your DB migrations?

**Comment by kumarjeyaprakasam** [comment]
Hi Dennis,
I am currently trying to implement UAA for a client. I have three issues
1. The client wants to use Oracle as the DB. I donot see there is out of box support for this. Is there ddl and dml scripts available?2. The DB script which come as part of UAA are split into multiple migration script so I am not able to convert the db script to Oracle db script3. The UAA startup updates the DB with values from UAA.yml and login.yml. Is there a way to load UAA.yml and login.yml configuration using a dbscript or api?
with regards,
Kumar Jeyaprakasam
kumarjeyaprakasam@yahoo.co.in
 

    On Friday, 9 November, 2018, 6:54:59 PM GMT, Dennis Leon <notifications@github.com> wrote:  
 
 
@kumarjeyaprakasam The UAA only supports running DB migrations during startup.
There is currently no way to run these migrations in a different part of its lifecycle.

May I know what problem you are trying to solve? What is the use case for being able to control when to run your DB migrations?

**Comment by DennisDenuto** [comment]
Thanks for sharing your use case. It is unfortunately one that we do not support.

- The uaa does not support Oracle DB. There are no DB scripts for that db.
- It is not possible to load `uaa.yml` or `login.yml` configuration via a db script or api.

Closing as this is not something we intend to change - at least in the foreseeable future.
