### ISSUE TITLE
Issues with token revocation in 4.24.0

### ISSUE THREAD

**Issue by sebastianGit** [cloudfoundry/uaa#927]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
<pre>
{
    "app": {
       "version": "4.24.0"
    },
    "links": {
        "uaa": "http://localhost:8080/uaa",
        "passwd": "/forgot_password",
        "login": "http://localhost:8080/uaa",
        "register": "/create_account"
    },
    "zone_name": "uaa",
    "entityID": "cloudfoundry-saml-login",
    "commit_id": "16d9900",
    "idpDefinitions": {},
    "prompts": {
        "username": [
            "text",
            "Email"
        ],
        "password": [
            "password",
            "Password"
        ]
    },
    "timestamp": "2018-11-06T01:20:26+0000"
} 
</pre>

### How are you deploying the UAA?

I am deploying the UAA

- locally

uaa.yml configuration part related to revocation (here: refresh token case)
<pre>
jwt:
  token:
    refresh:
      format: opaque
      restrict_grant: true
      unique: false
    revocable: false
</pre>

### What did you do?

Revoke a single refresh token (tried both opaque refresh token & revokable JWT as refresh token - error is the same for opaque refresh token and jwt refresh token)

**Revocation request** (here opaque refresh token):
curl 'http://localhost:8080/uaa/oauth/token/revoke/487ef991be124a11accbbba85e0400c4-r' -i -X DELETE \
    -H 'Authorization: Bearer 487ef991be124a11accbbba85e0400c4-r'

### What did you expect to see? What goal are you trying to achieve with the UAA?

**Expected response**
HTTP/1.1 200 OK

### What did you see instead?

**Actual response**
HTTP status 401
{
    "error": "invalid_token",
    "error_description": "The token does not bear a &quot;scope&quot; claim."
}

Please include UAA logs if available.

[INFO] [talledLocalContainer] [2018-12-05 14:45:50.017] cloudfoundry-identity-server - ???? [http-nio-8080-exec-10] .... DEBUG --- UaaMetricsFilter: Successfully matched URI: /uaa/oauth/token/revoke/487ef991be124a11accbbba85e0400c4-r to a group: /token-api
[INFO] [talledLocalContainer] [2018-12-05 14:45:50.020] cloudfoundry-identity-server - ???? [http-nio-8080-exec-10] .... DEBUG --- DisableIdTokenResponseTypeFilter: Processing id_token disable filter
[INFO] [talledLocalContainer] [2018-12-05 14:45:50.021] cloudfoundry-identity-server - ???? [http-nio-8080-exec-10] .... DEBUG --- DisableIdTokenResponseTypeFilter: pre id_token disable:false pathinfo:null request_uri:/uaa/oauth/token/revoke/487ef991be124a11accbbba85e0400c4-r response_type:null
[INFO] [talledLocalContainer] [2018-12-05 14:45:50.021] cloudfoundry-identity-server - ???? [http-nio-8080-exec-10] .... DEBUG --- DisableIdTokenResponseTypeFilter: post id_token disable:false pathinfo:null request_uri:/uaa/oauth/token/revoke/487ef991be124a11accbbba85e0400c4-r response_type:null
[INFO] [talledLocalContainer] [2018-12-05 14:45:50.021] cloudfoundry-identity-server - ???? [http-nio-8080-exec-10] .... DEBUG --- SecurityFilterChainPostProcessor$HttpsEnforcementFilter: Filter chain 'tokenRevocationFilter' processing request DELETE /uaa/oauth/token/revoke/487ef991be124a11accbbba85e0400c4-r
[INFO] [talledLocalContainer] [2018-12-05 14:45:50.073] cloudfoundry-identity-server - ???? [http-nio-8080-exec-10] .... ERROR --- TokenValidation: The token does not bear a "scope" claim.

**Comment by davipc** [comment]
Hi @sebastianGit @cf-gitbot I'm having the same issue.

Even if using the JTI in the request, it never revokes the refresh token. 
It will only revoke **access tokens** acquired through calls to _uaa/oauth/token_ with _grant_type:refresh_token_ and using the refresh token to acquire it. You will also need to inform the JTI returned on that response to revoke that access token.

Is it possible at all to revoke the refresh token itself?

-----------------------------------------------------------------------------------------------------
**EDIT:** 

It does work, I found the issue in the way I was using it.
The proper way to use it to remove either access or refresh tokens is to pass the token to be deleted in the URL / Path Request, and the access token as the bearer.

**For Refresh Tokens:**

curl 'http://localhost:8080/uaa/oauth/token/revoke/487ef991be124a11accbbba85e0400c4-r' -i -X DELETE
-H 'Authorization: Bearer <your access token, not the refresh token>'

**For any access tokens acquired through the refresh token process:**

curl 'http://localhost:8080/uaa/oauth/token/revoke/<your access token, not the refresh token>' -i -X DELETE
-H 'Authorization: Bearer <your access token, not the refresh token>'

**Comment by shamus** [comment]
Closing this issue as it seems the original issue was user error.  Please feel free to open a new issue if you believe future action is necessary.

Thanks!
