### ISSUE TITLE
Does not compile with Java 11 - simple fix

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [cloudfoundry/uaa#933]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
- without the below mentioned small changes, openjdk 11 reports a compile error because it cannot find the classes that were removed from java 11.
- with the changes, I am running the current develop version (commit hash 9394af61) and get the output {"app":{"version":"4.27.0-SNAPSHOT"}, ...

### How are you deploying the UAA?

I am deploying the UAA
- locally only using gradlew

### What did you do?

git clone ...
cd uaa
./gradlew run

### What did you expect to see? What goal are you trying to achieve with the UAA?

BUILD SUCCESSFUL (resp. the uaa starts as usual with the run target)

### What did you see instead?

It fails on JDK 11:

(only showing the relevant parts of the output and only the main error that causes all 3 compile errors)

```
> Task :cloudfoundry-identity-server:compileJava
...
...\uaa\server\src\main\java\org\cloudfoundry\identity\uaa\oauth\OpenIdSessionStateCalculator.java:8: error: package javax.xml.bind does not exist
import javax.xml.bind.DatatypeConverter;
                     ^
...
3 errors
> Task :cloudfoundry-identity-server:compileJava FAILED
...
BUILD FAILED in 18s
```

### Quick fix 

To make it compile with JDK 11, I added to uaa/server/build.gradle at top level, just below the main dependencies block:

```
if(JavaVersion.current() >= JavaVersion.VERSION_11) {
  dependencies {
    compile 'javax.xml.bind:jaxb-api:2.3.0'
    compile 'com.sun.xml.bind:jaxb-core:2.3.0'
    compile 'com.sun.xml.bind:jaxb-impl:2.3.0'
  }
}
```

Not sure if this is the best available solution, but it worked. To make it work with Java 8 one would probably have to hardcode the java VERSION_11 constant, as it is not available in java 8.

It causes the server to compile and start as expected (for successful startup, I also had to apply the fixes mentioned in #911 ).

**Comment by andrewedstrom** [comment]
UAA now builds with java 11! :)
