### ISSUE TITLE
UAA quickstart problems. Can't get it working after many many hours.

### ISSUE THREAD

**Issue by martabelfm** [cloudfoundry/uaa#946]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?

1) $ git clone git://github.com/cloudfoundry/uaa.git
2) $ cd uaa
3) $ ./gradlew run
4) curl -H "Accept: application/json" localhost:8080/uaa/login

Then I did every possible things it recommended I could find but nothing really helped.

### What did you expect to see? What goal are you trying to achieve with the UAA?
```
{
  "timestamp":"2012-03-28T18:25:49+0100",
  "commit_id":"111274e",
  "prompts":{"username":["text","Username"],
    "password":["password","Password"]
  }
}

```
### What did you see instead?

FAILURE

Please include UAA logs if available.

[uaa-server.log](https://github.com/cloudfoundry/uaa/files/2844910/uaa-server.log)

**Comment by fhanik** [comment]
Followed your exact steps. That checks out the `develop` branch

```
curl -H "Accept: application/json" localhost:8080/uaa/login


{"app":{"version":"4.28.0-SNAPSHOT"},"links":{"uaa":"http://localhost:8080/uaa","passwd":"/forgot_password","login":"http://localhost:8080/uaa","register":"/create_account"},"zone_name":"uaa","entityID":"cloudfoundry-saml-login","commit_id":"6c68c1a","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2019-02-07T16:08:53-0800"}

```

Are you using Java 8? Your log shows that it works too.
