### ISSUE TITLE
How to deploy standalone UAA without using Bosh? Best practices please.

### ISSUE THREAD

**Issue by martabelfm** [cloudfoundry/uaa#961]
I would like to deploy UAA as a standalone java application. What are the things I have to do to achieve this?

I used spring_profiles: ldap,default,postgresql

1. I have configured most of the things in UAA.yml (ldap, postgresql, external idp)
Is this the right approach, I see that most the things configured in uaa.yml get populated into the postgresql database aswell. 
2. Do I only need to package the "server" folder?
3. Which basic things i have to remove?

What else do I have to think of before deploying it as a standalone java application?

**Comment by RodrigoPetter** [comment]
Most of the documentation here about the uaa.yml are wrong. Compare your uaa.yml whit the versions in
https://github.com/cloudfoundry/uaa-release/ (I don't know why they have this 2 repos, uaa-release seems to have more accurate documentation)

First make sure all properties in the example file `./uaa/src/main/resources/required_configuration.yml` are filed in the uaa.yml that you'll be using.

Next, build UAA using gradle: `./gradlew clean build -x test`. This will generate a .war file `uaa/build/libs/cloudfoundry-identity-uaa-4.28.0.war` (4.28.0 is the current version of the banch i'm using)

To run, I'm using UAA inside a docker container with tomcat. This is the minimum you'll need in a Dockerfile to build an image:

```
FROM tomcat:8-jre8-alpine

ENV CATALINA_OPTS="-Xmx800m"

RUN rm $CATALINA_HOME/webapps/ROOT -r -f
ADD uaa/build/libs/cloudfoundry-identity-uaa-4.28.0.war $CATALINA_HOME/webapps/ROOT.war

EXPOSE 8080

CMD ["$CATALINA_HOME/bin/catalina.sh run"]
```
If you don't want do ship your .war with sensitive configuration in the uaa.yml (database passwork, certificates, etc) you could use an environment variable to point where a config file will be: `CLOUD_FOUNDRY_CONFIG_PATH=/uaa` (you can read more about it in the UAA documentation)

**Comment by martabelfm** [comment]
> Most of the documentation here about the uaa.yml are wrong. Compare your uaa.yml whit the versions in
> https://github.com/cloudfoundry/uaa-release/ (I don't know why they have this 2 repos, uaa-release seems to have more accurate documentation)
> 
> First make sure all properties in the example file `./uaa/src/main/resources/required_configuration.yml` are filed in the uaa.yml that you'll be using.
> 
> Next, build UAA using gradle: `./gradlew clean build -x test`. This will generate a .war file `uaa/build/libs/cloudfoundry-identity-uaa-4.28.0.war` (4.28.0 is the current version of the banch i'm using)
> 
> To run, I'm using UAA inside a docker container with tomcat. This is the minimum you'll need in a Dockerfile to build an image:
> 
> ```
> FROM tomcat:8-jre8-alpine
> 
> ENV CATALINA_OPTS="-Xmx800m"
> 
> RUN rm $CATALINA_HOME/webapps/ROOT -r -f
> ADD uaa/build/libs/cloudfoundry-identity-uaa-4.28.0.war $CATALINA_HOME/webapps/ROOT.war
> 
> EXPOSE 8080
> 
> CMD ["$CATALINA_HOME/bin/catalina.sh run"]
> ```
> If you don't want do ship your .war with sensitive configuration in the uaa.yml (database passwork, certificates, etc) you could use an environment variable to point where a config file will be: `CLOUD_FOUNDRY_CONFIG_PATH=/uaa` (you can read more about it in the UAA documentation)

Are you using the uaa-release project or just taking some code from the uaa-release project?

**Comment by RodrigoPetter** [comment]
@mart223 I'm using only the example file uaa.yml from uaa-release.

**Comment by martabelfm** [comment]
> @mart223 I'm using only the example file uaa.yml from uaa-release.

https://github.com/cloudfoundry/uaa-release/blob/develop/releases/uaa/uaa-34.yml So this one?

Or this?

https://github.com/cloudfoundry/uaa-release/blob/develop/docs/uaa.md

**Comment by RodrigoPetter** [comment]
Sory, I give you the wrong information.

I'm using [this file](https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/resources/uaa.yml) plus this one [required_configuration.yml](https://github.com/cloudfoundry/uaa/blob/develop/uaa/src/main/resources/required_configuration.yml)

If you see any error, you could use this file [all-properties-set-uaa.yml](https://github.com/cloudfoundry/uaa-release/blob/5a7999d2ed55e0ac25ea16359bd558e3f480c0d6/spec/compare/all-properties-set-uaa.yml) to check if any property has changed and they forgot to rename it.

**Comment by martabelfm** [comment]
Thanks!
