### ISSUE TITLE
Releasing on Maven

### ISSUE THREAD

**Issue by bernardpletikosa** [cloudfoundry/uaa#963]
### What version of UAA are you running?

4.24.0

### How are you deploying the UAA?

Official Maven WAR from Maven Central

#### Issue 

Can you please explain how the process of releasing on Maven works?

Usually a release on Github is not on Maven for a while 
and there were other issues related to this like; https://github.com/cloudfoundry/uaa/issues/813

Any ETA for 4.28.0 to get to maven, or even 4.29.0 or 4.30.0?

Thanks!

**Comment by joshuatcasey** [comment]
@bernardpletikosa Thanks for your question. We're currently blocked on publishing new releases to Maven central after some process changes require us to reorganize some permission structures. I don't have an ETA on this. 

Could you share with us how you're using the UAA? We don't have a lot of information about who is consuming UAA from Maven central.

**Comment by bernardpletikosa** [comment]
@jCaseyPivotal We are currently running v4.24.0 using official Maven JAR from Maven Central.

**Comment by wc22222** [comment]
@bernardpletikosa Could you let us know what jars are you using, and what are your use cases? Thanks!

**Comment by bernardpletikosa** [comment]
Sorry @wc22222 , I was not clear enough.

We get the WAR from here:
http://central.maven.org/maven2/org/cloudfoundry/identity/cloudfoundry-identity-uaa/4.27.0/
and package it in a Docker (https://hub.docker.com/_/tomcat) container.

**Comment by mouellet** [comment]
We also use the releases from Maven Central and repackage the war with customized pages because Branding alone doesn't provide enough customization options.

**Comment by strehle** [comment]
@wc22222 can you please check upload of server ja, e.g. https://repo1.maven.org/maven2/org/cloudfoundry/identity/cloudfoundry-identity-model/4.30.0/ this is not visible there, the other artifacts have been uploaded with your update , thanks

**Comment by mouellet** [comment]
The `cloudfoundry-identity-server` jar was not released properly. The signature file was uploaded instead (i.e. https://repo1.maven.org/maven2/org/cloudfoundry/identity/cloudfoundry-identity-server/4.30.0/cloudfoundry-identity-server-4.30.0.jar.asc)

**Comment by wc22222** [comment]
@strehle @mouellet The UAA team is currently fixing it in this tracker story: https://www.pivotaltracker.com/story/show/165541470

**Comment by strehle** [comment]
@wc22222  thanks, works now
