### ISSUE TITLE
Status for releases v4.29 + v4.30?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/uaa#964]
The last formal release of UAA was 4.28.0 28 days ago. Since then there are two new tagged releases - 4.29 + 4.30 - and 200+ commits to `develop` branch but no github release notes. ETA for release notes; or have these versions been deemed bad?

<img width="750" alt="Screen Shot 2019-03-29 at 9 02 09 am" src="https://user-images.githubusercontent.com/108/55198349-62f24400-5201-11e9-9b6b-6c5039d019bb.png">

Confusingly you've included v4.29 in uaa-release https://github.com/cloudfoundry/uaa-release/releases/tag/v71.0

And there is an unreleased uaa-release that is tagged https://github.com/cloudfoundry/uaa-release/releases

<img width="974" alt="Screen Shot 2019-03-29 at 9 06 28 am" src="https://user-images.githubusercontent.com/108/55198506-f62b7980-5201-11e9-8bfe-4470a00546c3.png">

**Comment by dbeneke** [comment]
Closing as versions have progressed beyond this question.
