### ISSUE TITLE
SAML logout issue if IDP initiated

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#967]
### What version of UAA are you running?
4.24, but guess does not matter if newer

### How are you deploying the UAA?

bosh

### What did you do?

Use 2 UAA instance together with one IDP. If I start SLO with /logout.do the first UAA instance is 
performing logout but the 2nd one we see 

<saml2p:LogoutResponse ... >
    ...
    <saml2p:Status>
        <saml2p:StatusCode 
            Value="urn:oasis:names:tc:SAML:2.0:status:UnknownPrincipal"/>
        <saml2p:StatusMessage>No user is logged in</saml2p:StatusMessage>
    </saml2p:Status>
</saml2p:LogoutResponse>
similar to  https://github.com/spring-projects/spring-security-saml/issues/166

### What did you expect to see? What goal are you trying to achieve with the UAA?

Logout on all UAA instances

### What did you see instead?

Problem is that authentication is null, see
https://github.com/spring-projects/spring-security-saml/blob/1.0.9.RELEASE/core/src/main/java/org/springframework/security/saml/SAMLLogoutProcessingFilter.java#L169-L173

Security context is not set thereofore always null
https://github.com/spring-projects/spring-security-saml/blob/1.0.9.RELEASE/core/src/main/java/org/springframework/security/saml/SAMLLogoutProcessingFilter.java#L169

**Comment by tack-sap** [comment]
Merged the PR. Thus closing the issue.
