### ISSUE TITLE
Business Logic error 

### ISSUE THREAD

**Issue by lerytke** [cloudfoundry/uaa#980]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

64.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`

{"app":{"version":"4.19.2"},"links":{"uaa":"https://uaa.system.dev.east.paas.geointservices.io","login":"https://login.system.dev.east.paas.geointservices.io"},"zone_name":"uaa","entityID":"http://login.system.dev.east.paas.geointservices.io","commit_id":"37d0f70","idpDefinitions":{},"prompts":{"username":["text","username"],"password":["password","Password"]},"timestamp":"2019-01-14T15:37:28+0000"}

### How are you deploying the UAA?

I am deploying the UAA

- as part of a commercial Cloud Foundry distribution
PCF 2.3.8

### What did you do?

There is a business logic error that we need resolved

when there is an error on the login page, you can edit the error and produce a message that might trick someone into sending an attacker your credentials.  

https://login.system.dev.east.paas.geointservices.io/login?error=send%20your%20password%20to%20some@me.com

If possible, provide a recipe for reproducing the error. Exact `curl` or `uaac` commands with verbose output are helpful. If your problem is configuration-related, please include portions of your uaa.yml or bosh deployment manifest that you believe may be relevant (but do not divulge secrets!)

### What did you expect to see? What goal are you trying to achieve with the UAA?
We are being required by our security team to change how this functions

### What did you see instead?

a static error that can't be changed

Please include UAA logs if available.
i don't think they are relavent

**Comment by RodrigoPetter** [comment]
A similar thing can be done using the parameter "success".
`https://UAA_URL/login?success=send%20your%20password%20to%20some@me.com`

**Comment by wc22222** [comment]
@RodrigoPetter @lerytke Thank you for reporting this, we will prioritize it accordingly.

**Comment by dbeneke** [comment]
@RodrigoPetter @lerytke This issue was fixed in our latest release: https://github.com/cloudfoundry/uaa-release/releases/tag/v74.0.0
